### ISSUE TITLE
[Question] Moving issues from atlassian to jfrog

### ISSUE THREAD

**Issue by josh-barker** [jfrog/terraform-provider-artifactory#1]
Hi, I'm wondering when issues will be migrated from https://github.com/atlassian/terraform-provider-artifactory?

Cheers

**Comment by lindhe** [comment]
Will they ever? I'm not sure that JFrog have officially taken over the maintenance of this provider, I think this is just a hard fork and now there's two providers being maintained. So the old issues should not be migrated.

Please correct me if I'm wrong. There's awfully little information available regarding the forking.

**Comment by peters95** [comment]
Hi @josh-barker and @lindhe JFrog is taking over official maintenance now of this provider. We are reaching out to Atlassian to deprecated their repo. Please raise any issues or PRs in this repo as its now being actively maintained.

**Comment by peters95** [comment]
We are working to get the proper permissions in the Atlassian repo to transfer all issues here and update their repo w/ a deprecation notice.

**Comment by peters95** [comment]
Issues have been moved but Atlassian is taking time to deprecate the official repo. Reaching out again about deprecation and a final issue migration.
