### ISSUE TITLE
`external_dependencies_patterns` incorrectly forces new on go virtual repos 

### ISSUE THREAD

**Issue by jamestoyer** [jfrog/terraform-provider-artifactory#1004]
**Describe the bug**
Changing the value of `external_dependencies_patterns` for a go virtual repository causes the resource to be replaced. This is cause by https://github.com/jfrog/terraform-provider-artifactory/blob/45c0e0495fcbb865419ab9b30c9ec097a019305c/pkg/artifactory/resource/repository/virtual/virtual.go#L125 begin `true`.

This behaviour is inconsistent with the UI which does allow you to change the patterns after repository creation.

**Requirements for an issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**
Setting `external_dependencies_patterns` should not cause the go virtual repository resource to be recreated.

**Additional context**

**Comment by alexhung** [comment]
@jamestoyer Thanks for the report. I don't recall the reason this attribute is set with `ForceNew` but I'm sure there **was** correct.

Its behavior in Artifactory probably has changed since then, so I'll update this in our next sprint.

**Comment by gjasny** [comment]
Hi @alexhung,

Even with latest `v11.5.1` the golang virtual repo would be replaced when I add an entry to `external_dependencies_patterns`:

```
  # artifactory_virtual_go_repository.test-tf-go must be replaced
-/+ resource "artifactory_virtual_go_repository" "test-tf-go" {
      ~ external_dependencies_patterns                     = [ # forces replacement
            # (1 unchanged element hidden)
            "**/github.com/**",
          + "**/github.comic/**",
        ]
      ~ id                                                 = "test-tf-go" -> (known after apply)
      ~ package_type                                       = "go" -> (known after apply)
      ~ project_environments                               = [] -> (known after apply)
        # (11 unchanged attributes hidden)
    }
```

Do you have an idea what's going on?

Thanks,
Gregor

**Comment by gjasny** [comment]
Works like a charm! Thank you for the fast fix
