### ISSUE TITLE
Add a provider for webhooks related to clients events

### ISSUE THREAD

**Issue by sebastienvermeille** [jfrog/terraform-provider-artifactory#1012]
I could not find any terraform provider for webhooks related to `users account being locked`. 

Some providers exist for artifacts, dockers, but nothing for users: https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifact_property_webhook

Could you please consider implementing it?

**Describe the solution you'd like**
I would like to be able to define a custom webhook related to the user account being locked. 

**Describe alternatives you've considered**
At the moment I defined the webhook via the UI.
However, this goes against our practice (Config as Code)

Thank you for your consideration

**Comment by alexhung** [comment]
@sebastienvermeille Thanks for the suggestion. I'll add this to our plan.
