### ISSUE TITLE
Data resource gives 400 for Federated repositories

### ISSUE THREAD

**Issue by sparshs413** [jfrog/terraform-provider-artifactory#1018]
**Describe the bug**
When using data resources for managing Federated Repositories, it gives 400 when the repositories don't exist; if the repositories exist, it doesn't give any errors.

If we create new Federated Repositories, we get the above error.

Code for creation of federated repo:

```
data "artifactory_federated_generic_repository" "docker_test" {
  key = "docker_test"
}

resource "artifactory_federated_docker_repository" "docker_test" {
  key                    = "docker_test"
  description        = "This repository is for docker images."

  dynamic "member" {
    for_each = var.federated_urls
    content {
      url     = join("/", [member.value, "artifactory", "docker_test"])
      enabled = true
    }
  }
}

```

**Expected behavior**
Ideally, it should give a null value instead of exiting with a 400.

**Comment by alexhung** [comment]
@sparshs413 Thanks for the report. I'll add this to our plan to investigate.

**Comment by alexhung** [comment]
@sparshs413 Having said that, the error stamps from the fact the data source is not dependent on the resource creation. You should use the resource reference for `key` attribute to ensure the resource is created **before** fetching the data from it.

e.g.
```terraform
data "artifactory_federated_generic_repository" "docker_test" {
  key = artifactory_federated_docker_repository.docker_test.key
}

resource "artifactory_federated_docker_repository" "docker_test" {
  key                    = "docker_test"
  description        = "This repository is for docker images."

  dynamic "member" {
    for_each = var.federated_urls
    content {
      url     = join("/", [member.value, "artifactory", "docker_test"])
      enabled = true
    }
  }
}
```

**Comment by sparshs413** [comment]
@alexhung In the case of multiple artifactory instances, the resource creation is done on a single instance, and for others I am trying to use data resources to fetch the data so that the Terraform apply doesn't fail (since the federated repository would already exist)
