### ISSUE TITLE
Failed to install provider

### ISSUE THREAD

**Issue by activalexsimon** [jfrog/terraform-provider-artifactory#1027]
**Describe the bug**
I am seeing an error when trying to download the latest version of the provider due to SHA-256. 

Local
```bash
Error: Failed to install provider
│ 
│ Error while installing jfrog/artifactory v11.2.0: checksum list has no SHA-256 hash for
│ "https://github.com/jfrog/terraform-provider-artifactory/releases/download/v11.2.0/terraform-provider-artifactory_11.2.0_darwin_arm64.zip"
```

CI
```bash
╷
│ Error: Failed to install provider
│ 
│ Error while installing jfrog/artifactory v11.2.0: checksum list has no
│ SHA-256 hash for
│ "https://github.com/jfrog/terraform-provider-artifactory/releases/download/v11.2.0/terraform-provider-artifactory_11.2.0_linux_amd64.zip"
╵

```
I am seeing this within out CI platforms and also on my local. Pinning the version back down to `v11.1.0` seems to resolve the issue and I am able to init just fine. 

**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**
I expect this providers version to also be working like v11.1.0 is. 

**Additional context**
[This](https://github.com/hashicorp/terraform/issues/31093) is for a different provider, but looks like a similar error.

**Comment by adoraisa** [comment]
We are also observing this issue.

**Comment by alexhung** [comment]
@activalexsimon @adoraisa We recently switched to the Terraform Registry Org beta program and I suspect it may be the issue. 11.2.0 is the first version to be published after migrating to the beta program. Nothing on our side with regards to the packaging or signing of the provider has changed.

**Comment by kamilsimek-ecb** [comment]
Thanks for the feedback @alexhung!

Do you know when it will be resolved? Indeed, it seems like it is missing from https://releases.hashicorp.com/ (there is no terraform-provider-artifactory).

**Comment by alexhung** [comment]
@kamilsimek-ecb Commented too soon!

HashiCorp has resolved the issue with this release. I've verified I can install 11.2.0 now.

They have also identified the issue on their side and are working on a fix.

**Comment by activalexsimon** [comment]
@alexhung thank you! Confirming on my end that I also can install 11.2.0. 

Appreciate it!
