### ISSUE TITLE
Terraform Failed to install jfrog/artifactory v11.2.0 provider

### ISSUE THREAD

**Issue by ASH0410** [jfrog/terraform-provider-artifactory#1029]
Error while installing jfrog/artifactory v11.2.0: checksum list has no SHA-256 hash for "https://github.com/jfrog/terraform-provider-artifactory/releases/download/v11.2.0/terraform-provider-artifactory_11.2.0_linux_amd64.zip"

As of now, we are using below version that is working absolutely fine.
Terrform = >1.0
jfrog/artifactory: 11.1.0

provider.tf
------------
```terraform
terraform {
  required_version = "~> 1.0"
  backend "s3" {
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "11.1.0"
    }

  }
}

provider "artifactory" {
  url           = var.artifactory_url
  access_token  = var.artifactory_access_token
  check_license = false
}
```

**Comment by Sartigan** [comment]
We re facing the same issue since yesterday

**Comment by alexhung** [comment]
Dups of #1027
