### ISSUE TITLE
Issue with Moving the Terraform Resource.

### ISSUE THREAD

**Issue by ashrithacjfrog** [jfrog/terraform-provider-artifactory#1030]
**Describe the bug**
The new version of the Terraform provider (11.1.0) for Artifactory no longer supports `artifactory_access_token` as it is deprecated. The customer is attempting to move the resource using the command `terraform state mv` but is encountering an error. 

The error message is:

> Cannot move artifactory_access_token.code_dependencies to artifactory_scoped_token.code_dependencies: resource types don't match."

**Requirements for and issue** 

Snippet:

This is the initial resource:

```terraform
resource "artifactory_access_token" "code_dependencies" {
  username          = artifactory_user.code_dependencies.name
  end_date_relative = "0s"
}
```

which is changed to:

```terraform
resource "artifactory_scoped_token" "code_dependencies" {
  username   = artifactory_user.code_dependencies.name
  expires_in = 0
}
```

**Artifactory Version**: Saas/ 7.90.2

**Expected behavior**
The customer should be able to move the resource using the `terraform state mv` command without errors.

**Additional context**
Currently, the customer is unable to move the resource using the `terraform state mv` command.

**Comment by AlessioCasco** [comment]
Hello

We are impacted by this. 
Can you tell us how to move the terraform resource without destroying the old one and creating the new one?

Thanks

**Comment by alexhung** [comment]
@AlessioCasco It is not possible as far as I can see.

This is the reason `artfactory_access_token` resource has been marked as deprecated since **May 2022** to give ample time for existing tokens to expire and migrate to the new `artifactory_scoped_token` resource.
