### ISSUE TITLE
`artifactory_managed_user`: `terraform validate` fails with "Attribute password string length must be at least 8, got 0"

### ISSUE THREAD

**Issue by NiklasRosenstein** [jfrog/terraform-provider-artifactory#1031]
**Describe the bug**

With `jfrog/artifactory=11.2.0`, the `artifactory_managed_user` fails to validate when passing in a `random_password.result`.

__Example__

```tf
resource "random_password" "main" {
  length = 24
}

resource "artifactory_managed_user" "main" {
  name              = "foo"
  email             = "foo@example.com"
  disable_ui_access = true
  admin             = false
  profile_updatable = false
  password          = random_password.main.result
}
```

Gives

```
❯ terraform  validate
╷
│ Error: Invalid Attribute Value Length
│ 
│   with artifactory_managed_user.main,
│   on main.tf line 25, in resource "artifactory_managed_user" "main":
│   25:   password          = random_password.main.result
│ 
│ Attribute password string length must be at least 8, got 0
╵
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] ~Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`~
- [x] Your version of terraform &rarr; 1.8.4
- [x] Your version of terraform provider &rarr; 11.2.0

**Expected behavior**

The validation does not fail.

**Additional context**

This does not happen with `jfrog/artifactory<11.2.0`

**Comment by alexhung** [comment]
@NiklasRosenstein Thanks for the report. I'll investigate.
