### ISSUE TITLE
max_unique_snapshots configuration for Remote repositories

### ISSUE THREAD

**Issue by welandaz** [jfrog/terraform-provider-artifactory#1039]
**Is your feature request related to a problem? Please describe.**
In Artifactory, it is possible to specify the Maximum Number of Snapshots to store when a Remote repository is created (e.g., Gradle, Maven etc.).
The Terraform configuration, on the other hand, doesn't allow to do so. The `max_unique_snapshots` field is only present for Local ones, though.

**Describe the solution you'd like**
`max_unique_snapshots` is available for configuration in Remote repository resources.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by alexhung** [comment]
@welandaz Thanks for the suggestion. I've added this to our plan.
