### ISSUE TITLE
Add ability to set properties on a repository

### ISSUE THREAD

**Issue by critchtionary** [jfrog/terraform-provider-artifactory#1041]
**Is your feature request related to a problem? Please describe.**
It would be useful if we could define properties on the repository using the Terraform provider.

**Describe the solution you'd like**
Ideal scenario would be a new `properties` attribute on the existing repository resources. However, I can understand if that is not possible as the repository management and property setting seem to be different API endpoints.

- [Repository management](https://jfrog.com/help/r/jfrog-rest-apis/repositories?tocId=cz2A_OsjoOysuLs_~gcTHw) - `/artifactory/api/repositories/{repoKey}`
- [Set Properties](https://jfrog.com/help/r/jfrog-rest-apis/set-item-properties) - `/artifactory/api/storage/{repoKey}?properties=p1=v1`

An alternative could be to define a new resource e.g. `artifactory_repository_property` (or plural) which takes the repository key and details of the property keys and values.

**Describe alternatives you've considered**
I confirmed you can't abuse the `artifactory_artifact` resource to set a property on a repository (like you can for an artifact), as you need to specify an existing `file_path` and `path` can't simply be `/`.

**Additional context**
N/A

**Comment by alexhung** [comment]
@critchtionary Thanks for the suggestion. I've added this to our plan.

Most likely I'll add a new resource as you suggest to handle this.
