### ISSUE TITLE
Unable to import permission target which has per repository exclusion pattern

### ISSUE THREAD

**Issue by manojkumar-kallagunta** [jfrog/terraform-provider-artifactory#1054]
**Describe the bug**
We are trying to import the permission target from artifactory using terraform but when we have exclusion pattern **Per Repository** instead of **All Repositories**. Please find the below image for the same
![image](https://github.com/user-attachments/assets/d618076b-0a07-4c77-9af3-8319000f241f)

terraform command: **terraform import**

Please find the below image for terraform output
![image](https://github.com/user-attachments/assets/ae71bba0-7835-4c16-8b4a-da2c8f42884e)

Cloud Artifactory version: 7.93.3
Terraform version: Terraform v1.9.3
Terraform provider: provider registry.terraform.io/jfrog/artifactory v10.0.2

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
terraform import is working even with the exclusion pattern per repository instead of All Repositories.

**Comment by alexhung** [comment]
@manojkumar-kallagunta The error message suggests that the resource already exists for the ID in the configuration, therefore it can't be imported again. Please check the ID is correct and you are not attempting to import into an existing resource state.

These are the steps I took in attempt to reproduce this issue (but found no error):

1. Create a new permission in Artifactory called `test` with exclude patterns.
2. Fetch the same permission from Artifactory using API:
```sh
$ curl -L 'http://localhost:8082/artifactory/api/v2/security/permissions/test' -H 'Authorization: Bearer eyJ2ZiIy...eb1odq9g'
{
  "name" : "test",
  "repo" : {
    "actions" : { },
    "repositories" : [ "ANY LOCAL" ],
    "include-patterns" : [ "**" ],
    "exclude-patterns" : [ "test/**" ]
  }
}
```
3. Create Terraform configuration to match the permission:
```terraform
terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "11.6.1"
    }
  }
}

provider "artifactory" {
  //  supply ARTIFACTORY_ACCESS_TOKEN / JFROG_ACCESS_TOKEN / ARTIFACTORY_API_KEY and ARTIFACTORY_URL / JFROG_URL as env vars
}

resource "artifactory_permission_target" "my-test" {
  name = "test"
  repo {
    repositories = ["ANY LOCAL"]
    includes_pattern = ["**"]
    excludes_pattern = ["test/**"]
  }
}
```
4. Import the permission into Terraform state:
```sh
$ terraform import artifactory_permission_target.my-test test
artifactory_permission_target.my-test: Importing from ID "test"...
artifactory_permission_target.my-test: Import prepared!
  Prepared artifactory_permission_target for import
artifactory_permission_target.my-test: Refreshing state... [id=test]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

```
5. Check there is no state drift:
```sh
$ terraform plan
artifactory_permission_target.my-test: Refreshing state... [id=test]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Deprecated Resource
│
│   with artifactory_permission_target.my-test,
│   on sample.tf line 14, in resource "artifactory_permission_target" "my-test":
│   14: resource "artifactory_permission_target" "my-test" {
│
│ This resource has been deprecated in favor of "platform_permission" (https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission)
│ resource.
│
│ (and one more similar warning elsewhere)
╵
```

**Comment by manojkumar-kallagunta** [comment]
Thanks for the quick response.
With one repository terraform import is working.
Example json:
```
 {
  "name" : "test",
  "repo" : {
    "actions" : { },
    "repositories" : [ "example-repo-local" ],
    "include-patterns" : [ "**" ],
    "exclude-patterns" : [ "test/**" ]
  }
}
```
If we have two repositories and have different exclude patterns terraform import is not working.
Example json:
```
{
    "name": "test",
    "resources": {
        "artifact": {
            "actions": {
                "users": {},
                "groups": {
                    "test-admins": [
                        "ANNOTATE",
                        "SCAN",
                        "WRITE",
                        "DELETE",
                        "MANAGE",
                        "READ"
                    ]
                }
            },
            "targets": {
                "example1": {
                    "include_patterns": [],
                    "exclude_patterns": [
                        "test/**"
                    ]
                },
                "example2": {
                    "include_patterns": [
                        "**"
                    ],
                    "exclude_patterns": []
                }
            }
        }
    }
}
```

**Comment by alexhung** [comment]
@manojkumar-kallagunta Ok let me try this out.

FYI this resource is deprecated and replaced by the more advanced [`platform_permission`](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission) in the `platform` provider.

**Comment by alexhung** [comment]
@manojkumar-kallagunta After digging a little more, I think this issue is inherited to the limitation of the permission target API in Artifactory. See the `application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json` in the [API schema](https://jfrog.com/help/r/jfrog-rest-apis/security-configuration-json).

The newer [Platform Permission API](https://jfrog.com/help/r/jfrog-rest-apis/create-permission) allows for per repository patterns configuration.

My recommendation is to use the `platform_permission` resource instead.

**Comment by alexhung** [comment]
@manojkumar-kallagunta Another workaround is to create separate `artifactory_permission_target` resource for each repository.

**Comment by manojkumar-kallagunta** [comment]
Could you please provide me an example to create separate artifactory_permission_target resource for each repository.

**Comment by alexhung** [comment]
@manojkumar-kallagunta 

```terraform
resource "artifactory_permission_target" "my-permission-1" {
  name = "permission-1"
  repo {
    repositories = ["example-repo-local"]
    includes_pattern = ["**"]
    excludes_pattern = ["test/**"]
  }
}

resource "artifactory_permission_target" "my-permission-2" {
  name = "permission-2"
  repo {
    repositories = ["my-repo-local"]
    includes_pattern = ["**"]
    excludes_pattern = ["foo/**"]
  }
}
```
