### ISSUE TITLE
Document for version 6.37.0 is not correct 

### ISSUE THREAD

**Issue by dinhdobathi1992** [jfrog/terraform-provider-artifactory#1077]
**Describe the bug**
I'm using version 6.37.0 to create scoped_token and follow the document, but there was a missing configuration in scoped_token resource and it cause the issue when trying to create token. 

![image](https://github.com/user-attachments/assets/bf9892cb-15a7-480b-b817-5df1b1bcfdd3)
 

**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**

**Additional context**

**Comment by alexhung** [comment]
@dinhdobathi1992 Are you referring to missing required attributes in the example? FYI, those example are not meant to be comprehensive, they are to show the attribute(s) for particular use cases.
