### ISSUE TITLE
resource to create cocoapods virtual repository resource

### ISSUE THREAD

**Issue by madelaney** [jfrog/terraform-provider-artifactory#1079]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to create a `cocoapods` virtual repository via Terraform.

**Describe the solution you'd like**
While we can create a virtual repository on the Artifactory UI, there seems to be lacking that ability to do this via Terraform.

**Describe alternatives you've considered**
The only alternative is to either use the jfrog-cli or the web ui; both are not very good alternatives.

**Additional context**
N/A

**Comment by alexhung** [comment]
@madelaney Thanks for the report! It is indeed missing from virtual repository list. I'll add this to our plan to fix.
