### ISSUE TITLE
Retrieve SHA256 from remote server option is missing in remote generic repositories

### ISSUE THREAD

**Issue by renjfk** [jfrog/terraform-provider-artifactory#1080]
**Is your feature request related to a problem? Please describe.**
`artifactory_remote_generic_repository` is currently missing "Retrieve SHA256 from remote server" option where it's available in GUI.

**Describe the solution you'd like**
It's possible to configure this option via Terraform.

**Describe alternatives you've considered**
Currently there's no alternative if you want to manage Artifactory fully IaC.

**Additional context**
![image](https://github.com/user-attachments/assets/7c43de01-5823-4807-b2e2-73081f4915b8)

**Comment by alexhung** [comment]
@renjfk Thanks for the suggestion! I've added this to our plan to add to the resource.
