### ISSUE TITLE
OIDC integrations, Identity Mappings and AWS AssumeRole mappings

### ISSUE THREAD

**Issue by elestedt** [jfrog/terraform-provider-artifactory#1090]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for managing OIDC integrations, Identity Mappings and AWS AssumeRole mappings

**Describe alternatives you've considered**
REST API without TF

**Comment by alexhung** [comment]
@elestedt OIDC Integration can be configured in the Platform provider ([OIDC Configuration](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/oidc_configuration) and [OIDC Identity Mapping](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/oidc_identity_mapping)). Same with [AWS IAM Role](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/aws_iam_role).
