### ISSUE TITLE
Curation for remote nuget repositories not available in terraform provider

### ISSUE THREAD

**Issue by owen-delaney-admiral** [jfrog/terraform-provider-artifactory#1091]
Curation for remote nuget repositories not available in terraform provider but are in the UI

```
resource "artifactory_remote_nuget_repository" "nuget-remote" {
  key                        = "nuget-org"
  url                        = "https://www.nuget.org/"
  download_context_path      = "api/v2/package"
  force_nuget_authentication = true
  v3_feed_url                = "https://api.nuget.org/v3/index.json"
  symbol_server_url          = "https://symbols.nuget.org/download/symbols"
  description                = "Repository that proxies the NuGet gallery, used for managing .NET packages"
  xray_index                 = true
  # Having to manually set as curated in the UI, not currently supported in the terraform provider
  # curated                    = true
}
```

Artifactory version 
"version" : "7.95.0",
"revision" : "79500900"

Terraform v1.6.6
on windows_amd64
+ provider registry.terraform.io/jfrog/artifactory v12.1.0
+ provider registry.terraform.io/jfrog/project v1.6.2

Expectation of being able to add the curated attribute for remote nuget via Terraform rather than having to set in the UI

**Comment by alexhung** [comment]
@owen-delaney-admiral Thanks for the report! I've added this to our plan to add Curation support for NuGet and HuggingFace package types.
