### ISSUE TITLE
Cannot set cron_exp in artifactory_local_repository_multi_replication while updating resource

### ISSUE THREAD

**Issue by keyboardsmash** [jfrog/terraform-provider-artifactory#1099]
**Describe the bug**
Terraform returns a 400 claiming that cronExp is not set when changing the cron expression.

**Requirements for and issue**
- [X] A description of the bug

**Output of plan when using target to module:**

```
# module.test.artifactory_local_repository_multi_replication.test-helm-prod[0] will be updated in-place
  ~ resource "artifactory_local_repository_multi_replication" "test-helm-prod" {
      ~ cron_exp                 = "0 0 */2 * * ?" -> "0 16 * * * ? 2099"
      ~ id                       = "test-helm-prod" -> (known after apply)
        # (2 unchanged attributes hidden)

      ~ replication {
          ~ replication_key                     = "<redacted>" -> (known after apply)
            # (13 unchanged attributes hidden)
        }
    }

```
**Error message after apply**
```

Error: Unable to Update Resource
│ 
│   with module.test.artifactory_local_repository_multi_replication.test-helm-prod[0],
│   on ../../modules/projects/test/test-helm.tf line 43, in resource "artifactory_local_repository_multi_replication" "test-helm-prod":
│  202: resource "artifactory_local_repository_multi_replication" "test-helm-prod" {
│ 
│ An unexpected error occurred while updating the resource update request. Please report this issue to the provider developers.
│ 
│ Error: {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "cronExp is required"
│   } ]
│ }
```

- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**

```
resource "artifactory_local_repository_multi_replication" "test-helm-prod" {
  repo_key = artifactory_local_helm_repository.test-helm-prod.key
  replication {
    url = "https://example.com/artifactory/test-helm-prod/"
    username        = ****
    password        = ****
    enabled         = true
    sync_deletes    = true
    sync_properties = true
    sync_statistics = true
  }
  cron_exp                 =  "0 16 * * * ? 2099"
  enable_event_replication = true
}
```

- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
7.90.8
- [X] Your version of terraform
1.9.7
- [X] Your version of terraform provider
12.0.0
12.3.0 

**Expected behavior**
It should update the cron_exp value with the new value.

**Additional context**
Our code works when creating a new resource, but not when updating the resource.

Values we have used are:
"0 0 */2 * * ?" (every 30 minutes)
"0 16 * * * ? 2099" (jan 1 2099 aka never)

**Comment by alexhung** [comment]
@keyboardsmash Thanks for the report! I'm able to reproduce this issue and confirmed that this originates from the Artifactory REST API. I will open an internal bug report for the Artifactory team to investigate.
