### ISSUE TITLE
last_downloaded_before_in_months value can not be set to 0 using TF

### ISSUE THREAD

**Issue by AleksanderOlszewski** [jfrog/terraform-provider-artifactory#1122]
**Describe the bug**
`last_downloaded_before_in_months` value in the `artifactory_package_cleanup_policy` resource must be at least 1 but it is possible to specify 0 using UI.

Sample code that throws an error:

```
resource "artifactory_package_cleanup_policy" "docker-staging-TF-managed" {
  key             = "docker-staging-TF-managed"
  description     = "Cleanup policy for docker-staging"
  enabled         = false
  cron_expression = "0 0 0 ? * MON-SUN *"
  skip_trashcan   = false
  search_criteria = {
    include_all_projects             = true
    included_packages                = ["**"]
    package_types                    = ["docker"]
    repos                            = ["docker-staging"]
    created_before_in_months         = 1
    last_downloaded_before_in_months = 0
  }
}
```
Version: "7.99.2"
TF: 1.5.7
Provider: v12.4.0 

**Expected behavior**
I can specify 0 as the `last_downloaded_before_in_months` value in the `artifactory_package_cleanup_policy` resource, exactly as I'm able to do using UI.

**Additional context**

**Comment by alexhung** [comment]
@AleksanderOlszewski Thanks for the report! I've added this to our plan to fix.
