### ISSUE TITLE
unable to set default deployment repository artifactory_virtual_npm_repository

### ISSUE THREAD

**Issue by madelaney** [jfrog/terraform-provider-artifactory#1131]
**Describe the bug**
With Artifactory (v7.98.8), with artifactory provider (12.4; terraform 1.5.7) using  I am unable to set the default deployment repo when creating a `artifactory_virtual_npm_repository` resource.

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
I expect to be able to set the default deployment repository for `artifactory_virtual_npm_repository`.

**Additional context**
I looked at the documentation at https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/virtual_npm_repository, and it's not listed there.

**Comment by alexhung** [comment]
@madelaney The list of common attributes for **all** virtual repository is here: https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/virtual

**Comment by madelaney** [comment]
@alexhung oh!, my apologies. I totally missed that. I'll close this out.
