### ISSUE TITLE
cargo: git_registry_url is not required field

### ISSUE THREAD

**Issue by rayasm1** [jfrog/terraform-provider-artifactory#1153]
**Describe the bug**
[git_registry_url](https://github.com/jfrog/terraform-provider-artifactory/blob/b2d31a982e84b65eaaa74ce079fa8a01d7aa876f/pkg/artifactory/resource/repository/remote/resource_artifactory_remote_cargo_repository.go#L24) in the code is mentioned as `Required: true` , but the document says [optional](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/remote_cargo_repository#git_registry_url-2)
I want to use http sparse index and not git_repository.

Artifactory version: 7.98.7
Terraform version : Terraform v1.9.0
terraform-provider-artifactory: v11.5.1

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
git_registry_url should be optional

**Additional context**

**Comment by alexhung** [comment]
@rayasm1 Thanks for the report! I've added this to our plan to update the code as well as documentation.
