### ISSUE TITLE
2.3.1 causing panic error on terraform validate

### ISSUE THREAD

**Issue by emmaroberts-nbs** [jfrog/terraform-provider-artifactory#121]
**Describe the bug**
Recently upgraded to 2.3.1 version of the tf provider and now when running `terraform validate`, an error is thrown

![2.3.1_error](https://user-images.githubusercontent.com/74302098/132644033-6aa38f80-9d66-4578-b284-38a5533a34a6.png)

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform: **0.15.5**

**Expected behaviour**
Terraform Validate command should return saying the `The configuration is valid`

**Additional context**
```hcl
terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "~>2"
    }
  }
}

provider "artifactory" {
  url     = "https://artifactory.example.com"
  api_key = "test-api-key"
}
```

**Comment by emmaroberts-nbs** [comment]
Workaround: Downgrading to v2.2.15 of the provider

**Comment by chb0github** [comment]
Somehow, it was missed in all the testing. I am digging into it now
