### ISSUE TITLE
artifactory_user resource now has required password - not appropriate for external users

### ISSUE THREAD

**Issue by medains** [jfrog/terraform-provider-artifactory#122]
**Describe the bug**
The 2.3.1 release changed the artifactory_user resource password field from Optional to Required.
It is still listed as optional in the documentation, and this makes sense when using external authentication mechanisms.

**Requirements for and issue**
Artifactory provider version 2.3.1 (artifactory version irrelevant)
TF 1.0.5

```
resource "artifactory_user" "example" {
   name                       = "example"
   email                      = "example@localdomain"
   groups                     = ["readers"]
   admin                      = false
   internal_password_disabled = true
}
```

**Expected behavior**
User example created

**Actual behaviour**
```
│ Error: Missing required argument
│ 
│   on main.tf line 1, in resource "artifactory_user" "example":
│   1: resource "artifactory_user" "example" {
│ 
│ The argument "password" is required, but no definition was found.
```

**Additional context**
This change was not in the release notes.

**Comment by chb0github** [comment]
Thank you for bringing this to my attention. With the release of 2.3.1, much more stringent validation was done. Sometimes too aggressively. That was noted in the readme. I've updated the docs to be more specific and removed the required field. However, if you do use it, it's going to try to validate that it matches the default ruleset for passwords. This can be overridden with `JFROG_PASSWD_VALIDATION_ON=false`

If you continue to have problems, please reach out
