### ISSUE TITLE
Allow dots and dashes in resource names again

### ISSUE THREAD

**Issue by spuder** [jfrog/terraform-provider-artifactory#129]
We are trying to upgrade from 2.2.4 to 2.3.4 and are finding the new version has extreemly restrictive regex limiting what allowed names are. 

```
resource "artifactory_remote_repository" "debian-remote_teleport" {
    key              = "debian-remote.teleport"
    package_type     = "debian"
    repo_layout_ref  = "simple-default"
    url              = "https://deb.releases.teleport.dev/"
    notes            = "managed by terraform"
    property_sets    = ["artifactory"]
    includes_pattern = "**/*"
    content_synchronisation {
        enabled = false
    }
}
```

Produces this error
```
Error: expected value of key to not contain any of " !@#$%^&*()_+={}[]:;<>,./?~`|\\", got debian-remote.teleport

  on repository-debian.tf line 551, in resource "artifactory_remote_repository" "debian-remote_teleport":
 551:     key              = "debian-remote.teleport"
```

Why were the resource names made so restrictive? There is no technical reason in artifactory since artifactory will happily serve artifacts with `.` or `-` in the resource name

![Screen Shot 2021-09-15 at 1 49 57 PM](https://user-images.githubusercontent.com/242382/133499881-a77331c1-18f9-4e1f-8ad8-ec8eadd79feb.png)

**Comment by spuder** [comment]
Futhermore, this makes it impossible to import any existing resources from artifactory into terraform unless they are renamed to these naming conventions.

**Comment by chb0github** [comment]
Hey @spuder 

With the new major release, a lot of effort was put in to prevalidate - Although I tried to maintain backward compatibility, it's a major version bumb for reasons; validation being one.

This points to the inconsistency between the API and the UI. The UI very clearly states that

"... May not begin with a number, contain a space or a special character". `-` and `.` are definitely special characters, but obviously the warning on the UI is wrong. I am looking at the [API documentation ](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateRepository) And it's entirely silent. 

I can add the `.-` into the allowed values no problem. Thanks for bringing this to my attention

**Comment by chb0github** [comment]
`-` was already allowed. I added changes and a test to allow `.` as well

**Comment by clemensw** [comment]
Restricting underscores `_` in repo names seems a similarly unnecessary restriction on what would be quite common practice.
