### ISSUE TITLE
cannot unmarshal object with artifactory_single_replication_config

### ISSUE THREAD

**Issue by tdgeery** [jfrog/terraform-provider-artifactory#133]
**Describe the bug**
Error when creating artifactory_single_replication_config:

```
╷
│ Error: json: cannot unmarshal object into Go value of type []utils.ReplicationBody
│
│   with artifactory_single_replication_config.remote_replication_config["upstream-docker-remote"],
│   on repositories.tf line 112, in resource "artifactory_single_replication_config" "remote_replication_config":
│  112: resource "artifactory_single_replication_config" "remote_replication_config" {
│
╵
```

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
```
resource "artifactory_single_replication_config" "remote_replication_config" {
  for_each = {
    for repo, config in var.remote_repositories : repo => config
    if lookup(config, "replication", false) && can(regex("prod", terraform.workspace))
  }

  repo_key                 = each.key
  cron_exp                 = var.remote_replication_cron_expression
  enable_event_replication = false
  sync_deletes             = true
  sync_properties          = true

  lifecycle {
    ignore_changes = [password]
  }
}
```
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: 6.23.7
- [x] Your version of terraform: 1.0.3
- [x] Artifactory Provider Version: 2.3.8

**Comment by tdgeery** [comment]
This was working previously on Provider version 2.2.15

**Comment by jamestoyer** [comment]
For reference, I wrote the original implementation before `2.3.x`. Looking through the code, it appears the change is https://github.com/jfrog/terraform-provider-artifactory/blob/d88ae3f9d93e9cc104d1fffae2dd4dcced0295f4/pkg/artifactory/resource_artifactory_single_replication_config.go#L90.

The `[]utils.ReplicationBody` should actually be wrapped inside another struct, as per the original code I contributed to the Atlassian library https://github.com/atlassian/go-artifactory/blob/6111b34bd09a5f74a3fb36a2a882687693c984a8/artifactory/v1/artifacts.go#L33-L38.

I've tried to unpick how to actually make things work here, but I'm having a hard time following how the Artifactory client by JFrog actually works, if it works at all with replication.

**Comment by chb0github** [comment]
Let me investigate.

**Comment by chb0github** [comment]
@jamestoyer - I see the problem and you're definitely right. That's a huge oversight. Wild that none of the tests cause this.

**Comment by chb0github** [comment]
Well, here is what I get when fetch a resource at the sam as the API:
```
christianb@christianb-mac terraform-provider-artifactory % curl http://localhost:8081/artifactory/api/system/version | jq .version                           
"7.24.3"
christianb@christianb-mac terraform-provider-artifactory % curl https://partnership.jfrog.io/artifactory/api/system/version | jq .version
"7.26.3"

```
the first is a self-hosted instance and the second a saas

And, here is fetching that one single repo

```bash
christianb@christianb-mac terraform-provider-artifactory % curl https://partnership.jfrog.io/artifactory/api/replications/art-docker2art-test | jq .
```
```json
[
  {
    "url": "https://johnp.jfrog.tech/artifactory/art-replicated/",
    "socketTimeoutMillis": 15000,
    "username": "admin",
    "password": "JE2coeftYghHegXzE6KMk7pud1FwNDBZjPPbkMzoLyy1u7AmSY",
    "syncStatistics": true,
    "enabled": true,
    "cronExp": "* * * * * ? *",
    "syncDeletes": true,
    "syncProperties": true,
    "repoKey": "art-docker2art-test",
    "replicationKey": "art-docker2art-test_ada5dfc641",
    "enableEventReplication": true,
    "checkBinaryExistenceInFilestore": false
  }
]
```
And here is the struct that backs this up:
```go
type ReplicationBody struct {
	Username               string `json:"username"`
	Password               string `json:"password"`
	URL                    string `json:"url"`
	CronExp                string `json:"cronExp"`
	RepoKey                string `json:"repoKey"`
	EnableEventReplication bool   `json:"enableEventReplication"`
	SocketTimeoutMillis    int    `json:"socketTimeoutMillis"`
	Enabled                bool   `json:"enabled"`
	SyncDeletes            bool   `json:"syncDeletes"`
	SyncProperties         bool   `json:"syncProperties"`
	SyncStatistics         bool   `json:"syncStatistics"`
	PathPrefix             string `json:"pathPrefix"`
}
```

@tdgeery - you're using a very old instance of artifactory, so it's going to be hard for me to confirm what's going on. But, based on the payloads here, the code in place now works fine and lines ups. I can't see any reason that outer wrapper would have ever have been needed. That outer wrapper looks like an abstraction layer and that explains why I could never find an analog to it in jfrog-client-go. Even if your company doesn't allow username/password login (using SAML or something like that), you can get credentials by generating an API key for yourself in you user profile (top right) -> edit profile -> generate API key. You can use this in lieu of your password. 

if you can capture the payload and put it here I can analize it


@jamestoyer - since you wrote that atlassian code, if you can explain what the wrapper was for, that'd be great. 

Finally: The API docs are wrong: 
It says payload is this:
GET /api/replications/libs-release-local
```json
{
  "url" : "http://localhost:8081/artifactory/remote-repo",
  "socketTimeoutMillis" : 15000,
  "username" : "admin",
  "password" : "password",
  "enableEventReplication" : false,
  "enabled" : true,
  "cronExp" : "0 0 12 * * ?",
  "syncDeletes" : true,
  "syncProperties" : true,
  "syncStatistics" : false,
  "repoKey" : "libs-release-local",   "replicationKey" : "generic-local_http__5d00703ade",
  "pathPrefix" : "/path/to/repo",
  "checkBinaryExistenceInFilestore" : false
}
```
This is what I get when I curl:
```bash
christianb@christianb-mac terraform-provider-artifactory % curl https://partnership.jfrog.io/artifactory/api/replications/art-docker2art-test | jq .               
```
```json
[
  {
    "url": "https://johnp.jfrog.tech/artifactory/art-replicated/",
    "socketTimeoutMillis": 15000,
    "username": "admin",
    "password": "JE2coeftYghHegXzE6KMk7pud1FwNDBZjPPbkMzoLyy1u7AmSY",
    "syncStatistics": true,
    "enabled": true,
    "cronExp": "* * * * * ? *",
    "syncDeletes": true,
    "syncProperties": true,
    "repoKey": "art-docker2art-test",
    "replicationKey": "art-docker2art-test_ada5dfc641",
    "enableEventReplication": true,
    "checkBinaryExistenceInFilestore": false
  }
]
```
Notice a subtle difference? The docs show it should produce a single entity (makes sense), but the returned payload is an array. 

My current thinking is an out-of-date artifactory and API

**Comment by chb0github** [comment]
It is an abstraction layer. But that doesn't explain a JSON serialization error

```go
	replicationConfig := new(ReplicationConfig)
	
	if len(replications) > 0 {
		replicationConfig.Replications = new([]SingleReplicationConfig)
	}
	
	for _, replication := range replications {
		replicationConfig.RepoKey = replication.RepoKey
		replicationConfig.CronExp = replication.CronExp
		replicationConfig.EnableEventReplication = replication.EnableEventReplication
	
		*replicationConfig.Replications = append(*replicationConfig.Replications, replication)
	}
```

**Comment by jamestoyer** [comment]
Ah, I think I've worked it out @chb0github. So the documentation is both right and wrong. For `remote` repositories, you can only have pull replication, which returns the following (this is taken from our cluster and anonymised)
```json
{
  "enabled" : true,
  "cronExp" : "0 0 0/6 ? * *",
  "syncDeletes" : true,
  "syncProperties" : true,
  "repoKey" : "libs-release-local",
  "replicationKey" : "generic-local_http__5d00703ade",
  "enableEventReplication" : false,
  "checkBinaryExistenceInFilestore" : false
}
```

However, you can also enable push replication, and that is what I think you're seeing with your list of replications being returned. Pull replication can only be enabled on `remote` repositories whilst push replication can be enabled on many. I suspect the reason it fails now is that the JSON parser before was more forgiving. 

For reference we're running 7.25.7.

**Comment by chb0github** [comment]
I think I remember seeing some code that explains this. Let me see if I can resurrect it

**Comment by chb0github** [comment]
I am ready to give this a test, but I need you to give me a copy-and-paste example. What you've supplied has externals I don't have access to

**Comment by jamestoyer** [comment]
@chb0github I just switched out the `repoKey` and `replicationKey` from the examples you posted in https://github.com/jfrog/terraform-provider-artifactory/issues/133#issuecomment-922114572. To ETE test I think all you need is to set up a new repository of type remote, then you'd set up pull replication on it. The upstream repo doesn't need to actually exist for testing

**Comment by chb0github** [comment]
I have working code and I am trying to get some acceptance tests together. With luck this fix will be out today

**Comment by chb0github** [comment]
will release with 2.6.5
