### ISSUE TITLE
artifactory_group auto_join=true should not import all users_names

### ISSUE THREAD

**Issue by spuder** [jfrog/terraform-provider-artifactory#135]
Upgraded from module 2.2.4 to 2.3.6 

We now find that importing an artifactory group includes _all_ users in that group which is undesireable

Using `auto_join = true` and manually defining users with `users_names` should be mutually exclusive. Otherwise you run into this scenarios where terraform tries to import and manage all users. 

```
resource "artifactory_group" "debian-read" {
  name      = "debian-read"
  auto_join = true
}
```

```
terraform state rm artifactory_group.debian-read
terraform import artifactory_group.debian-read debian-read
```

```
  # artifactory_group.debian-read will be updated in-place
  ~ resource "artifactory_group" "debian-read" {
        id               = "debian-read"
        name             = "debian-read"
      ~ users_names      = [
          - "adam.readacted",
          - "bob.readacted",
          - "charlie.readacted",
          - "daisey.readacted",
          - "erica.readacted",
          - "anonymous",
```

This is not ideal since we have hundreds of users that were automatically added to the group that terraform is trying to manage now. 
Specifying `users_names` should be mutually exclusive with `autojoin=true`. If the latter is specified, then `users_names` should be ignored.

**Comment by chb0github** [comment]
I am seeing that your coming from v2.2.4 - the latest v2.2.x release was v2.2.15 and 2.3.x is derived from that. The version you're migrating from is almost a year old. 

When I was working on 2.3.x, I tried to be as faithful as possible to the original implementation. Deviations from time-to-time were a necessity. 

Can you please try and reproduce this on 2.2.15 and report your results? The exact same endpoint is being used now as then

**Comment by spuder** [comment]
Thanks for the feedback. I've only got one artifactory server which is our production instance. I'm hesitant to downgrade our module since I don't know what that would do to our state file. 

It appears that terraform isn't actually modifying `users_names` for this resource. Looking at the comments it appears that we are hitting this edge case where `Update` tries to use the `POST` api and doesn't actually update anything

https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource_artifactory_group.go#L167

I would prefer a feature request that if `auto_join==true`, then `users_names` is just ignored.

I've temporarily worked around the issue with this alternative syntax


```
resource "artifactory_group" "debian-read" {
  name      = "debian-read"
  auto_join = true
    lifecycle {
    ignore_changes = ["users_names"]
  }
}
```

**Comment by chb0github** [comment]
Thanks for the update. Without some comparative analysis to 2.2.15, I can't know if this is a bug or not. If you want to change the provider version and give it another go, and give me the results, then I can have a think. For now, since you have a fairly straightforward workaround, and no one else has brought this up, I am going to leave this issue back to hang

**Comment by chb0github** [comment]
If you can show me this issue occurring with 2.2.15 and give me more to go on, then please reopen
