### ISSUE TITLE
Support Cargo repository management

### ISSUE THREAD

**Issue by asvoboda** [jfrog/terraform-provider-artifactory#141]
As of [7.17.4](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.17.4), Artifactory supports native management of cargo repos. 

**Describe the bug**
The terraform-provider-artifactory does not support cargo repos.

**Expected behavior**
As of https://github.com/jfrog/jfrog-client-go/pull/375, it looks like Cargo repos are now supported by jfrog-client-go. The terraform provider should also be able to support cargo out of the box.

**Comment by asvoboda** [comment]
Sorry @chb0github , I meant to file this as an FR not a bug.

**Comment by chb0github** [comment]
It's fine, I changed it. This is under the umbrella of "repo specific features". If I can clear the deck of all recent bugs, then I am move on to features

**Comment by chb0github** [comment]
I looked at your link to client-go - it refers to federated repos and nothing about cargo
