### ISSUE TITLE
Invalid 2.6.x versions on Terraform registry

### ISSUE THREAD

**Issue by bendrucker** [jfrog/terraform-provider-artifactory#147]
**Describe the bug**

The Terraform registry has a bunch of 2.6.x versions of this provider published in the last few days. These versions aren't in this repo's GitHub releases and aren't installable.

https://registry.terraform.io/providers/jfrog/artifactory/latest

```tf
terraform {
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
      version = "~> 2.3"
    }
  }
}
```

```sh
terraform version && terraform init
```

```
Terraform v1.0.7
on darwin_amd64

Initializing the backend...

Initializing provider plugins...
- Finding jfrog/artifactory versions matching "~> 2.3"...
╷
│ Error: Failed to install provider
│
│ Error while installing jfrog/artifactory v2.6.4: could not query provider
│ registry for registry.terraform.io/jfrog/artifactory: failed to retrieve
│ authentication checksums for provider: 404 Not Found
╵
```

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform

**Expected behavior**
Successful installation of 2.3.10

**Comment by chb0github** [comment]
@danielmkn - Yes, we are aware.  I am not sure what to do about it. We had some automation go crazy. I don't know if they can be removed from the TF registry. I am open to suggestions

**Comment by bendrucker** [comment]
You could try a re-sync from the registry, that might see the missing releases and remove the versions. I don't see a way to delete specific versions so if re-syncing doesn't work I think you'd either have to get help from HashiCorp or just move to 2.6.x (or 2.7.x).

**Comment by chb0github** [comment]
My plan was to just start releasing from 2.6.x

**Comment by chb0github** [comment]
This should be fixed. Let me know if you continue to have issues
