### ISSUE TITLE
[Feature] Support for argument "force_maven_authentication" for virtual repositories

### ISSUE THREAD

**Issue by skrgoesgit** [jfrog/terraform-provider-artifactory#149]
Dear Artifactory developers, could you please add the argument "force_maven_authentication" for virtual repositories of package type "Maven" the same way as the provider currently supports "force_nuget_authentication"?

Thank you very much.

**Comment by chb0github** [comment]
Support for repo specific features is on the roadmap.

**Comment by chb0github** [comment]
Your feature has been implemented. It will be released within the day

**Comment by skrgoesgit** [comment]
Thank you very much.
Have a nice day.
