### ISSUE TITLE
[DISCUSSION]: Move xray code to it's own provider

### ISSUE THREAD

**Issue by chb0github** [jfrog/terraform-provider-artifactory#160]
It's currently under consideration to move the xray portion of the provider to it's own TF provider package. This has some advtanages:

1. Less code clutter in the current code base. Artifactory is a much for feature rich product and takes up the vast portion of this code base.
2. Currently xray can't be deployed locally (if someone has a local RT+XR setup it would be welcome). Which means that testing is much more complicated as it requires a dedicated stack.
3. Some users have remapped their infrastructure and `/artifactory` doesn't resolve to the default API path. This can be more easily addressed if 1 provider doesn't have to accomodate multiple product lines as each could have their own config.

This is an open commentary request from the community

**Comment by skyzyx** [comment]
Great idea. Done. Ship it. 🚢

**Comment by antonmos** [comment]
New provider is at https://github.com/jfrog/terraform-provider-xray

**Comment by jasonwbarnett** [comment]
@chb0github for what it's worth, I am strongly in favor of this. I think it makes a lot of sense.

**Comment by chb0github** [comment]
Yeah, and it's been released. Have a look and give input
