### ISSUE TITLE
Add support for RSA Key for Alpine Linux repos

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#161]
**Describe the bug**
In the UI, when creating a new Alpine Linux repo, you can select a pre-uploaded RSA key to use for signing.

Such an option is neither documented in <https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_local_repository> or <https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON>. Or, if it is, it's unclear.

**Requirements for and issue**
- [X] Snippet:

    ```hcl
    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_local_repository
    # https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON
    resource "artifactory_local_repository" "alpine_local" {
        key             = "alpine-local"
        package_type    = "alpine"
        repo_layout_ref = "simple-default"

        includes_pattern = "**/*"
        excludes_pattern = ""

        checksum_policy_type     = "server-generated-checksums"
        blacked_out              = false
        archive_browsing_enabled = true
        xray_index               = true

        # RSA Key for Alpine Linux repos?
    }
    ```

- [X] Artifactory v7.24.3
- [X] Terraform version:

    ```plain
    Terraform v1.0.7
    on darwin_amd64
    + provider registry.terraform.io/jfrog/artifactory v2.6.7
    ```

**Expected behavior**

There is a clear description of the parameter which allows me to set the RSA key to use for signing the Alpine Linux repo. Also, that what is described _actually works_.

**Comment by chb0github** [comment]
This isn't a bug. The current TF implementation tries to just pile a bunch of crap into a "repo" - some of the fields are repo-type specific and some aren't. This is one of those repo specific fields. 

I began working this week and being able to roll out repo-specific support. This can be added in

side note: I read over the documentation and it isn't very clear. I can tell you for certain though that there is some functionality on the UI (and the endpoints it uses) that have no analog in the official APIs. And, shamefully, I have had to reverse engineer UI endpoints to get things done and use those.

**Comment by skyzyx** [comment]
> I can tell you for certain though that there is some functionality on the UI (and the endpoints it uses) that have no analog in the official APIs. And, shamefully, I have had to reverse engineer UI endpoints to get things done and use those.

I've had to delay our roll-out of Artifactory because there are so many places where it doesn't do what it says on the tin (neither the wiki-based documentation, nor the splashy marketing website), and as I've been working through the nuts and bolts of the implementation, we're definitely squeezing every last dollar out of our support contract. It's disappointing that JFrog treats their customers this way, but after the responses I've received from JFrog support about things that are broken, I can't say I'm surprised.

> The current TF implementation tries to just pile a bunch of crap into a "repo" - some of the fields are repo-type specific and some aren't. This is one of those repo specific fields.
>
> I began working this week and being able to roll out repo-specific support. This can be added in

Yeah, I was able to discern this from looking over https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON; it's pretty obvious that you're meant to throw shit at the API to see what sticks. :)

Thanks for taking a look.

**Comment by chb0github** [comment]
As an official employee, I can only say so much. But, I recognize your plight and I am doing my part to try to make it better. I will forward your comments along. I doubt it's gonna shake things up, but at least you'll be heard

**Comment by skyzyx** [comment]
> As an official employee, I can only say so much.

Understood.

> But, I recognize your plight and I am doing my part to try to make it better. I will forward your comments along. I doubt it's gonna shake things up, but at least you'll be heard.

That's all I can ask. I was in the same boat when I worked at AWS on the SDK team. I recognized the plight of developers, and did whatever I could to make it better. Sometimes, I was told by management to sit down and shut up. Then again, sometimes I was successful.

Thank you. I appreciate the response. Sincerely.

**Comment by chb0github** [comment]
I used to work at amazon too... those were hard times

**Comment by chb0github** [comment]
This is in progress
