### ISSUE TITLE
[Question] Smoothing-over underlying API changes?

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#168]
Breaking out from #167 —

My preference would be that these Terraform resources are _use-case_ oriented, rather than a 1:1 map of the API. One example is that as a new API is built to replace functionality provided by an older API, that the Provider will smooth-over those changes so that I don't have to change my HCL configuration (as much as possible, anyway).

Is this the case? Is there a philosophy/methodology that you apply for things like this?

**Comment by chb0github** [comment]
I am orienting them toward use-case. 

For example: The current way repositories are managed is basically as a glob that's thrown at the API. Right now it's a mix of repo specific flags for several different repo types and a generic repository. I have started to implement repository specific resources like `artifactory_virtual_maven_repository` which specifically allows for things like `force_authentication` - it's a feature only available to maven repos. And, non-sense fields like `force_nuget_authentication` on a maven repo just aren't even available. 

As far as APIs: The intent it to keep the provider HCL consistent even when/if APIs change; though API changes drastic enough that would make this a challenge are very rare. Even when a V1 api is "deprecated" it seems to stick around forever. 

So, **philosophy** 
1. specific resources for specific cases
2. keep the HCL consistent. If that's just not tenable, deprecate and major version bump
