### ISSUE TITLE
[Question] Provider docs

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#169]
Breaking out from #167 —

Presently, the [REST API documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API) has lots of words, but there are a great-many gotchas that are undocumented.

When it comes to the [provider docs](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs):

* Is it reasonable to expect that nuances missing from the REST API docs will be clarified and improved here?
* Alternatively, should I anticipate roughly equivalent quality to the REST API docs in the Provider docs?
* If we run into issues or unclear areas in the docs, can we open an issue/PR here?

**Comment by chb0github** [comment]
1. You assume that I have somehow figured out the great mysteries myself! I am from the school of "full disclosure". So, as much as it may not paint other teams at jfrog in the prettiest of lights, I feel an obligation to point out discrepancies. 

For example: In a previous issue you had asked / mentioned about creating `AUTH_TOKENS` and mentioned how there was no way through APIs to do this, but it's needed to actually make some APIs work (xray and projects, as example). I know for a _fact_ it's not possible through the documented API to create `AUTH_TOKEN`s - internally we have been able to do it by reverse engineering the UI endpoints (which are entirely different) and using those. 

So, if I were to implement it, I would actually do just that but emit warnings that said resource uses undocumented APIs (the oauth code in this repo does just that) and that it's subject to change without notice. 

BTW: You can only create xray webhooks through the UI as well.

2:. I frankly don't understand the APIs and fields much better than most. I have access to the same documentation you do; just the public wiki. So, when I discover something divergent enough to note, I will make note of it. I have in fact found entirely undocumented fields in the API and reverse engineered and documented them and their usage based strictly on observation and no actual knowledge of the underlying code. 

3. If you find some documentation that is unclear, please, offer improvement.  I can write code or docs. I have been focusing on code and documenting as I go. And, to be honest, I can't document things even I don't understand.

**Comment by skyzyx** [comment]
I wanted to ask this question specifically because, at AWS, all of the SDKs and their documentation are (for the most part) generated from internal models of the services and documentation is added at that level. So changing/improving documentation is far more difficult once the code lands in GitHub.

But I greatly appreciate the answer, and appreciate your approach. We need more engineers like this in the world.
