### ISSUE TITLE
[Request] Contribution Guide

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#172]
For those who are interested in contributing, what would be the best way to orient new developers onto this project? Pretending I'm a new team-mate on his first day at JFrog, what would that person need to know about how this software works, is built, what the internal flow of the software is, how to run tests, etc.?

Here are some really great examples that have helped greatly lower the bar to contribution:

* https://golangci-lint.run/contributing/architecture/
* https://github.com/serverless/serverless/blob/master/docs/anatomy.md

Could something like this be added to `CONTRIBUTING.md`? Where that document becomes the canonical contributor documentation for internal + external contributors (as much as possible, anyway)?

**Comment by skyzyx** [comment]
I'm certainly open to it, since this is a piece of software I really want to be able to lean on (_grumbles_ about the REST API), but that also means that _I_ need to go through the process of figuring it out. :)

Let me see what I have bandwidth for. 👍🏻

**Comment by chb0github** [comment]
I hear you about the "REST" apis. I mean, I know 15 years into the "REST" revolution the debate still rages between `PUT` vs `PATCH` and if `GET` can or even should have a body. But it wasn't until working with our APIs that I realised some people had missed class and were using `PUT` for create/update, and `POST` for update as well, but only for the really really important fields. `GET` can produce 400, 404 or 500 when the resource doesn't exist. Just depends on the day

**Comment by chb0github** [comment]
@skyzyx - Did you want to make a contribution?

**Comment by skyzyx** [comment]
Yes. I had to switch gears and work on a different project for a few weeks, but I'm switching back to Artifactory work next week.

**Comment by chb0github** [comment]
@skyzyx great! This project is going to be handed off and it's finally getting the attention it deserves. We are going from 1 -> 3 people supporting TF. 

As an FYI (unrelated): We are carving out XRAY into it's [own provider](https://github.com/jfrog/terraform-provider-xray), as well as a [provider for projects](https://github.com/jfrog/terraform-provider-projects) and I encourage you to participate in the drafting phase. The xray provider is going entirely toward v2 apis and the xray code in artifactory is going to be entirely purged coming up.

**Comment by alexhung** [comment]
@skyzyx I'm closing this issue since there hasn't been any activity since Nov. Feel free to re-open this issue when you are ready to contribute and have a PR for review.
