### ISSUE TITLE
Datasource for local and remote repositories

### ISSUE THREAD

**Issue by coreyjackwilson** [jfrog/terraform-provider-artifactory#179]
**Is your feature request related to a problem? Please describe.**
I want to re-use remote repositories between by artifactory stacks that are separated by service (e.g. identity-service). If i want to re-use the same remote repository across stacks, I need to reference it by string in the virtual repository definition.

**Describe the solution you'd like**
I want a datasource to lookup the repositories (at least remote) so I can get the key.

**Describe alternatives you've considered**
I use a list of string to track all the remotes for maven, debs, etc and then just copy that sting across variables.tf across stacks.

**Comment by chb0github** [comment]
Can you give me some free-form HCL you'd like to see work?

**Comment by chb0github** [comment]
I meant more like, show we the interaction you want between the 2 stacks

**Comment by chb0github** [comment]
FYI: This will close in a week without additional input
