### ISSUE TITLE
artifactory_user resource does not persist changes to `groups`

### ISSUE THREAD

**Issue by antonmos** [jfrog/terraform-provider-artifactory#191]
**Describe the bug**

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
using SaaS Artifactory
```
  "version" : "7.23.4",
  "revision" : "72304900",
```
- [x] Your version of terraform
```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/jfrog/artifactory v2.6.13
```

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.0"
    }
    artifactory = {
      source  = "jfrog/artifactory"
      version = ">= 2"
    }
  }
}
resource "artifactory_user" "admin" {
  name  = "admin"
  admin = true
  email = "foo@bar.com"
  lifecycle {
    ignore_changes = [password]
  }
}
```

**Expected behavior**
The initial state of the admin user in the UI is `member of "readers" group'

the generated plan is 
```
 # artifactory_user.admin will be updated in-place
  ~ resource "artifactory_user" "admin" {
        admin                      = true
        disable_ui_access          = false
        email                      = "foo@bar.com"
      ~ groups                     = [
          - "readers",
        ]
        id                         = "admin"
        internal_password_disabled = false
        name                       = "admin"
        profile_updatable          = true
    }

```
Expected: After the plan is applied, the user is not a member of "readers" group.
Actual: After the plan is applied, the user is still member of "readers" group.

**Comment by maheshjfrog** [comment]
Hi @antonmos  ... 
In Artifactory, The default group 'readers' will have the option "Automatically join new user to this group" set to true by default. So, When a user is created it will be automatically added the 'readers' group.
This will explain why you see the user getting the 'readers' group automatically.

Also, recently (ie: Jan 27, 2022) the user resource's struct handling was updated to take out 'omitempty' setting so the default fields are passed to RT without omitting fields.

**Comment by danielmkn** [comment]
Maybe we need to ignore the group field verification?

**Comment by alexhung** [comment]
The state drift for `groups` is because we don't have a `DefaultFunc` for `groups` and set the `readers`. If we have that then TF won't detect the drift.
