### ISSUE TITLE
LDAP config

### ISSUE THREAD

**Issue by pbecotte** [jfrog/terraform-provider-artifactory#193]
It would be appreciated to add ldapSettings and ldapGroupSettings to one of the resources.

**Comment by TJM** [comment]
What is the status on this? We can see that the OIDC authentication stuff is there, but without groups, that makes permissions a nightmare. We do not want to have to manage/create all the groups locally in Artifactory, that is why we have tools like LDAP :)

**Comment by maheshjfrog** [comment]
Working on this LDAP config support. Will update this thread soon.

**Comment by alexhung** [comment]
@pbecotte @TJM LDAP support is released as part of [v2.9.0](https://github.com/jfrog/terraform-provider-artifactory/releases/tag/v2.9.0)

We are looking forward to your feedback!
