### ISSUE TITLE
artifactory_virtual_repository and artifactory_virtual_go_repository does not persist removing of default_deployment_repo

### ISSUE THREAD

**Issue by antonmos** [jfrog/terraform-provider-artifactory#194]
**Describe the bug**

artifactory_virtual_repository and artifactory_virtual_go_repository does not persist removing of default_deployment_repo

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
using SaaS Artifactory
```
  "version" : "7.23.4",
  "revision" : "72304900",
```
- [x] Your version of terraform
```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/jfrog/artifactory v2.6.13
```

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.0"
    }
    artifactory = {
      source  = "jfrog/artifactory"
      version = ">= 2"
    }
  }
}
 resource "artifactory_virtual_go_repository" "test-repo" {
   key                                                = "test-repo"
   external_dependencies_enabled = true
   external_dependencies_patterns                     = [
     "**/github.com/**",
     "**/go.googlesource.com/**",
     "**/golang.org/**",
     "**/gopkg.in/**",
     "**/k8s.io/**",
   ]
   repositories                                       = [
      "go-local",
      "public-go",
    ]
  }
```

**Expected behavior**
The initial state of the admin user in the UI is `default_deployment_repo                            = "go-local"`

the generated plan is 
```
   # artifactory_virtual_go_repository.test-repo will be updated in-place
  ~ resource "artifactory_virtual_go_repository" "test-repo" {
        artifactory_requests_can_retrieve_remote_artifacts = false
      - default_deployment_repo                            = "go-local" -> null
        external_dependencies_enabled                      = true
        external_dependencies_patterns                     = [
            "**/github.com/**",
            "**/go.googlesource.com/**",
            "**/golang.org/**",
            "**/gopkg.in/**",
            "**/k8s.io/**",
        ]
        id                                                 = "test-repo"
        includes_pattern                                   = "**/*"
        key                                                = "test-repo"
        package_type                                       = "go"
        repositories                                       = [
            "go-local",
            "public-go",
        ]
    }
```
Expected: After the plan is applied, default_deployment_repo is set to blank.
Actual: After the plan is applied, default_deployment_repo is still "go-local"`

**Comment by alexhung** [comment]
@antonmos This is caused by the current Artifactory REST API unable to clear out `defaultDeploymentRepo` value when updating the repository configuration with any sensible value.

You can test this out yourself by making a `POST /api/repositories/{repoKey}` request with `defaultDeploymentRepo` set to `""`, `null`, or omit the key. None of them will have any effect.

However, if you set `defaultDeploymentRepo` to a repo key that doesn't exist, the POST request will still be successful and the `defaultDeploymentRepo` is now reset to default.

I've opened a bug ticket with the Artifactory team but I'll apply this workaround to resolve the issue for the time being.
