### ISSUE TITLE
Add GPG support for Debian repo

### ISSUE THREAD

**Issue by korjek** [jfrog/terraform-provider-artifactory#198]
RIght now there is no way to specify gpg key for Debian repo with Artifatory terraform provider. So Debian repo which is created by Terraform requires an additional manual step to specify GPG key using Artifactory API/UI.

It would be great if GPG key for Debian repo could be specified in Terraform.

**Comment by chb0github** [comment]
#199 - This will be merged on Monday

**Comment by chb0github** [comment]
supported in 2.6.17

**Comment by korjek** [comment]
Awesome! Thanx alot!
