### ISSUE TITLE
Lifecycle ignore_changes for password is not ignored and breaks the replication password resulting in the 401 Unauthorized

### ISSUE THREAD

**Issue by peters95** [jfrog/terraform-provider-artifactory#20]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- 0.12.24
- 0.12.29

### Affected Resource(s)

* artifactory_replication_config

### Terraform Configuration Files

```hcl
resource "artifactory_replication_config" "npm-test" {
  repo_key                 = artifactory_local_repository.npm-test.key
  cron_exp                 = "0 0 6,23 ? * * *"
  enable_event_replication = false

  replications {
    enabled               = true
    socket_timeout_millis = 15000
    sync_deletes          = true
    sync_properties       = true
    sync_statistics       = true
    url                   = "https://art-instance.com/artifactory/npm-test/"
    username              = "username"
  }

  lifecycle {
    ignore_changes = [
      replications.0.password
    ]
  }

}
```

### Debug Output

[Gist link](https://gist.github.com/MyKEms/a8e770c0747b7f2036d71afb7ce5f6fe)

### Expected Behavior

- If artifactory_replication_config has defined:

```hcl
  lifecycle {
    ignore_changes = [
      replications.0.password
    ]
  }
```

- Password should be never updated.

### Actual Behavior

- If you don't use decrypted passwords in the artifactory and you specify to ignore password with:

```hcl
  lifecycle {
    ignore_changes = [
      replications.0.password
    ]
  }
```

- Then you will modify replication (in this case just enable from disabled state) and apply via terraform:

```hcl
# artifactory_replication_config.npm-test will be updated in-place
  ~ resource "artifactory_replication_config" "npm-test" {
        cron_exp                 = "0 0 6,23 ? * * *"
        enable_event_replication = false
        id                       = "npm-test"
        repo_key                 = "npm-test"

      ~ replications {
          ~ enabled               = false -> true
            password              = (sensitive value)
            socket_timeout_millis = 15000
            sync_deletes          = true
            sync_properties       = true
            sync_statistics       = true
            url                   = "https://art-instance.com/artifactory/npm-test/"
            username              = "username"
        }
    }
```
- Replication will be set according to the terraform plan **but password will be also set with random hashed value**. By this replication will stop to work with **_Connection failed: Target replication URL returned error 401: Unauthorized_**

### Steps to Reproduce

1. Define artifactory_local_repository + artifactory_replication_config with the ignore_changes for the password.
2. `terraform apply`
3. Check the replication settings in the artifactory and hit the test button - you will receive _401: Unauthorized_

### Important Factoids

- This could be related to the https://github.com/hashicorp/terraform/issues/21433
- [Lifecycle configuration in this repository is invalid for 0.12.X](https://github.com/atlassian/terraform-provider-artifactory/blob/master/website/docs/r/artifactory_replication_config.html.markdown#passwords). Needs to be used `    ignore_changes = [replications.0.password]` instead of `ignore_changes = ["password"]`

### References

* https://github.com/hashicorp/terraform/issues/21433
* https://github.com/hashicorp/terraform/pull/21788

**Comment by chb0github** [comment]
I will look into this - if it's urgent, and you're a paying customer of jfrog, please create a support ticket - this seems to get some people's attention

**Comment by chb0github** [comment]
I will leave this issue open and wait for more users to upvote this issue

**Comment by michael-sabrnak-swi** [comment]
Hi @chb0github, support case with number `171896` was created. Thanks.

**Comment by chb0github** [comment]
@michael-sabrnak-swi and you see, I have received received word and it's getting attention :)

**Comment by chb0github** [comment]
Ok, I have discovered the problem (but not the solution)

Locally, TF computes the state of every property, including the password for replications. Currently it uses a salted MD5; I have no idea why the salt is used. 

As some point, RT started sending back scrambled passwords when the replication was fetched and it's using and it isn't using a discernible algorithm that I can replicate. 

So, given the password `password`:
locally 
`password` ->  `fd7bdc67a81cc7e56688a6a5a9cc3b56bc9927d787fcc1f7e69060b23be5917d`, which is a salted MD5
from RT:
`password` ->  `JE2fNsEThvb1buiH7h7S2RDsGWSdp2EcuG9Pky5AFyRMwE4UzG`

until and if I can get information on how to line up the local state with the RT state this will remain broken - 

It's only been a few times in my career where I can legitimately say something _can't_ be fixed, but this would be one of those times if I can't get these details

**Comment by chb0github** [comment]
To get extra traction, please create a support ticket

**Comment by chb0github** [comment]
Ok, I have gotten official input from the RT team. At some point in the past they decided to encrypt the password and that's what comes back (I suspected). But in addition, they use a rotating key system as per best practices. I won't waste my time asking for a hashed, but consistent, version. It took me 30 days to get an answer

So, in a nutshell: this field can no longer be tracked. The best thing to do is literally just delete the password field from the TF provider and not even allow it to be managed. You could create the replication with a password but TF would frequently. Before I take any steps on this I will offer some time for comment.

**Comment by michael-sabrnak-swi** [comment]
Thanks for the explanation @chb0github . Is somehow possible to just ignore the password field? I mean we need to have configured replication via TF + provide password otherwise TF will remove it if no password provided, right. So if this would work as expected:

```hcl
  lifecycle {
    ignore_changes = [
      replications.0.password
    ]
  }
```

it would be great. On a background, terraform will change the replication password even lifecycle should be ignored and I don't understand why.

**Comment by chb0github** [comment]
So, the problem is this:

config replication in TF with password -> send to rt -> rt responds with encrypted pass -> terraform sees a diff and does a sync -> we just accept the encrypted pass as the real pass and be done.

At some point later, the key rotates, so the password changes and TF does a sync because "password" has changed (but, actually it hasn't, the key has just rotated). 

I just don't see a way you can use the password for the initial setup, but then ignore it from then on. It's either part of the state, or it's not. And, once submitted, you're never gonna get the password back, so you won't ever notice if it's actually changed, but TF will think it has

**Comment by michael-sabrnak-swi** [comment]
I see. So there is no easy workaround for this. We have few artifactory instances and we need to use replications with a password defined. We have the password saved as a code in TF (SOPSed) therefore we don't care much if TF will change the password to the same values, it's just annoying in plan output and ignoring these changes...

I guess the only solution would be to disable artifactory internal encryption via [API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-DeactivateArtifactoryKeyEncryption) and then TF will see raw values. This on the other hand brings security risk.

**Comment by chb0github** [comment]
Well, I spoke with the team: If you can get the master.key (which is just in a file) then you can decrypt this. I could offer that as an option (seems they DONT rotate keys, but I am told some admins will rotate them). I mean, I still don't have the algo they use so even if you had the key, there is nothing I could do

Honestly, I think just marking this field as computed and being done with it is the way to go.

**Comment by chb0github** [comment]
Ok, I have looked at this ticket long enough - password is going to become computed and you won't be able to edit it. Sorry.

**Comment by chb0github** [comment]
#206

**Comment by chb0github** [comment]
will be updated in 2.6.18
