### ISSUE TITLE
Anonymous authentication

### ISSUE THREAD

**Issue by jornfranke** [jfrog/terraform-provider-artifactory#218]
**Is your feature request related to a problem? Please describe.**

I would like to fetch an artifact in Jfrog Artifactory, but without the need to provide username and password. The registry is internally open, but the Terraform provider always forces me to put some credentials.

**Describe the solution you'd like**

I can simply define the provider without the need to authenticate, e.g.
```
provider "artifactory" {
 url = "https://myinternaljfrogartifactory"
}
```

**Describe alternatives you've considered**
Managing authentication credentials for artifacts that are internally anyway open means additional effort - also to store them securely in a secret vault etc.
Some public sources may not have authentication needs as well.

**Additional context**

**Comment by chb0github** [comment]
This question comes up from time-to-time and the answer is the same: Unfortunately this won't be implemented, but the change is easy to implement in a fork (remove the username and password validator in the schema in `provider.go`)

Terraform is all about resource creation/destruction - it's one of the few cases where an app's primary job isn't to _read_ data. The creation and destruction of resources can cause outages and spike cloud bills by 10's or 100's of thousands of dollars; someone has to be accountable for that. 

If your instance is that open and inside some super-secure network, then usage of the default username/password (`admin`:`password`) should work - it's what we use to test. 

Sorry we won't be able to implement this

**Comment by alexhung** [comment]
@jornfranke Can you provide a use case for fetching artifact from Artifactory using the provider?

**Comment by jornfranke** [comment]
Thanks for looking into this. Unfortunately using admin:password even in very secure networks is for us not adviseable and I do not recommend this to anyone.

We essentially use the Jfrog provider only to fetch packages from artifactory, e.g. to fetch serverless function packages. We do not use it to create infrastructure. 

We found a workaround with anonymous access.

**Comment by chb0github** [comment]
To be clear: I don't recommend it either. But, for what you're trying to do, you can actually use a [basic http/curl command](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http). At the end of the day, artifactory talks http (only)
```hcl
data "http" "example" {
  url = "https://checkpoint-api.hashicorp.com/v1/check/terraform"

  # Optional request headers
  request_headers = {
    Accept = "application/json"
  }
}
```

Although, looking at the provider documentation, for your case it probably wouldn't work because you are certainly downloading a jar or zip files and the content type won't line up.
