### ISSUE TITLE
[FEATURE] Do not query Artifactory server when initializing the provider

### ISSUE THREAD

**Issue by generalov** [jfrog/terraform-provider-artifactory#224]
I added jfrog/artifactory v2.6.20 provider to fetch optional artifacts from Artifactory server using the `data.artifactory_fileinfo` data source.

```terraform
variable "artifactory_api_key" {
   type    = string
   default = null
}

provider "artifactory" {
  url      = "https://<artifactory>" 
  api_key  = var.artifactory_api_key # this may be empty because Artifactory is not allowed to be used in this environment
}

data "artifactory_fileinfo" "test" {
  count var.artifactory_api_key != null ? 1 : 0

  repository = "repo"
  path       = "path/to/archive.zip"
}
```

Expected: `terraform plan` works fine when "artifactory_api_key" variable is not set
Actual: `terraform plan` fails with an error message

The issue comes from the providers implementation here https://github.com/jfrog/terraform-provider-artifactory/blob/a4480d76bb5abfd2d452b433af887b718f71c75d/pkg/artifactory/provider.go#L193-L197

During intialization, the provider checks credentials and then sends a request to the "artifactory/api/system/usage" artifactory server endpoint (this seems to be a kind of telemetry data).

A workaround cannot be implemented because of the terraform does not support optional providers (https://github.com/hashicorp/terraform/issues/9448). That's why I'm looking for a solution from your side. If the "usage" telemetry request which is require a user to be authenticated anyway cannot be omitted on the provider initialization phase, I'll have to look for another solution without using `jfrog/artifactory` at all. However I would prefer to use the offical Artifactory terraform provider.

Let me suggest a couple of ideas for a possible solution so you still get your piece of the usage data: 
a) Add an ability to the provier for skipping the credentials verification during initialization (this could also solve https://github.com/jfrog/terraform-provider-artifactory/issues/218)
b) Send a telemetry request to Artifactory on the first request for any artifactory `data` or `resource`, not during the provider initialization phase (this may be related to https://github.com/jfrog/terraform-provider-artifactory/issues/75).

**Comment by chb0github** [comment]
I have discussed this with @alexhung - the solution would be to move the telemetry down to the CRUD operations per resource (which, is actually better because it tells us which resources are being managed and how often). 

It's some work, but not impossible.

**Comment by chb0github** [comment]
@alexhung - I created a sample implementation for this on GH-224-push-telemtry-down

**Comment by chb0github** [comment]
@alexhung did we ever make progress on this?

**Comment by alexhung** [comment]
@chb0github JIRA ticket created but not scheduled for development yet.

**Comment by chb0github** [comment]
You know, we are revisiting this ticket and I have reread this problem a few times now. 

When you do `terraform plan` terraform _must_ query the state of the resources in the `hcl` file in order to determine what the `plan` is - this directory implies `GET` on the resource state which also implies *you must already be authorized*. 

So, I am going to state my current understanding of the problem just to make sure we're on the same page:
- You want to be able to do `terraform plan` without having to authenticate?

If that's the case, that's just impossible as the plan could never determine a state diff without being authed. Please confirm
