### ISSUE TITLE
Downloading jars using the artifactory_file requires the exact jar name in the "path" 

### ISSUE THREAD

**Issue by elinafl** [jfrog/terraform-provider-artifactory#227]
**Description:**
When attempting to download jar files from a local snapshot repository, it appears that the exact jar name is expected, or else a 404 response is received. Downloading the file using cURL without specifying the exact snapshot name (with the timestamp) returns the latest file with this name from the repository. With terraform, the full name should be mentioned (for instance, multi1-3.7-20210914.114327-1.jar).

_cURL request that succeeds:_
`curl https://<ART_HOST>/artifactory/test-libs-snapshot-local/org/jfrog/test/multi1/3.7-SNAPSHOT/multi1-3.7-SNAPSHOT.jar -o multi1-3.7-20210914.114327-1.jar`

_Files in the tree view:_
![image](https://user-images.githubusercontent.com/81092704/144403505-e7d974e8-9ba4-4fc5-8d1f-ac9d6662091d.png)

_Output from terraform:_
`Error:
│ 404 GET https://elinaf.jfrog.io/artifactory/api/storage/test-libs-snapshot-local/org/jfrog/test/multi1/3.7-SNAPSHOT/multi1-3.7-SNAPSHOT.jar
│ {
│   "errors" : [ {
│     "status" : 404,
│     "message" : "Unable to find item"
│   } ]
│ }
│
│   with data.artifactory_file.my-file,
│   on test.tf line 16, in data "artifactory_file" "my-file":
│   16: data "artifactory_file" "my-file" {
│`

```hcl
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "2.6.17"
    }
  }
}

provider "artifactory" {
  url = "https://<ART_HOST>/artifactory"
  username = "admin"
  password = "<password>"
}
data "artifactory_file" "my-file" {
   repository = "test-libs-snapshot-local"
   path = "org/jfrog/test/multi1/3.7-SNAPSHOT/multi1-3.7-20210914.114327-1.jar"
   output_path = "tmp/multi-3.7-SNAPSHOT.jar"
}
```

**Requirements for and issue**
Artifactory version: 7.26.3, 7.24.3
Terraform version: Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/jfrog/artifactory v2.6.17

**Expected behavior**
It is expected that the jar file will be resolved as it is resolved using the cURL request. In this case, when specifying the full jar name, terraform is able to download the jar file.

**Comment by alexhung** [comment]
@elinafl From the description I can't determine if this is provider issue, Artifactory issue, or some other configuration issues. Can you provide some additional information to help me reproduce?

1. What kind of repo is it? Maven? Gradle?
2. Does the file `https://elinaf.jfrog.io/artifactory/api/storage/test-libs-snapshot-local/org/jfrog/test/multi1/3.7-SNAPSHOT/multi-3.7-SNAPSHOT.jar` exists in the repo? Can you share the response when you do `curl https://elinaf.jfrog.io/artifactory/api/storage/test-libs-snapshot-local/org/jfrog/test/multi1/3.7-SNAPSHOT/`?

**Comment by elinafl** [comment]
@alexhung I agree it is hard to determine at this point. This is a maven repository, the file named "multi-3.7-SNAPSHOT.jar" does not exist under the repository as can be seen in the screenshot of the repo path content, however, it is being returned when executing the cURL request (it appears it returns the latest jar matching that naming structure). When retrieving the same file using terraform, it is not found, and the file name should be mentioned explicitly, for instance - multi1-3.7-20210914.114327-1.jar. It appears that this mechanism might not be implemented. 
These jars were deployed using the [JFrog maven project example](https://github.com/jfrog/project-examples/tree/master/maven-examples/maven-example).

**Comment by alexhung** [comment]
@elinafl Sorry it took this long for us to respond. I've done some digging and testing and discover the following. For Maven repository, when the setting "Handle Snapshot" or "Handel Release" is enabled, Artifactory will figure out the latest version of the artifact when you try to download it without a specific path. i.e. as you described in this issue.

However, this feature is currently not supported by `artifactory_file` resource. In order to support this feature, we would likely create a separate resource and uses the Artifactory API for this.

**Comment by danielmkn** [comment]
Functionality added. Should be in 2.32.2
