### ISSUE TITLE
Add legit support for nuget packages

### ISSUE THREAD

**Issue by peters95** [jfrog/terraform-provider-artifactory#23]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While Jfrog Rest API docs for create repo do not seem to list this flag (https://www.jfrog.com/confluence/display/RTF6X/Repository+Configuration+JSON#RepositoryConfigurationJSON-LocalRepository), when I raised a support ticket with Jfrog support, they have confirmed that forceNugetAuthentication should work. I will look to raise a PR for this, but I have not worked with GOlang before (I have done plenty of work in C#).

### New or Affected Resource(s)

* artifactory_local_repository
* artifactory_remote_repository

### Potential Terraform Configuration

```hcl
artifactory_local_repository {
  force_nuget_authentication = true
}
```

**Comment by chb0github** [comment]
The current TF provider implements repo creation as basically "generic repo+" - the generic repos is used and then some misc fields related other repos is added and then optionally used. Not ideal. A dedicated resource type is ideal

**Comment by chb0github** [comment]
This is done
