### ISSUE TITLE
[Question] Recommended way to migrate from artifactory_remote_repository to package specific resource(eg. artifactory_docker_remote_repository)

### ISSUE THREAD

**Issue by manojwajekar** [jfrog/terraform-provider-artifactory#230]
**Describe the bug**
I am trying to migrate from artifactory_remote_repository to package-specific resource(eg. artifactory_docker_remote_repository). But terraform delete the current repository first and recreate it using a new resource type losing artifacts in progress. 

What is recommended way to migrate without deleting the current repository?

**Comment by chb0github** [comment]
Assuming you want to keep the original repo name:

1. create a temp repo
2. Create a replication from old -> new. Currently, to my knowledge, this has to be a "remote" copy to "self"
3. When 2 is done, delete the old repo in TF
4. recreate the old repo name under new resource specific TF
5. create the replication from temp -> new (previously old) name
6. When replication is done, delete temp repo

I am trying to see if the "copy" can be done locally - internally RT shares files across repos - so, actual physical, on-disk files never move - the new repo simply references the same files as the other repo. Then the "backup" is instantaneous.

Trying to get an answer on this

**Comment by chb0github** [comment]
Ok, there is a [copy api](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CopyItem), but it's not a TF "resource" so you'd have to manage this yourself. 

If you want a purely TF solution, create a push replication back to self to a temp repo, then do the rename and type update. Then replicate back.

It should be extremely fast as it's all loopback communication.

Hope that helps
