### ISSUE TITLE
Documentation sample for multiple replications per replication_config

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/terraform-provider-artifactory#236]
**Is your feature request related to a problem? Please describe.**
We have a JFrog Enterprise+ license which means we're about to create multiple replications for a repository. Quite possibly it's my Terraform experience but I can't see how you do achieve this in HCL.

**Describe the solution you'd like**
An example showing how you configure multiple replications for the same repository would be really helpful alongside the per resource docs.

**Describe alternatives you've considered**
I've tried digging through other resources that use TypeList to see if that can give some hints but I can't work this one out.

**Additional context**
N/A

**Comment by mikeycmccarthy** [comment]
Based on reading the documentation for virtual repositories, it looks like it should be:

```
resource "artifactory_replication_config" "foo-rep" {
	repo_key = "${artifactory_local_repository.provider_test_source.key}"
	cron_exp = "0 0 * * * ?"
	enable_event_replication = true
	
	replications = [
	{
		url = "$var.artifactory_url"
		username = "$var.artifactory_username"
		password = "$var.artifactory_password"
                 path_prefix = "/xyz"
	},
	{
		url = "$var.artifactory_url"
		username = "$var.artifactory_username"
		password = "$var.artifactory_password"
                path_prefix = "/abc"
	},
        ]
}
````

But this gives:

```
│ Error: Unsupported argument
│
│   on replications.tf line 25, in resource "artifactory_replication_config" "XXX":
│   25:   replications = [
│
│ An argument named "replications" is not expected here. Did you mean to
│ define a block of type "replications"?
```

**Comment by alexhung** [comment]
@mikeycmccarthy Terraform doesn't provide explicit documentation for resource schema with type `TypeSet` or `TypeList` in the general HCL documentation section. However, in the provider documentation section for [TypeSet](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset), they left a clue in "Configuration example".

For you example, the HCL should be like:

**Comment by mikeycmccarthy** [comment]
Thanks @alexhung.

I had actually tried this one, should have put it into the original issue. When I planned as above, I saw that each subsequent replication would force a change and I'd be left with one replication.

I've done some more digging by hitting the UI first and it appears that this is actually my issue. Multiple replications likely work exactly as you say, but these cannot have the same url. Terraform seems to work basically by taking the last replication value and using that, the UI complains about the URL already existing for the replication target.

I guess this is something that isn't entirely obvious unless you try on the UI first.

Let me know if you'd welcome some documentation for this corner case.

**Comment by alexhung** [comment]
@mikeycmccarthy 

> Let me know if you'd welcome some documentation for this corner case.

Documentation will be welcomed. Depending on the length of the documentation, there are a few places to put it. If it is relatively short, we can add to the existing [artifactory_push_replication.md](https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/artifactory_push_replication.md). Otherwise, I can enable the wiki on this repo and add the link to `artifactory_push_replication.md`.

**Comment by alexhung** [comment]
@mikeycmccarthy I'm closing this issue. Feel free to re-open this once you have a PR ready to be reviewed.
