### ISSUE TITLE
Authorization Error on version 2.6.22

### ISSUE THREAD

**Issue by binelson** [jfrog/terraform-provider-artifactory#237]
**Describe the bug**
When running the artifactory provider on version 2.6.22, I'm getting authorization errors against my artifactory instance:

```
Error:
403 GET https://artifactory.coxautoinc.com/artifactory/api/system/licenses/
{
  "errors" : [ {
    "status" : 403,
    "message" : "Forbidden"
  } ]
}
```

**Requirements for and issue**
```
- Artifactory Version: 6.23.28
- Terraform Version: 0.13.6
- Snippet:

data "artifactory_file" "lambda_artifact" {
  repository      = var.artifactory_repository
  path            = "/${local.artifactory_dir}/${var.lambda_build_tag}/${var.lambda_build_tag}.zip"
  output_path     = "${path.module}/lambda.zip"
  force_overwrite = true
}
```

**Expected behavior**
The artifactory provider should successfully authenticate against my artifactory instance and pull the file in qeustion.

**Additional context**
Testing out when pinning to 2.6.21, it successfully pulls the requested resource:

```
module.cloudwatch_splunk_logger_lambda.data.artifactory_file.lambda_artifact: Refreshing state... [id=https://.../master-17.zip]
```

**Comment by alexhung** [comment]
@binelson Does the Artifactory user/API key has admin permission/role?

2.6.22 contains a new provider attribute `check_license` and you can set it to `false` to bypass this step.

**Comment by stefanfreitag** [comment]
I was seeing similar behavior after upgrading the provider version from 2.6.21 to 2.6.22.
Terraform version is 1.0.9.
A `terraform plan` ended up in 

```
400 GET https://rwest.jfrog.io/artifactory/api/system/licenses/
 {
   "errors" : [ {
     "status" : 400,
     "message" : "Artifactory Online does not require license, Please contact support@jfrog.com for further assistance if equired."
   } ]
 }

```

Adding the `check_license = false` to the provider made the `terraform plan` complete successfully.

**Comment by binelson** [comment]
I'll test that out and see if it fixes it, however can that value just be updated to default to `false` in the code base?  I feel like that should be the case if the behavior has changed with this release.

**Comment by aliculPix4D** [comment]
Hi, when doing a terraform init, I started to see the same issue as in `Incompatible provider version` https://github.com/jfrog/terraform-provider-artifactory/issues/240 after which I tried to upgrade from `2.6.21` to `2.6.22`. After the upgrade, `terraform init` worked fine, but when running `terraform plan` I started to get:
```
│ Error: Artifactory requires Enterprise license to work with Terraform!
│ 
│   with provider["registry.terraform.io/jfrog/artifactory"],
│   on main.tf line 12, in provider "artifactory":
│   12: provider "artifactory" {
```
our type of licence is: `"type": "Commercial"` self hosted Artifactory Pro.

Everything works fine again if I set: `check_license = false` in provider section.

**Comment by chb0github** [comment]
Even we are surprised sometimes by RT and it's APIs - @alexhung maybe we can add this as one of the acceptable license types?

@aliculPix4D - the idea is to bail quickly if your version of RT won't support terraform because API access is prevented.

**Comment by alexhung** [comment]
@aliculPix4D I'll add `Commercial` to the license check.

And judging from the feedback, I'll switch the default value of `check_license` from `true` to `false`.

**Comment by aliculPix4D** [comment]
Thanks @chb0github @alexhung for quick reaction.
