### ISSUE TITLE
`terraform destroy` command fails while trying to destroy to many repositories in a single go

### ISSUE THREAD

**Issue by aliculPix4D** [jfrog/terraform-provider-artifactory#245]
**Describe the bug**
`terraform destroy` command fails when trying to destroy multiple resources at once with the following errorrs:
(single example, since it repeats itself just for a different repository name)
```

│ Error: 
│ 500 DELETE https://artifactory-hostname/artifactory/api/repositories/conan-repo-2
│ {
│   "errors" : [ {
│     "status" : 500,
│     "message" : "Could not merge and save new descriptor [org.jfrog.common.ExecutionFailed: Last retry failed: Should update revision 39. Not trying again]"
│   } ]
│ }
```

Example configuration:
```
locals {
  generic_repos = {
    "generic-repo-1" = "description: generic-repo-1"
    "generic-repo-2" = "description: generic-repo-2"
    "generic-repo-3" = "description: generic-repo-3"
    "generic-repo-4" = "description: generic-repo-4"
    "generic-repo-5" = "description: generic-repo-5"
  }
  conan_repos = {
    "conan-repo-1" = "description: conan-repo-1"
    "conan-repo-2" = "description: conan-repo-2"
    "conan-repo-3" = "description: conan-repo-3"
    "conan-repo-4" = "description: conan-repo-4"
    "conan-repo-5" = "description: conan-repo-5"
  }
  gitlfs_repos = {
    "gitlfs-repo-1" = "description: gitlfs-repo-1"
    "gitlfs-repo-2" = "description: gitlfs-repo-2"
    "gitlfs-repo-3" = "description: gitlfs-repo-3"
    "gitlfs-repo-4" = "description: gitlfs-repo-4"
    "gitlfs-repo-5" = "description: gitlfs-repo-5"
  }
  npm_repos = {
    "npm-repo-1" = "description: npm-repo-1"
    "npm-repo-2" = "description: npm-repo-2"
    "npm-repo-3" = "description: npm-repo-3"
    "npm-repo-4" = "description: npm-repo-4"
    "npm-repo-5" = "description: npm-repo-5"
  }
  pypi_repos = {
    "pypi-repo-1" = "description: pypi-repo-1"
    "pypi-repo-2" = "description: pypi-repo-2"
    "pypi-repo-3" = "description: pypi-repo-3"
    "pypi-repo-4" = "description: pypi-repo-4"
    "pypi-repo-5" = "description: pypi-repo-5"
  }
}

resource "artifactory_local_generic_repository" "repos" {
  for_each        = local.generic_repos
  key             = each.key
  description     = each.value
  repo_layout_ref = "simple-default"
}

resource "artifactory_local_conan_repository" "repos" {
  for_each        = local.conan_repos
  key             = each.key
  description     = each.value
  repo_layout_ref = "conan-default"
}

resource "artifactory_local_gitlfs_repository" "repos" {
  for_each        = local.gitlfs_repos
  key             = each.key
  description     = each.value
  repo_layout_ref = "simple-default"
}

resource "artifactory_local_npm_repository" "repos" {
  for_each        = local.npm_repos
  key             = each.key
  description     = each.value
  repo_layout_ref = "npm-default"
}

resource "artifactory_local_pypi_repository" "repos" {
  for_each        = local.pypi_repos
  key             = each.key
  description     = each.value
  repo_layout_ref = "simple-default"
}
```
Note that I used specific repository resources (pypi, npm, gitlfs, conan...) instead of more generic `artifactory_local_repository` and the same issue is still there. I choose to go with above example just to show/mimic what we have in production and staging environments.

When using `terraform destroy -parallelism=1` as suggested in https://github.com/jfrog/terraform-provider-artifactory/issues/103 the issue goes away. Unfortunately this is not a very good workaround (long term) for us.

Terraform version: v1.0.11 on Ubuntu 20.04
Artifactory provider version(s): 2.6.21 and 2.6.22
Artifactory version: 7.27.6 Revision: 72706900

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform

**Expected behavior**
Successful execution of `terraform destroy` command. 

**Additional context**
This issue is probably related to [Stagger creation or update of Artifactory resources to avoid flooding the API with too many requests](https://github.com/jfrog/terraform-provider-artifactory/issues/103) but while using `terraform destroy` instead of `apply`

**Comment by oallauddin** [comment]
@alexhung 
I was creating and destroying 89 resources and encountered this issue. Open a new issue?

**Comment by alexhung** [comment]
@oallauddin Yes please open new issue.
