### ISSUE TITLE
Not possible to specify user password for replication

### ISSUE THREAD

**Issue by korjek** [jfrog/terraform-provider-artifactory#246]
When configuring replication using `artifactory_single_replication_config` resource, it's not possible to pass `password` for a user that is configured for replication.

The error is 
```
Cant configure a value for "password": its value will be decided
automatically based on the result of applying this configuration
```

Terraform version: 0.13.4
Artifactory version: 7.19.4
Provider version: 2.6.22

The expected behaviour is that it's possible to configure user password that will be used for replication.

**Comment by korjek** [comment]
@chb0github thanx for the reply.
Could you please explain why we can't use `ignore_changes` for password? I.e. terraform set it with the first run and then it ignores it with all subsequent runs.

Cause having manually set password for, in my case, ~20 replication and remembering to do it once new repo is added doesn't look that attractive.

**Comment by chb0github** [comment]
At some point we may revisit this and maybe that's what we will do (again) - if you want to fork and make the change, it's easy - change the value of `Computed` to `False` (or just remove it) . I would certainly understand

**Comment by chb0github** [comment]
have a look at #252

**Comment by danielmkn** [comment]
Related to the password dilemma, work will be done under #252
