### ISSUE TITLE
REQ: Support "project" API

### ISSUE THREAD

**Issue by TJM** [jfrog/terraform-provider-artifactory#254]
**Is your feature request related to a problem? Please describe.**
We would like to use some of the new functionality that is now part of the API, projects:

https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-PROJECTS

**Describe the solution you'd like**
The ability to create/manage projects, and there may have to be changes to some of the other commands to accept a project ID parameter, or maybe that would be part of the "URL" ?

**Describe alternatives you've considered**

We are just getting started with this provider, but have considered coding it with "curl" :(

**Additional context**

We are trying to build a "shared" artificatory in the cloud that will support multiple different interests. The projects capability appears to provide a way to delegate administrative capabilities to a "namespace" so that the different "interests" cannot interfere with eachother, rather than having a single, shared namespace that everyone has to agree to.

**Comment by alexhung** [comment]
@TJM We are getting close to releasing the 'Projects' provider: https://github.com/jfrog/terraform-provider-project
