### ISSUE TITLE
Unfork this repo?

### ISSUE THREAD

**Issue by Kamori** [jfrog/terraform-provider-artifactory#255]
**Is your feature request related to a problem? Please describe.**
github searching isn't possible on the fork. Plus its confusing for newcomers.

**Describe the solution you'd like**
The atlassian/terraform-provider-artifactory repository already has a deprecation notice. And there have now been a significant number of changes to this fork. It would be nice to see this repository be a standalone repo.

**Describe alternatives you've considered**
I'm not negatively impacted, minus search. So I just clone the repository and search with my tools.

**Additional context**
Github support's Automated Assistant can do it for you, weirdly you can't in the project settings.
https://support.github.com/request?tags=detach_fork&q=detach_fork

**Comment by alexhung** [comment]
@Kamori The GitHub Virtual Assistant has been flaky on me today and I haven't been able to complete it yet. This will most likely be worked on after the holiday season in next Jan.

**Comment by Kamori** [comment]
That's great news to hear! I mean, the part about this something you want to do. :P 

 Hope you and your loved ones have a great holiday time, and enjoy the New Year!

**Comment by chb0github** [comment]
It's a long overdue change - the state of this repo is a fork in name only. The code base is entirely different

**Comment by alexhung** [comment]
@Kamori In case you didn't notice, GitHub unforked this repo on Dec 23rd!

**Comment by Kamori** [comment]
Thank you :) Hope everyone had a great holiday!
