### ISSUE TITLE
Terraform throws an error if repository removed, but replication is configured

### ISSUE THREAD

**Issue by korjek** [jfrog/terraform-provider-artifactory#258]
When Artifactory repository is removed with API/UI, Terraform is not working anymore in case replication is configured.

**Expected behavior**
Terraform recreates removed repository.

**Additional context**
Output

```Error:
400 GET http://my_artifactory_url:8082/artifactory/api/replications/my_removed_repo
{
  "errors" : [ {
    "status" : 400,
    "message" : "Could not find repository"
  } ]
}
```

**Comment by chb0github** [comment]
Can you please supply a fully working terraform example? We need to replicate your results.

**Comment by korjek** [comment]
@chb0github sorry for not being very clear.
Here is a detailed explanation.

Both repo and replication are configured with terraform:
```
resource "artifactory_local_maven_repository" "maven_local" {
  key                       = "maven-local"
  snapshot_version_behavior = "unique"
}
resource "artifactory_single_replication_config" "maven_local" {
  repo_key                 = artifactory_local_maven_repository.maven_local.key
  cron_exp                 = "0 */10 * * * ?"
  enable_event_replication = true
  url                      = "http://dest_artifactory_url:8082/artifactory/maven-local"
  username                 = "replication"
  enabled                  = true
  sync_deletes             = true
  sync_properties          = true
  sync_statistics          = false
}
```
At this point everything works as expected: terraform creates repo and replication.

Now remove repo with Artifactory API:
`curl -X DELETE http://dest_artifactory_url:8082/api/repositories/maven-local`.

I expect that the next terraform apply should recreate the removed repo (and replication), but instead, I got the error:
```
400 GET http://my_artifactory_url:8082/artifactory/api/replications/my_removed_repo
{
  "errors" : [ {
    "status" : 400,
    "message" : "Could not find repository"
  } ]
}
```

Please let me know if you need more info.
