### ISSUE TITLE
`artifactory_user.profile_updatable` shows a change even when unchanged

### ISSUE THREAD

**Issue by jcogilvie** [jfrog/terraform-provider-artifactory#261]
**Describe the bug**
`profile_updatable` is showing me a change from `true` to `false` when I set it to false in code, even after several applies.

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
See the code snippet in https://github.com/jfrog/terraform-provider-artifactory/issues/228

- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
Cloud

- [x] Your version of terraform
1.0.11

**Expected behavior**
Diff reflects actual state and only shows changes when attributes are changed.

**Additional context**
https://github.com/jfrog/terraform-provider-artifactory/issues/228

**Comment by jcogilvie** [comment]
I know this is probably really low priority, but of the several bugs I have opened in the past few weeks, this one is definitely the most annoying because it injects junk into *every* plan.

**Comment by alexhung** [comment]
@jcogilvie This is scheduled to be worked on in our next sprint which starts tomorrow.

**Comment by jcogilvie** [comment]
I appreciate how active and responsive your team has been.
