### ISSUE TITLE
Detect platform in makefile, not hardcode darwin_amd64

### ISSUE THREAD

**Issue by tenstad** [jfrog/terraform-provider-artifactory#264]
**Is your feature request related to a problem? Please describe.**
It was confusing to build and test my contribution with `darwin` hardcoded in the `GNUmakefile`  (I'm on `linux_amd64`).  
Eventually got it working by replacing all `darwin_amd64` with `linux_amd64` in `GNUmakefile`.

**Describe the solution you'd like**
Automatically figure out current platform in makefile, and name the folder accordingly.

**Describe alternatives you've considered**
Add a NOTE in the build section of README: https://github.com/jfrog/terraform-provider-artifactory#build-the-provider

**Additional context**
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/jfrog/artifactory v2.6.26 does not have a package available for your current platform, linux_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

**Comment by alexhung** [comment]
@tenstad We recognize this issue as we develop the providers for Xray and Project. See the project's [makefile](https://github.com/jfrog/terraform-provider-project/blob/master/GNUmakefile#L2). Whilst it isn't auto-detection, it is the first step to solving this issue.
