### ISSUE TITLE
Support for priority resolution in local repositories

### ISSUE THREAD

**Issue by tenstad** [jfrog/terraform-provider-artifactory#266]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to set priority resolution for local repos, e.g. local python repo.

**Describe the solution you'd like**
Add priority resolution field to local repo base.

**Describe alternatives you've considered**
Add priority resolution field to specific local repo types.

**Additional context**
Related issue: https://github.com/jfrog/terraform-provider-artifactory/issues/62

**Comment by alexhung** [comment]
@tenstad Does #268 fulfill this feature request?

**Comment by tenstad** [comment]
It does. Thanks @jonattta! 😄
