### ISSUE TITLE
Create / Retrieve / Update / Delete apiKey for any user

### ISSUE THREAD

**Issue by evilensky** [jfrog/terraform-provider-artifactory#269]
The [documentation](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_api_key) it not super clear but it appears that the API key resource is only available for the user that's been configured as part of the `provider {}`.

We would like to be able create/update/delete `api_key` resources for users. Either specifying the `user` as a parameter to `api_key` resource, or creating an api_key for each [`artifactory_user` resource](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_user).  Both would be ideal for flexibility.

We tried to create an instance of `provider {}` for reach `artifactory_user` we manage, so as to retrieve the apiKey, but it does not seem obvious how to do so.

**Comment by danielmkn** [comment]
@evilensky, the provider uses the Artifactory REST API on the backend. The current [Artifactory API implementation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateAPIKey) allows generating a new API key only for the current user.
Admin user can revoke an API key for another user. But this is the only operation, that can be performed on the other user by the admin. So, the admin can't generate an API key for a user. 
API key can't be created at the same time as a user, per [API documentation] (https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateorReplaceUser) either.
 
Looks like all we can do is to generate an API key for the current user, whose credentials are used in the provider {}
@chb0github what do you think?

**Comment by chb0github** [comment]
You can only generate an API per user and there is a security reason why:

Imagine if user A could Generate a key for user B - User A could use key for user B and impersonate him. 

This isn't possible - by design
