### ISSUE TITLE
Email_Attribute property for LDAP Settings has incorrect validation

### ISSUE THREAD

**Issue by ShreyasNBS** [jfrog/terraform-provider-artifactory#277]
**Describe the bug**
email_attribute can have values like "mail" or "userPrincipalName" in ldap_settings, but the validation routine (validateIsEmail), is looking for a correctly formed email address. 

**Requirements for and issue**

![image](https://user-images.githubusercontent.com/56643631/150566077-fb5e2640-68e2-442c-9063-12078d029f24.png)

Using the above settings gives error

![image](https://user-images.githubusercontent.com/56643631/150565813-0f5b465d-1dc0-43c9-96c2-41f86092ffbb.png)

**Expected behavior**
"userPrincipalName" should be allowed an an accepted value for email_attribute.

**Additional context**
Official Jfrog [https://www.jfrog.com/confluence/display/JFROG/LDAP](docs) show "mail" as an accepted value for email_attribute.

**Comment by ShreyasNBS** [comment]
Thanks for the fast fix. Do you know how long it takes for the new version to be released? :)

**Comment by chb0github** [comment]
That is up to @alexhung

**Comment by alexhung** [comment]
@chb0github @maheshjfrog founds an issue when `email_attribute` is left empty. He's working on a fix now so I won't do a patch release until the fix is in.
