### ISSUE TITLE
Unable to add more than 1 user to permission target

### ISSUE THREAD

**Issue by spuder** [jfrog/terraform-provider-artifactory#28]
There does not currently appear to be a way to manage multiple users on a permission target. 
I'd like to be able to define multiple users on a permission

```
resource "artifactory_permission_target" "foobar" {
  name = "foobar"
  repo {
    excludes_pattern = []
    includes_pattern = [
      "**"
    ]
    repositories = [
      "bakerstreet",
    ]
    actions {
      users {
        name = "bar
        permissions = [
          "annotate",
          "read",
          "write"
        ]
      }
    }
  }
}
```

Actions appears to only take 1 'users' or 'groups' object, if you try and use a hash or array of objects, it failes

Attempt 1 (array) 

```
actions [
      users {
        name = "user1"
        permissions = ["read"]
       }, 
      users {
        name = "user2"
        permissions = ["read"]
       }, 
    ]
```

Attempt 2 (hash)

```
actions {
      users {
        name = "user1"
        permissions = ["read"]
       }, 
      users {
        name = "user2"
        permissions = ["read"]
       }, 
    }
```

Attempt 3 (users array)

```
actions [
      users {
        name = ["user1", "user2"]
        permissions = ["read"]
       }, 
    ]
```

Is there no way to pass an array to `actions` so that multiple users can be added to a permission target?

**Comment by chb0github** [comment]
I think I see the issue - Can you please give me the output of your attempts.

**Comment by chb0github** [comment]
Closing as no repeatable steps or updates have been supplied

**Comment by feliu** [comment]
I found the same blocker. Trying to use the same permission for multiple groups is not possible. I'm happy to take a look at it and open a PR. Would that work @chb0github?
