### ISSUE TITLE
Default repo_layout_ref for artifactory_local_docker_v2_repository resources is maven-2-default

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/terraform-provider-artifactory#282]
**Describe the bug**
When creating a resource of type artifactory_local_docker_v2_repository, unless overriden you'll end up with a repo with layout maven-2-default. This doesn't seem to cause any issues as such, just in the screenshot in https://www.jfrog.com/confluence/display/JFROG/Docker+Registry it seems to imply that simple-default would be the type to choose.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform

Terraform Version

```
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/jfrog/artifactory v2.9.1
```

Artifactory version

```
{
  "version" : "7.31.10",
  "revision" : "73110900",
  "addons" : [ "ha", "build", "docker", "vagrant", "replication", "filestore", "plugins", "gems", "composer", "npm", "bower", "git-lfs", "nuget", "debian", "opkg", "rpm", "cocoapods", "conan", "vcs", "pypi", "release-bundle", "jf-event", "replicator", "keys", "alpine", "cargo", "chef", "cran", "federated", "git", "go", "helm", "observability", "pub", "rest", "swift", "conda", "terraform", "tracker", "license", "puppet", "ldap", "sso", "layouts", "properties", "search", "securityresourceaddon", "filtered-resources", "p2", "watch", "webstart", "support", "xray", "retention" ],
  "license" : "XXX"
}
```

**Expected behavior**
Based on the screenshot in the JFrog documentation I'd expect the default layout to be simple-default for local Docker repositories.

**Additional context**
-

**Comment by ADSapozhnikov** [comment]
This situation for all new local repository resources(docker, generic, etc). Fix it for me added repo_layout_ref="simple-default" section.
```
resource "artifactory_local_docker_v2_repository" "terraform-local-docker-repo" {
  for_each = {
    for q in local.all_docker_repos : q => q
    if contains(var.art_repos_types, "docker")
  }
  key                     = each.value
  repo_layout_ref  = "simple-default"
  description         = "Docker repository for ${var.art_base} artifacts"
  notes                  = "SR: ${var.art_service_request_number}"
}
```

**Comment by mikeycmccarthy** [comment]
A similar fix worked for me too @ADSapozhnikov . I wonder if the default should be changed for this resource just to save people writing more code than they need to, or not realising they'll get a maven-2 layout (and whatever issues come or don't come with that)

**Comment by ADSapozhnikov** [comment]
I propose assign default `repo_layout_ref` for all specific repository types and feature for manually assign specific `repo_layout_ref`. (Because some type of repos have a several layouts) Also I suppose need to update official documentation for all specific repository resources for provide information about `repo_layout_ref` key.
I think this solution will be more friendly for all

**Comment by mikeycmccarthy** [comment]
It isn't particularly clear what JFrog even recommend here - I'm assuming simple-default is the right type only because of that screenshot above and it is what you get as the default value if you use the UI to create a Docker repo. If I get any more info I'll update this.
