### ISSUE TITLE
License check fails on Edge nodes

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/terraform-provider-artifactory#284]
**Describe the bug**
If you try and run the provider against an Artifactory Edge node, you'll see an error:

```
│ Error: Artifactory requires Pro or Enterprise license to work with Terraform! If your usage doesn't require a license, you can set `check_license` attribute to `false` to skip this check.
│
│   with provider["registry.terraform.io/jfrog/artifactory"],
│   on provider.tf line 11, in provider "artifactory":
│   11: provider "artifactory" {
```

This is happening because of the check at https://github.com/jfrog/terraform-provider-artifactory/blob/ddb3907c0227f600181e98a4bd170482102223d4/pkg/artifactory/provider.go#L255-L257. Essentially it checks for this:

```
regexp.MatchString(`(?:Enterprise|Commercial)`, licenseType)
```

This is the call you get back from the API on an Edge node:

```
curl -u admin https://XXXartifactory/api/system/licenses
Enter host password for user 'admin':
{
  "type" : "Edge",
  "validThrough" : "Jul 22, 2022",
  "licensedTo" : "XXX"
}
```
If you read https://www.jfrog.com/confluence/display/JFROG/JFrog+Artifactory+Edge, an Edge node is something that you can only get on an Enterprise+ license.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

Terraform 1.1
Artifactory:   "version" : "7.31.10",  "revision" : "73110900",

**Expected behavior**
Given that most of the resources for an Artifactory instance are valid for an Edge instance, I'd expect to be able to deal with an Edge instance in the same manner.

**Additional context**
The check_license workaround should be fine here so this isn't an urgent thing our side.

**Comment by alexhung** [comment]
@mikeycmccarthy While we work on the fix, you can set the `check_license` attribute to `false` to bypass the license checking. See https://registry.terraform.io/providers/jfrog/artifactory/latest/docs#argument-reference

**Comment by alexhung** [comment]
@mikeycmccarthy While we work on the fix, you can set the `check_license` attribute to `false` to bypass the license checking. See https://registry.terraform.io/providers/jfrog/artifactory/latest/docs#argument-reference

**Comment by chb0github** [comment]
You can now skip license check with a flag - but, we'll roll out a fix

**Comment by mcaulifn** [comment]
This appears to be broken again.

```
curl -H "Authorization: Bearer $TOKEN"  https://xxxx.jfrog.io/artifactory/api/system/license
{
  "type" : "Edge",
  "validThrough" : "N/R",
  "licensedTo" : "Artifactory Online Dedicated"
}
```

Terraform v1.2.5
+ provider registry.terraform.io/jfrog/artifactory v6.11.2
+ provider registry.terraform.io/jfrog/project v1.1.3

**Comment by alexhung** [comment]
@mcaulifn There's no code changes to the license checking code since May 11th. If this breakage occurs recently, my hunch is something else is causing this issue.
