### ISSUE TITLE
Can keypairs be `terraform import`’d?

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#289]
**Is your feature request related to a problem? Please describe.**
I'm trying to model the existing state of our Artifactory cluster in Terraform, including state. [The docs](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_keypair) do not make clear whether or not it is possible to import the state of the `artifactory_keypair` resource.

**Describe the solution you'd like**
A correct implementation and matching documentation.

**Describe alternatives you've considered**
Trial and error.

**Comment by skyzyx** [comment]
Turns out, yes they can. The private + public key contents remain as plain text inside the statefile, so appropriate measures should be taken to protect the state file.

**Comment by danielmkn** [comment]
@skyzyx, I see that `private_key` has an attribute `Sensitive:        true,`
Is the issue still relevant?

**Comment by danielmkn** [comment]
If I understand your question correctly, we should protect the state file?

**Comment by alexhung** [comment]
@skyzyx Looking forward to your feedback. As far as I can tell from Terraform documentation, protecting state file is the responsibility of the users (e.g. local file permission, remote backend, etc.) so we are not planning to apply any changes to state file handling on our end.

**Comment by skyzyx** [comment]
So, looking at [this page](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_keypair), there are a few documentation updates I'd like to request. I know that the team is transitioning how the docs are generated, but I'd like to request the following end-state.

* "alpine" should be changed to match the official branding, which is "Alpine Linux".

* In lists, either use an ending period consistently or not at all.

* In "[Argument Reference](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_keypair#argument-reference)", we don't need to say "duh!". Nobody here is a stupid person.

* "RT" may be the internal name of the software, but your own corporate branding is 
"Artifactory" and should be used instead.

* Nowhere on this page does it explicitly state that there are any sensitive values, but it should. (This is different from needing to secure our own statefile. This is signaling to users that the statefile _needs_ to be secured.)

* Lastly, it would be nice to document _how_ to leverage `terraform import` for this resource.
