### ISSUE TITLE
Smooth way to migrate from `artifactory_local_repository` → `artifactory_local_alpine_repository`

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#290]
**Describe the bug**
I appreciate making more specific local/remote/virtual repo types that can be modeled appropriately for each type. I think it's a positive move.

That said, what's the best way to migrate from the older `artifactory_local_repository` type to the newer `artifactory_local_alpine_repository` type?

**Requirements for and issue**

Artifactory:

```bash
$ curl -sSL https://{host}/artifactory/api/system/version | jq -Mr '.version'
7.24.3
```

Terraform:

```bash
$ terraform version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/jfrog/artifactory v2.10.0
```

Old code:

```hcl
resource "artifactory_local_alpine_repository" "alpine_local" {
  key             = "alpine-local"
  package_type    = "alpine"
  repo_layout_ref = "simple-default"

  description = "DO NOT USE THIS DIRECTLY. Use the 'alpine' repo instead."
  notes       = "Internal repository for storing MHE packages built for Alpine Linux. Only the @cloud team is allowed to push packages here."

  includes_pattern = "**/*"
  excludes_pattern = ""

  property_sets = [
    "artifactory",
  ]
  checksum_policy_type     = "server-generated-checksums"
  blacked_out              = false
  archive_browsing_enabled = true
  xray_index               = true

  # Missing RSA Key for Alpine Linux repos.
  provisioner "local-exec" {
    command = "echo '@TODO: Go into alpine-local settings and set the RSA Keypair to artifactory-rsa.'"
  }
}
```

New code:

```hcl
resource "artifactory_local_alpine_repository" "alpine_local" {
  key             = "alpine-local"
  repo_layout_ref = "simple-default"

  description = "DO NOT USE THIS DIRECTLY. Use the 'alpine' repo instead."
  notes       = "Internal repository for storing MHE packages built for Alpine Linux. Only the @cloud team is allowed to push packages here."

  includes_pattern = "**/*"
  excludes_pattern = ""

  property_sets = [
    "artifactory",
  ]
  blacked_out              = false
  archive_browsing_enabled = true
  xray_index               = true
}
```

**Actual behavior**

```plain
$ terraform plan
artifactory_local_repository.alpine_local: Refreshing state... [id=alpine-local]
artifactory_keypair.rsa: Refreshing state... [id=artifactory-rsa]
artifactory_remote_repository.alpine_remote: Refreshing state... [id=alpine-remote]
artifactory_remote_repository.corretto_alpine_remote: Refreshing state... [id=corretto-alpine-remote]
artifactory_virtual_repository.alpine: Refreshing state... [id=alpine]

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # artifactory_local_alpine_repository.alpine_local will be created
  + resource "artifactory_local_alpine_repository" "alpine_local" {
      + archive_browsing_enabled = true
      + blacked_out              = false
      + description              = "DO NOT USE THIS DIRECTLY. Use the 'alpine' repo instead."
      + excludes_pattern         = (known after apply)
      + id                       = (known after apply)
      + includes_pattern         = "**/*"
      + key                      = "alpine-local"
      + notes                    = "Internal repository for storing MHE packages built for Alpine Linux. Only the @cloud team is allowed to push packages here."
      + package_type             = (known after apply)
      + priority_resolution      = false
      + property_sets            = [
          + "artifactory",
        ]
      + repo_layout_ref          = "simple-default"
      + xray_index               = true
    }

  # artifactory_local_repository.alpine_local will be destroyed
  # (because artifactory_local_repository.alpine_local is not in configuration)
  - resource "artifactory_local_repository" "alpine_local" {
      - archive_browsing_enabled        = true -> null
      - blacked_out                     = false -> null
      - calculate_yum_metadata          = false -> null
      - checksum_policy_type            = "server-generated-checksums" -> null
      - debian_trivial_layout           = false -> null
      - description                     = "DO NOT USE THIS DIRECTLY. Use the 'alpine' repo instead." -> null
      - docker_api_version              = "V2" -> null
      - enable_file_lists_indexing      = false -> null
      - force_nuget_authentication      = false -> null
      - handle_releases                 = true -> null
      - handle_snapshots                = true -> null
      - id                              = "alpine-local" -> null
      - includes_pattern                = "**/*" -> null
      - key                             = "alpine-local" -> null
      - max_unique_snapshots            = 0 -> null
      - max_unique_tags                 = 0 -> null
      - notes                           = "Internal repository for storing MHE packages built for Alpine Linux. Only the @cloud team is allowed to push packages here." -> null
      - package_type                    = "alpine" -> null
      - property_sets                   = [
          - "artifactory",
        ] -> null
      - repo_layout_ref                 = "simple-default" -> null
      - snapshot_version_behavior       = "unique" -> null
      - suppress_pom_consistency_checks = true -> null
      - xray_index                      = true -> null
      - yum_root_depth                  = 0 -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.

╷
│ Warning: Deprecated Resource
│
│   with artifactory_virtual_repository.alpine,
│   on alpine-repos.tf line 88, in resource "artifactory_virtual_repository" "alpine":
│   88: resource "artifactory_virtual_repository" "alpine" {
│
│ This resource is deprecated and you should use repo type specific resources (such as
│ artifactory_virtual_maven_repository) in the future
│
│ (and one more similar warning elsewhere)
╵
```

**Desired behavior**
Any helpful instructions for migrating the Terraform code _smoothly_ **without** deleting existing repositories that are managed with Terraform (and their contents).

**Comment by chb0github** [comment]
The only way to do this is in phases:
1. Create a new, type specific repo
2. Create a loopback replication (push)
3. Make the old repo readonly
4. When you're confident artifacts and people are migrated, delete the old repo from TF.

Another way would be to 
1. point everyone now at a virtual repo, 
2. Put both old and new repo in the virtual - resolution old, then new
3. setup replication
4. remove old when ready

I read/heard somewhere that there is an internal copy mechanism, but I never tested it and I can't find it.

**Comment by tjstansell** [comment]
I tried to use the terraform 1.x `moved {}` block feature to do this transparently, but no luck.
```
│ Error: Resource type mismatch
│
│ This statement declares a move from artifactory_remote_repository.test-docker-remote to artifactory_remote_docker_repository.test-docker-remote, which is a resource of a different type.
```
Looks like the only non-destructive way might be to:

1. change the terraform config to the new resource types
2. manually import the new resources (`terraform import`)
3. manually delete the old resources (`terraform state rm`)
4. do a plan to check for differences (`terraform plan`)

**Comment by skyzyx** [comment]
Presently, this is not a great migration story. Especially when getting it wrong may result in deleting repositories full of data/artifacts.

> I appreciate making more specific local/remote/virtual repo types that can be modeled appropriately for each type. I think it's a positive move.

I still believe this. But the migration path needs to be bullet-proof.

While working on solving this challenge, I learned that Artifactory’s "move" API takes a `from` and a `to` repo path. Unfortunately, I forgot to create the `to` repo before attempting to move the contents, and Artifactory ended up moving them to `/dev/null`. Gone. Just gone. No warning. No validation before moving. Nothing.

Luckily, this is the new system we've been trying to get working and configured for 9 months, so I'll be able to re-export the data from the production system… but holy shit.

**Comment by chb0github** [comment]
If you come up with a strategy that works better, and you'd like to share it, please reopen the ticket. I won't deny that RT sometimes catches us off guard too. We are working to finish up repo specific resources in the next week or so and complete the job. At which point, those legacy repos will all be gone. 

I am sorry it's not as smooth as hoped and we welcome input

**Comment by tjstansell** [comment]
I don't really need to reopen this ticket, but wanted to share with folks here that I wrote a simple utility to try to upgrade our hundreds of repositories by modifying the state file itself and rewriting any .tf configs it finds that include references to the old deprecated types.  It's the only way I could see doing this non-destructively since there are inter-resource dependencies and references.  I've shared the script and written instructions that have so far worked for us in my repository here:

https://github.com/tjstansell/artifactory-repository-upgrade

**Comment by chb0github** [comment]
If this worked for you, and you'd like, we could consider folding it in
