### ISSUE TITLE
Usage of Undocumented Artifactory API Endpoints

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#291]
**Describe the bug**
I unexpectedly was warned about using "Undocumented Artifactory API Endpoints". There is no mention of this in [`artifactory_general_security`](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_general_security).

**Requirements for and issue**

Artifactory:

```bash
$ curl -sSL https://{host}/artifactory/api/system/version | jq -Mr '.version'
7.24.3
```

Terraform:

```bash
$ terraform version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/jfrog/artifactory v2.10.0
```

Code:

```hcl
resource "artifactory_general_security" "security" {
  enable_anonymous_access = true
}
```

**Expected behavior**
No warning.

**Actual behavior**

```plain
│ Warning: Usage of Undocumented Artifactory API Endpoints
│
│   with artifactory_general_security.security,
│   on general-security.tf line 2, in resource "artifactory_general_security" "security":
│    2: resource "artifactory_general_security" "security" {
│
│ The artifactory_general_security resource uses endpoints that are undocumented and may not work with SaaS
│ environments, or may change without notice.
```

**Comment by chb0github** [comment]
This isn't a bug. It uses APIs that aren't in the official documentation anywhere and are different between hosted and SaaS - This issue has been brought up before and it works as expected

**Comment by skyzyx** [comment]
Then this should be bubbled-up to the Markdown documentation, instead of being buried inside the Go source.

**Comment by knorx** [comment]
Is there any means of disabling this warning? I am aware of what it tells me and I want to do it anyways. I furthermore like a warning free run of terraform.

**Comment by alexhung** [comment]
@knorx I'll removed the warning message from the OAuth and SAML resources. This message was added long time ago when the use of Artifactory Configuration API was not well documented.
