### ISSUE TITLE
Hardcoded artifactory in api call when sendUsageRepo is called

### ISSUE THREAD

**Issue by oxatkoCZ** [jfrog/terraform-provider-artifactory#292]
Hi 

https://github.com/jfrog/terraform-provider-artifactory/blob/v2.6.1/pkg/artifactory/provider.go#L188 on this line from version 2.6.1 in all other versions is hard-coded artifactory / api / . .. but if you have running artifactory on the domain, it doesn't work and all uses of this provider will lead to a failed deployments

**Comment by alexhung** [comment]
@oxatkoCZ Can you elaborate more? The version prior to 2.6.1 is 2.3.10 and the api endpoint has not changed between those versions.

https://github.com/jfrog/terraform-provider-artifactory/blob/v2.3.10/pkg/artifactory/provider.go#L188

**Comment by chb0github** [comment]
I think he's saying that their endpoints are remapped by some proxy. Else, why would hardcoding the path be a problem?

**Comment by oxatkoCZ** [comment]
We were using version 2.2.4 which call sendUsageRepo without expecting anything. 
https://github.com/jfrog/terraform-provider-artifactory/blob/v2.2.4/pkg/artifactory/provider.go 

But hardcoded `artifactory` in path causes problem and returns of course 404 not found. 
```
if err != nil {
    return nil, fmt.Errorf("unable to report usage %s", err)
}
```
error is catched and returned

**Comment by alexhung** [comment]
@oxatkoCZ That is what my guess is the problem.

That version uses JFrog Go client which (I think) figures out the API path mapping based on proxy, hostname, etc.

After we migrated away from using JFrog Go client, all(?) the API paths have hardcoded `/artifactory`. So this problem is system-wide and not just affects telemetry.

**Comment by alexhung** [comment]
@oxatkoCZ Also see #85

**Comment by ofayans** [comment]
We are experiencing the same issue. We ended up locking the provided to one of the earlier versions that did not have "artifactory" hardcoded in all endpoints.

**Comment by chb0github** [comment]
@alexhung - all the more reason to have the `override` flag we talked about before. @ofayans A few users have wanted this URL to be more flexible for a variety of reasons, but the overwhelming group of users takes the default settings.

**Comment by oxatkoCZ** [comment]
I understand, but what is supposed in #85 with ability override or modify base path is in this modern world the main thing - "be able to customise". We are behind reverse proxy and we are not able to use newer version of this provider. And if this is an official provider from jfrog, i don't understand why is not supported whole community. If you don't have capacity to do this, we can contribute somehow of course.

**Comment by chb0github** [comment]
@oxatkoCZ - you and your team/company chose a reverse proxy for your own reasons; you're asking us to provide a solution to a problem your team introduced. I spoke with @alexhung and the more we brainstormed about this, I am not so sure it's straightforward even as I suggested. 

He and I will discuss it more

**Comment by alexhung** [comment]
A cursory search through the code base shows that all API endpoint paths uses `/artifactory`, except for the Xray API calls. So this should be implementable, *after* we remove all the deprecated Xray resources from this provider.

**Comment by alexhung** [comment]
FYI, the webhook resources/API uses the `/event` path so this isn't just a simple map `/artifactory` to some subdomain.

**Comment by chb0github** [comment]
Yeah, if we can't assume that `${base}` -> `/artifactory` then it would mean webhooks can't work

**Comment by alexhung** [comment]
@oxatkoCZ Which version of Artifactory are you using?

**Comment by alexhung** [comment]
@oxatkoCZ The remapping of subdomain to `/artifactory` is no longer recommended or officially supported in Artifactory v7. While it is [still technically possible](https://jfrog.com/knowledge-base/how-to-remove-artifactory-from-the-context-url-in-artifactory-7/), we won't be supporting this with Terraform providers.
