### ISSUE TITLE
list_remote_folder_items not available for resource_artifactory_remote_docker_repository

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/terraform-provider-artifactory#294]
**Describe the bug**
I'm trying to configure an instance of Artifactory Edge. These are special instances in that the only remotes allowed are smart remotes.

I've noticed that some of the remote repository types support the list_remote_folder_items argument (see https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource_artifactory_remote_npm_repository.go#L13-L16) while others such as the remote Docker one don't.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

Terraform 1.1
Artifactory: "version" : "7.31.10", "revision" : "73110900",

**Expected behavior**
I'd expect list_remote_folder_items to be able to be provided as an argument given it can be set in the UI for a remote Docker registry.

**Additional context**
N/A

**Comment by alexhung** [comment]
@mikeycmccarthy `list_remote_folder` attribute is part of smart repository but I think Artifactory determines if a remote repository is 'smart' or not through the url. See https://www.jfrog.com/confluence/display/JFROG/Smart+Remote+Repositories.

**Comment by mikeycmccarthy** [comment]
@alexhung is correct and this was fixed in https://github.com/jfrog/terraform-provider-artifactory/pull/300/files.

I think it should be possible still to configure list_remote_folder_items - possible the description of this issue should change to decouple it from it being anything to do with being able to create smart remotes or not.

**Comment by alexhung** [comment]
@mikeycmccarthy We have scheduled to fix `list_remote_folder` attribute soon. No ETA.

**Comment by oallauddin** [comment]
Hi. Will this also fix list_remote_folder_items not being supported in artifactory_remote_repository? I need to setup a remote repository to github for node-sass. Setup is described here https://stackoverflow.com/a/50372913

**Comment by alexhung** [comment]
@oallauddin no plan to apply this fix to `artifactory_remote_repository`. However, if you need this feature for generic remote repository, please create a separate issue for adding `artifactory_remote_generic_repository` resource.
