### ISSUE TITLE
Support priority_resolution for remote repositories

### ISSUE THREAD

**Issue by keithluong42** [jfrog/terraform-provider-artifactory#295]
**Describe the bug**
I want to set `priority_resolution=true` for an `artifactory_remote_repository` resource, but I get errors reporting the config is unexpected, even though it appears [in the code here ](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/repositories.go#L74).

Terraform snippet:
```
resource "artifactory_remote_repository" "pypi-remote-repo" {
  for_each = toset(var.repos)

  key = "${var.pypi_repo_config.repo_name}-${each.value}-${var.other_inst_name}"
  description = "Remote Pypi ${each.value} repo (local file cache) for ${var.inst_name} (sourced from ${var.other_inst_name})"
  excludes_pattern = var.pypi_repo_config.excludes_pattern
  includes_pattern = "**/*"
  package_type = "pypi"
  username = var.remote_access_user
  password = var.remote_access_pass
  repo_layout_ref = "simple-default"
  url = "https://${var.other_inst_name}.jfrog.io/artifactory/pypi-${each.value}-local"

  missed_cache_period_seconds = var.pypi_repo_config.missed_cache_period_seconds
  retrieval_cache_period_seconds = var.pypi_repo_config.retrieval_cache_period_seconds
  socket_timeout_millis = var.pypi_repo_config.socket_timeout_millis
  store_artifacts_locally = true
  synchronize_properties = true
  unused_artifacts_cleanup_period_hours = 0
  priority_resolution = true
}
```

Error:
```
╷
│ Error: Unsupported argument
│ 
│   on modules/repos/modules/pypi/repos.tf line 40, in resource "artifactory_remote_repository" "pypi-remote-repo":
│   40:   priority_resolution = true
│ 
│ An argument named "priority_resolution" is not expected here.
╵
```

Artifactory version: v7.31.10
Terraform version: v1.0.3

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform

**Expected behavior**
Expect `priority_resolution` to be enabled for remotes, the same way it has been for locals in this change: https://github.com/jfrog/terraform-provider-artifactory/pull/268

**Additional context**
I've tried adding it to this `unpackBaseRemoteRepo` function [here (looks like it was missing)](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/repositories.go#L649) and rebuilding the provider locally , but haven't had success.

**Comment by chb0github** [comment]
I've seen this feature requested before

**Comment by alexhung** [comment]
`priority_resolution` was added to local repo #268

**Comment by chb0github** [comment]
If you decide to add this @alexhung , make sure it's only supported on repo specific types. You may need to create a ticket to support this repo type remotely
