### ISSUE TITLE
Cannot manage smart repositories with provider

### ISSUE THREAD

**Issue by mikeycmccarthy** [jfrog/terraform-provider-artifactory#297]
**Describe the bug**
We're trying to manage repositories on an Artifactory Edge instance, they're a little bit special in that they only support smart remotes (Artifactory to Artifactory) rather than simply any type of remote. It seems the provider is unable to manage repositories of this type - see the output below. Looking at the network calls in Chrome developer mode when you using the UI it appears that creation of the smart remote is just a POST to /repositories and nothing more special than that.

```bash

$ tf apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # artifactory_remote_docker_repository.smart_remote will be created
  + resource "artifactory_remote_docker_repository" "smart_remote" {
      + allow_any_host_auth                     = (known after apply)
      + assumed_offline_period_secs             = 300
      + blacked_out                             = (known after apply)
      + block_mismatching_mime_types            = (known after apply)
      + block_pushing_schema1                   = (known after apply)
      + bypass_head_requests                    = (known after apply)
      + client_tls_certificate                  = (known after apply)
      + description                             = (known after apply)
      + enable_cookie_management                = (known after apply)
      + enable_token_authentication             = (known after apply)
      + excludes_pattern                        = (known after apply)
      + external_dependencies_enabled           = true
      + failed_retrieval_cache_period_secs      = (known after apply)
      + hard_fail                               = (known after apply)
      + id                                      = (known after apply)
      + includes_pattern                        = (known after apply)
      + key                                     = "my_smart_remote"
      + missed_cache_period_seconds             = (known after apply)
      + offline                                 = (known after apply)
      + package_type                            = (known after apply)
      + password                                = (sensitive value)
      + priority_resolution                     = (known after apply)
      + propagate_query_params                  = false
      + property_sets                           = [
          + "artifactory",
        ]
      + proxy                                   = (known after apply)
      + remote_repo_layout_ref                  = (known after apply)
      + repo_layout_ref                         = "simple-default"
      + retrieval_cache_period_seconds          = 7200
      + share_configuration                     = (known after apply)
      + socket_timeout_millis                   = (known after apply)
      + store_artifacts_locally                 = (known after apply)
      + synchronize_properties                  = true
      + unused_artifacts_cleanup_period_enabled = (known after apply)
      + unused_artifacts_cleanup_period_hours   = (known after apply)
      + url                                     = "https://XXX"
      + username                                = "XXX"
      + xray_index                              = (known after apply)

      + content_synchronisation {
          + enabled = true
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on provider.tf line 3, in terraform:
│    3:   experiments      = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

artifactory_remote_docker_repository.smart_remote: Creating...
╷
│ Error:
│ 400 PUT https://XXX/artifactory/api/repositories/my_smart_remote
│ {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "Only smart remote repositories are supported with Artifactory Edge license\n"
│   } ]
│ }
│
│   with artifactory_remote_docker_repository.smart_remote,
│   on provider.tf line 17, in resource "artifactory_remote_docker_repository" "smart_remote":
│   17: resource "artifactory_remote_docker_repository" "smart_remote" {
```

```bash
terraform {
  required_version = "1.1.1"
  experiments      = [module_variable_optional_attrs]
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
    }
  }
}

provider "artifactory" {
  url           = var.artifactory_url
  access_token  = var.artifactory_access_token
  check_license = var.check_license
}

resource "artifactory_remote_docker_repository" "smart_remote" {

  key                           = "my_smart_remote"
  repo_layout_ref               = "simple-default"
  property_sets                 = ["artifactory"]
  external_dependencies_enabled = true
  url                           = "https://XXX"
  username                      = "XXX"
  password                      = "XXX"
  synchronize_properties        = true
  content_synchronisation {
    enabled = true
  }


  lifecycle {
    ignore_changes = [password]
  }

}
```

Terraform 1.1
Artifactory: "version" : "7.31.10", "revision" : "73110900",

**Requirements for and issue**
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

**Expected behavior**
I would expect a smart remote to be manageable the same way as a regular remote.

**Additional context**
-

**Comment by alexhung** [comment]
Possibly related to #50

**Comment by mikeycmccarthy** [comment]
I thought it might be related but I don't think it is looking closer. I looked at the payload when creating via the UI and none of the settings that we can't manage seemed to be mandatory.

I'll try an API call outside of Terraform and post the results here in case it helps. I can't work out yet at what point Artifactory is doing the 'is this a smart remote' check before it returns the error.

**Comment by mikeycmccarthy** [comment]
I can confirm that this is supported via the API for both generic and docker repositories at least:

```bash
curl -u admin https://XXX/artifactory/api/repositories/edge-generic-remote -d '{"key":"edge-generic-remote","username":"admin","password":"XXX","rclass":"remote","url":"https://XXX/artifactory/XXX","packageType":"generic","contentSynchronisation":{"enabled":"true"}}' -H "Content-Type: application/json" -XPUT
Enter host password for user 'admin':
Successfully created repository 'edge-generic-remote'
```

```bash
curl -n https://XXX/artifactory/api/repositories/edge-docker-remote -d '{"key":"edge-docker-remote","username":"admin","password":"XXX","rclass":"remote","url":"https://XXX/artifactory/XXX","packageType":"docker","contentSynchronisation":{"enabled":"true"}}' -H "Content-Type: application/json" -XPUT
Successfully created repository 'edge-docker-remote'
```

**Comment by mikeycmccarthy** [comment]
Proxied the Terraform code via Charles so I could see what was being sent:

```json
{
	"key": "my_smart_remote",
	"rclass": "remote",
	"packageType": "docker",
	"url": "https://XXX/XXX",
	"username": "admin",
	"password": "XXX",
	"proxy": "",
	"repoLayoutRef": "simple-default",
	"remoteRepoLayoutRef": "",
	"propagateQueryParams": false,
	"priorityResolution": false,
	"retrievalCachePeriodSecs": 7200,
	"missedRetrievalCachePeriodSecs": 0,
	"assumedOfflinePeriodSecs": 300,
	"synchronizeProperties": true,
	"propertySets": ["artifactory"],
	"contentSynchronisation": {
		"enables": true
	},
	"externalDependenciesEnabled": true,
	"externalDependenciesPatterns": [],
	"enableTokenAuthentication": false,
	"blockPushingSchema1": false
}
```

I'll try and see what differs between that and the curl above, and whether the same data works in the curl

**Comment by jcoste-orange** [comment]
The bug is here : https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/repositories.go#L52
enables instead of enabled

**Comment by mikeycmccarthy** [comment]
Snap - just reached the same conclusion!

**Comment by mikeycmccarthy** [comment]
I'll try and set myself up locally to be able to make this change and submit a PR

**Comment by Olamzykenth** [comment]
> **Describe the bug** We're trying to manage repositories on an Artifactory Edge instance, they're a little bit special in that they only support smart remotes (Artifactory to Artifactory) rather than simply any type of remote. It seems the provider is unable to manage repositories of this type - see the output below. Looking at the network calls in Chrome developer mode when you using the UI it appears that creation of the smart remote is just a POST to /repositories and nothing more special than that.
> 
> ```shell
> $ tf apply
> 
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   + create
> 
> Terraform will perform the following actions:
> 
>   # artifactory_remote_docker_repository.smart_remote will be created
>   + resource "artifactory_remote_docker_repository" "smart_remote" {
>       + allow_any_host_auth                     = (known after apply)
>       + assumed_offline_period_secs             = 300
>       + blacked_out                             = (known after apply)
>       + block_mismatching_mime_types            = (known after apply)
>       + block_pushing_schema1                   = (known after apply)
>       + bypass_head_requests                    = (known after apply)
>       + client_tls_certificate                  = (known after apply)
>       + description                             = (known after apply)
>       + enable_cookie_management                = (known after apply)
>       + enable_token_authentication             = (known after apply)
>       + excludes_pattern                        = (known after apply)
>       + external_dependencies_enabled           = true
>       + failed_retrieval_cache_period_secs      = (known after apply)
>       + hard_fail                               = (known after apply)
>       + id                                      = (known after apply)
>       + includes_pattern                        = (known after apply)
>       + key                                     = "my_smart_remote"
>       + missed_cache_period_seconds             = (known after apply)
>       + offline                                 = (known after apply)
>       + package_type                            = (known after apply)
>       + password                                = (sensitive value)
>       + priority_resolution                     = (known after apply)
>       + propagate_query_params                  = false
>       + property_sets                           = [
>           + "artifactory",
>         ]
>       + proxy                                   = (known after apply)
>       + remote_repo_layout_ref                  = (known after apply)
>       + repo_layout_ref                         = "simple-default"
>       + retrieval_cache_period_seconds          = 7200
>       + share_configuration                     = (known after apply)
>       + socket_timeout_millis                   = (known after apply)
>       + store_artifacts_locally                 = (known after apply)
>       + synchronize_properties                  = true
>       + unused_artifacts_cleanup_period_enabled = (known after apply)
>       + unused_artifacts_cleanup_period_hours   = (known after apply)
>       + url                                     = "https://XXX"
>       + username                                = "XXX"
>       + xray_index                              = (known after apply)
> 
>       + content_synchronisation {
>           + enabled = true
>         }
>     }
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> ╷
> │ Warning: Experimental feature "module_variable_optional_attrs" is active
> │
> │   on provider.tf line 3, in terraform:
> │    3:   experiments      = [module_variable_optional_attrs]
> │
> │ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
> │
> │ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
> ╵
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> artifactory_remote_docker_repository.smart_remote: Creating...
> ╷
> │ Error:
> │ 400 PUT https://XXX/artifactory/api/repositories/my_smart_remote
> │ {
> │   "errors" : [ {
> │     "status" : 400,
> │     "message" : "Only smart remote repositories are supported with Artifactory Edge license\n"
> │   } ]
> │ }
> │
> │   with artifactory_remote_docker_repository.smart_remote,
> │   on provider.tf line 17, in resource "artifactory_remote_docker_repository" "smart_remote":
> │   17: resource "artifactory_remote_docker_repository" "smart_remote" {
> ```
> 
> ```shell
> terraform {
>   required_version = "1.1.1"
>   experiments      = [module_variable_optional_attrs]
>   required_providers {
>     artifactory = {
>       source = "jfrog/artifactory"
>     }
>   }
> }
> 
> provider "artifactory" {
>   url           = var.artifactory_url
>   access_token  = var.artifactory_access_token
>   check_license = var.check_license
> }
> 
> resource "artifactory_remote_docker_repository" "smart_remote" {
> 
>   key                           = "my_smart_remote"
>   repo_layout_ref               = "simple-default"
>   property_sets                 = ["artifactory"]
>   external_dependencies_enabled = true
>   url                           = "https://XXX"
>   username                      = "XXX"
>   password                      = "XXX"
>   synchronize_properties        = true
>   content_synchronisation {
>     enabled = true
>   }
> 
> 
>   lifecycle {
>     ignore_changes = [password]
>   }
> 
> }
> ```
> 
> Terraform 1.1 Artifactory: "version" : "7.31.10", "revision" : "73110900",
> 
> **Requirements for and issue**
> 
> * [x]  A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
> * [x]  Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
> * [x]  Your version of terraform
> 
> **Expected behavior** I would expect a smart remote to be manageable the same way as a regular remote.
> 
> ## **Additional context**

**Comment by Olamzykenth** [comment]
@alexhung

**Comment by alexhung** [comment]
@Olamzykenth I took a quick look at this issue last year and this is due to the lack of support of smart repository attributes in the `content_synchronisation` attribute. #50 is related to the same.

@maheshjfrog is working on #50 right now.

**Comment by alexhung** [comment]
@Olamzykenth In the future, please create a new issue instead of adding to a related one.
