### ISSUE TITLE
Unable to import provider in go project - package is outdated

### ISSUE THREAD

**Issue by tenstad** [jfrog/terraform-provider-artifactory#298]
**Describe the bug**
Unable to `go get` the provider. It also appears to be very outdated: `Version: v1.2.4 Latest` https://pkg.go.dev/github.com/jfrog/terraform-provider-artifactory
```
go get github.com/jfrog/terraform-provider-artifactory
go: downloading github.com/jfrog/terraform-provider-artifactory v1.12.0
go get: github.com/jfrog/terraform-provider-artifactory@v1.12.0: parsing go.mod:
        module declares its path as: gopkg.in/resty.v1
                but was required as: github.com/jfrog/terraform-provider-artifactory
```

I think it could be easily fixed, but am not sure why it is outdated.

**Additional context**
I want to import it to get the latest provider schema: https://github.com/jfrog/terraform-provider-artifactory/blob/2385a079da1b16c6179ec4917e1f9801c743f101/pkg/artifactory/provider.go#L19

**Comment by alexhung** [comment]
I've published the provider with `go.mod` and `main.go` to include `/v2` in the module path. Ran `GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/jfrog/terraform-provider-artifactory/v2@v2.12.0` and https://pkg.go.dev/ is still not updated.

Need more investigation.

**Comment by alexhung** [comment]
Turns out this is now updated here at https://pkg.go.dev/github.com/jfrog/terraform-provider-artifactory/v2

**Comment by tenstad** [comment]
Thank you! :smiley:
