### ISSUE TITLE
Artifactory Project Resource

### ISSUE THREAD

**Issue by ColtonHerrodWork** [jfrog/terraform-provider-artifactory#301]
**Is your feature request related to a problem? Please describe.**

The Artifactory provider doesn't have a resource that allows for the creation and management of Artifactory projects.  Our team is aiming to manage all of our Artifactory configurations through Terraform and the lack of project resource results in a gap in our code capabilities.

**Describe the solution you'd like**

Our preferred solution would be for an `artifactory_project` resource to be added to the provider that allows our team to manage the Artifactory Project construct through Terraform code.

**Describe alternatives you've considered**

We can currently manage projects manually, but this results in some confusion as most of our Artifactory usage is managed through Terraform.

**Additional context**

None

**Comment by alexhung** [comment]
@ColtonHerrodWork We have a separate [provider to support Artifactory Project](https://github.com/jfrog/terraform-provider-project)
