### ISSUE TITLE
Avoid downloads when file exists and matches

### ISSUE THREAD

**Issue by mscottnelson** [jfrog/terraform-provider-artifactory#309]
**Is your feature request related to a problem? Please describe.**
When pulling files from Artifactory, they are pulled every time, even if "force_overwrite" is set to false. When a file pull is very large, this can greatly slow down things unnecessarily in the case that a matching local file already exists and matches the remote. In v2.3.1 the artifactory provider did not download every time. It changed to download regardless of whether remote and local files matched on commit eef9a5cd96c10665b5fe8e50337f7979757d9b59.

**Describe the solution you'd like**
If the remote file and the local file have matching checksums, and "force_overwrite" is set to "false", then do not download the remote file.

Please let me know if you would accept a pull-request to re-enable the ability to skip downloads when the remote file matches the local file.

**Comment by alexhung** [comment]
@mscottnelson we very much welcome PR from our community.

**Comment by chb0github** [comment]
This should have been working - @alexhung if you check history for this code I made some changes - you can check them out and see if you can identify the issue (or just revert)
