### ISSUE TITLE
Project level repo creation 

### ISSUE THREAD

**Issue by yash95shah** [jfrog/terraform-provider-artifactory#318]
The way we have set up Jfrog in our organization is that we request a new project and are given the project admin rights to that project. We can only create resources in that project, (By resources I mean creation of repositories) so I guess I'm just failing to understand how to create a repositories scoped at the project level. I'm using to pass in the key 'projectKey' which is listed in the REST API documentation. https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON
something like this- 
`resource "artifactory_local_repository" "pypi-libs" {
  key             = "pypi-libs"
  **projectKey = 'XYZ**
  package_type    = "pypi"
  repo_layout_ref = "simple-default"
  description     = "A pypi repository for python packages"
}`

**Comment by yash95shah** [comment]
Upon not providing a project key, our TFE gives off a 403 as I do not have admin access at the root/organization level.

**Comment by alexhung** [comment]
The `projectKey` attribute is not currently supported in the provider. I'll schedule this to be fixed.

**Comment by chb0github** [comment]
Perhaps you're not aware, but there is a [dedicated provider for projects](https://github.com/jfrog/terraform-provider-project) and you may find what you're looking for there. 

Also, you're using deprecated code - @alexhung - will `artifactory_local_pypi_repository` be available soon?

**Comment by yash95shah** [comment]
> Perhaps you're not aware, but there is a [dedicated provider for projects](https://github.com/jfrog/terraform-provider-project) and you may find what you're looking for there.
> 
> Also, you're using deprecated code - @alexhung - will `artifactory_local_pypi_repository` be available soon?

Correct. That dedicated provider is used to create the project resource and users etc. I am looking to just create a repo within a project without having to go tf import the project.

**Comment by alexhung** [comment]
@chb0github We are currently missing 2 attributes in repo resources to support Projects. One is `projectKey` and the other `environments`. These are set in each repo in this provider, not with the project provider.

**Comment by alexhung** [comment]
@chb0github PyPi repo type support is being worked on right now. Should be available soon. I'm adding `projectKey` support to non-legacy repos.

**Comment by alexhung** [comment]
@chb0github @yash95shah I spoke too soon. The PyPi repo support I referred to is for remote repo, which has been released. Local PyPi repo support is not yet planned.

**Comment by alexhung** [comment]
@yash95shah `artifactory_local_pypi_repository` is already supported. See [doc](https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/artifactory_federated_pypi_repository.md)
