### ISSUE TITLE
Not able to use artifactory_file data source as the input to a lambda

### ISSUE THREAD

**Issue by alexanderluiscampino** [jfrog/terraform-provider-artifactory#323]
**Describe the bug**
Artifactory provider not downloading file from artifactory upon correctly identifying it. 

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform

**Expected behavior**
The data source should be accepted in the lambda resource.

Furthermore, I have checked the pipeline artifacts (Running in GitLab) and the package (.zip) cannot be found anywhere, which leads me to think it never got downloaded.

**Additional context**

- Terraform version: 1.0.11
- jfrog/artifactory v2.19.1
- hashicorp/aws v4.1.0

Terraform code:
```hcl
provider "artifactory" {
  url           = "https://artifactory.net/artifactory/"
  check_license = false
}

data "artifactory_file" "artifact" {
  repository     = "generic-local"
  path             = "/test/test.2070511.86d15eb7.zip"
  output_path = "${path.module}/source_classifier.zip"
}

resource "aws_lambda_function" "main" {
  function_name    = "test"
  role                 = aws_iam_role.lambda_role.arn
  handler          = "counter.handler"
  runtime          = "python3.8"
  filename         = data.artifactory_file.artifact.output_path
  source_code_hash = base64encode(data.artifactory_file.artifact.sha256)
  # source_code_hash = filebase64sha256(data.artifactory_file.artifact.output_path)
  memory_size      = 1024
  timeout          = 900
  architectures    = ["x86_64"]
  description      = ""
}

```

Error:

![image](https://user-images.githubusercontent.com/32500355/154630053-7692aabf-32cd-4483-b1f7-1b700cc0b203.png)

Looking at the .tfstate, I can see that this artifact was correctly located and information about it was fetched (redacted):
```json
{
      "module": "module.service",
      "mode": "data",
      "type": "artifactory_file",
      "name": "artifact",
      "provider": "module.service.provider[\"registry.terraform.io/jfrog/artifactory\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "created": "2022-02-17T22:03:03.666Z",
            "created_by": "user",
            "download_uri": "https://artifactory.net/artifactory/test/test.2070511.86d15eb7.zip",
            "force_overwrite": false,
            "id": "https://artifactory.net/artifactory/test/test.2070511.86d15eb7.zip",
            "last_modified": "2022-02-17T22:03:03.632Z",
            "last_updated": "2022-02-17T22:03:03.667Z",
            "md5": "b08f1be060830908b46f5d4205d7a10e",
            "mimetype": "application/zip",
            "modified_by": "user",
            "output_path": "../../../source.zip",
            "path": "/test/test.2070511.86d15eb7.zip",
            "repository": "generic-local",
            "sha1": "a1e8907c72f9efb77f9578c76bff73cf62[549]()f41",
            "sha256": "11efb4a005ffa9c91c0c364d69a4b44e35e98d7403bb9c6167a274a2d603a13d",
            "size": 484
          },
          "sensitive_attributes": []
        }
      ]
    },
```

Additionally, I tried using the `username` and `password` attribute initially, and got the following:

![image](https://user-images.githubusercontent.com/32500355/154631201-3bb5d106-2370-4f60-a818-a2482b70f395.png)

Then attempted to simply use the `api_key`, but same error as above. Really confusing. Sourced from [docs](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs)

What am I doing wrong?

**Comment by alexhung** [comment]
@alexanderluiscampino I think the Artifactory can't find your file in the repo because your path is prefixed with `/`. This means you are asking Artifactory for the file from `test` repository which I don't think is what you intended, as you have `generic-local` as the repository to fetch from.

Your state file shows the download url is `https://artifactory.net/artifactory/test/test.2070511.86d15eb7.zip`, instead of `https://artifactory.net/artifactory/generic-local/test/test.2070511.86d15eb7.zip`

Removing the leading slash should solve your problem.

Let me know if works.

**Comment by alexanderluiscampino** [comment]
@alexhung, thank you for the input. Some information I put above was redacted for the sake of being private, hence the / prefix is just a result of that redaction. 

If I try to run terraform --plan with a clearly wrong path, a non existent one, the artifactory immediately throws an error, 404. Hence, the fact I get all the way to --apply,  and the fact that in the .tfstate file I can see the file hash, size, etc, leads me to think the resource is being found. Just not downloaded. 

```
404 GET https://artifactory.net/artifactory/api/storage/wrong-filename.zip
{
  "errors" : [ {
    "status" : 404,
    "message" : "Unable to find item"
  } ]
}
```

**Comment by alexhung** [comment]
@alexanderluiscampino Given this repo structure in Artifactory:
<img width="200" alt="Screen Shot 2022-02-18 at 3 34 55 PM" src="https://user-images.githubusercontent.com/27263/154774819-9d8bb8de-6f92-4e0c-b8fc-0992cce7f1aa.png">
This is the HCL I used to download the file:

```hcl
data "artifactory_file" "artifact" {
  repository  = "example-repo-local"
  path        = "foo/bar/crash.zip"
  output_path = "${path.module}/foo/bar/crash.zip"
}
```

**Comment by alexhung** [comment]
@alexanderluiscampino Are you running Terraform locally or on GitLab? If on a cloud service like GitLab, you may want to check that the process has permission to write file to that target location.

Have you test the HCL locally to verify?

**Comment by alexanderluiscampino** [comment]
I'm not running locally, indeed. But permissions not an issue for instance, I have done a workaround using a curl local-exec null resource to the exact same location and it works

```hcl
resource "null_resource" "artifact" {
  triggers = {
    # Multiple triggers to ensure artifact gets fetched everytime
    filename     = "${path.module}/${var.output_filename}"
    artifact_url = "${var.artifactory_url}/${var.repository}/${var.artifact_path}"
    timestamp    = timestamp()
  }

  provisioner "local-exec" {
    command = <<EOT
      curl -o ${self.triggers.filename} ${self.triggers.artifact_url}
    EOT
  }
}

data "local_file" "artifact" {
  # Referring to null_resource.artifact here ensures that the provisioner
  # will complete before Terraform attempts to read this file.
  filename = null_resource.artifact.triggers.filename
}
```

**Comment by alexanderluiscampino** [comment]
In the CI ENV variables, we have the following defined by default

- ARTIFACTORY_API_KEY
- ARTIFACTORY_USERNAME

which are mentioned to be used in the provider [here](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs#basic-auth) in the docs. 

To download resources from our artifactory, we do not need username:password. Are these ENVs being setup causing some sort of conflict in the JFrog provider? Long shot, but worth mentioning.

**Comment by alexhung** [comment]
@alexanderluiscampino The code for `artifactory_file` data source is here: https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/datasource_artifactory_file.go#L107

We create the output paths and then use Resty to download the data into it. I noticed the `output_path` in your state file has `../../../source.zip`. Whilst it should work in theory, I wonder if Golang `os` prevents this as security measure (i.e. path traversal). Need some testing to verify.

**Comment by alexhung** [comment]
@alexanderluiscampino I also recommend you to reproduce this locally first to verify this bug. This will isolate if the issue lies with the provider or the environment that it runs in.

**Comment by rlee89** [comment]
Hi everyone, 

Interestingly, I've landed on the same problem with a similar scenario where we have nested child modules that are referenced in an intermediate and root module. I'm currently stumped as well because I can reproduce this locally where I get a similar error and issues described:
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/19547617/159064570-ea69b702-7254-42a5-8b02-ea138a5e09d2.png">


Our workflow looks this like:
```
root/
├── (references intermediate module)
├── (deploys a slew of other resources)

intermediate/
├── (references child module)
├── (additional resources related to the functionality of the lambda)
└── (calls additional helper child modules for vpc details, etc)

child-module/
├── (near exact same implementation as the tf code above at its core)
└── (where the data resource is defined)

child-module.tf (snippet)
#--- Artifactory --------------------------------------------------------------
data "artifactory_file" "artifact" {
  count = module.this.enabled ? 1 : 0

  repository      = var.artifactory_repository
  path            = var.artifactory_path
  output_path     = "tmp/${basename(var.artifactory_path)}"
  force_overwrite = var.artifactory_force_overwrite
}

#--- Lambda ----------------------------------------------------------------
resource "aws_lambda_function" "default" {
  count = module.this.enabled ? 1 : 0

  function_name = module.this.id
  role          = var.lambda_iam_role_arn
  description   = local.description

  filename         = data.artifactory_file.artifact[0].output_path
  source_code_hash = filebase64sha256(data.artifactory_file.artifact[0].output_path)
#-- Settings -----------------------------------------------------------------
...

}
```

I can see the zip file is never downloaded locally. What's interesting is that this only happens on clean runs (the state is clean and no .zip exists already). Whenever we run our tests for the first time from the root module. It isn't to ever able to evaluate the data resource (`artifactory_file`) in the child module and download the zip. If the zip already exists, then it's no problem. The issue is that it'll never pass in the CICD the first time.

Also to add, because we have a toggle for most of our resources in tf with a `count`. If I specifically disable the child module to deploy the lambda and its resources for a first run without deploying/calling the child module, then toggle the child module to deploy. The entire TF plan and apply succeed and our tests pass, which feels like a dependency/timing issue. I've tried to add `depends_on`, waits, null triggers on the child module and within the intermediate modules and no luck. 

A workaround is if I split up the child module and build the lambda resource in the intermediate module. I can have the artifactory data resource on the root level, and pass the path down to the intermediate which works fine, except we don't have a reusable lambda child module 😭 ...

Open to any thoughts, my next steps are to try using a curl to artifactory to rule out any provider/resource issues to grab the zip file in the child module. I've tested the child module by itself and nested and it's behaving correctly... I still feel like it's a dependency issue that I could be missing as we get into more nesting and toggles. 😞

**Comment by chb0github** [comment]
Sorry for not getting back to you sooner. We'll dig into this. @alexhung will be back on Monday

**Comment by dasmanas** [comment]
> 
What is the value getting passed for `force_overwrite` through `var.artifactory_force_overwrite`?

We tested the from our side with the following template and download is working as expected.

with following hcl snippet  for `artifactory_file` we have tested
```
data "artifactory_file" "my-file" {
  repository = "example-repo-local"
  path = "crash.zip"
  output_path = "crash.zip"
  force_overwrite = false
}

output "output_path_value" {
  value = filebase64sha256("~/crash.zip")
}
```
output from `% terraform apply`
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

output_path_value = "eiSJ3SCdCsty9/EdFxtBjmVki5zJbGw1HgDiJVH92PE="
```

### Additionally investigate with nested module
```
./
├── intermediate
│   ├── child
│   │   └── sample.tf
│   └── sample.tf
├── sample.tf
└── terraform.tfstate
```
## ./sample.tf
```
module "intermediate" {
  source = "./intermediate"
}

output "sha256" {
  value = filebase64sha256(module.intermediate.output_path)
}
```

## ./intermediate/sample.tf
```
module "child" {
  source = "./child"
}

output "output_path" {
  value = module.child.output_path
}
```

## ./intermediate/child/sample.tf
```
# Required for Terraform 0.13 and up (https://www.terraform.io/upgrade-guides/0-13.html)
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "4.0.0"
    }
  }
}

provider "artifactory" {
  url = "<artifactory_url>"
  access_token = "<access_token>"
}

data "artifactory_file" "my-file" {
  repository = "example-repo-local"
  path = "crash.zip"
  output_path = "crash.zip"
  force_overwrite = false
}

output "output_path" {
  value = data.artifactory_file.my-file.output_path
}
```

We are getting expected output every time for `artifactory_file`
```
% terraform apply                

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

sha256 = "eiSJ3SCdCsty9/EdFxtBjmVki5zJbGw1HgDiJVH92PE="
```

_Please make sure to cascade output all the way from child module to root module like the above example._

**Comment by dasmanas** [comment]
@rlee89 please review the comments along with implementations. 

We will close the ticket if we don't hear back in 7 days from you on the same line. If you face other issue, please open new issue.

**Comment by rlee89** [comment]
@dasmanas we were passing `true` to force_overwrite (`var.artifactory_force_overwrite`)

> We tested the from our side with the following template and download is working as expected.

Interesting... I can't think of anything besides some weird dependency with all the additional resources where it's going ahead with trying to deploy the lambda before it can download the file. We also went with the curl local-exec workaround (assume similar to @alexanderluiscampino). :( 

Appreciate you trying to investigate the issue. I'll see if I can revisit the problem to provide more information, but for now it's not a blocker. 🙏
