### ISSUE TITLE
Assumed Offline Period parameter support in remote repository configuration

### ISSUE THREAD

**Issue by korjek** [jfrog/terraform-provider-artifactory#328]
This is a feature request.

It would be really great if it's possible to specify Assumed Offline Period field for a remote repository using this provider.

Thank you!

**Comment by ShreyasNBS** [comment]
Have you tried using assumed_offline_period property? I vaguely remember seeing it somewhere online, but now google yields no search results :(

**Comment by korjek** [comment]
@ShreyasNBS thanx for your reply.

You are right and I had to be more specific -this option is not supported in generic artifactory_remote_repository resource.
And since we use it for Maven repos (that doesn't have dedicated remote resource) this is the issue for us.

**Comment by alexhung** [comment]
@korjek We are still in the process of adding all the repo type specific remote repo sources. Let me add Maven to the sprint schedule.
