### ISSUE TITLE
Resource artrifactory_ldap_setting not injecting manager_password

### ISSUE THREAD

**Issue by erickortemaxar** [jfrog/terraform-provider-artifactory#334]
When using the terraform artifactory provider version 2.20.1, I am noticing that the  artifactory_ldap_setting resource does not properly inject the manager_password into the LDAP settings on the server. All other settings are injected properly and appear in the LDAP settings on my Artifactory server.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
resource "artifactory_ldap_setting" "ldap_name" {
  key = "DG-ENT-AD"
  ldap_url = "ldap://${var.ldap_hostname}:389/${dc_path}"
  user_dn_pattern = "uid={0},ou=People"
  email_attribute = "mail"
  auto_create_user = true
  ldap_poisoning_protection = true
  allow_user_to_access_profile = false
  paging_support_enabled = true
  search_filter = "(sAMAccountName={0})"
  #search_base = "ou=users"
  search_sub_tree = true
  manager_dn = "CN=${var.ldap_service_account},${ou_dc_path}"
  manager_password = data.aws_ssm_parameter.ldap_service_account_password.value
}
- [ 7.33.12] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ 0.13.7] Your version of terraform

**Expected behavior**
I was expecting to run the above terraform and have all LDAP settings defined in the terraform injected into the LDAP settings of the Artifactory server. Instead, I see all settings injected properly except the manager_password. I double checked that the aws_ssm_parameter data source actually contained the secret by creating a terraform output variable which displayed the value of the password after a terraform apply.

**Additional context**

**Comment by alexhung** [comment]
@maheshjfrog @dasmanas @chb0github Related to password roundtrip issue #283

**Comment by erickortemaxar** [comment]
Should I use a previous version of the artifactory terraform provider? This is my first time working with the provider.

**Comment by ShreyasNBS** [comment]
@alexhung Can we please roll this back to how it was a year ago? It would be massively useful. This is blocking us from using the new LDAP resources, due to manager password not being set correctly.

**Comment by erickortemaxar** [comment]
If not, then can we get an update on this issue?

**Comment by ShreyasNBS** [comment]
@maheshjfrog I merely asked for a rollback of the bug in #283 because I was unable to add a comment there for some reason.

**Comment by erickortemaxar** [comment]
I just ran another test and the manager password populated correctly on my artifactory server.
