### ISSUE TITLE
Add resource artifactory_remote_generic_repository

### ISSUE THREAD

**Issue by oallauddin** [jfrog/terraform-provider-artifactory#339]
Description:
Need to setup a generic remote repository as described here. https://stackoverflow.com/a/50372913
Part of the setup requires setting list_remote_folder_items to false. 

Issue:
list_remote_folder_items is not available in resource artifact_remote_repository and there are no plans to enhance it further.

Requirements:
A new resource artifactory_remote_generic_repository needs to be created that will have list_remote_folder_items available for use.

Workaround:
Logging into the UI and unchecking List Remote Folder Items

**Comment by chb0github** [comment]
I believe this was [just implemented ](https://github.com/jfrog/terraform-provider-artifactory/issues/294)
Still not released

**Comment by oallauddin** [comment]
Not sure. I had a comment in that issue. alexhung asked me to create a separate issue.

**Comment by maheshjfrog** [comment]
Currently docker, helm, npm, pypi and cargo remote repositories are in new implementation. Rest are all in legacy implementation.
