### ISSUE TITLE
Enable full support for docker remote repos

### ISSUE THREAD

**Issue by gw0** [jfrog/terraform-provider-artifactory#34]
The option "Enable Foreign Layers Caching" (`enableForeignLayersCaching`) for remote Docker repos is available in the UI, but missing from the Terraform provider.

Because many other type-specific options are also missing, I would suggest you add an option to directly provide a JSON for `typeSpecific` map that would be passed to the Artifactory API as-is (without validation). This way you will no longer have to maintain and keep type-specific options up-to-date with the Artifactory API.

**Comment by chb0github** [comment]
You are right about repo specific features being unavailable. I am more in favor of implementing a docker repo correctly and can take this up right away.

**Comment by chb0github** [comment]
You'll be happy to know this is moving up the priority list
