### ISSUE TITLE
User password is changed after changing an attribute with terraform

### ISSUE THREAD

**Issue by martinm82** [jfrog/terraform-provider-artifactory#340]
**Describe the bug**
If a user attribute is changed, e.g., enable/disable UI access, a user cannot login with the previously set user password. It seems that the password is reset to a different value.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: Artifactory Cloud 7.34.4
- [x] Your version of terraform: 1.0.11

**Expected behavior**
When creating a user with a specific password I am expecting that any modification of a user attribute (e.g. enable/disable UI access) won't result in a changed password.

**Additional context**

**Comment by martinm82** [comment]
@alexhung do you know when this issue will be picked up and fixed?

**Comment by martinm82** [comment]
The problem is quite nasty in case you have groups with `auto_join` enabled. Terraform will update the user every time a user gets added to such a group and update as well the password again.

**Comment by martinm82** [comment]
@chb0github @alexhung I looked a bit into the code and I think I found the issue.

The `unpackUser` function is used in `resourceUserCreate` and `resourceUserUpdate`. Inside `unpackUser` in both situations the password is obtained. In case of creating a new one the correct password is used. But when using `resourceUserUpdate` it seems that `ResourceData` contains some wrong password. 

I suspect that the password value is here the base64 encoded hash value that was generated for storing the password in the state file but that is just a theory.

**Comment by chb0github** [comment]
You're right about where to change the code but not why. The password actually comes back encrypted

All password related issues are at the top of our priority list. Each case requires a complete think on how to handle it. Stay tuned

**Comment by chb0github** [comment]
We have [this discussion](https://github.com/jfrog/terraform-provider-artifactory/discussions/333) open. Please track there

**Comment by martinm82** [comment]
How is the password coming back encrypted? The REST API is not returning the password when fetching user details with `GET`. And I haven't found anywhere a call to the `encryptedPassword` endpoint.

In general we have no problem with the current implementation and provide the password. The REST API (https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.User+json) states that `password` is a mandatory field. But I understand that others have a different use case.

We are managing access with SCIM for regular users and groups. But we do manage service accounts with internal Artifactory users and generate random passwords initially (`random_password`) and store them in Hashicorp Vault (HCV). Those generated passwords follow the Artifactory password policy.

Customers get access to their credentials in HCV and have the possibility to modify the password whenever they want or when we decide to rotate it. Single source of truth is HCV. 

When a password is changed manually a new version in HCV is created and it needs to be bumped in the Terraform code. We basically treat IaC as single source of truth. Any changes in the UI are overwritten by it and customers have access to the infra code and need to modify it. Since we manage only service accounts, majority of customers do not see the need to modify the passwords. 

I went through the discussion (thanks for pointing to it as I was not aware) and I understand certain uses cases. In our case we strictly follow what the REST API provides and it requires a password.

So yes, I believe this discussion is important but we need a way to fix this issue somehow temporarily. Any hints for a good fix are welcome. We are even thinking to use a custom version of the provider until a proper fix from your side will be available.

**Comment by martinm82** [comment]
BTW, I think there is even a more severe issue but on Artifactory side.

I've been playing around with the REST API only and the `/api/security/users/` `POST` endpoint and discovered that:

* if the user payload does contain an empty `password` attribute, Artifactory accepts the request
* if the user payload does not contain the `password` attribute, Artifactory accepts it as well
* if the user payload contains a password not matching the password policy (e.g., foo123) it returns a `BAD REQUEST` error stating that `New password doesn't qualify password policy: uppercase requirement is invalid. Should include at least 1\`

But based on the REST API docs it clearly says that the password is a mandatory field and even an empty password should result in a bad request.

We are using Artifactory Cloud 7.36.4. 

Will report this as well to the JFrog Support.

**Comment by martinm82** [comment]
I just realised that if the `Password` attribute is not provided in the `resourceUserUpdate` function to the API call the password is not modified on Artifactory side.

**Comment by chb0github** [comment]
Handy observations. Let me know if you have time you want to contribute. Can always find a ticket to assign 😄

**Comment by martinm82** [comment]
I am wondering whether the following change of the `User` struct would be enough:

```
Password                 string   `json:"password,omitempty"`
```

**Comment by martinm82** [comment]
> Handy observations. Let me know if you have time you want to contribute. Can always find a ticket to assign 😄

Haha, yeah why not. I think I volunteered in one of the tickets already for the release process automation. I hope I will have soon some time to do that.

But if you have some low hanging fruits I am more than happy to contribute back.

**Comment by martinm82** [comment]
I can confirm that the `omitempty` change solved the issue on our side. Tested as well the initial create and follow-up updates and all seems to work fine.

@alexhung what do you think about this change? Do you know why the password in case of an update is actually empty? Is this by design? If yes, then this change with `omitempty` on the password could a solution.

**Comment by martinm82** [comment]
Isn't the real issue actually caused by the fact that the password is stored as base64 encoded hash? By design Terraform does not encrypt sensitive data (there is quite old ticket on this: https://github.com/hashicorp/terraform/issues/516). 

We are already using Hashicorp Vault and guess what, the state file contains all the passwords we store in HCV text plain in the state. 

So in that sense the hashing of the password is not making (at least for us) our setup safer. 

Maybe we should instead remove the `StateFunc` for the passwords and store the values text plain. Together with this change and calling `getString("password", false)` instead `getString("password", true)` would be as well a possible solution?

**Comment by alexhung** [comment]
@martinm82 All of your suggestions are part of the larger password PR I started work on yesterday.

As for release scheduling, we will take your request into consideration. @chb0github ☝🏼

**Comment by alexhung** [comment]
@chb0github For the user API, we don't get `password` field at all with `GET` request (we create a hash for nil), hence the complexity on how to keep the state valid.

**Comment by chb0github** [comment]
Oh.. just this problem. Nevermind

**Comment by alexhung** [comment]
> P.S. If you want to release a new version it would be good to do it before #380 since we haven't yet migrated some repos to the specific resources

@martinm82 You were referring to fix to this specific issue, not the broader password changes, right?

**Comment by martinm82** [comment]
> > P.S. If you want to release a new version it would be good to do it before #380 since we haven't yet migrated some repos to the specific resources
> 
> @martinm82 You were referring to fix for this specific issue, not the broader password changes, right?

Yes, I was referring only to this issue.

> @martinm82 The `omitempty` tag was removed couple of months ago in #288 so I am not sure which version of the code base you are referring to 😄
> 
I was saying that by adding the `omiteempty` tag the problem disappeared :) I was not aware that the tag was in a previous version removed.

> Removing the `StateFunc` hashing and switching to `getString("password", false)` fixes the problem. So look for a PR soon.
Wohoo

**Comment by martinm82** [comment]
@alexhung, I have tested right now v4.0.0 and it works like a charm. Thanks a lot for the fast feedback you guys give and the fast fix. Appreciating it.
