### ISSUE TITLE
Remove basic authentication support from the Artifactory provider

### ISSUE THREAD

**Issue by danielmkn** [jfrog/terraform-provider-artifactory#342]
We are removing basic auth support from the provider. Only `access_key` (Bearer) should be used for all the calls. 
`username`, `password` and `api_key` will be removed to align with the projected core product change.

**Comment by danielmkn** [comment]
I'm asking project contributors for your feedback! Please share your thoughts on that change: 
@chb0github 
@alexhung
@maheshjfrog
@jamestoyer
@dillon-giacoppo
@jasonwbarnett
@ax-taustgen
@volkc-basf
@ttsangAtlassian
@tenstad
@KierranM
@josh-barker-coles
@bodgit
@antonmos
@jfroche
@zymzxq
@ryndaniels
@cappyzawa
@AlexanderRMcNeill
@trevorah
@bendrucker
@MichaelChristopherson
@rossedman
@dasmanas
@wc-s

**Comment by chb0github** [comment]
@jamestoyer yes, this would push the version to 3.0.0.
I'm sorry you're struggling with a migration. If there is anyone input we can give let us know

We really had to ditch atlassian completely, as well as the jfrog client for a variety of reasons. The result is a consistent experience and quicker turn around on features. We've also eliminated some long standing annoyances inherent in RT

**Comment by skyzyx** [comment]
I agree with the move forward to remove these alternate authentication methods. However, I disagree with the premise:

> […] to align with the projected core product change.

As someone who has been trying to read JFrog's tea-leaves, I've been able to see this coming. But I don't think this has been made _clear_ by JFrog, Inc. by _any_ means.
