### ISSUE TITLE
artifactory_local_sbt_repository feature request

### ISSUE THREAD

**Issue by karthik-nannapaneni** [jfrog/terraform-provider-artifactory#345]
artifactory_local_sbt_repository  is missing the following SBT settings.

https://registry.terraform.io/providers/jfrog/artifactory/latest/docs

  #suppress_pom_consistency_checks = false
  #snapshot_version_behavior = "unique"

```hcl
resource "artifactory_local_sbt_repository" "repo-local-sbt" {
  key = "repo-local-sbt"
  repo_layout_ref  = "sbt-default"
  #suppress_pom_consistency_checks = false
  #snapshot_version_behavior = "unique"
}
```

**Comment by chb0github** [comment]
@maheshjfrog and @dasmanas and @danielmkn - those are both fields present in all java repo - please verify that, for sbt those settings are in the UI

**Comment by maheshjfrog** [comment]
@chb0github ... yes. Looks like that. Will add story for this request in next sprint.

**Comment by karthik-nannapaneni** [comment]
@maheshjfrog SBT settings are only enabled on "artifactory_remote_sbt_repository", Can you please enable the same on the local SBT repo.

**Comment by maheshjfrog** [comment]
@karthik-nannapaneni ... 
I just checked following config in my test env which worked fine.

`resource "artifactory_local_sbt_repository" "terraform-local-test-sbt-repo" {
  key = "terraform-local-test-sbt-repo"
  checksum_policy_type            = "client-checksums"
  snapshot_version_behavior    = "unique"
  max_unique_snapshots           = 6
  handle_releases                       = true
  handle_snapshots                    = true
  suppress_pom_consistency_checks = true
}`
Wondering what is causing your issue.
