### ISSUE TITLE
Request to create the missing virtal repositories.

### ISSUE THREAD

**Issue by karthik-nannapaneni** [jfrog/terraform-provider-artifactory#346]
The following repos are not available in https://registry.terraform.io/providers/jfrog/artifactory/latest/docs

artifactory_virtual_docker_v2_repository
artifactory_virtual_pypi_repository
artifactory_virtual_sbt_repository

**Comment by ADSapozhnikov** [comment]
Also. Any plans to implementing?
artifactory_virtual_nuget_repository
artifactory_virtual_npm_repository
artifactory_virtual_debian_repository
artifactory_virtual_gitlfs_repository

**Comment by chb0github** [comment]
Well, there are plans in the classic sense of "we definitely want to do this" - but now that we have actual asks, let's see if we can get it moving forward
