### ISSUE TITLE
artifactory_remote_maven_repository always updating password in plan/apply

### ISSUE THREAD

**Issue by erlarson85** [jfrog/terraform-provider-artifactory#347]
**Describe the bug**

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform

**Expected behavior**

**Additional context**

Terraform v1.1.7
on linux_amd64
- Installing hashicorp/aws v4.3.0...
- Installing hashicorp/helm v2.4.1...
- Installing hashicorp/kubernetes v2.8.0...
- Installing hashicorp/random v3.1.0...
- Installing jfrog/artifactory v2.21.0...
- Installing hashicorp/vault v3.3.1...

```hcl
resource "artifactory_remote_maven_repository" "mulesoft-ee" {
  key                            = "mulesoft-ee"
  repo_layout_ref                = "maven-2-default"
  url                            = data.vault_generic_secret.mulesoft.data["url"]
  handle_releases                = true
  handle_snapshots               = true
  includes_pattern               = "**/*"
  username                       = data.vault_generic_secret.mulesoft.data["username"]
  password                       = data.vault_generic_secret.mulesoft.data["password"]
  socket_timeout_millis          = "5000"
  store_artifacts_locally        = true
  block_mismatching_mime_types   = true
  retrieval_cache_period_seconds = "6000"
  missed_cache_period_seconds    = "1800"
  project_environments           = []
  property_sets                  = []
}
```

Terraform Plan:

Artifactory 107.33.12

Terraform will perform the following actions:
```
  # artifactory_remote_maven_repository.mulesoft-ee will be updated in-place
  ~ resource "artifactory_remote_maven_repository" "mulesoft-ee" {
        id                                    = "mulesoft-ee"
      ~ password                              = (sensitive value)
        # (43 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

After applying it will continue to state it will update in place. This happens whether password is hard coded or a data lookup. 

Terraform state shows:
```
# artifactory_remote_maven_repository.mulesoft-ee:
resource "artifactory_remote_maven_repository" "mulesoft-ee" {
    allow_any_host_auth                   = false
...
    password                              = (sensitive value)

...
   unused_artifacts_cleanup_period_hours = 0
    url                                   = (sensitive)
    username                              = (sensitive)
    xray_index                            = false
```

**Comment by chb0github** [comment]
There is a long, tortured story about passwords. We are working on a solution and [welcome your commentary](https://github.com/jfrog/terraform-provider-artifactory/discussions/333):

**Comment by chb0github** [comment]
@alexhung - This may not be at all related to general password issues

**Comment by alexhung** [comment]
@chb0github After worked on #383 I think this issue may be similar with state or unpacking or `omitempty`. Will take a quick look today.

**Comment by alexhung** [comment]
Depends on #380

**Comment by alexhung** [comment]
Confirmed that this issue is caused by the hashing of the password for TF state, as well the unpacking not ignoring `password` field on `read()`.
