### ISSUE TITLE
Not able to set enable_event_replication using artifactory_replication_config resource

### ISSUE THREAD

**Issue by cw1797** [jfrog/terraform-provider-artifactory#349]
Artifactory Enterprise Plus 7.33.12 rev
Terraform v0.13.7

After executing a terraform apply it seems the option `enable_event_replication` from the `artifactory_replication_config` resource does not apply. 

Here's an example of a replication we had created using the replication resource

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # artifactory_replication_config.npm-build-repo will be created
  + resource "artifactory_replication_config" "npm-build-repo" {
      + cron_exp                 = "0 00 05 * * ?"
      + enable_event_replication = true
      + id                       = (known after apply)
      + repo_key                 = "npm-build-repo"

      + replications {
          + enabled               = true
          + password              = (sensitive value)
          + socket_timeout_millis = (known after apply)
          + sync_deletes          = false
          + sync_properties       = true
          + sync_statistics       = true
          + url                   = (sensitive)
          + username              = (sensitive)
        }
    }
```
What we expect to see is when logging in the UI the 'Enable Event Replication' option should be set to true.

**Comment by maheshjfrog** [comment]
Hi @cw1797  ... I was not able to reproduce this issue. In my setup 'Enable Event Replication' was set ie: enabled when checked from UI.

Note: We have a Deprecation Message for 'artifactory_replication_config' resource. This resource has been deprecated in favor of the more explicitly name 'artifactory_push_replication' resource.

**Comment by danielmkn** [comment]
@cw1797 if you can reproduce this with the new resource, please reopen this or open a new ticket.
