### ISSUE TITLE
Add a bold warning that the TF provider does not work with Artifactory OSS

### ISSUE THREAD

**Issue by gw0** [jfrog/terraform-provider-artifactory#35]
It seems in Artifactory OSS the REST API is unavalable. Consequently, this TF provider is useless and the `README.md` should contain a bold warning that is does not work with Artifactory OSS.

If you attempt to use this TF provider with `jfrog/artifactory-jcr`:
```
Error: PUT http://127.0.0.1:8082/artifactory/api/repositories/dockerhub: 400 [{Status:400 Message:This REST API is available only in Artifactory Pro (see: jfrog.com/artifactory/features). If you are already running Artifactory Pro please make sure your server is activated with a valid license key.
}]
```

**Comment by chb0github** [comment]
Sure, That's doable - you can also feel free to offer a PR for this.
