### ISSUE TITLE
cannot unmarshal string into Go struct field WatchFilter.project_resources.resources.filters.value of type artifactory.WatchFilterValueWrapper

### ISSUE THREAD

**Issue by balusarakesh** [jfrog/terraform-provider-artifactory#369]
**Describe the bug**
 - Unable to run terraform plan after upgrading the artifactory provider version
 - we are trying to upgrade `registry.terraform.io/jfrog/artifactory` version from `2.2.12` to `2.25.0` which is causing the error `Error: json: cannot unmarshal string into Go struct field WatchFilter.project_resources.resources.filters.value of type artifactory.WatchFilterValueWrapper`
 - enabling `TF_LOG=trace` is also not helpful
 - we have multiple types of resources like `artifactory_xray_policy`, `artifactory_xray_watch`, `artifactory_virtual_repository`, `artifactory_remote_repository` and `artifactory_local_repository` and we are not sure for which resource this error is happening
  - I tried running a plan by removing all the resources but the issue seems to happen when pulling the terraform state
  - one way to fix this is to remove all resources from state file and import them again but it's a lot of work and I wanted to check with you what could be done to fix this
 
**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

Artifactory Version:
```
{
  "version" : "7.25.9",
  "revision" : "72509900",
  "addons" : [**** ]
}
```

Terraform version: `0.14.6`

**Expected behavior**
 - terraform plan to succeed

**Comment by chb0github** [comment]
support for xray in this provider is being totally removed with a few days - we now have a dedicated provider. If you can reproduce it with the new provider, please open a ticket there
https://github.com/jfrog/terraform-provider-xray
