### ISSUE TITLE
Support cache config for virtual repositories

### ISSUE THREAD

**Issue by zehuac** [jfrog/terraform-provider-artifactory#372]
**Is your feature request related to a problem? Please describe.**
From the [documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration) I can see that virtual cache config (virtualRetrievalCachePeriodSecs specifically) is allowed by artifactory, yet it seems not to be supported by this terraform module.

**Describe the solution you'd like**
Support argument ***virtualRetrievalCachePeriodSecs*** or something like that which allows users to customize the retrieval cache period for virtual repositories.

**Describe alternatives you've considered**

**Additional context**

**Comment by maheshjfrog** [comment]
Hi @zehuac ... virtualRetrievalCachePeriodSecs setting maps to "retrieval_cache_period_seconds" attribute in terraform module's virtual repo resource. 
Eg: https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/artifactory_virtual_generic_repository.md
Will update the doc accordingly. Thanks.

**Comment by maheshjfrog** [comment]
@zehuac ... Artifactory YAML is not having 1:1 mapping with terraform hcl attribute.
Please use "retrieval_cache_period_seconds" for your use case.

Reference: REST API JSON fields https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON
