### ISSUE TITLE
Remove legacy repositories

### ISSUE THREAD

**Issue by danielmkn** [jfrog/terraform-provider-artifactory#375]
Different repository types have multiple unique fields. To make them more manageable, we split repository resources by `package_type`. 

We will remove the following legacy resources: `artifactory_local_repository`, `artifactory_remote_repository` and `artifactory_virtual_repository`. 

These resources will be replaced by more specific resources, declaring the package type in their name. For example:
`artifactory_local_alpine_repository`, 
`artifactory_remote_docker_repository` ,
`artifactory_virtual_alpine_repository`
and so on.

This will be a breaking change and will be released as a major version update.

**Comment by jcoste-orange** [comment]
I don't see artifactory_remote_vcs_repository. So how could I migrate from artifactory_remote_repository with package_type = "vcs" ?

**Comment by alexhung** [comment]
@jcoste-orange Thanks for bringing that to our attention. We will create a new PR for this.

**Comment by danielmkn** [comment]
VCS added in v6.0.1
