### ISSUE TITLE
Managing which "Create Token" endpoint to use with different versions of Artifactory

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#377]
**Describe the bug**

This is a weird-ish one. We've been working on a migration from v6 → v7 for going-on 10 months now. I'm going to skip the "why" and simply say that we've filed a few dozen tickets with support. As part of the upgrade, we started on v7.24.3, then went to v7.29.7, and now we're on v7.31.10.

During the time we were on v7.24.3, the now-deprecated "Create Token" endpoint was the only one that worked as advertised (because the old endpoint was deprecated before the new endpoint had parity). Support instructed us to use the old endpoint.

Then we went to v7.29.7 and remote repositories stopped caching even when the user had the Deploy/Cache permission. Between the opening of the ticket and the resolution of the ticket, we moved to v7.31.10. At that point, Support explained that "the docs say the old endpoint is deprecated" so stupid me, I guess. Anyway, caching only started working again when I replaced the token created by the old endpoint with a token created by the new endpoint. It seems that the incomplete state of the new endpoint in v7.24.3 was resolved at some point, and the old endpoint was no longer function for practical purposes. (It still vends a token, but the token inexplicably doesn't work for certain cases, while still working for others.)

Question: How does this provider handle the (apparently very fluid) approach to creating Access Tokens using different endpoints across different versions of v7? Or does it? Is the provider tested across multiple versions of Artifactory Server? Or just latest-ish?

**Requirements for and issue**
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)

	This worked on v7.24.3. I just got a response from Support about v7.31.10, and haven't had a chance to test it again yet.

    ```hcl
    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_group
    resource "artifactory_group" "svc_account_group" {
      name = var.account_name
    }
    
    # Create the Artifactory user.
    # Password MUST be defined, then we can disable it.
    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_user
    resource "artifactory_user" "svc_account_user" {
      name                       = var.account_name
      email                      = var.account_email
      groups                     = ["readers", var.account_name]
      password                   = random_password.password.result
      depends_on                 = [artifactory_group.svc_account_group]
      internal_password_disabled = true
    }
    
    # Create a timer for rotating the access token.
    # The `triggers` setting forces a token rotation before expiration.
    # https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating
    resource "time_rotating" "now_plus_days" {
      rotation_days = 2 # Lambda should rotate daily, with some jitter.
      triggers = {
        "key" = timestamp()
      }
    }
    
    # Create a random password for user.
    # https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password
    resource "random_password" "password" {
      length = 64
    }
    
    # Create access_token for the user.
    # Use either "end_date" or "end_date_relative" exclusively
    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_access_token
    resource "artifactory_access_token" "svc_account_user" {
      username    = artifactory_user.svc_account_user.name
      end_date    = time_rotating.now_plus_days.rotation_rfc3339
      refreshable = true
      groups      = ["*"]
    }
    ```

- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`

	Presently v7.31.10.

- [X] Your version of terraform

	1.1.x.

**Expected behavior**

This provider is tested across multiple versions of Artifactory v7, and there are smoke tests that show that things inside of Artifactory still work as expected when generating an access token on an older v7 installation with the older endpoint, and a newer v7 installation with the newer endpoint.

The provider handles each case appropriately, depending on the user's version of Artifactory.

**Comment by chb0github** [comment]
```
Question: How does this provider handle the (apparently very fluid) approach to creating Access Tokens using different endpoints across different versions of v7? Or does it? Is the provider tested across multiple versions of Artifactory Server? Or just latest-ish?
```

We only test against tip-of-the-spear, and for all the reasons you have noticed and then some. Being diplomatic: we get our product updates the same way you do and you have arguably more input on product direction. We have explicitly decided to only test against latest-ish because doing otherwise would require analysing and deciding which versions to maintain and for how long. 

If there is some way we can assist you? We are limited in what we can do, but we do try to help.

**Comment by skyzyx** [comment]
I'd figured this, but it was worth asking.

It's clear that the Artifactory product doesn't follow semantic versioning. Would it be possible, moving forward, to add to the release notes which version(s) of Artifactory you _did_ test the provider against? That way, if we want to leverage an improvement in the Terraform Provider, and we know the ball-park version it was tested against, we can burn a new Base AMI and re-deploy the cluster to match.

Or, if we fall behind, and something isn't working as anticipated, we can at least be able to make educated guesses about required next steps. Right now, we tend to keep up with versions that the Support team seems to have available for testing (so that they can reproduce the bugs we report). As of a few weeks ago, that was v7.31.10-ish.

**Comment by chb0github** [comment]
You know, i think the ask about what version any given release was tested against is fair, and we can probably automate it too. I'll talk with the team on Monday

Side note: can you see about giving this repo a star and maybe ask some friends? We're still not top in Google search
