### ISSUE TITLE
Always changed(update in place) repositories if these repositories are added to the project

### ISSUE THREAD

**Issue by OSapozhnikov** [jfrog/terraform-provider-artifactory#382]
**Describe the bug**
I have pipeline for create repositories and create project with adding repos. First run works fine, but if I prepare new plan without any changes I get message:
```
  # artifactory_local_generic_repository.terraform-local-generic-repo["exmpl-generic-dev-local"] will be updated in-place
  ~ resource "artifactory_local_generic_repository" "terraform-local-generic-repo" {
        id                       = "exmpl-generic-dev-local"
      - project_key              = "exmpl" -> null
        # (13 unchanged attributes hidden)
    }

  # artifactory_local_generic_repository.terraform-local-generic-repo["exmpl-generic-prod-local"] will be updated in-place
  ~ resource "artifactory_local_generic_repository" "terraform-local-generic-repo" {
        id                       = "exmpl-generic-prod-local"
      - project_key              = "exmpl" -> null
        # (13 unchanged attributes hidden)
    }
Plan: 0 to add, 2 to change, 0 to destroy.
```
**Requirements for and issue**
- [x] Example of terraform snippet
```
## Repository
resource "artifactory_local_generic_repository" "terraform-local-generic-repo" {
  for_each = {
    for q in local.all_generic_repos : q => q
    if contains(var.art_repos_types, "generic")
  }
  key             = each.value
  repo_layout_ref = "simple-default"
  description     = "Generic repository for ${var.art_base} artifacts"
  notes           = "SR: ${var.art_service_request_number}"
  xray_index      = var.art_xray_index

  property_sets = [
    "artifactory"
  ]

  project_environments = var.art_create_project == true ? ["DEV"] : null
}
## Project
resource "project" "terraform-project" {
  count        = (var.art_create_project) ? 1 : 0
  key          = var.art_project_key
  display_name = "${upper(var.art_base)} Project"
  description  = "Business unit: ${upper(var.business_unit)}, Responsobility person: ${var.responsibility_person}"
  admin_privileges {
    manage_members   = false
    manage_resources = false
    index_resources  = true
  }
  max_storage_in_gibibytes   = var.art_repos_size
  block_deployments_on_limit = false
  email_notification         = true

  repos = concat(local.all_repos_list, local.all_virtual_repos)
}
```
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`:
  "version" : "7.35.1",
  "revision" : "73501900"
- [x] Your version of terraform: v1.1.7

**Expected behavior**
I want to see update message only if I provide the "project_key" to repository.  The current behavior is confusing when preparing for deployment (adding new repositories or environments). always gives a long list of what will be changed.

**Comment by alexhung** [comment]
Related to #329 and https://github.com/jfrog/terraform-provider-project/issues/27

**Comment by alexhung** [comment]
@OSapozhnikov Sorry for taking this long to get to this ticket.

What you are seeing is a function of how Terraform and Artifactory works unfortunately. So the sequence of events are like this:

1. TF creates repo (without `project_key` value)
2. TF fetches the repo and stores the data in TF state (repo state has empty `project_key` as project has not been created yet and no relationship is established)
3. TF creates project with list of repos
4. TF fetches the project and stores the data in TF state (project state has a list of repos)

Now when you execute `terraform plan`, TF fetches the repo data from Artifactory again to compare with the stored states. The repo is now assigned to the project so `project_key` now has the project key. This is what causes TF to update-in-place.

To resolve this, the recommended way from TF is to execute `terraform apply -refresh-only` which will not apply any changes. This will only update the states with the current configuration from Artifactory. Therefore executing `terraform plan` afterward TF will not attempt to update again.

Let me know if you have other questions. I will close this issue in a few days if I do not see any updates.
