### ISSUE TITLE
Error on import artifactory_push_replication resource into state

### ISSUE THREAD

**Issue by engineerXIII** [jfrog/terraform-provider-artifactory#386]
**Describe the bug**
When you import _artifactory_push_replication_ resource into state, you receive following error:

> artifactory_push_replication.puppet_replication: Importing from ID "puppet"...
> artifactory_push_replication.puppet_replication: Import prepared!
>   Prepared artifactory_push_replication for import
> artifactory_push_replication.puppet_replication: Refreshing state... [id=puppet]
> ╷
> │ Error: json: cannot unmarshal object into Go value of type []artifactory.getReplicationBody
> │ 
> │ 
> ╵

It seems that terraform provider doesn't handle API response from Artifactory properly

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
```
resource "artifactory_push_replication" "puppet_replication" {
  repo_key                 = "puppet"
  cron_exp                 = "0 0 */1 * * ?"
  enable_event_replication = false
  replications {
    url      = "some_ip"
    username = "some_user"
    sync_deletes    = true
    sync_properties = true
    sync_statistics = true
  }
}
```
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`:
  "version" : "7.33.12",
  "revision" : "73312900"
- [x] Your version of terraform: v1.0.5, v1.1.*

**Expected behavior**
Successful resource import

**Additional context**
Local repository with mentioned key exists in artifactory instance.

**Comment by engineerXIII** [comment]
Reproduced issue in  Artifactory 7.35.2-73502900

**Comment by chb0github** [comment]
I am not entirely shocked - artifactory produces entirely different payloads depending on if it's a push or a pull and this has persistently been a sore spot. We'll get it handled.

**Comment by maheshjfrog** [comment]
Hi @engineerXIII  ... I am trying to reproduce this issue in my setup (used the same Artifactory versions mentioned). 
Can you share some more details on your setup? Like ... the list of replication settings in Artifactory.
If possible, curl response of REST API "artifactory/api/replications/<repo-key>" call.
Thanks.

**Comment by alexhung** [comment]
@engineerXIII We have not been able to reproduce this import issue so I'm closing this issue. If you can provider more details on your Artifactory setup and a fully executable HCL to reproduce this issue, please open a new issue.
