### ISSUE TITLE
artifactory_keypair documentation updates

### ISSUE THREAD

**Issue by chb0github** [jfrog/terraform-provider-artifactory#388]
So, looking at [this page](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_keypair), there are a few documentation updates I'd like to request. I know that the team is transitioning how the docs are generated, but I'd like to request the following end-state.

* "alpine" should be changed to match the official branding, which is "Alpine Linux".

* In lists, either use an ending period consistently or not at all.

* In "[Argument Reference](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_keypair#argument-reference)", we don't need to say "duh!". Nobody here is a stupid person.

* "RT" may be the internal name of the software, but your own corporate branding is 
"Artifactory" and should be used instead.

* Nowhere on this page does it explicitly state that there are any sensitive values, but it should. (This is different from needing to secure our own statefile. This is signaling to users that the statefile _needs_ to be secured.)

* Lastly, it would be nice to document _how_ to leverage `terraform import` for this resource.

_Originally posted by @skyzyx in https://github.com/jfrog/terraform-provider-artifactory/issues/289#issuecomment-1086697535_

**Comment by martinm82** [comment]
Another important item would be the need to document all the relevant attributes for repository creation. Since now the legacy `artifactory_local_repository` resource is gone there is no documentation in place stating which attributes one can and should use in the specific repository resources. Not all attributes are relevant for various repositories even though the REST API accepts all of them. In the Artifactory UI only a subset is available when creating a repository.

**Comment by alexhung** [comment]
@martinm82 We understand the need to improve the documentation in general. We will have a separate GitHub issue for that piece of work. In the meantime, this issue is scoped to improving documentation for `artifactory_keypair`.

**Comment by martinm82** [comment]
@alexhung I agree. I just added my comment here as the title was quite generic.

**Comment by danielmkn** [comment]
done

**Comment by skyzyx** [comment]
> Another important item would be the need to document all the relevant attributes for repository creation. Since now the legacy `artifactory_local_repository` resource is gone there is no documentation in place stating which attributes one can and should use in the specific repository resources. Not all attributes are relevant for various repositories even though the REST API accepts all of them. In the Artifactory UI only a subset is available when creating a repository.

In the interim, check out https://github.com/minamijoyo/tfschema.
