### ISSUE TITLE
Inconsistency between `artifactory_local_rpm_respository` and `artifactory_local_debian_respository`

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#389]
**Describe the bug**

Defined a GPG key to match the RSA key we have for Alpine Linux.

```hcl
resource "artifactory_keypair" "gpg" {
  pair_type = "GPG"
  pair_name = "E4FE7A7B"
  alias     = "E4FE7A7B"

  private_key = file("keys/gpg/E4FE7A7B.asc")
  public_key  = file("keys/gpg/E4FE7A7B.pub.asc")
  # passphrase = ""

  lifecycle {
    ignore_changes = [
      private_key,
      passphrase,
    ]
  }
}
```

In the `local` and `virtual` repo resources for `rpm` and `debian` (a matrix), `keypair` appears to have changed to `primary_keypair_ref`. No problem. I'm using the HashiCorp Terraform extension in VSCode to introspect the provider and provide inline error messages in my `.tf` files.

In `artifactory_local_debian_repository`, I am able to set `primary_keypair_ref = artifactory_keypair.gpg.id`. I can also set this in `artifactory_virtual_debian_repository` (e.g., the only two places where you can set it). I can also set it in `artifactory_virtual_rpm_repository`.

However, in `artifactory_local_rpm_repository`, the `keypair` and `primary_keypair_ref` attributes appear to be undefined. This is inconsistent with the comparable `artifactory_local_debian_repository` resource.

**Requirements for and issue**

* https://github.com/jfrog/terraform-provider-artifactory/blob/e440b36bc60333a73f1f4e6cddaba87353c973e5/pkg/artifactory/resource_artifactory_local_debian_repository.go#L10-L27
* https://github.com/jfrog/terraform-provider-artifactory/blob/e440b36bc60333a73f1f4e6cddaba87353c973e5/pkg/artifactory/resource_artifactory_local_rpm_repository.go#L11-L43
* https://github.com/jfrog/terraform-provider-artifactory/blob/e440b36bc60333a73f1f4e6cddaba87353c973e5/pkg/artifactory/resource_artifactory_virtual_rpm_repository.go#L12-L25

Artifactory v7.31.10.

```plain
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/jfrog/artifactory v4.0.0
```

**Expected behavior**

Keypairs would be supported by `local_rpm` just like it is for `local_debian` and `virtual_(rpm|debian)` resources.

**Comment by chb0github** [comment]
I vaguely remember an inconsistency in RT about this - you're saying "just make them consistent by name" in the HCL? That should be doable with deprecation

**Comment by chb0github** [comment]
Oh. I think we can accomodate. Thanks for being such a _productive_ and active community member
