### ISSUE TITLE
Unable to update replication setting using artifactory_push_replication

### ISSUE THREAD

**Issue by manojwajekar** [jfrog/terraform-provider-artifactory#392]
**Describe the bug**
Unable to update replication settings using artifactory_push_replication. 

**Requirements for and issue**
- [ ] We have created push replication for the repository with enabled=false initially. Now when we are trying to enable it, terraform apply is failing

Terraform plan:
```
  # artifactory_push_replication.downloads_replication[0] will be updated in-place
  ~ resource "artifactory_push_replication" "downloads_replication" {
        id                       = "downloads"
        # (3 unchanged attributes hidden)

      ~ replications {
          ~ enabled               = false -> true
            # (6 unchanged attributes hidden)
        }
    }
```
Terraform apply error:
```
Terraform v0.14.5
Initializing plugins and modules...
artifactory_push_replication.downloads_replication[0]: Modifying... [id=downloads]
Error: 
404 POST https://artifactory.redacted.com/api/replications/downloads
404 page not found


  on local_repositories_replications.tf line 381, in resource "artifactory_push_replication" "downloads_replication":
 381: resource "artifactory_push_replication" "downloads_replication" {



```
I checked in UI as well API. Replication config exists for this repository.
Also, I noticed the same issue when I tried to update other fields like enable_event_replication.

```
curl https://artifactory.redacted.com/artifactory/api/replications/downloads
[ {
  "url" : "https://artifactory2.redacted.com/artifactory/downloads",
  "socketTimeoutMillis" : 0,
  "username" : "replication",
  "password" : "",
  "syncStatistics" : true,
  "enabled" : false,
  "cronExp" : "0 0 4 * * ?",
  "syncDeletes" : true,
  "syncProperties" : true,
  "pathPrefix" : "",
  "repoKey" : "downloads",
  "replicationKey" : "downloads_https___ar406a745xxx",
  "enableEventReplication" : false,
  "checkBinaryExistenceInFilestore" : false
} ]
```

- [ ] Your version of artifactory: 7.27.3
- [ ] Your version of terraform : 0.14.5
- [ ] Your version of terraform provider: 2.6.19

**Expected behavior**
We should be able to update the replication config using artifactory_push_replication

**Comment by alexhung** [comment]
@manojwajekar Thanks for the report. We'll investigate.

**Comment by chb0github** [comment]
@manojwajekar - do you have a reproducible HCL? We've spent a lot of time tracking down issues because we can't repo them. Please supply HCL we can readily use

**Comment by alexhung** [comment]
@chb0github I think this error is caused by invalid API path [here](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource_artifactory_push_replication.go#L293).
