### ISSUE TITLE
Xray property missing from local, remote and federated repo types

### ISSUE THREAD

**Issue by jamestoyer** [jfrog/terraform-provider-artifactory#395]
**Describe the bug**
The Xray property type is missing from from all local, remote and federated dedicated repository types.

**Affected versions**
v2.3 and above

**Expected behavior**
The old `local_repository` and `remote_repository` types accepted a property called `xray_index`. This is a valid property that can be should be managed by the repository types and is listed in the spec [1]. By removing this, we have a hard blocker on migrating to the new dedicated repository types in v6 of the provider. For now the highest version we can upgrade to is v5.

This property can be set regardless of Xray being enabled and does not require special Xray permissions. In addition, even if we were using the Xray provider, which we're not, nothing exists in it to manage it. In addition, even the plan is to never support this, the current implementations override it instead of ignoring it.

```
resource "artifactory_remote_alpine_repository" "this" {
    id                                    = "external-alpine-main"
  ~ list_remote_folder_items              = true -> false
  ~ property_sets                         = [
      - "artifactory",
    ]
  ~ xray_index                            = true -> false
    # (26 unchanged attributes hidden)

    # (1 unchanged block hidden)
}
```

**Additional context**
[1] Repository API spec: https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON

**Comment by alexhung** [comment]
@jamestoyer As far as I can see from the code, `xray_index` attribute is supported in v6. This may be a combination of this attribute missing from documentation and a code bug that not getting the value correctly from HCL.

We will take a look.

**Comment by maheshjfrog** [comment]
@jamestoyer  ... I was able to use "xray_index" attribute for my test remote repo without issues. 
Following is my hcl block.
```
resource "artifactory_remote_alpine_repository" "test-alpine-remote-repo" {
  key              = "test-alpine-remote-repo"
  url               = "http://dl-cdn.alpinelinux.org/alpine"
  xray_index = true
}
```
I could see the plan having the value for this attribute and REST calls passing the json payload accordingly.
Used Provider version: 6.1.3 (latest) and Artifactory version 7.35.2.
Would like to know the sequence of operations in your setup that causes the issue. Thanks.

**Comment by jamestoyer** [comment]
@maheshjfrog it looks like my issue was a documentation issue. On other providers, e.g. AWS, TFE, all the acceptable arguments are listed in the "Argument Reference" section of the documentation. When looking at the `alpine` repository, I saw that there were only four arguments and assumed that these were the only four accepted. On re-reading the docs, I noticed this:
> Arguments for remote Alpine repository type closely match with arguments for remote Generic repository type.
Whilst this is a fair comment, it doesn't follow the expectations built by other providers in listing out the full arguments. If the docs aren't going to do this, may I suggest this is made more prominent, for example in an info box, and a link to the generic repo equivalents is added? This would save the confusion going forward.

**Comment by maheshjfrog** [comment]
Thanks @jamestoyer ... Sure. We have similar requests like #398).
We are working on the documentation update story.

**Comment by chb0github** [comment]
@jamestoyer - we do our best to support the community. We would love a ⭐  on the repo from you and your friends

**Comment by chb0github** [comment]
I am closing this issue as a new one re: documentation has been openned
