### ISSUE TITLE
Can't set attributes to null/default value once set for repository resources

### ISSUE THREAD

**Issue by takaze-kuzu** [jfrog/terraform-provider-artifactory#399]
**Describe the bug**
For some repository resources, once I set a value to some of the attributes, I cannot update those attributes to the null/empty/default value.

**Terraform Snippet**

Using `artifactory_local_npm_repository` as an example, but seems pretty consistent with other repo resources (local/remote/virtual). _While in this example I'm using description & excludes_pattern, it seems to be pretty consistent for all optional attributes regardless of type on repository resources._

```hcl
provider "artifactory" {
  url          = "${var.artifactory_url}/artifactory"
  access_token = var.artifactory_access_token
}

terraform {
  required_version = ">= 1.0"
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "~> 6.0"
    }
  }
}

resource "artifactory_local_npm_repository" "main" {
  key              = "terraform-test"
  description      = "some description"
  excludes_pattern = "abcd/*"
}
```
The above snippet works as expected. 

```sh
artifactory_local_npm_repository.main: Creation complete after 1s [id=terraform-test]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

But the issue comes if I want to change some of the attributes on the resource. While I can update the values to another value, I cannot clear the values by omitting them, setting to an empty string, or null. Making the below changes ...

```diff
resource "artifactory_local_npm_repository" "main" {
  key              = "terraform-test"
-  description      = "some description"
+  description      = null
-  excludes_pattern = "abcd/*"
}
```

results in the following plan: 

```sh
  # artifactory_local_npm_repository.main will be updated in-place
  ~ resource "artifactory_local_npm_repository" "main" {
      - description              = "some description" -> null
        id                       = "terraform-test"
        # (12 unchanged attributes hidden)
    }
```

1. It's not picking up the changes to excludes_pattern. This is consistent regardless if I omit the value, or set the value to `null` or `""`. It does work as expected if I set it to a non-null value, however. (e.g. `excludes_pattern = "abce/*"` accurately detects the changes). _This is the same for both `includes_pattern` and `excludes_pattern`_

2. Despite it accurately picking up the changes to description, it does not update the attribute, resulting in future plans attempting to make the same update. Again, like excludes_pattern, if the value is changed to a non-null value, the update works as expected. (e.g. `description = "new description 1234"` accurately updates the the description). This could be similar to Issue 329.

After that second apply, here's the end result of the repository: from getting the attributes on `terraform-test` back from the API (also shows the same via the UI)

```json
{
    "key": "terraform-test",
    "packageType": "npm",
    "description": "some description",
    "notes": "",
    "includesPattern": "**/*",
    "excludesPattern": "abcd/*",
cont...
}
```

**Terraform/provider version**

```
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/jfrog/artifactory v6.0.1
```

(Also used terraform 1.0.11).

**Artifactory version**  
7.33.9

**Expected behavior**

1. Accurately detect changes to *_pattern attributes when setting to null
2. Accurately apply changes for other attributes when set to null values.

**Comment by alexhung** [comment]
@takaze-kuzu Thank you for the report. We'll investigate.

From my experience with other attributes (noticeably `proxy` and `public_key_ref`/`private_key_ref`), Artifactory API will not affect any changes if the value is `null` or `""` (empty string). The workaround we implemented is to give Artifactory API a non-existent value (e.g. random string) and this will reset the value to default.

I don't know if this is a strategy we can apply in general though.

**Comment by takaze-kuzu** [comment]
Thanks @alexhung  - I guess that makes sense as I found some inconsistencies with which attributes it seems to affect. I used `description` just because it was an easy thing to test with, but ultimately I'm not too concerned there. The bigger issue will before attributes that affect behavior (e.g. patterns). I only tried it with a handful of attributes.

Probably another one that has the same affliction is `username` for the `artifactory_remote_*_repository` resources. Which would be awkward if you wanted to go from authenticating to a remote source to accessing it anonymously by clearing out the username/password fields. 

If there's other details I can provide, would be happy to so do.

**Comment by alexhung** [comment]
@takaze-kuzu Like other system-wide issue, if you have any particular attributes that are blocking your work, please open separate issue for them. This way we can take care of them individually without having to wait for *everything* to get fix together.

**Comment by takaze-kuzu** [comment]
Nothing at the moment, so at the moment I'm OK to wait for a more complete fix. But if anything does come up - will certainly do that and update here. Thanks.

**Comment by alexhung** [comment]
@takaze-kuzu My sense is that there won't be one single fix for this issue. Depending on the attributes and what they represent in Artifactory, some simply needs to be 'reset' with random string, whilst others would require destroying existing resource and recreate a new one.

**Comment by alexhung** [comment]
Closing this issue as this pertain to general, system wide behavior. Please create new issue for specific bug.
