### ISSUE TITLE
Error: no schema available for artifactory_virtual_repository.default_helm while reading state

### ISSUE THREAD

**Issue by jcogilvie** [jfrog/terraform-provider-artifactory#405]
**Describe the bug**
When trying to upgrade to the new repository types from the old ones, while upgrading to provider v6, I get this error:

> Error: no schema available for artifactory_virtual_repository.default_helm while reading state; this is a bug in Terraform and should be reported

**Expected behavior**
I can upgrade with no error.

**Additional context**
This seems to be because I have a 2.x state stored and am upgrading to 6.x.  

I believe either the schema needs to be updated, or a documentation note needs to be added that a user *must* upgrade to 5.x and fix all deprecations before upgrading to 6.x.

**Comment by alexhung** [comment]
@jcogilvie @benoit-parmentier-2 The user created this script in https://github.com/jfrog/terraform-provider-artifactory/issues/290#issuecomment-1100757651 may be of interest to you guys.

**Comment by chb0github** [comment]
@alexhung - we need to close this issue, and/or create a new one where we develop a migration script. I am going to close this issue and creating a migration script can be at a later date
