### ISSUE TITLE
Synchronize Access keys for Artifactory & XRAY Terraform Providers

### ISSUE THREAD

**Issue by alexeiser** [jfrog/terraform-provider-artifactory#414]
The Artifactory terraform provider uses the ENV Flag: `JFROG_ACCESS_TOKEN`, but the XRAY provider https://registry.terraform.io/providers/jfrog/xray/latest/docs uses `XRAY_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN`. When you have a TF file that includes both XRAY and Artifactory items - then you need to provide 2 different ENV flags, even though they both are likely going to be the same access token.

**Describe the solution you'd like**
Support the `JFROG_ACCESS_TOKEN` Environment flag as well as the more specific Artifactory one.

**Comment by alexhung** [comment]
@alexeiser You mean adding `JFROG_ACCESS_TOKEN ` to this provider in addition to existing `ARTIFACTORY_ACCESS_TOKEN` right?

**Comment by alexeiser** [comment]
> @alexeiser You mean adding `JFROG_ACCESS_TOKEN ` to this provider in addition to existing `ARTIFACTORY_ACCESS_TOKEN` right?

Yup, thats exactly what I mean... or add `ARTIFACTORY_ACCESS_TOKEN`to the xray provider - but I think it makes more sense for you to add `JFROG_ACCESS_TOKEN`

**Comment by alexeiser** [comment]
@alexhung I know you assigned it to @maheshjfrog , but I can send you a PR if it would help?

Looks like it's jus switching out https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/provider.go#L119  to 
```lang:go
schema.MultiEnvDefaultFunc([]string{"ARTIFACTORY_ACCESS_TOKEN", "JFROG_ACCESS_TOKEN"}, "")
```

**Comment by alexeiser** [comment]
Although, probably also should update the docs, and add a test case - so... not just one line.

**Comment by alexhung** [comment]
@alexeiser that's correct. The PR will need to include the code change along with new acceptance tests. You can refer to https://github.com/jfrog/terraform-provider-project for example of additional tests.

**Comment by chb0github** [comment]
The intention was to allow 1 key for all or different key for all. Somehow this got missed

**Comment by alexeiser** [comment]
@chb0github so which what did you decided to go?

**Comment by alexhung** [comment]
@alexeiser `JFROG_ACCESS_TOKEN` is the env var we will be using across all providers.

**Comment by danielmkn** [comment]
LGTM, but we need to add info to CHANGELOG.md
