### ISSUE TITLE
Improve documentation around required params

### ISSUE THREAD

**Issue by chb0github** [jfrog/terraform-provider-artifactory#422]
@maheshjfrog it looks like my issue was a documentation issue. On other providers, e.g. AWS, TFE, all the acceptable arguments are listed in the "Argument Reference" section of the documentation. When looking at the `alpine` repository, I saw that there were only four arguments and assumed that these were the only four accepted. On re-reading the docs, I noticed this:
> Arguments for remote Alpine repository type closely match with arguments for remote Generic repository type.

Whilst this is a fair comment, it doesn't follow the expectations built by other providers in listing out the full arguments. If the docs aren't going to do this, may I suggest this is made more prominent, for example in an info box, and a link to the generic repo equivalents is added? This would save the confusion going forward.

_Originally posted by @jamestoyer in https://github.com/jfrog/terraform-provider-artifactory/issues/395#issuecomment-1098969397_

**Comment by danielmkn** [comment]
I'm working on the documentation now. Each repository type (local, remote, virtual, and federated) will have one document, that contains all the arguments they have in common. Each repo-specific document will have a link to the common list of arguments.
