### ISSUE TITLE
[Question] adding 1 repository + permission fails

### ISSUE THREAD

**Issue by kaychamo** [jfrog/terraform-provider-artifactory#428]
Hello, when adding one repository and its permission it fails for us.

What's happening (imo) :
0- plan : create 1 repo + its permission
1- creates permission => fails because repository not created yet
│     "message" : "Permission target contains a reference to a non-existing repository 'docker-proxy-asis-gitlab'."
2- creates new repository
3- ci fails
rerun ci :
0- plan: create permission
1- apply: creates permission => all good

Is there a way I can sort the "runtime" of my differents tf files or any other fix for this?
Thanks!! Fabien

**Comment by alexeiser** [comment]
Did you use a TF resource reference in your permission config? 

https://learn.hashicorp.com/tutorials/terraform/dependencies

**Comment by danielmkn** [comment]
@alexeiser is right, you can use the `depends_on` functionality to preserve the correct order of creating resources.

**Comment by kaychamo** [comment]
thanks for the help (we are trying to solve our issue today)! 
would be great if the provider could do the dependancy check implicitly (between repository existance and permission)
if it already doe,s it's parallelism that didn't work for us (creation takes some ms too long for the permission to be ready to be set)
