### ISSUE TITLE
checkBinaryExistenceInFilestore support for replication

### ISSUE THREAD

**Issue by jjohnson-okta** [jfrog/terraform-provider-artifactory#434]
**Is your feature request related to a problem? Please describe.**
I wish to set the [checkBinaryExistenceInFilestore](https://www.jfrog.com/confluence/display/JFROG/Repository+Replication#RepositoryReplication-OptimizingRepositoryReplicationUsingStorageLevelSynchronizationOptions) to `true` in replication config.

**Describe the solution you'd like**
Augment the existing replication-type resources to have an argument to adjust this flag.

**Describe alternatives you've considered**
Running a bash script to set this flag via the REST API after each apply.

**Additional context**
We are experimenting synchronizing the binarystore via S3 bucket replication, where we would then set this flag to `false`

**Comment by chb0github** [comment]
@alexhung and @danielmkn Will this be addressed?

**Comment by danielmkn** [comment]
yes, in the current sprint.

**Comment by danielmkn** [comment]
@jjohnson-okta, thanks for the ticket! It was released in 6.7.2
