### ISSUE TITLE
Webhooks do not support multiple handlers

### ISSUE THREAD

**Issue by martinm82** [jfrog/terraform-provider-artifactory#439]
**Describe the bug**
The Artifactory Webhook REST API supports within one webhook definition multiple handlers with url/secret/proxy.

**Example**:

```
"handlers": [
    {
      "handler_type": "webhook",
      "url": "https://webhook.my-company.test/",
      "secret": "tell no one",
      "proxy": "mainProxy",
      "custom_http_headers": [
        {
          "name": "X-MyCompany-Header",
          "value": "whatever"
        }
      ]
    }
  ]
```

On the other side, the Terraform Provider supports per webhook only one handler/URL.

**Example**:

```
resource "artifactory_artifact_webhook" "artifact-webhook" {
  key         = "artifact-webhook"

  [...]

  url         = "http://tempurl.org/webhook"
  secret      = "some-secret"
  proxy       = "proxy-key"
}
```

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: 7.37
- [x] Your version of terraform: 1.1
- [x] Your version of terraform provider: 6.6.0

**Expected behavior**
Possibility to define multiple urls/secrets (aka handlers) within one webhook resource like this:

```
resource "artifactory_artifact_webhook" "artifact-webhook" {
  key         = "artifact-webhook"
  handlers = [
     - url: https://
        secret: abc
        custom_http_headers:
          token: value
     - url: https://
        secret: abcd
        custom_http_headers:
          token2: value2
  ]
```

**Additional context**

**Comment by alexhung** [comment]
@martinm82 The reason the initial implementation only support one handler is to match the capability the Artifactory UI provides. It only allows setting up one handler per webhook.

For the same reason, if you configure a webhook with multiple handlers via the API, you won't be able to see or manage handlers except the first one in the list in the UI.

**Comment by martinm82** [comment]
@alexhung you are right, from UI perspective it is indeed just one handler. I was not aware of it because we configured webhooks in the past on our on-premise environment via REST API (custom Yaml format). 

Since we are migrating from our custom REST API based solution to Terraform, the only way around this is to duplicate each webhook that has multiple handlers. 

I believe the provider should be in line with the official REST API since it's kind of a replacement for it. Do you think this is something we can change, maybe introduce a new handler block and still have the single url/custom_http_header/proxy values for backwards compatibility?

**Comment by martinmigasiewicz-tomtom** [comment]
Fair point, but I am wondering who would create webhooks with TF and later modify it via the UI. We follow strictly the IaC approach.  But you never know how others do it ;)

**Comment by alexhung** [comment]
@martinm82 Because it is possible, someone _will_ do it one day and then come here for help 😄

**Comment by martinm82** [comment]
But that is already nowadays possible if you manage Artifactory directly via REST API.

**Comment by alexhung** [comment]
> @martinm82
> 
> > Do you think this is something we can change, maybe introduce a new handler block and still have the single url/custom_http_header/proxy values for backwards compatibility?
> 
> Totally!
> 
@martinm82 

I misspoke in my previous message. I was thinking of the `criteria` block which can be made to support multiples easily. For handler, I will definitely migrate to using `handler` block for each. I will provide a state migration code as well to transit from current structure to new one.
