### ISSUE TITLE
Terraform plan is never empty when using credentials in remote docker repository resource

### ISSUE THREAD

**Issue by aliculPix4D** [jfrog/terraform-provider-artifactory#447]
**Describe the bug**
When using Artifactory Remote Docker Repository resource with credentials terraform plan is never empty, even though the password did not change.

Example:
```
data "aws_ssm_parameter" "token" {
  name = "my_public_docker_registry_token"
}

resource "artifactory_remote_docker_repository" "my-remote-docker" {
  key                            = "my-remote-docker"
  external_dependencies_enabled  = true
  enable_token_authentication    = true
  url                            = "https://hub.docker.io/"
  username                       = "my-user"
  password                       = data.aws_ssm_parameter.token.value
}

```

Resulting in: 
```
  # artifactory_remote_docker_repository.repos["my-remote-docker"] will be updated in-place
  ~ resource "artifactory_remote_docker_repository" "my-remote-docker" {
        id                                    = "dockerhub"
      ~ password                              = (sensitive value)
        # (37 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
By looking in the Artifactory UI, the password shown there is different then the one set by terraform (artifactory provider). This is probably because the password gets encrypted by master key from Artifactory side (only guessing), but this could explain why the artifactory provider want to change it each time.

Ugly workaround is to add ignore_changes to the resource:
```
  lifecycle {
    ignore_changes = [
      password
    ]
  }
```
artifactory version: 7.33.9
terraform version:
```
Terraform v1.1.7
on linux_amd64
```
artifactory terraform provider version: 2.6.24

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**

An empty terraform plan without any need to add ignore_changes.

**Additional context**

**Comment by alexhung** [comment]
@aliculPix4D This issue was fixed in #385 and was released in [v4.0.1](https://github.com/jfrog/terraform-provider-artifactory/releases/tag/v4.0.1).

**Comment by chb0github** [comment]
@aliculPix4D You're using an ancient version of the provider that is no longer supported. If she need information on migration we can help, but please open another ticket

**Comment by aliculPix4D** [comment]
@alexhung @chb0github Thank you both for your answers. We will upgrade the provider as suggested ASAP.
