### ISSUE TITLE
Support for Terraform repositories

### ISSUE THREAD

**Issue by danielmkn** [jfrog/terraform-provider-artifactory#450]
We need to add support for Terraform and Terraform BE repositories. 
https://www.jfrog.com/confluence/display/JFROG/Terraform+Repositories

**Comment by ChocPanda** [comment]
Hey, @danielmkn do you have an ETA on this at all?

**Comment by danielmkn** [comment]
Hi! @ChocPanda, we will work on that in the current sprint. Thanks!

**Comment by ChocPanda** [comment]
Amazing, thanks @danielmkn this will be a huge help
