### ISSUE TITLE
Handle multiple Access Token API endpoints

### ISSUE THREAD

**Issue by yannc21** [jfrog/terraform-provider-artifactory#451]
**Is your feature request related to a problem? Please describe.**
Since [Artifactory v7.21.1](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AccessTokens), the API for managing Access Tokens  has changed
The [latest version of the provider](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource/security/resource_artifactory_access_token.go#L216) is still relying on the "old" endpoints 

**Describe the solution you'd like**
The provider should handle both endpoints based on the Artifactory version

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by alexhung** [comment]
@yannc21 We have plan to replace the old access token resource with the new API. No ETA as of now.

**Comment by yannc21** [comment]
@chb0github the "new API" is the recommended one since v7.21 and so the currently used one is obsolete. The "new API" provides more advanced usage of Access Tokens and fixes some issues.  The previous release (v7.19)  which only supports the "old API" will be EOL in November 2022. If we don't support the new API then we are penalizing users relying with the latest Artifactory version.
