### ISSUE TITLE
Artifactory LDAP settings apply fails

### ISSUE THREAD

**Issue by matejc** [jfrog/terraform-provider-artifactory#452]
**Describe the bug**
We have an issue with configuration provisioning for Artifactory LDAP settings.
- We have an Online version of JFrog
- The issue is when GETting /artifactory/api/system/configuration API call
- The LDAP settings are getting applied but the read fails at the end which makes the whole process fail
- Although we have this issue in Pulumi, we believe that is an issue with this Terraform provider

Error from Pulumi:
```

Updating (prod):
     Type                              Name                    Status                  Info
     pulumi:pulumi:Stack               service-provision-prod  **failed**              1 error; 8 messages
 +   └─ artifactory:index:LdapSetting  company-ldap            **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (service-provision-prod):
    error: update failed

    2022/05/09 10:48:09.687034 ERROR RESTY
    400 GET https://company.jfrog.io/artifactory/api/system/configuration
    {
      "errors" : [ {
        "status" : 400,
        "message" : "Artifactory Online does not support accessing this API endpoint, please contact support@jfrog.com for further assistance if required."
      } ]
    }, Attempt 1

  artifactory:index:LdapSetting (company-ldap):
    error: 1 error occurred:
        * creating urn:pulumi:prod::service-provision::artifactory:index/ldapSetting:LdapSetting::company-ldap: 1 error occurred:
        * failed to retrieve data from API: /artifactory/api/system/configuration during Read

Resources:
    1 unchanged
```

**Requirements for and issue**
- [*] A description of the bug
- [/] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.** - we do not use Terraform directly but Pulumi
- [*] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [/] Your version of terraform
- [*] Your version of terraform provider

**Expected behavior**
The apply should work without an error.

**Additional context**
Artifactory version: 7.37.14
Terraform provider: 6.4.0

The error that we are receiving is on this line: https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource/configuration/resource_artifactory_ldap_setting.go#L156

**Comment by matejc** [comment]
@chb0github 
1. This is not Pulumi's issue since this provider is being used in backend anyway, and the error is coming from this provider, so its not like that Pulumi is using this provider wrong
2. The actual issue is that this Terraform provider is using endpoint that is maybe too broad for reading LDAP configuration (but it does work with just applying the LDAP settings, because after Pulumi failure the LDAP configuration is visible in Artifactory)
3. This did happen, so you say that modification should not be modified, since the modification was done but just failed to re-read the settings with this provider?
```
SaaS instances are not dedicated to a single client and thus the ability to modify security settings that would effect everyone is not allowed
```

**Comment by matejc** [comment]
One confusion is coming from the assumption that the Online means a SaaS product, but we have Marketplace solution (https://jfrog.com/pricing/#marketplace)

**Comment by chb0github** [comment]
I'm not going to pretend I understand artifactory, but this is not a problem with the provider; It is entirely on artifactory and what they choose to allow and not and why. You'd have to file a ticket with them to get a better answer

**Comment by alexhung** [comment]
@matejc Your instance is running on jfrog.io domain, which means it is a JFrog SaaS instance. This also means not all API endpoints are supported.

**Comment by chb0github** [comment]
Not to worry. If it makes you feel any better, we frequently learn things from the community that are totally undocumented. We don't have access to any extra info than you.

In this case, we stumbled on it months ago
