### ISSUE TITLE
License check failing for 'Commercial' type in 6.6.1

### ISSUE THREAD

**Issue by ribbybibby** [jfrog/terraform-provider-artifactory#455]
**Describe the bug**
Since version 6.6.1 of the provider we've been getting the following error when `check_license = true`:
```
$ terraform plan
╷
│ Error: Artifactory Projects requires Enterprise license to work with Terraform!
│
│   with provider["registry.terraform.io/jfrog/artifactory"],
│   on main.tf line 10, in provider "artifactory":
│   10: provider "artifactory" {
│
```

Our license is `Commercial`:
```
$ curl -H "Authorization: Bearer $ARTIFACTORY_ACCESS_TOKEN" https://<host>/artifactory/api/system/license
{
  "type" : "Commercial",
  "validThrough" : "EXPIRY",
  "licensedTo" : "ORG"
}
```

Looks like this is down to switching to the check licenses function in `terraform-provider-shared`:
- https://github.com/jfrog/terraform-provider-artifactory/blob/bd2f0390f83ed4d926635b8f852cf60644ef457e/pkg/artifactory/provider/provider.go#L239
- https://github.com/jfrog/terraform-provider-shared/blob/v0.5.0/util/util.go#L344

Obviously we can set `check_license = false` but I'd like to confirm that this is expected behaviour (i.e the license check should be excluding `Commercial` now). I wouldn't expect a breaking change like this in a patch release.

**Expected behavior**
I wouldn't necessarily expect an error when this worked previously. Especially when bumping a patch version from 6.6.0 to 6.6.1.

**Additional context**

Some information:
- Artifactory version: 7.35.2
- Terraform provider version: 6.6.1
- Terraform version: 1.1.9

**Comment by alexhung** [comment]
@ribbybibby Thanks for catching this. Will get this fix ASAP.
