### ISSUE TITLE
scoped token for non-existing users

### ISSUE THREAD

**Issue by oallauddin** [jfrog/terraform-provider-artifactory#472]
Recently updated the provider and noticed the deprecation warning below.
Currently using artifactory_access_token to create tokens for non-existing users.
artifactory_scoped_token seems to require an existing user.
Is the direction to no longer support tokens for non-existing users?

```
Warning: Deprecated Resource

with module.token.artifactory_access_token.readonly_token,
on ../modules/token/readonly.tf line 12, in resource "artifactory_access_token" "readonly_token":
12: resource "artifactory_access_token" "readonly_token" {

This resource is being deprecated and replaced by artifactory_scoped_token
```

**Comment by gevraud** [comment]
Hello,

I am also interested by the issue. I encountered the same log.

Also the expires_in field isn't very clear to my eyes. How to set expiration to illimited ?

Regards

**Comment by alexhung** [comment]
@gevraud As far as I can tell with the new access token API, there is no way to set unlimited expiration.

**Comment by alexhung** [comment]
@oallauddin @gevraud The answer I get from JFrog Access team is that the new access token API (e.g. `artifactory_scoped_token` resource) doesn't support creation of non-existing user like the old API.

Even though the old API will be deprecated at some point in the future (no date is set yet), you can still use it for this use case. Meaning, continue to use `artifactory_access_token` resource for non-existing user token.

**Comment by alexhung** [comment]
@oallauddin @gevraud Another suggestion from the Access team is to use group scope (`applied-permissions/groups:groupName'`, along with setting `username` to the non-existing user. The non-existing user gets permissions by the Artifactory groups so the username is not checked.

**Comment by gevraud** [comment]
> @gevraud As far as I can tell with the new access token API, there is no way to set unlimited expiration.

This is surprising because the UI allows people to set it to "never"

Regards

**Comment by alexhung** [comment]
@oallauddin First, the API you referenced is the one being deprecated. The new [Access Token API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AccessTokens) has the same issue.

If you have `default-expiry` set to 0 in your access configure, and the API still applies a non-zero default `expires_in` then this sounds like a bug.

I highly encourage you to open a ticket with JFrog support team to get this fix.
