### ISSUE TITLE
enable_token_authentication was turned off after upgrading to 2.25.0

### ISSUE THREAD

**Issue by zymzxq** [jfrog/terraform-provider-artifactory#474]
**Describe the bug**
We have a remote docker repository that proxies dockerhub. We need to turn on `enable_token_authentication` to make sure Artifactory makes authenticated requests to dockerhub. We use resource type `artifactory_remote_repository` to manage the repo. 

```
# a tf module that defines generic remote repo
terraform {
  required_version = ">= 0.13"
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "2.25.0"
    }
  }
}

resource "artifactory_remote_repository" "remote" {
  package_type = var.package_type
  key          = var.key
  url          = var.url

  /*
   * General
   */

  repo_layout_ref  = var.repo_layout_ref
  description      = var.description
  notes            = var.notes
  includes_pattern = var.includes_pattern
  excludes_pattern = var.excludes_pattern
  offline          = var.offline

  /*
   * Remote Authentication
   */

  username               = var.username
  password               = var.password
  client_tls_certificate = var.client_tls_certificate

  /*
   * Network
   */

  proxy                 = var.proxy
  local_address         = var.local_address
  socket_timeout_millis = var.socket_timeout_millis
  # TODO: Missing: Query Params
  allow_any_host_auth      = var.allow_any_host_auth
  enable_cookie_management = var.enable_cookie_management

  /*
   * Property sets
   */

  property_sets = var.property_sets

  /*
   * Cache
   */

  unused_artifacts_cleanup_period_hours = var.unused_artifacts_cleanup_period_hours
  retrieval_cache_period_seconds        = var.retrieval_cache_period_seconds
  # TODO: Missing: Assumed Offline Period
  missed_cache_period_seconds = var.missed_cache_period_seconds

  /*
   * Others
   */

  blacked_out = var.blacked_out
  # TODO: Missing: Allow content browsing
  store_artifacts_locally = var.store_artifacts_locally
  synchronize_properties  = var.synchronize_properties
  # TODO: Missing: Propagate query params
  bypass_head_requests         = var.bypass_head_requests
  block_mismatching_mime_types = var.block_mismatching_mime_types

  # TODO: Missing: Override default blocked Mime types JIRA-213


  /*
   * VCS based settings
   * Affects Bower, CocoaPods, Go, PHP Composer, VCS.
   */

  vcs_type             = var.vcs_type
  vcs_git_provider     = var.vcs_git_provider
  vcs_git_download_url = var.vcs_git_download_url

  /*
   * Bower settings
   */

  bower_registry_url = var.bower_registry_url

  /*
   * Docker settings
   */

  enable_token_authentication = var.enable_token_authentication

  /*
   * Gradle/Ivy/Maven/SBT settings
   */

  remote_repo_checksum_policy_type = var.checksum_policy_type
  max_unique_snapshots             = var.max_unique_snapshots
  fetch_jars_eagerly               = var.fetch_jars_eagerly
  suppress_pom_consistency_checks  = var.suppress_pom_consistency_checks
  fetch_sources_eagerly            = var.fetch_sources_eagerly
  handle_releases                  = var.handle_releases
  handle_snapshots                 = var.handle_snapshots

  /*
   * Nuget settings
   */

  v3_feed_url           = var.v3_feed_url
  download_context_path = var.download_context_path
  feed_context_path     = var.feed_context_path

  # TODO: Support Nuget Force Authentication


  /*
   * PyPi settings
   */

  pypi_registry_url = var.pypi_registry_url

  content_synchronisation {
    enabled = false
  }
}

# a tf module for docker remote repo
module "remote" {
  source = "../common"

  key         = var.key
  url         = var.url
  blacked_out = var.blacked_out
  username    = var.username
  password    = var.password

  package_type                   = "docker"
  enable_token_authentication    = true
  retrieval_cache_period_seconds = var.retrieval_cache_period_seconds
  missed_cache_period_seconds    = var.missed_cache_period_seconds

  excludes_pattern = var.excludes_pattern
  includes_pattern = var.includes_pattern
}

# docker hub remote repo
module "dockerhub" {
  source = "./modules/remote/docker"

  key = "dockerhub"
  url = "https://registry-1.docker.io/"

  retrieval_cache_period_seconds = 3600

  username         = var.dockerhub_username
  password         = var.dockerhub_password
}

```

When running tf plan, terraform prints out
```
 ~ resource "artifactory_remote_repository" "remote" {
        id                                    = "dockerhub"
      ~ password                              = (sensitive value)
        # (34 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

Although terrafrom does not menton it will change `enable_token_authentication`, the attribute is turned off after running tf apply and the flag is also changed to false in tfstate.

Artifactory: 7.35.1
Terraform: 1.2.2
TF proider: 2.25.0

**Expected behavior**
`enable_token_authentication` attribute should not be modified if it is not changed in tf code.

**Additional information**
This seems to be a bug introduced in newer version of the provider. It did not exist when we use 2.2.15

**Comment by alexhung** [comment]
@zymzxq The code for handling Docker remote repository between [2.25.0](https://github.com/jfrog/terraform-provider-artifactory/blob/v2.25.0/pkg/artifactory/resource_artifactory_remote_docker_repository.go) and [latest](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource/repository/remote/resource_artifactory_remote_docker_repository.go) is largely unchanged.

The `enable_token_authentication` attribute is marked `Computed: true`, meaning it will override the TF state with the value retrieved from Artifactory. This may be the reason it gets reset to `false` in your case.

Can you verify that this option is unset in Artifactory UI?

**Comment by zymzxq** [comment]
@alexhung , It is not just tfstate was set to `false`, the flag in Artifactory was also turned off by tf apply, which broke our remote proxy :(

**Comment by alexhung** [comment]
@zymzxq I suspect something else is going on other than a code bug. If the flag in your HCL hasn't changed there's zero reason/way the provider will flip that for you. My hunch is that the Artifactory instance was changed and it just so happens you notice it after you apply the HCL, and the provider picks up the new value from Artifactory.

I shall have time to take a quick look in a day or 2.

**Comment by alexhung** [comment]
@zymzxq I have not been able to reproduce your issue. I am using the following HCL:

```hcl
# Required for Terraform 0.13 and up (https://www.terraform.io/upgrade-guides/0-13.html)
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "6.9.3"
    }
  }
}

provider "artifactory" {
  //  supply ARTIFACTORY_ACCESS_TOKEN / JFROG_ACCESS_TOKEN / ARTIFACTORY_API_KEY and ARTIFACTORY_URL / JFROG_URL as env vars
}

resource "artifactory_remote_docker_repository" "my-remote-docker" {
  key                            = "my-remote-docker"
  external_dependencies_enabled  = true
  external_dependencies_patterns = ["**/hub.docker.io/**"]
  enable_token_authentication    = true
  url                            = "https://hub.docker.io/"
  block_pushing_schema1          = true
}
```

Execute `terraform apply` and the remote repo was created on Artifactory with the 'Enable Token Authentication' option set.

Then I set `external_dependencies_enabled` to `false` and ran `terraform apply`.

```
alexh@alexh-mac terraform-provider-artifactory % terraform apply
artifactory_remote_docker_repository.my-remote-docker: Refreshing state... [id=my-remote-docker]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # artifactory_remote_docker_repository.my-remote-docker will be updated in-place
  ~ resource "artifactory_remote_docker_repository" "my-remote-docker" {
      ~ external_dependencies_enabled         = true -> false
        id                                    = "my-remote-docker"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

artifactory_remote_docker_repository.my-remote-docker: Modifying... [id=my-remote-docker]
artifactory_remote_docker_repository.my-remote-docker: Modifications complete after 0s [id=my-remote-docker]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

The 'Enable Token Authentication' option remains set.

**Comment by zymzxq** [comment]
Thanks @alexhung . Please note I am using `artifactory_remote_repository` instead of `artifactory_remote_docker_repository`. I suspect it is caused by the refactor that makes [MessyRemoteRepo](https://github.com/jfrog/terraform-provider-artifactory/blob/v2.25.0/pkg/artifactory/resource_artifactory_remote_repository.go#L49) a composition struct instead containing each attribute locally. Also migrating to the new `artifactory_remote_docker_repository` is annoying because we have to do that by manipulating our tfstate in order to avoid outage of our services.

**Comment by alexhung** [comment]
@zymzxq That make more sense now. I'll take a look at `artifactory_remote_repository` code.

**Comment by alexhung** [comment]
@zymzxq I tested with `artifactory_remote_repository` in 2.25.0 and can confirm this issue exists.

My recommendation is to upgrade to the latest version (currently at 6.9.2). If that is not possible (for variety of reasons) my next recommendation is to migrate from `artifactory_remote_repository` to the repository specific resource, e.g. `artifactory_remote_docker_repository`.

You can do that by first importing your docker repository into a new `artifactory_remote_docker_repository` resource. Test and confirm that this is correct, then you can use `terraform state rm` to remove the existing `artifactory_remote_repository` resource.

As always, we encourage you to test this process in testing environment or test repositories before applying to production environment.

**Comment by zymzxq** [comment]
Thanks, I migrated to the new resource type in the end
