### ISSUE TITLE
access token that provides access to artifactory and xray

### ISSUE THREAD

**Issue by oallauddin** [jfrog/terraform-provider-artifactory#475]
**Is your feature request related to a problem? Please describe.**
We would like to setup an access token that has access to Artifactory and Xray.
From what I understand this a feature that is available in the REST API. 

**Describe the solution you'd like**
I think the validation for audience in `artifactory_access_token` and audiences in `artifactory_scoped_token` could be modified to allow jfxr@. Not sure if there are more possible values for audience.  

```
resource "artifactory_group" "readonly_group" {
  name        = "readonly-group"
  auto_join   = false
  realm       = "internal"
  description = "Group for read only access"
}

resource "artifactory_user" "scoped_user" {
  name   = "scoped-readonly"
  email  = "scoed-readonly@noemail.com" 
  groups = [artifactory_group.readonly_group.name]
}

resource "artifactory_scoped_token" "scoped_token" {
  username  = artifactory_user.scoped_user.name
  audiences = ["jfrt@*", "jfxr@*"]
}

resource "artifactory_access_token" "readonly_token" {
  username          = "artifactory-readonly"
  end_date_relative = "0s"
  audience          = "jfrt@* jfxr@*"

  groups = [artifactory_group.readonly_group.name]
}

Error: invalid value for audiences (must begin with 'jfrt@')

{
  "error" : "invalid_request",
  "error_description" : "Illegal audience: jfxr@*, audience can contain only service IDs of Artifactory servers."
}
```

**Comment by alexhung** [comment]
@oallauddin I've already started on this before you file this issue 😄

**Comment by alexhung** [comment]
@oallauddin For `artifactory_access_token`, the old Artifactory API doesn't seem to support `jfxr@` when used with other service ID. Works when uses by itself, e.g. `audience = "jfxr@*"`. That is a bug in Artifactory API.

For `artifactory_scoped_token`, I'm working to expand the provider's validation to include all the valid service prefixes.

**Comment by oallauddin** [comment]
Thanks for working on this. One thing I found in my testing is that if I create the token through the ui. The token works for artifactory and xray. The default value for the audience in the ui is *@*. The ui does not seem provide an option to customize the audience.
![image](https://user-images.githubusercontent.com/13156842/172224714-9e2ef2b7-759c-47bc-9080-d5ab4c0ade1f.png)

**Comment by alexhung** [comment]
@oallauddin The "Service" drop down is what control the audience field.
<img width="588" alt="Screen Shot 2022-06-06 at 11 54 36 AM" src="https://user-images.githubusercontent.com/27263/172228174-d2203524-277a-4455-857f-ce40eccb89f4.png">
<img width="585" alt="Screen Shot 2022-06-06 at 11 54 45 AM" src="https://user-images.githubusercontent.com/27263/172228190-6d3f5f80-1143-4627-b57c-e55e724d054f.png">
