### ISSUE TITLE
artifactory_user password length

### ISSUE THREAD

**Issue by oallauddin** [jfrog/terraform-provider-artifactory#482]
**Is your feature request related to a problem? Please describe.**
Password policy that is set on our artifactory server is not in line with the random password that is generated by the resource artifactory_user/artifactory_unmanaged_user.

**Describe the solution you'd like**
Add optional attributes for minimum length, minimum number of digits, minimum number of lowercase letters, and minimum number of uppercase letter so the random generated password can be in line with our password policy. 
[How to set a password policy in terraform](https://jfrog.com/knowledge-base/how-to-set-a-password-policy-in-artifactory/)
If you can't add the feature can you increase the defaults? Like the example from the [library.](https://github.com/sethvargo/go-password)
```
func main() {
  // Generate a password that is 64 characters long with 10 digits, 10 symbols,
  // allowing upper and lower case letters, disallowing repeat characters.
  res, err := password.Generate(64, 10, 10, false, false)
  if err != nil {
    log.Fatal(err)
  }
  log.Printf(res)
}
```

**Describe alternatives you've considered**
I tried ignore_changes for password and an empty string for password. 
Unable to get past minimum length validation on artifactory server due to the password policy.   
```
resource "artifactory_user" "readonly_user" {
  name  = "artifactory-${var.group}-readonly"
  email             = var.password_reset_email
  profile_updatable = true
  disable_ui_access = false
  groups            = [artifactory_group.readonly_group.name]

  lifecycle {
    ignore_changes = [password]
  }
}
```

**Additional context**
Error from terraform apply.
```
{
  "errors" : [ {
    "status" : 400,
    "message" : "New password doesn't qualify password policy: length requirement is invalid. At least 15 characters are required."
  } ]
}
```

**Comment by chb0github** [comment]
@alexhung I think we need to change the hcl a bit - I don't like the `""` being the indicator of generating a password or not.

I am thinking

```hcl
resource "artifactory_user" "readonly_user" {
  name  = "artifactory-${var.group}-readonly"
  email             = var.password_reset_email
  profile_updatable = true
  disable_ui_access = false
  groups            = [artifactory_group.readonly_group.name]
  auto_generate_password = true
  lifecycle {
    ignore_changes = [password]
  }
}
```

By default, auto gen is `false` which is different than how it is now. 

Basically, I want it so that if you set `auto_gen_pass = true` you must now give it all the params. I don't like the details hidden. If you have to override this, then obviously it didn't work and you are responsible for all the params

thoughts?

For the record: I am not a fan.

**Comment by alexhung** [comment]
@chb0github The second version looks ok to me. Also not a fan but 🤷🏼 . I'd like to see `min_` prefix for `password.len`, etc. e.g. `password.min_len`, `password.min_symbols`, etc.

I don't think `ignore_changes` is needed since the `pack()` already not updating the state.

**Comment by oallauddin** [comment]
Trying to workaround this issue in a test environment. I added the password attribute and a default password in the terraform code so I could perform the terraform apply and create the user. Then I logged into the UI and changed the password for the user to a new value. Then in the terraform code I removed the password attribute and also changed the email address for the user and performed another terraform apply. Behavior we noticed is that the old password was being applied. The terraform plan said that the password would not be changed but that was not case. The old password was saved in the state and added to the PUT to update the user. Only way we could fix this was for our admin to set the password to null in the state. If we initially have a password and then the password attribute what should the value of it be in the state? Should it be the initial password or null?

**Comment by chb0github** [comment]
Let's start with what we know about how artifactory works with regard to passwords

1. You can create a user, using TF, but the password has to match the system settings which the TF provider cannot possibly know. 
2. The password is not returned at all in the current version of artifactory in the API - so, there is no way to sync it with local state. 
If you change the password in your HCL to `""`, exactly what would you expect to occur? That the password for the user would be blanked? Then it wouldn't pass the artifactory policy for passwords (or the TF provider policy for that matter). So, it's entirely unclear to me what you hope to achieve with either `""` or `null` in your HCL. 

[There is a terraform provider ](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password)that will actually allow you to generate and manage passwords with the params as you listed - you definitely should use that to manage password changes. Passwords will then become another resource that you can manage or not

I wasn't a big fan of including password management in our user resource for exactly this reason I am extremely hesitant to reimplement password management - which is entirely orthogonal to this provider.
