### ISSUE TITLE
update documentation for artifactory_local_maven_repository

### ISSUE THREAD

**Issue by oallauddin** [jfrog/terraform-provider-artifactory#488]
Documentation for [artifactory_local_maven_repository](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/local_maven_repository) needs to be updated. Options for checksum_policy_type should be `client-checksums` and `server-generated-checksums` .

**Comment by chb0github** [comment]
We'll have a look

**Comment by chb0github** [comment]
subtle. change coming

**Comment by chb0github** [comment]
#493
