### ISSUE TITLE
scoped_token without expired date

### ISSUE THREAD

**Issue by ADSapozhnikov** [jfrog/terraform-provider-artifactory#498]
**Is your feature request related to a problem? Please describe.**
I am try to create scoped_token without expired date
```
resource "artifactory_scoped_token" "scoped_token_group" {
  description = "Integration RO token"
  scopes        = ["applied-permissions/groups:sec_artifactory_ro"]
  expires_in   = 0
}
```
**Describe the solution you'd like**
If I provide 0 to expires_in or do not set this option I am waiting to have access token without expired date

**Comment by alexhung** [comment]
@ADSapozhnikov This is currently a limitation with the Artifactory API. The only workaround I can suggest is to set a very long expiration period.

**Comment by ADSapozhnikov** [comment]
Thanks, I also thinking about this workaround.
