### ISSUE TITLE
Remote repository - Smart remote repository settings reset after terraform apply

### ISSUE THREAD

**Issue by ivohlavaty** [jfrog/terraform-provider-artifactory#50]
**Describe the bug**
When configuring remote repository, **Smart Remote Repository** settings are reseted to default values even if those settings are not supported by Artifactory provider. ("Report Statistics" & "Sync Properties" & "Source Absence Detection" checkboxes are cleared, "List Remote Folder Items" stays checked)

**Requirements for and issue**
- [ ] Snippet
```
resource "artifactory_remote_repository" "repo-remote" {
  provider     = artifactory.myinstance
  key          = "nuget-repo-remote"
  package_type = "nuget"
  description  = "(local file cache)"
  url          = "https://artifactory.company.com/artifactory/api/nuget/nuget-location-a-local/"
  username     = var.art_login_cloud_account
  password     = var.art_login_cloud_password
  offline      = false

  allow_any_host_auth          = false
  blacked_out                  = false
  block_mismatching_mime_types = true
  bypass_head_requests         = true
  content_synchronisation {
    enabled = true
  }
  download_context_path                 = "Download"
  enable_cookie_management              = false
  enable_token_authentication           = false
  feed_context_path                     = null
  fetch_jars_eagerly                    = false
  fetch_sources_eagerly                 = false
  force_nuget_authentication            = false
  handle_releases                       = true
  handle_snapshots                      = true
  hard_fail                             = false
  includes_pattern                      = "**/*"
  max_unique_snapshots                  = 0
  missed_cache_period_seconds           = 900
  notes                                 = "abcd note"
  property_sets                         = ["artifactory"]
  remote_repo_checksum_policy_type      = "generate-if-absent"
  repo_layout_ref                       = "nuget-abcd-layout"
  retrieval_cache_period_seconds        = 1800
  share_configuration                   = false
  socket_timeout_millis                 = 15000
  store_artifacts_locally               = true
  suppress_pom_consistency_checks       = true
  synchronize_properties                = false
  unused_artifacts_cleanup_period_hours = 168
  v3_feed_url                           = "https://api.nuget.org/v3/index.json"
}
```
- [ ] Version of artifactory: 7.13.4
- [ ] Version of terraform: 0.13.6
- [ ] Version of provider: 2.2.7

**Expected behavior**
When "Smart Remote Repository" are set up using WebUI, terraform apply command does not affect them when it is not supported by provider. Or better way, include these settings in provider.

**Comment by chb0github** [comment]
Please update your snippet to be fully functioning hcl. I will have a look at this, but the reason we ask for copy-and-paste working hcl it to eliminate any guessing

**Comment by ivohlavaty** [comment]
Hi @chb0github ,
I hope it's fully functional now, it was complete but missing newline so the resource was ommited. I am applying the snippet using  
`terraform apply -target="artifactory_remote_repository.repo-remote"`

**Comment by chb0github** [comment]
I will see if I can reproduce it today. Thanks for the udpate

**Comment by chb0github** [comment]
Ok, I am finally getting around to reading this - what is a "smart" repository in your mind?

**Comment by ivohlavaty** [comment]
Hi Christian,
"smart" is just a part of the remote repository config. Thanks for looking at it ..
<img width="290" alt="Screenshot 2021-09-17 at 06 24 38" src="https://user-images.githubusercontent.com/75631093/133723952-82038e2e-bee3-429e-828b-616be75b869e.png">
.

**Comment by chb0github** [comment]
LOL! I know this system by APIs - I hardly ever use the UI

**Comment by mikeycmccarthy** [comment]
@ivohlavaty Out of interest were you able to create smart remote repositories via the provider in the first place, or are your importing repositories already created as smart remotes?

**Comment by ivohlavaty** [comment]
hi @mikeycmccarthy I don't use these settings anymore because they are not part of terraform provider and we don't want to do any steps manually via webUI.

**Comment by mikeycmccarthy** [comment]
Thanks @ivohlavaty. Are you using the provider at all to create smart repositories or some other tool? I'm just wondering if its possible and I didn't want to raise a bug if someone is successfully able to create smart repos using the provider.

**Comment by ivohlavaty** [comment]
I am not using smart repositories features because provider does not support it. You cannot have system "as a code" and do manual steps after terraform apply. In fact absence of smart repository is not such an issue, worst thing is that jfrog is introducing new features like fedarated repository but you cannot deploy them using terraform so you don't use them unless you change your tooling or introduce super complicated deploy workflow ..

**Comment by mikeycmccarthy** [comment]
Thanks, @ivohlavaty, good to know. In our case we cannot avoid this because Artifactory Edge nodes ONLY support smart remote repos and not any other type. I think we'll probably run into the federated issue at some point soon, which would be a shame. Anyways, I'll move this conversation to a more appropriate thread, cheers again for the feedback.

**Comment by alexhung** [comment]
@ivohlavaty Re federated repos, I'm working on that right now and should have something soon.

**Comment by alexhung** [comment]
@ivohlavaty We will be releasing support for smart repo for types npm, helm, docker and cargo soon. Is nuget repo type you want support for specifically?

**Comment by ivohlavaty** [comment]
@alexhung it would be great if terraform provider supports also nuget but it is not critical, thanks

**Comment by chb0github** [comment]
If you create a ticket, it'll be easier to track and get done
