### ISSUE TITLE
option no_auto_user_creation

### ISSUE THREAD

**Issue by dekar-sun** [jfrog/terraform-provider-artifactory#500]
**Describe the bug**
option `no_auto_user_creation` doesn't work as describe [here](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/saml_settings#auto_redirect) and must be true for enabling the `Auto Create Artifactory Users`.

**Requirements for and issue**
- The our code:
  ```

  resource "artifactory_saml_settings" "saml" {
  enable                = true
  service_provider_name = "our_atrifactory_fqdn"
  login_url             = "our_saml_service"
  logout_url            = ""
  certificate           = "our_saml_certificate"
  email_attribute       = "email"
  group_attribute       = "groups" 
  no_auto_user_creation        = true
  allow_user_to_access_profile = true
  auto_redirect                = false
  sync_groups                  = true
  verify_audience_restriction  = true
  use_encrypted_assertion      = false
  }

  ```
- Our version of artifactory is 7.38.10
- Our version of terraform is 1.2.2
- Our version of artifactory terraform provider is 6.6.0

**Comment by chb0github** [comment]
So, `no_auto_user_creation = true` actually ends up auto creating the user anyways?

This second part I don't get:

> must be true for enabling the Auto Create Artifactory Users.

**Comment by dekar-sun** [comment]
> 
Yes, with the option `no_auto_user_creation = true` users auto created inside the artifactory.

`Auto Create Artifactory Users` - this is the option on the SAML page in artifactory.
