### ISSUE TITLE
property_sets can't be removed

### ISSUE THREAD

**Issue by gevraud-cicd** [jfrog/terraform-provider-artifactory#502]
Hello,

It seems that this problem is still there.

I migrated my code from 2.25.0 to 6.9.3.

Here is one of the resource where I removed the property_sets.

Before
```
resource "artifactory_local_generic_repository" "cicd-archive" {
  key             = "cicd-archive"
  description     = "CICD archive repository"
  repo_layout_ref = "simple-default"
  property_sets = [ "artifactory"]
}
```

After
```
resource "artifactory_local_generic_repository" "cicd-archive" {
  key             = "cicd-archive"
  description     = "CICD archive repository"
  repo_layout_ref = "simple-default"
}
```
Plan + apply.

Plan again and this is the output :

```
  # artifactory_local_generic_repository.cicd-archive will be updated in-place
  ~ resource "artifactory_local_generic_repository" "cicd-archive" {
        id                       = "cicd-archive"
      ~ property_sets            = [
          - "artifactory",
        ]
        # (11 unchanged attributes hidden)
    }
```

The terraform show command still displays it:  

```
 ~/p/b/ar/terraform-cloud | master *1 !3 ?3  terraform state show artifactory_local_generic_repository.cicd-archive
# artifactory_local_generic_repository.cicd-archive:
resource "artifactory_local_generic_repository" "cicd-archive" {
    archive_browsing_enabled = false
    blacked_out              = false
    description              = "CICD archive repository"
    download_direct          = false
    id                       = "cicd-archive"
    includes_pattern         = "**/*"
    key                      = "cicd-archive"
    package_type             = "generic"
    priority_resolution      = false
    project_environments     = []
    property_sets            = [
        "artifactory",
    ]
    repo_layout_ref          = "simple-default"
    xray_index               = false
```

But it's not present in the UI

![image](https://user-images.githubusercontent.com/98534077/177603236-0ce401f4-95aa-411e-bc91-c21d07599847.png)

Regards

**Comment by alexhung** [comment]
@gevraud-cicd You said "It seems that this problem is still there.". I'm not familiar with this problem and a cursory search of issues doesn't return anything. Is there an existing, closed issue for this?

**Comment by gevraud-cicd** [comment]
Hello @alexhung , I saw this https://github.com/atlassian/terraform-provider-artifactory/issues/80 on the old provider

**Comment by alexhung** [comment]
@gevraud-cicd Thanks! This can be one of those Artifactory API behavior where empty value (`[]` or `null`) doesn't reset the value. We will investigate.

**Comment by chb0github** [comment]
Ok, I have dug into this:

1. `[]` as the set in the body payload does nothing
2. `[""]` or `["foo"]` produces and error about an unknown set
3. `null` does nothing
4. Deleting the key does nothing

I have reached out directly to the artifactory team and this is due to a bug on their end that this ticket has apparently unearthed in 12 year old code. 

You might ask yourself: Well, how does the UI do it? Can't you do it as they do it? The answers are:
- The UI has it's own special endpoint which is not a documented api
- Technically, maybe. And, in exigent circumstances we have. But, as this is a mature feature in the TF provider using the documented APIs I am loath to utterly revamp it. And, I am not entirely sure that the UI endpoint would support bearer token auth, which is what all the API endpoints are moving to and we are removing support for everything else. 

A ticket will be opened with the artifactory team internally. But, as this has been around 12 years it's clearly not obvious or crucial so I am not too hopeful it will get fixed in our lifetime

**Comment by piotrminkina** [comment]
I have similar problem, but with fields _description_ and _username_ (I did not examine the other fields) in all repositories. I set a value for these fields, then ran Terraform Plan. Terraform detected differences in state, well it wants to restore it, as follows:

```
  # artifactory_virtual_pypi_repository.pypi_snapshot will be updated in-place
  ~ resource "artifactory_virtual_pypi_repository" "pypi_snapshot" {
      - description                                        = "a" -> null
        id                                                 = "pypi-snapshot"
        # (9 unchanged attributes hidden)
    }
  # artifactory_remote_rpm_repository.rpm_remote will be updated in-place
  ~ resource "artifactory_remote_rpm_repository" "rpm_remote" {
        id                                    = "rpm-remote"
      - username                              = "a" -> null
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Finally, I ran Terraform Apply, which was successful, but unfortunately the value of these fields was not cleared. A subsequent call to Terraform Plan shows the same results as before Terraform Apply.

**Comment by alexhung** [comment]
@piotrminkina Please create a separate GitHub issue for your problem, and we'll investigate. Thanks.

**Comment by piotrminkina** [comment]
@alexhung done, as You requested.

**Comment by oallauddin** [comment]
Experiencing state drift when using `property_sets = []` for `artifactory_remote_docker_repository`. 
Value flips between [] and ["artifactory"] in terraform plan and applies. 
Is there any harm in just using the default value of `property_sets = ["artifactory"]` for all local and remote repositories?
When I create local and remote repositories via the quick setup UI the artifactory property set is automatically added. 

Also found this ticket in the Artifactory JIRA board. 
https://jfrog.atlassian.net/browse/RTFACT-29332
State drift may be related to this bug.

**Comment by alexhung** [comment]
@oallauddin Yes, there's an internal JIRA ticket for this issue. It has not been assigned/scheduled by the product engineering team. Please open a customer support ticket and pass on the JIRA ticket ID `RTDEV-27318` as reference.

**Comment by alexhung** [comment]
@oallauddin There may be a separate issue here with the provider not populating the state correctly. @danielmkn let's create a ticket for this to investigate.

**Comment by danielmkn** [comment]
Hi @oallauddin, I'm using the following config: 
```
resource "artifactory_remote_docker_repository" "my-remote-docker1" {
  key                            = "my-remote-docker1"
  external_dependencies_enabled  = true
  external_dependencies_patterns = ["**/registry-1.docker.io/**"]
  enable_token_authentication    = true
  url                            = "https://registry-1.docker.io/"
  block_pushing_schema1          = true
  property_sets                  = []
}
```
After I apply the initial config, I don't see state drift when I run `terraform plan` or `terraform apply`. 
An empty array in HCL is omitted by the provider, so in the API call there is no such attribute as `propertySets`. 
At the same time, the repo that was created has an empty array assigned to `propertySets`. 
This is what I see in the state file: `"property_sets": null,`. 
If we add a default value for the attribute, we will need to add another schema version. It's doable, but let's figure out where is the problem here first.

**Comment by danielmkn** [comment]
@oallauddin which Artifacotry and Provider versions do you use?

**Comment by tbutler-qontigo** [comment]
> @oallauddin Yes, there's an internal JIRA ticket for this issue. It has not been assigned/scheduled by the product engineering team. Please open a customer support ticket and pass on the JIRA ticket ID `RTDEV-27318` as reference.

@alexhung You may also want to look at RTFACT-29332 which was raised recently when I opened a ticket with support - it appears to be the same issue

**Comment by alexhung** [comment]
@tbutler-qontigo Thanks. I have looked at it yesterday and you're right that they are the same issue. I don't have permission to link those 2 tickets but I'll post a comment to the internal ticket.

**Comment by oallauddin** [comment]
@alexhung and @danielmkn 
Sorry for not getting back you all sooner. I have set the value of property_sets to artifactory in all of our local and remote repositories and have moved on from the state drift issue. Also we are no longer on the previous version of the providers. 

Our docker remote repository had ignore_changes on username and password. 
There was recent fix for ignore_changes https://github.com/jfrog/terraform-provider-artifactory/issues/642
So not sure if that was related to problem I was having.
