### ISSUE TITLE
Support for Repository Layouts

### ISSUE THREAD

**Issue by cliffchapmanrbx** [jfrog/terraform-provider-artifactory#503]
While the majority of our repositories use the "simple-default" layout we do have a handful of specific repository layouts that we make use of. Currently they're manually configured via the UI, which breaks our goal of having all common Artifactory configurations in config-as-code.

We would be very appreciative if your team could [add support for custom repository layouts](https://www.jfrog.com/confluence/display/JFROG/Repository+Layouts).

**Comment by chb0github** [comment]
Please give us an example of the kind of HCL you had in mind

Also, do you know this guy:
https://github.com/pjweisberg

**Comment by cliffchapmanrbx** [comment]
The Edit interface is pretty straightforward, it'd be mostly about getting these options into HCL.

**Comment by cliffchapmanrbx** [comment]
> Also, do you know this guy: https://github.com/pjweisberg
> 
> My avatar is normally redmage

Alas no, this is a somewhat random user icon I use for work purposes :)

**Comment by chb0github** [comment]
Do you know what the icon is?

re the request: Will consider
