### ISSUE TITLE
Terraform Backend repository type naming

### ISSUE THREAD

**Issue by OSapozhnikov** [jfrog/terraform-provider-artifactory#506]
All terraform resource type have naming like this terraform_{resourceType}, but for local terraform backend used "artifactory_local_terraformbackend_repository"

**Describe the solution you'd like**
I suppose this resource need rename to "artifactory_local_terraform_backend_repository"
Because this will be have similar naming and easy to read

**Comment by chb0github** [comment]
This is because it follows our internal convention and matches the repo name exactly as it's found in the API docs.
