### ISSUE TITLE
Project Key - character limitations of 3 to 10 characters

### ISSUE THREAD

**Issue by blyles** [jfrog/terraform-provider-artifactory#513]
**Describe the bug**
The project key set on a local repository is required to be the project key being the prefix and then the repository key.  It's restricted to 10 characters and most of our repositories are 

projectkey (3 characters) - (repository name 10-15).

```
locals {
  normal_ruby_repositories = {
    img-dssalt-ruby-suo = {
      key = "img-mysalt-ruby-suo"
      project_key = "mykey-img-mysalt-ruby-suo"
    }
  }
}


resource "artifactory_local_gems_repository" "normal_repository" {
  for_each = local.normal_ruby_repositories
  key      = each.value.key
  project_key = each.value.project_key == "" ? null : each.value.project_key
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
1.2.3
- [x] Your version of terraform provider
6.11.0

**Expected behavior**
25 character limit.  

**Additional context**
It may be a simple miss-understanding of how this is meant to work but the same repo via the portal can be added manually, just not via terraform.

**Comment by alexhung** [comment]
@blyles This is due to the character limits was 3-10 characters when `project_key` was added to the provider. Since then, Artifactory has expanded the limit to 25.

**Comment by blyles** [comment]
Ah ok I feel less insane so the provider just has to be updated to be in line with artifactory?

**Comment by alexhung** [comment]
That's right. I don't have an ETA for you though.

**Comment by apr-1985** [comment]
I have hit this issue too which is a bit of a blocker for using the provider.
I have raised https://github.com/jfrog/terraform-provider-artifactory/issues/513 to update the validator if you accept PRs to to that repo.

**Comment by alexhung** [comment]
@apr-1985 There are also tests in this repo for the `project_key` validation that require updating as well.

**Comment by alexhung** [comment]
@blyles @apr-1985 Upon closer examination, I misunderstood your original issue.

The `project_key` should contain *only* the project key, not project key + repo key.

e.g. assuming your project key is `proj`

```hcl
locals {
  normal_ruby_repositories = {
    img-dssalt-ruby-suo = {
      key = "my-repo-key"
      project_key = "proj-my-repo-key"
    }
  }
}
```

So there's no need to expand the validation for the `ProjectKey` validator to 25 characters.

**Comment by blyles** [comment]
@alexhung thanks for update, I'll rework our stuff to go inline with this.

![image](https://user-images.githubusercontent.com/5386554/181722407-89c116bf-2fce-4b8c-bf77-e62925374d73.png)

Here's the confusion.  The documentation in terraform is misleading.

**Comment by alexhung** [comment]
@blyles That is in reference to the **repository** `key`. See the HCL in my comment above.
