### ISSUE TITLE
Support adding multiple users and groups to a permission target

### ISSUE THREAD

**Issue by kaiku** [jfrog/terraform-provider-artifactory#514]
### Summary
Artifactory's v2 REST API supports attaching multiple users and groups to a single permission target using the "[Create Permission Target](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API+V2#ArtifactoryRESTAPIV2-CreatePermissionTarget)" endpoint. It consumes [`application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json`](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json):

```json
{
  "name": "java-developers",
  "repo": {
    "repositories": ["local-rep1", "local-rep2", "remote-rep1"],
    "actions": {
      "users" : {
        "bob": ["read","write","manage"],
        "alice" : ["write","annotate", "read"]
      },
      "groups" : {
        "dev-leads" : ["manage","read","annotate"],
        "readers" : ["read"]
      }
    }
  }
}
```

### Issue
The provider's [`artifactory_permission_target`](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/permission_target), which uses the v2 endpoint above, supports only a single user and group per permission target. As a result, I'm unable to manage any existing permission with >1 user or group in terraform.

```tf
resource "artifactory_permission_target" "test-perm" {
  name = "test-perm"

  repo {
    includes_pattern = ["foo/**"]
    excludes_pattern = ["bar/**"]
    repositories     = ["example-repo-local"]

    actions {
      users {
        name        = "anonymous"
        permissions = ["read", "write"]
      }

      groups {
        name        = "readers"
        permissions = ["read"]
      }
    }
  }
```

A shot in the dark – comma-separated strings are unsupported:

```tf
resource "artifactory_permission_target" "test-multiperm" {
  name = "test-multiperm"

  repo {
    repositories     = ["testrepo"]
    includes_pattern = ["**"]

    actions {
      groups {
        name        = "group-1,group-2"  # both groups exist, but no group named "group-1,group-2" exists
        permissions = ["read", "write", "annotate"]
      }
    }
  }
}
```

Output (terraform via atlantis):

```
│ Error: 
│ 400 POST https://<url>/artifactory/api/v2/security/permissions/test-multiperm
│ {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "Permission target contains a reference to a non-existing group 'group-1,group-2'."
│   } ]
│ }
```

### Desired Solution

https://github.com/jfrog/terraform-provider-artifactory/issues/28 raised a similar request with proposals.

I'm open to any syntax as long as it allows me to attach many users and groups.

### Workaround

No workaround other than:
1. Do not import permissions with multiple groups and/or users, leaving them unmanaged by terraform
2. Redesign our user-permission-model to achieve the same functionality

**Comment by alexhung** [comment]
@kaiku As far as I can tell from the code/schema, there's no limit on how many `users`/`groups` you can define in the `actions` attributes.

Have you tried?

```hcl
resource "artifactory_permission_target" "test-perm" {
  name = "test-perm"

  repo {
    includes_pattern = ["foo/**"]
    excludes_pattern = ["bar/**"]
    repositories     = ["example-repo-local"]

    actions {
      users {
        name        = "anonymous-1"
        permissions = ["read", "write"]
      }

      users {
        name        = "anonymous-2"
        permissions = ["read", "write"]
      }

      groups {
        name        = "readers-1"
        permissions = ["read"]
      }

      groups {
        name        = "readers-2"
        permissions = ["read"]
      }
    }
  }
}
```

**Comment by kaiku** [comment]
I noticed the author in https://github.com/jfrog/terraform-provider-artifactory/issues/28 indicated they tried that without success, which is why I didn't bother to attempt it.

I'll give it a try shortly!

**Comment by alexhung** [comment]
@kaiku Let me know if you run into issues. If this is reproducible then we will take a look.

**Comment by kaiku** [comment]
@alexhung that works! I feel a bit 🤦 for not giving it a try first.

I think it would still be helpful to see an example of this in the terraform documentation.
