### ISSUE TITLE
Support the ability to override/remove the "artifactory context" 

### ISSUE THREAD

**Issue by jphelton** [jfrog/terraform-provider-artifactory#515]
**Is your feature request related to a problem? Please describe.**

I work for an enterprise that runs self-managed Artifactory Instances.  When we first began using this product (pre 7.0) we removed the "/artifactory" context from the running application.  Even after upgrading to artifactory 7.0 we've kept this capability in place to maintain backwards compatibility

- [How to Remove “artifactory” from the Context URL in Artifactory 7](https://jfrog.com/knowledge-base/how-to-remove-artifactory-from-the-context-url-in-artifactory-7/)

Unfortunately, this means that we're unable to leverage the terraform provider for artifactory.  This is because there are several places within the provider where `/artifactory` is hardcode.
- example: [datasource_artifactory_file.go#L265](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/datasource/datasource_artifactory_file.go#L265)

**Describe the solution you'd like**

I would like the terraform provider to provide similar functionality as the jfrog-cli.  When configuring the jfrog-cli I have option to explicitly provide an artifactory URL that is used in place of platform url.

```
$ jfrog config show
Server ID:			ent-art
JFrog platform URL:	https://artifactory.mycompany.internal/
Artifactory URL:		https://artifactory.mycompany.internal/
Distribution URL:		https://artifactory.mycompany.internal/distribution/
```

I would like a similar capability to be present in this terraform provider

**Describe alternatives you've considered**

At present my only alternative (that I'm aware of) is not to use the terraform provider.  I'm mostly concerned with being able to use the datasource

**Additional context**

If there are no objects I can contribute this change.  However, I'm not entirely sure what the contract would look like

This contract most closely lines up with the configuration options available in the jfrog-cli.  But the jfrog-cli also supports distribution, xray, mission control, and pipelines URLs.  Would those be necessary here too?
```hcl
provider "artifactory" {
  url = "${var.artifactory_url}"
  artifactory_url = "${var.artifactory_url}"  // If not set, defaults to "${var.artifactory_url}/artifactory"
  access_token  = "${var.artifactory_access_token}"
}
```

This option could work too, though I don't know enough about the non-artifactory paths to tell if this dangerous
```hcl
provider "artifactory" {
  url = "${var.artifactory_url}"
  context = "artifactory"  // can be set to the empty-string
  access_token  = "${var.artifactory_access_token}"
}
```

**Comment by alexhung** [comment]
@jphelton Apology for the late reply. We didn't miss this issue. This has been asked a few time before and it isn't a trivia change for the provider. We will investigate and see when we can take this on.

**Comment by chb0github** [comment]
This question has come up repeatedly and the problem comes down to the fact that endpoints that artifactory offers are not consistent

Here is an [example](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource/security/resource_artifactory_scoped_token.go#L243)

In the above case, if the url the user provides is just taken wholesale, and the `/artifactory` part is removed from hardcoding, then in 90% of cases, sure, this could work. But then, the case in the code above, and the given HCL 

```hcl
provider "artifactory" {
  url = "https://my.server.com/artifactory"
  access_token = "..."
}
```

would resolve to: `https://my.server.com/artifactory/access/api/v1/tokens/{id}` which isn't a valid endpoint for that resource. It has to be `https://my.server.com/access/api/vi/token/{id}`

It would come down to a case-by-case basis of whether or not to accept the URL as is, or strip it down and reconstitute it. Another solution, but potentially problematic also, is just to have an override flag that takes it as is, with the understanding that the user owns the results. Depending on the combination of resources the HCL, this may or may not work. 

@alexhung - perhaps a solution is allow the user to override, but in the case of mixed and incompatible resources make use of 2 provider invocations/configurations? I've never tried that before in TF

**Comment by alexhung** [comment]
@chb0github My thinking thus far is to store the default 'context' paths (e.g. `/artifactory`, `/access`, etc.) in the provider's config (return from `ConfigureContextFunc`). Then in each resource's CRUD context func, we have access to this 'context' paths as part of the meta argument. In combination of exposing these 'context' paths as part of the provider's schema, we will allow users to override them (if they so desired).

**Comment by chb0github** [comment]
I see what you're saying, but wow, does it get complicated fast!

**Comment by chb0github** [comment]
[here's](https://medium.com/scalereal/how-to-use-multiple-aws-providers-in-a-terraform-project-672da074c3eb) what I am thinking

The idea is to use one provider configuration for where you want to `override` and 1 where you don't. And then you select which provider does the resource creation. Then, all you need is a `url_override = true`, and if set, this will be the base. You still have to know how to distinguish between needing `/artifactory` - did the user supply it? If not it needs adding, but only in some cases. If they did, do nothing (but only in some cases). 

You know what, @alexhung , it's almost like you need a factory function that literally has a mapping of all known endpoints without any `/artifactory` and so when you give it:

```go
url := findEndPoint("repositories/{id}")
```
this would yield 
`url -> "/artifactory/repositories/{id}"` depending on how it was configured. 

You really need a function that, on a url-by-url basis, determines how to construct the full path and for every resty call you use it to get the final URL

**Comment by chb0github** [comment]
@jphelton - as you can see: This is not straightforward and it's for an edge case. Some places decide to remap their artifactory instance for their own reasons, most don't.

**Comment by alexhung** [comment]
@chb0github

> You really need a function that, on a url-by-url basis, determines how to construct the full path and for every resty call you use it to get the final URL

100% agree on this! 😄
