### ISSUE TITLE
resource "artifactory_backup" is missing attributes

### ISSUE THREAD

**Issue by olwe0002** [jfrog/terraform-provider-artifactory#516]
**Is your feature request related to a problem? Please describe.**

artifactory_backup can't set the following fields, compared to the GUI:
- Server Path For Backup
- Included Items
- Incremental
- Verify enough disk space is available for backup

additionally, the excluded_repositories is not available in the provider but not visible in the GUI

**Describe the solution you'd like**
add all missing fields to the provider

**Comment by alexhung** [comment]
@olwe0002 `excluded_repositories` is actually for "Included Items" in the UI. The Artifactory configuration implementation is opposite of the UI in this case.

When you move an included items to "Available Items" column, Artifactory adds that item to the `excluded_repositories` list. 🤷🏼

**Comment by alexhung** [comment]
@olwe0002 So far I can see support in the Artifactory configuration API to support "Server Path" and "Verify disk space". There's no schema support for "Incremental" setting.
