### ISSUE TITLE
Some defaults in the user HCL dont match the description

### ISSUE THREAD

**Issue by apr-1985** [jfrog/terraform-provider-artifactory#518]
**Describe the bug**
profile_updatable and disable_ui_access default to True when the docs say they should be False

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**
Docs match actuals

**Additional context**

**Comment by apr-1985** [comment]
https://github.com/jfrog/terraform-provider-artifactory/pull/517

**Comment by apr-1985** [comment]
Actually docs here say it should be `true` https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/user.md not sure what is the correct default value and which bit is wrong :)

**Comment by alexhung** [comment]
@apr-1985 Per [my comment](https://github.com/jfrog/terraform-provider-artifactory/pull/517#pullrequestreview-1053197133), it's the `Description` that is incorrect.
