### ISSUE TITLE
Create Property set

### ISSUE THREAD

**Issue by jckos** [jfrog/terraform-provider-artifactory#522]
**Is your feature request related to a problem? Please describe.**
I was wondering if there is a way to create property set via the provider

**Describe the solution you'd like**
The property set can be defined with Terraform as it can be done with the UI:
<img width="1368" alt="Screenshot 2022-07-29 at 14 28 10" src="https://user-images.githubusercontent.com/90831591/181758380-b87108e7-f420-4787-956f-2021e30bd023.png">

**Describe alternatives you've considered**
- the Config Descriptor could be changed directly (e.g. with ansible)
- using [Artifactory YAML Configuration](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration)  (with e.g. curl ?)

**Comment by alexhung** [comment]
@jckos `property_sets` attribute is supported in all the repository resources. For example, the local repository: https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/local#property_sets

**Comment by jckos** [comment]
@alexhung Thank you, this does create the property set if it is not defined in Artifactory? What I want to achieve is to define Predefined value in property set (defined in Artifactory config - see the screen above).

**Comment by alexhung** [comment]
@jckos Ah, now I understand. No, the `property_sets` attribute doesn't create new property set. There's no support for creating new property sets in the provider.

**Comment by danielmkn** [comment]
@jckos, the resource is added in v6.16.0

**Comment by jckos** [comment]
Thank You!
