### ISSUE TITLE
Scoped Token doesn't return refresh_token while refreshable specified

### ISSUE THREAD

**Issue by krischblack** [jfrog/terraform-provider-artifactory#531]
**Describe the bug**
creating a new refreshable token does not return the refresh_token described in the API to use it later for a refresh.

Artifactory: 7.41.6
terraform: 1.2.7
terraform provider: 6.12.1

Terraform (based on https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/scoped_token#creates-a-refreshable-token):
resource "artifactory_scoped_token" "scoped_token_refreshable" {
  username    = "existing-user"
  refreshable = true
}

API Call for creating a token in Artifactory:
https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateToken.1
From the Sample: 
`curl -H "Authorization: Bearer <valid access token>" -XPOST "http://localhost:8082/access/api/v1/tokens" -d "scope=applied-permissions/user"
  
200
{
  "token_id": "<id>"
  "access_token": "<access-token>",
  _**"refresh_token": "<refresh-token>",  // optional**_
  "expires_in": "<seconds>",             // optional     
  "scope": "applied-permissions/groups:<group-name>"
  "scope": "applied-permissions/user",
  "token_type": "access_token"
}`

You can find the API Call for the refresh_token also in the "Access Tokens" part without a specific heading. (between Revoke Token by ID and Pairing Token)

**Expected behavior**
return the refresh_token during the token creation

**Comment by alexhung** [comment]
@krischblack Thanks for the report. We will schedule this to be fixed.
