### ISSUE TITLE
Need support to check xray index while creating repository

### ISSUE THREAD

**Issue by jkumar19** [jfrog/terraform-provider-artifactory#54]
**Describe the bug**
Actually this is not a bug. This is just a feature request to check xray index while creating the artifactory repository. We are actively using SaaS Artifactory and XRay and therefore need support to check XRay index checkbox to enable the XRay indexing for the repository.

**Requirements for and issue**
- [ ] Need support to enable XRay indexing while creating repository in artifactory
- [ ] We are using SaaS or Cloud Artifactory with XRay license.
- [ ] We are using terraform 0.14.5

**Expected behavior**
The expectation is to get the XRay index checkbox get enabled automatically via terraform code.

**Comment by jkumar19** [comment]
@chb0github - I just validated. It seems XRay Indexing is working fine. We can close this.

Additionally I saw xray policy and watch resource code is recently added. Any idea when we are planning release for this. We have a requirement to create XRay policies and watch using terraform.

**Comment by chb0github** [comment]
That was released a while back - it's the most recent code. If you don't see sample docs in the registry let me know and I will see about republishing them

**Comment by jkumar19** [comment]
@chb0github - Thanks. While creating watch I am facing this error:

Error: {"error":"Got invalid watch: binary manager id is missing"} 

Any idea about this error please?

**Comment by chb0github** [comment]
Because this ticket is very old and that flag is [already supported](https://github.com/jfrog/terraform-provider-artifactory/search?q=xray_index)

**Comment by martinm82** [comment]
I might be totally blind, but on which resource is this documented?

**Comment by alexhung** [comment]
@martinm82 Looks to me we are missing the documentation.
