### ISSUE TITLE
Add Support for `artifactory_federated_swift_repository`

### ISSUE THREAD

**Issue by mcaulifn** [jfrog/terraform-provider-artifactory#540]
**Is your feature request related to a problem? Please describe.**
The artifactory provider does not support `artifactory_federated_swift_repository` while Artifactory API does.

**Describe the solution you'd like**
Add support for `artifactory_federated_swift_repository`.

**Comment by danielmkn** [comment]
@mcaulifn, it's released in v6.17.0
