### ISSUE TITLE
Add artifactorypush

### ISSUE THREAD

**Issue by utviklingstjenester** [jfrog/terraform-provider-artifactory#547]
**Is your feature request related to a problem? Please describe.**

The API call currently used for creating a artifactory_push_replication (`/api/replications/multiple/`) is only available to `Enterprice license`, however, there exists a API call that adds a single configuration for push replication that works for Artifactory Pro. 

**Describe the solution you'd like**
A resource that use the `/api/replications` to add or replace push replication configuration for a single replication.

**Comment by alexhung** [comment]
@utviklingstjenester Thanks for the suggestion, we'll take a look.

**Comment by chb0github** [comment]
License specific functionality - This has been considered repeatedly, but to be honest, I don't think It can't be practically implemented. The matrix of API -> version(s) is simply non-existent, or if there is, no one has seen it. Without truly knowing the breadth of what's being asked, an implementation would just be a guess. Although, it's up to @alexhung to make that call, this one case isn't enough motivation to work with.

Literally, up until this issue, I had no idea the API distinction between these licenses existed.

**Comment by utviklingstjenester** [comment]
This API call could be used by both Enterprise license and Artifactory Pro and was suggested to make push replications more accessible. For our case in particular, such implementation would allow us to handle push replications with terraform instead of implementing an ad-hoc solution that can work together with our current terraform implementation.

**Comment by danielmkn** [comment]
The change was released in v7.3.0
`artifactory_local_repository_single_replication` and `artifactory_remote_repository_replication` are using the API, available for non-Ent+ licenses.
