### ISSUE TITLE
Data Sources

### ISSUE THREAD

**Issue by nivensb** [jfrog/terraform-provider-artifactory#548]
**Is your feature request related to a problem? Please describe.**
Virtual repositories often contain other repositories that are reused across virtual repositories. For instance, you can create a remote Docker repo that several virtual Docker repos will include. Since only resource types are included in the artifactory provider, this can cause consistency problems if your repos are defined in more than one terraform file.

**Describe the solution you'd like**
Create data sources for repositories, groups, permissions, and users.

**Describe alternatives you've considered**
There really isn't an alternative to data sources.

**Additional context**
None

**Comment by chb0github** [comment]
Can you supply some TF code as an example of what you're hoping for and some documentation? I am having a hard time visualizing what you're asking

**Comment by nivensb** [comment]
Here are some examples:

data "artifactory_remote_pypi_repository" "company_remote_pypi" {
  key = "company-remote-pypi"
}

resource "artifactory_local_pypi_repository" "teamA_pypi_local" {
  key             = "teamA-pypi-local"
  repo_layout_ref = "simple-default"
  description     = "TeamA local pypi repo"
}

resource "artifactory_virtual_pypi_repository" "teamA_pypi" {
  key                     = "teamA-pypi"
  description             = "teamA virtual pypi"
  repositories            = [artifactory_local_pypi_repository.teamA_pypi_local.key, data.artifactory_remote_pypi_repository.key]
  default_deployment_repo = artifactory_local_pypi_repository.teamA_pypi_local.key
}



data "artifactory_user" "userA" {
    name = "userA"
}

data "artifactory_user" "userB" {
    name = "userB"
}

resource "artifactory_group" "groupA" {
  name             = "groupA"
  description      = "test group"
  admin_privileges = false
  users_names      = [ data.artifactory_user.userA.name ]
}

data "artifactory_group" "groupB" {
  name             = "groupB"
}

resource "artifactory_permission_target" "test-perm" {
  name = "test-perm"

  repo {
    repositories     = [ artifactory_virtual_pypi_repository.teamA_pypi.key ]

    actions {
      users {
        name        = data.artifactory_user.userB.name
        permissions = ["read", "write"]
      }

      groups {
        name        = data.artifactory_group.groupB.name
        permissions = ["read"]
      }
    }
  }

}

For this example, a remote repo like 'company_remote_pypi' would be a remote repo for a external source like https://files.pythonhosted.org. Unless repos are data types, we could use only one terraform project for all repos.

The other data sources; users and groups, would be helpful. They aren't necessarily needed, since you can include things by a string name, but it would more of a 'terraform standard' way of adding types.

**Comment by ateoto** [comment]
Bumping this with my support. The lack of data sources is making my complex configuration significantly more brittle for the exact reasons nivensb posted. In my use case, I use a module to generate "teams" this module creates group resources, team specific repositories, permissions targets, and the like. Passing values as strings creates a situation where either your module requires a significant amount of inputs and outputs, or you end up hardcoding values and praying that anyone making changes fully understands the configuration.

**Comment by alexhung** [comment]
We are planning to implement this soon. No ETA yet.

**Comment by Jan-Pleva** [comment]
+1 by SKODA

**Comment by alexhung** [comment]
@ateoto @Jan-Pleva @nivensb FYI, in case you missed it, we've been adding data sources to the provider. Check out the CHANGELOG for more details.

**Comment by danielmkn** [comment]
Done.
