### ISSUE TITLE
[Feature Request] Add support for the NuGet Symbol Server URL

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#549]
**Is your feature request related to a problem? Please describe.**

As of v6.16.0, it appears that this provider does not yet support the NuGet Symbol Server URL. While <https://symbols.nuget.org/download/symbols> is the correct URL for https://nuget.org, it doesn’t apply to alternate remote repositories.

Also, I'd like to keep my configuration as deterministic and "non-magical" as possible.

**Describe the solution you'd like**

Implement support for the _NuGet Symbol Server URL_ in the provider.

**Describe alternatives you've considered**

None.

**Additional context**

It looks like a lot of core functionality bugs were fixed in [Artifactory 7.36.1](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.36.1), released about 6-ish months ago.

![nuget-symbols](https://user-images.githubusercontent.com/39447/194377598-86bda300-c784-4538-b816-96ede90c503b.png)

**Comment by danielmkn** [comment]
Hi @skyzyx! It was released in v6.18.0.
