### ISSUE TITLE
Configuration resource docs fail to mention that the `artifactory/api/system/configuration` endpoint is blocked/removed in SaaS environment

### ISSUE THREAD

**Issue by mdb** [jfrog/terraform-provider-artifactory#550]
**Describe the bug**

👋 Hi - thanks for your work on `terraform-provider-artifactory`. I believe I've discovered a misleading shortcoming of the documentation, which may lead to inoperable Terraform configurations and unexpected production problems for users...

The [terraform-provider-artifactory](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs) documentation pertaining to the "configuration" suite of resources fails to mention that these resources fundamentally rely on the `artifactory/api/system/configuration` endpoint, which is blocked/removed in the SaaS environment (i.e. in Artifactory online). This means these resources cannot be used with the SaaS environment.

This impacts at least the following resources, and possibly more...

* [artifactory_backup](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/backup)
* [ldap_setting](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/ldap_setting)
* [property_set](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/property_set)
* [respository_layout](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/repository_layout)

## Example

Terraform configuration utilizing the `property_set` resource:

```hcl
terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "~> 6.16.0"
    }
  }
}

provider "artifactory" {
  url          = "your-artifactory-url"
  access_token = "your-access-token"
}

resource "artifactory_property_set" "repository" {
  name    = "foo"
  visible = true

  property {
    name                     = "bar"
    closed_predefined_values = true
    multiple_choice          = false

    predefined_value {
      name          = "baz"
      default_value = true
    }
  }
}
```

Error:

```
Error: failed to retrieve data from API: /artifactory/api/system/configuration during Read
```

Verbose error when `TF_LOG=DEBUG` is set:

```
400 GET https://REDACTED.jfrog.io/artifactory/api/system/configuration

{
"errors" : [ {
"status" : 400,
"message" : "Artifactory Online does not support accessing this API endpoint, please contact [support@jfrog.com](mailto:support@jfrog.com) for further assistance if required."
} ]
}, Attempt 1"
```

**Requirements for and issue**
- [X] A description of the bug: see above
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue): see above
- [X] Your version of terraform: 1.3.1
- [X] Your version of terraform provider: 6.16.0

**Expected behavior**
I would expect to see either...

A. documentation explaining that the `artifactory/api/system/configuration` endpoint is blocked/removed in the SaaS environment (i.e. in Artifactory online), and that impacted Terraform resources therefore cannot be used with the SaaS environment or...
B. these resources functioning as documented

**Comment by chb0github** [comment]
As a side note: This issue has been discussed before because this isn't the only endpoint that behaves differently based on the version/type of Artifactory that's be targeted. Ideally it would fail before getting well into a plan, but documentation stating which resources are supported and on what version, doesn't exist, and thus implementing any code to figure that out would be just guessing.

**Comment by mdb** [comment]
> Ideally it would fail before getting well into a plan

I agree. In theory, resources and/or data sources could dynamically determine the version/type of Artifactory targeted and error accordingly if/when used with an incompatible version/type. However, I also think it's important to denote such incompatibilities in documentation.

Also, in my case, the property sets were somehow correctly created, despite the `artifactory/api/system/configuration` 400s, which raises other questions for me.

**Comment by chb0github** [comment]
@alexhung - what if you somehow added call home instrumentation that would passively report these endpoints as they are discovered by clients?
