### ISSUE TITLE
Cannot specify port correctly

### ISSUE THREAD

**Issue by rtxtmardesen** [jfrog/terraform-provider-artifactory#554]
**Describe the bug**
When attempting to use http.my.domain.com:8080 (notice the nonstandard http port) I cannot connect. The error thrown: 
http://my.domain.com:8080/artifactory/api/repositories/Images": proxyconnect tcp: dial tcp :80: connectex: No connection could be made because the target machine actively refused it.

Which leads me to believe that its trying to connect to port 80.

- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform: 1.3.2.
- [ ] Your version of terraform provider: 6.16.0

**Expected behavior**

**Additional context**

**Comment by alexhung** [comment]
@rtxtmardesen Please provide an example of your HCL. Our team uses local Artifactory runnin in Docker container with custom port for development/testing and we have no problem.

**Comment by rtxtmardesen** [comment]
@alexhung thank you for the reply! I assume I am doing something wrong here:

`terraform {
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
      version = "6.16.0"
    }
  }
}

provider "artifactory" {
  url = "http://my.internal.domain.com:8082/artifactory"
  api_key = "reallylongstring"
  check_license = false
}`

It is also something to note, I am just trying to import objects right now. It is how I am testing to see if I can get a connection. The only thing that made me report the bug was that the error message had mentioned that it was getting rejected on port 80

**Comment by alexhung** [comment]
@rtxtmardesen I assume you have a proxy between Artifactory and your network boundary? If so, please make sure the proxy is not mapping port 8082 to 80. The error message suggests that's the case and Artifactory instance is refusing connection on port 80, which is correct.

**Comment by alexhung** [comment]
> ```
> terraform {
>   required_providers {
>     artifactory = {
>       source = "jfrog/artifactory"
>       version = "6.16.0"
>     }
>   }
> }
> 
> provider "artifactory" {
>   url = "http://my.internal.domain.com:8082/artifactory"
>   api_key = "reallylongstring"
>   check_license = false
> }
> ```

This looks correct @rtxtmardesen 

FYI, the path `/artifactory` is unnecessary as the provider will only use the host portion of the URL.

**Comment by rtxtmardesen** [comment]
Thank you @alexhung, I am pretty sure that my networking is the culprit - I am trying now with the IP directly and the same issue persists. You were correct about the proxy as well, I don't think there is a mapping for our proxy but even if that is not the case, I would imagine its my networking. 

We have manually changed the port from 8080 to 8082, which I can verify that the API is queryable from that port. 

Thank you for the fast response, you can close this as my bad. I really appreciate the fast response!
