### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by aka-achea** [jfrog/terraform-provider-artifactory#562]
**Is your feature request related to a problem? Please describe.**
I'm not able to find a module for proxy in terraform

**Describe the solution you'd like**
I want to setup proxy setting with terraform in artifactory

**Comment by mcdonagj** [comment]
AFAIK, there isn't a Terraform resource for defining a proxy, but anyone can correct me if I'm mistaken.

Giving a +1 for this enhancement to be added; would be great to remove a manual step in my team's setup process -- we basically add a proxy manually to our Artifactory instance post-apply to cover the missing provider behavior.

**Comment by piotrminkina** [comment]
I join in the request. I am currently making up this deficiency by my own implementation of scripts in BASH using the "linyinfeng/shell" provider. This is not an expected option, but possible.
