### ISSUE TITLE
Support resolveDockerTagsByTimestamp for Docker virtual reporitories

### ISSUE THREAD

**Issue by jcoste-orange** [jfrog/terraform-provider-artifactory#563]
**Is your feature request related to a problem? Please describe.**
We can't set resolveDockerTagsByTimestamp on a Docker virtual repository today.

**Describe the solution you'd like**
Add a field resolveDockerTagsByTimestamp on a virtual docker repository

Thanks

**Comment by danielmkn** [comment]
@jcoste-orange it's released in v6.19.0, thanks!

**Comment by jcoste-orange** [comment]
Thank you to you @danielmkn.
