### ISSUE TITLE
Backup cron expression fails validation

### ISSUE THREAD

**Issue by bmanuel** [jfrog/terraform-provider-artifactory#564]
**Describe the bug**
When copying the default cron expression for daily backups from Artifactory and running `terraform validate`, a failure occurs on the date field.

**Expected behavior**
`terraform validate` passes with no reported issues.

**Additional context**
Provider version: 6.16.4

Sample resource:
```
resource "artifactory_backup" "daily" {
  key      = "backup-daily"
  enabled  = true
  cron_exp = "0 0 2 ? * MON-SAT"
}
```

Validation output:
```
│ Error: Invalid Cron expression
│
│   with artifactory_backup.daily,
│   on main.tf line 132, in resource "artifactory_backup" "daily":
│  132:   cron_exp = "0 0 2 ? * MON-SAT"
│
│ 0 0 2 ? * MON-SAT is not a valid cron: syntax error in year field: 'MON-SAT'
```
Note the error is for the year field. The validator seems to be parsing the expression into fields incorrectly.

**Comment by danielmkn** [comment]
@bmanuel, the cron expression you use is not correct. The provider uses https://github.com/gorhill/cronexpr to verify cron expression. 
In your case, you're missing a year field, it should be like this `0 0 2 ? * MON-SAT *`, then `terraform verify` will pass. 
The format is as following - `Minutes, Hours, Day of Month, Month, Day of Week, Year`. You need to use all the fields, starting with minutes, if not, replace them with *.

**Comment by bmanuel** [comment]
@danielmkn is there any documentation that shows that the provider expects a year given that all of the Artifactory documentation leaves that field out?

**Comment by danielmkn** [comment]
@bmanuel, this resource uses the [configuration call](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration#ArtifactoryYAMLConfiguration-ServiceConfigurations(Backups,MavenIndexer)), which is not very well documented, so there are no cron format examples.  

The thing is, if I remove the verification, the API takes any string as a cron expression, and the backup settings will be broken. I see the same behavior in the UI as well. 
In the [documentation](https://www.jfrog.com/confluence/display/JFROG/Backups) I see this description for the field: 
```
A valid CRON expression that you can use to control backup frequency. For example, to back up every 12 hours use a value of: 0 0 /12 * * ?
```
The cron expression there is not correct, unfortunately.
I think, the best we can get in the provider, is use this [verification module](https://github.com/gorhill/cronexpr), please, refer to the [documentation](https://chromium.googlesource.com/external/github.com/gorhill/cronexpr/+/d520615e531a6bf3fb69406b9eba718261285ec8/README.md). 

I'll add this information to the field description.
