### ISSUE TITLE
Resource artifactory_remote should support remote_repo_layout_ref attribute

### ISSUE THREAD

**Issue by Xaviou1003** [jfrog/terraform-provider-artifactory#568]
**Is your feature request related to a problem? Please describe.**
I want to use the resource artifactory_remote_vcs_repository to manage github repositories. 
To have a "pretty" internal layout, I want to have a different layout between  repo_layout_ref and remote_repo_layout_ref.
There is a [comment ](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/remote#remote_repo_layout_ref)for remote_repo_layout_ref attribute in documentation:
_Deprecated field. This field has currently no effect, because there is no corresponding field in the API body, and it's not returned by the GET call._

**Describe the solution you'd like**
The field must have an effect on the generated remote repository.
API body must have this field.

**Describe alternatives you've considered**
Actually I can change the remote layout manually with artifactory ui but it can't be a long term solution

Regards

**Comment by danielmkn** [comment]
@Xaviou1003, thank you for the ticket. We can't fix that on the Provider side, but we have an internal ticket for the Artifactory team to fix that. Currently, we don't have any ETA.

**Comment by danielmkn** [comment]
@Xaviou1003, @alexhung I see that `remote_repo_layout_ref` bug is fixed in Artifactory 7.47.0. Once it's released, we need to test and remove the deprecation notice.
