### ISSUE TITLE
Add missing virtual repos for cargo, and vagrant

### ISSUE THREAD

**Issue by rinconjc** [jfrog/terraform-provider-artifactory#570]
The virtual repository resource for cargo and vagrant are missing. I've tried to use the virtual generic for existing repositories, but Artifactory failed with:

```
│ Error: 
│ 400 POST https://<artifactory>/artifactory/api/repositories/<cargo-repo>
 {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "Changing a repository's type once it's set is not supported"
│   } ]
│ }
```

**Describe the solution you'd like**
Support virtual repository resources for cargo and vagrant:
artifactory_virtual_cargo_repository
artifactory_virtual_vagrant_repository

**Describe alternatives you've considered**
I tried to use the `virtual_generic` but it failed when applying the changes. Also it seems this doesn't allow setting the `package_type`, which would be useful to avoid the above error

**Additional context**
This is part of a painful migration from the version 2+ where generic resources matched pretty much the Artifactory REST API.

**Comment by danielmkn** [comment]
@rinconjc, thanks for the ticket! I'll add the missing repos soon. Can you please explain, what do you mean by `...generic resources matched pretty much the Artifactory REST API`? What doesn't match now?

**Comment by danielmkn** [comment]
Hmm, @rinconjc virtual Cargo and Vagrant repositories are not supported by Artifactory. See the list of supported repositories in 7.46.8:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/55418063/197898831-d6769ce8-3462-4918-a1f8-be6043325092.png">

**Comment by rinconjc** [comment]
Hi @danielmkn thanks for your quick reply :)
  
Sorry, that might have sounded as a criticism :( What I meant is that there's only 1 Artifactory API endpoint to create all the repository types, and the earlier provider version (2+) also had only one resource, so we were able to reuse quite a lot. On the plus side, I understand that now there's more strict validation in Terraform side.

**Comment by rinconjc** [comment]
Hi @danielmkn right I see that now. Hmm I'm guessing the API allows creating virtual repos for cargo and vagrant, and that's how the previous provider version managed to create the virtual repos for them. :(

**Comment by danielmkn** [comment]
The provider is reflecting the behavior you see in the UI, so I'd rather not try to create repos you don't see there :)

**Comment by rinconjc** [comment]
@danielmkn  The docs here https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/virtual.md, mention explicitly:  

> Arguments have a one to one mapping with the [JFrog API](https://www.jfrog.com/confluence/display/RTF/Repository+Configuration+JSON). The following arguments are supported: ...

And in the above configuration, cargo and vagrant are really supported in the packageType for virtual repository configuration:
```
application/vnd.org.jfrog.artifactory.repositories.VirtualRepositoryConfiguration+json
...
  + "packageType": "alpine"|"cargo"|"composer"|"bower"|"chef"|"cocoapods"|"conan"|"cran"|"debian"|"docker"|"helm"|"gems"|"gitlfs"|"go"|"gradle"|"ivy"|"maven"|"npm"|"nuget"|"opkg"|"pub"|"puppet"|"pypi"|"rpm"|"sbt"|"swift"|"terraform"|"vagrant"|"yum"|"generic" (default)   
```

Alternatively, if the UI is to be taken as the reference, then maybe the docs should also be updated to avoid confusion (and false expectations)

Thanks

**Comment by danielmkn** [comment]
Yes, you're right. I'll figure out the truth and update here.

**Comment by danielmkn** [comment]
Hi @rinconjc! The API documentation has been updated! Cargo and Vagrant repos are removed now, because they are not supported.
