### ISSUE TITLE
Expired/revoked scoped token causes fatal error

### ISSUE THREAD

**Issue by chrisa-arm** [jfrog/terraform-provider-artifactory#576]
**Describe the bug**
If the `artifactory_scoped_token` resource is used to generate a scoped token, and that token either expires (and then expunged by Artifactory) or is revoked manually outside of Terraform, when you next run the Terraform code it fails with a fatal error due to the 404 response from the API:
```
│ Error:
│ 404 GET https://artifactory.redacted.com/access/api/v1/tokens/62b1a58c-6bbc-4772-b4c4-6dd260392bb5
│ {"errors":[{"code":"NOT_FOUND","detail":"Not Found","message":"HTTP 404 Not Found"}]}
│
│   with artifactory_scoped_token.this,
│   on main.tf line 16, in resource "artifactory_scoped_token" "this":
│   44: resource "artifactory_scoped_token" "this" {
```

The only workaround is to use `terraform state rm` to manually remove the resource from the Terraform state.

**Expected behavior**
The provider should fail gracefully and treat the 404 response as the resource no longer exists; ie. recreate on apply, or ignore on destroy.

**Additional context**
Terraform version: 1.3.1
Provider version: 6.19.0
Artifactory version: 7.41.12

Example code:
```
terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "~> 6.19.0"
    }
  }
}

variable "username" {
  type = string
}

provider "artifactory" {}

resource "artifactory_scoped_token" "this" {
  username   = var.username
  expires_in = 300
}
```

**Comment by alexhung** [comment]
@chrisa-arm Thanks for the report. We'll look into this.
