### ISSUE TITLE
Add support for disable_ui_access in resource artifactory_anonymous_user

### ISSUE THREAD

**Issue by piotrminkina** [jfrog/terraform-provider-artifactory#577]
**Is your feature request related to a problem? Please describe.**
I'm using Artifactory 7.41.7. I noticed that Artifactory allows me to disable UI access for an anonymous user, but your Terraform provider doesn't have this capability implemented in the `artifactory_anonymous_user` resource.

**Describe the solution you'd like**
To make the following syntax possible.

```hcl
resource "artifactory_anonymous_user" "anonymous" {
  disable_ui_access = true
}
```

**Describe alternatives you've considered**
Currently changing option manually after provisioning Artifactory.

**Additional context**
Screenshot from page in path `/ui/admin/management/users/anonymous/edit`:

![image](https://user-images.githubusercontent.com/2574153/200852915-62d177c2-7c1e-4788-b4b1-1b1dc3b8a067.png)

**Comment by alexhung** [comment]
@piotrminkina The `artifactory_anonymous_user` resource doesn't support creation/update/deletion of the resource. Are you requesting this additional attribute to avoid state drift?

**Comment by piotrminkina** [comment]
Hello @alexhung 

Thanks for reply. In simple words, I want to manage the state of the "Set the Login page as the start page" field for the existing "anonymous" user. Of course first I need import existing "anonoymous" user to be managed by Terraform, then I will can change it's state.

From another side, I noticed that I can manage the state of this field via resource "artifactory_user", as follows:

```hcl
resource "artifactory_user" "anonymous" {
  name              = "anonymous" # this is default
  email             = "anonymous@example.com" # this is required by resource, but I don't want change this field
  admin             = false # this is default
  disable_ui_access = true # this is what I want to set up
  profile_updatable = false # this is default

  lifecycle {
    ignore_changes = [
      email
    ]
  }
}
```

![Screenshot from 2022-11-10 12-46-38](https://user-images.githubusercontent.com/2574153/201083160-8f7f0c26-b2ea-41d6-b441-739e0bdfb2b4.png)
![Screenshot from 2022-11-10 12-48-18](https://user-images.githubusercontent.com/2574153/201083161-444ce0f9-b7b0-4afe-b1c3-189ef766e8bd.png)

**Comment by alexhung** [comment]
@piotrminkina That's correct, `artifactory_anonymous_user` is not designed/intended to be used to manage anonymous user account. As you find out, you can use `artifactory_user` resource for that purpose.

**Comment by piotrminkina** [comment]
Could You document this use case for future users? In my opinion `artifactory_anonymous_user` resource sounds natural for manage state of _anonymous_ user, but as see above, for this purpose better will be `artifactory_user` resource. I think it would be useful to have some example in the documentation for managing the state of an anonymous user.

Regards
Piotr Minkina

**Comment by alexhung** [comment]
@piotrminkina We will add the recommendation to the documentation. The limitation is already in the [resource documentation](https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/anonymous_user.md?plain=1#L22) but it can be made more prominent.
