### ISSUE TITLE
resource.repo.repositories is not optional

### ISSUE THREAD

**Issue by renan-alm** [jfrog/terraform-provider-artifactory#583]
**Describe the bug**
When creating artifactory_permission_target, it is not possible to make this permission applicable to Any local/remote/distribution repository, like it is possible through the UI. 

Artifactory Version: 7.46.11
Terraform Version: 1.3.4
Artifactory Provider Version: 6.19.2

Code snippet:
````
resource "artifactory_permission_target" "deploy_permission" {
  name = "deploy-permission"

  repo {
    includes_pattern = ["**"]

    actions {
      groups {
        name        = "name"
        permissions = ["read", "write", "annotate", "managedXrayMeta"]
      }
    }
  }

  build {
    includes_pattern = ["**"]
    actions {
      groups {
        name        = "name"
        permissions = ["read", "write", "annotate", "managedXrayMeta"]
      }
    }
  }
}
````
Outcome:
```
╷
│ Error: Missing required argument
│ 
│   on permissions.tf line 4, in resource "artifactory_permission_target" "deploy_permission":
│    4:   repo {
│ 
│ The argument "repositories" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on permissions.tf line 15, in resource "artifactory_permission_target" "deploy_permission":
│   15:   build {
│ 
│ The argument "repositories" is required, but no definition was found.
╵
```

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
According to the documentation, one is supposed to be able to omit `repositories` field. 
https://github.com/jfrog/terraform-provider-artifactory/blob/master/docs/resources/permission_target.md?plain=1#L67

**Comment by alexhung** [comment]
@renan-alm Looks like the documentation is incorrect. The [Artifactory JSON schema](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json) shows `repositories` is a required field.

**Comment by stasostrovskyi** [comment]
@alexhung Is there a way to set `repositories` to mimic UI option `Any Local Repostiory` or `Any Remote Repository`?

**Comment by alexhung** [comment]
@stasostrovskyi Per the [API schema documentation](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json), you can use `ANY`, `ANY_LOCAL`, `ANY_REMOTE` in the `repositories` attribute.

```json
{
    "name": "alex-test",
    "repo": {
        "actions": {},
        "repositories": [
            "ANY LOCAL",
            "ANY REMOTE"
        ],
        "include-patterns": [
            "**"
        ],
        "exclude-patterns": []
    }
}
```

**Comment by alexhung** [comment]
Closed by mistake.

**Comment by stasostrovskyi** [comment]
@alexhung Thank you for a quick answer!
