### ISSUE TITLE
cron_exp not in line with Artifactory's UI.

### ISSUE THREAD

**Issue by anderson-bomfim** [jfrog/terraform-provider-artifactory#591]
Terraform Version: v1.1.9
Artifactory Version:  7.18.5
Provider Version: v6.20.2
Resource: artifactory_pull_replication

When trying to set a value for cron_exp on the pull replication resource on Terraform, the same value that is accepted on the UI is not acceptable by Terraform/Artifactory provider.

For example, the Cron expression `0 15 10 ? * 6#2` is accepted by Artifactory UI but fails during the Terraform Plan with:

```
Error: Invalid Cron expression 
│ 
│   with artifactory_pull_replication.*********,
│   on artifactory.tf line 664, in resource "artifactory_pull_replication" "*********:
│  664:     cron_exp                 = "0 15 10 ? * 6#2"
│ 
│ 0 15 10 ? * 6#2 is not a valid cron: syntax error in year field: '6#2'
```

The cron_exp field can not be left empty as its required, but no further explanation is provided in the official documentation (https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/pull_replication#cron_exp)

**Comment by alexhung** [comment]
Related to https://github.com/jfrog/terraform-provider-artifactory/issues/564

**Comment by danielmkn** [comment]
The Cron validation behavior for all replications is changed in v6.24.1
