### ISSUE TITLE
Migration to the provider should be possible

### ISSUE THREAD

**Issue by nrowealign** [jfrog/terraform-provider-artifactory#592]
We have a fairly large existing set of repositories that we're hoping to codify into TF using this provider. When using `terraform plan` to verify that we've codified them correctly, the provider sees existing repositories as "new" and then fails to create them if `terraform apply` is run.

Steps to reproduce:

1. Create a repo using the Artifactory UI that matches the below TF snippet
2. Add this TF snippet to your TF setup for that Artifactory instance
3. Run `terraform plan` and see that it thinks it will create the repo as new
4. Run `terraform apply` and watch it get a 400 error because that repo already exists

```
resource "artifactory_remote_bower_repository" "bower-proxy-github" {
  key = "bower-proxy-github"
  url = "https://github.com/"
  includes_pattern = "**/*"
  repo_layout_ref = "bower-default"
  download_direct = "false"
  priority_resolution = "false"
  retrieval_cache_period_seconds = 60
  xray_index = "false"
}
```

Artifactory version 7.46.10
Terraform version 1.2.5
Provider version 6.20.1

**Expected behavior**
The provider should discover existing entities so that migration to the provider is possible.

**Additional context**
I opened JFrog ticket 227306 and they referred me here. I spoke with our Enterprise Solutions Lead and he said that this provider was fully supported under our support contract. Please let me know if that's not the case or if you need any additional information from me. Thanks!

**Comment by alexhung** [comment]
@nrowealign Terraform does not support discovery of existing resources. To synchronize between the HCL and your infrastructure, you need to import each resource. See [this tutorial](https://developer.hashicorp.com/terraform/tutorials/state/state-import) for more details. We have plan to create a separate tool to generate HCL from existing infrastructure but that's in the future.

**Comment by danielmkn** [comment]
The ID could be `name` or `key` of the resource. For example, if the resource looks like this:
```
resource "artifactory_federated_nuget_repository" "terraform-federated-test-nuget-repo" {
  key       = "federated-test-nuget-repo"
}
```
The import command will be like this: 
```
terraform import artifactory_federated_nuget_repository.terraform-federated-test-nuget-repo federated-test-nuget-repo
```
