### ISSUE TITLE
Imported Federated maven repositories lose values and don't seem to be aware of the currrent state

### ISSUE THREAD

**Issue by nrowealign** [jfrog/terraform-provider-artifactory#593]
**Describe the bug**
Imported Federated Maven repositories don't retain maven-specific fields

**Requirements for and issue**
I imported all of our Federated repositories and when I "terraform plan" all of the Maven repositories are staged for modification to return the Maven-specific (checksum_policy_type, handle_releases, handle_snapshots, etc) values to the defaults. The correct values were not recorded in the import.

Here is the output of "terraform show" after the import
```
# artifactory_federated_maven_repository.maven-thirdparty-local:
resource "artifactory_federated_maven_repository" "maven-thirdparty-local" {
    archive_browsing_enabled = false
    blacked_out              = false
    download_direct          = false
    id                       = "maven-thirdparty-local"
    includes_pattern         = "**/*"
    key                      = "maven-thirdparty-local"
    package_type             = "maven"
    priority_resolution      = false
    project_environments     = []
    property_sets            = [
        "artifactory",
    ]
    repo_layout_ref          = "maven-2-default"
    xray_index               = false

    member {
        enabled = true
        url     = "https://repo1.mysite.com/artifactory/maven-thirdparty-local"
    }
    member {
        enabled = true
        url     = "https://repo2.mysite.com/artifactory/maven-thirdparty-local"
    }
}
```

This is the config in the .tf file with the corrected values:
```
# artifactory_federated_maven_repository.maven-thirdparty-local:
resource "artifactory_federated_maven_repository" "maven-thirdparty-local" {
    archive_browsing_enabled  = false
    blacked_out               = false
    download_direct           = false
    includes_pattern          = "**/*"
    key                       = "maven-thirdparty-local"
    priority_resolution       = false
    property_sets             = [
        "artifactory",
    ]
    repo_layout_ref           = "maven-2-default"
    snapshot_version_behavior = "non-unique"
    xray_index                = false

    member {
        enabled = true
        url     = "https://repo1.mysite.com/artifactory/maven-thirdparty-local"
    }
    member {
        enabled = true
        url     = "https://repo2.mysite.com/artifactory/maven-thirdparty-local"
    }
}
```

Note that without that config, the value for snapshot_version_behavior was going to revert to the default of "unique." This is true for all of our Federated Maven repositories and all of the Maven-specific values.

And here is an example of the "terraform plan" output
```
  # artifactory_federated_maven_repository.maven-thirdparty-local will be updated in-place
  ~ resource "artifactory_federated_maven_repository" "maven-thirdparty-local" {
      + checksum_policy_type            = "client-checksums"
      + handle_releases                 = true
      + handle_snapshots                = true
        id                              = "maven-thirdparty-local"
      + max_unique_snapshots            = 0
      + snapshot_version_behavior       = "non-unique"
      + suppress_pom_consistency_checks = false
        # (11 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

Artifactory version 7.46.10.
Terraform version 1.2.5
Provider version 6.20.1

**Expected behavior**
Imported Federated Maven repos should retain their configuration without the need for manual adjustment. Also even with the configuration fixed to match production, "terraform plan" thinks it still needs to modify.

**Additional context**

**Comment by alexhung** [comment]
@nrowealign thanks for the detailed info. @danielmkn and I will investigate. From first glance, this does look like a bug but we'll keep you updated as we find out more.

**Comment by nrowealign** [comment]
For our planning, should we expect the above patch to be in a release by the end of this calendar year?

**Comment by alexhung** [comment]
@nrowealign The PR is merged and the binary should be on Terraform registry soon.

**Comment by nrowealign** [comment]
@alexhung thanks. what will the version # be?

**Comment by alexhung** [comment]
@nrowealign [6.21.4](https://registry.terraform.io/providers/jfrog/artifactory/6.21.4)

**Comment by nrowealign** [comment]
Thanks. Seeing this when trying to import: Error: unknown resource type: artifactory_federated_docker_repository

Do you want another issue for it?

**Comment by alexhung** [comment]
There are 2 federated docker resource, one for v1 and one for v2. This mirrors the local resources.

**Comment by alexhung** [comment]
I also forgot to provider an alias for `artifactory_federated_docker_repository` to `artifactory_federated_docker_v2_repository`. A patch release will be coming later today or early tomorrow. Sorry about this.

**Comment by nrowealign** [comment]
No problem. Thanks for the quick turn-around.

**Comment by alexhung** [comment]
@nrowealign The fixed is released as https://registry.terraform.io/providers/jfrog/artifactory/6.21.6

**Comment by nrowealign** [comment]
@alexhung thanks again. FYI everything looks great except we're seeing `retrieval_cache_period_seconds` on NPM virtual repos get `plan`ed for update to the existing value as was happening with the Maven values when I opened this issue.

**Comment by nrowealign** [comment]
One other issue. We have a nuget remote that doesn't have a `v3_feed_url` and the provider fills in an incorrect default value (`https://api.nuget.org/v3/index.json`) for it. I'm looking to see if this provider has a v3 url, but if not, it should not provide a default, I think.
