### ISSUE TITLE
artifactory_keypair tries update immutable resource

### ISSUE THREAD

**Issue by piotrminkina** [jfrog/terraform-provider-artifactory#594]
I manage the GPG keys using the resource `artifactory_keypair`, as follows:

```hcl
resource "artifactory_keypair" "artifactory_gpg" {
  pair_name   = "artifactory-gpg"
  pair_type   = "GPG"
  alias       = "artifactory"
  private_key = file(var.gpg_key_file)
  public_key  = file(var.gpg_pub_file)
}
```

Such a definition registered the new GPG key in Artifactory as expected. I then wanted to set the password to an already existing key, as follows:

```hcl
resource "artifactory_keypair" "artifactory_gpg" {
  # ... previous code here ...
  # You have to set a password for the GPG keys, even though these keys are not
  # password protected.
  # See below links for details about issues:
  # - https://jfrog.atlassian.net/browse/RTFACT-25704
  # - https://jfrog.atlassian.net/browse/RTFACT-25534
  passphrase = "fake-passwd"
}
```

According to Terraform Plan, there should be an attempt to complete the password to the already existing GPG key, but Terraform Apply ends with an error, as in the screenshot below.

![Screenshot from 2022-12-05 15-20-28](https://user-images.githubusercontent.com/2574153/205663668-5208193a-517e-4f7a-a37f-392c51323333.png)

I believe that the resource `artifactory_keypair` should force the deletion first and then the addition of this GPG key anew. Likewise, in the WebUI Artifactory it is no possible to change the GPG key once added.

In order to make this change, I had to first remove the GPG key from the WebUI Artifactory, then from the tfstate file. Only then could I execute Terraform Apply to add the key as a new one.

I don't know if this is the expected behaviour, but when I removed only the key from the WebUI, but left it in the tfstate file, I got this error with Terraform Plan:

![Screenshot from 2022-12-05 15-22-08](https://user-images.githubusercontent.com/2574153/205664824-97ca03ff-95b8-4def-8ada-1108ada7244d.png)

**Addidional details**
Platform: Ubuntu GNU/Linux
Terraform Version:: 1.2.9
Provider Version: 6.20.2
Artifactory Version: 7.47.10

**Comment by alexhung** [comment]
@piotrminkina 

> I believe that the resource artifactory_keypair should force the deletion first and then the addition of this GPG key anew.

We can update the `passphrase` attribute to do this.

When you change/remove a resource *outside* of Terraform, this causes a state drift. The error you see is a bug and will be fixed.

In general, please avoid changing resources outside of Terraform to avoid this kind of situation. There're times when that's not possible and in those cases, you need to manage the Terraform state carefully.
