### ISSUE TITLE
Provider does not clear some fields as planned

### ISSUE THREAD

**Issue by piotrminkina** [jfrog/terraform-provider-artifactory#595]
I have problem with fields _description_ and _username_ (I did not examine the other fields) in all repositories. I set a value for these fields in WebUI, then ran Terraform Plan. Terraform detected differences in state, well it wants to restore it, as follows:

```
  # artifactory_virtual_pypi_repository.pypi_snapshot will be updated in-place
  ~ resource "artifactory_virtual_pypi_repository" "pypi_snapshot" {
      - description                                        = "a" -> null
        id                                                 = "pypi-snapshot"
        # (9 unchanged attributes hidden)
    }
  # artifactory_remote_rpm_repository.rpm_remote will be updated in-place
  ~ resource "artifactory_remote_rpm_repository" "rpm_remote" {
        id                                    = "rpm-remote"
      - username                              = "a" -> null
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Finally, I ran Terraform Apply, which was successful, but unfortunately the value of these fields was not cleared. A subsequent call to Terraform Plan shows the same results as before Terraform Apply.

**Addidional details**
Platform: Ubuntu GNU/Linux
Terraform Version:: 1.2.9
Provider Version: 6.20.2
Artifactory Version: 7.47.10

**Comment by danielmkn** [comment]
@piotrminkina, it's fixed in v6.23.0, #616
