### ISSUE TITLE
artifactory_user resource is not storing generated password in the TF state

### ISSUE THREAD

**Issue by alexhung** [jfrog/terraform-provider-artifactory#602]
**Describe the bug**

From discussion https://github.com/jfrog/terraform-provider-artifactory/discussions/598

`artifactory_user` resource is not storing generated password in the TF state.

**Expected behavior**

TF state should contain the auto-generated password.

**Additional context**

Fix is to move the password generation code from the create context func to unpacking func.

**Comment by danielmkn** [comment]
I've deprecated the resource since we can't store the generated password in the state due to SDKv2 limitations.
