### ISSUE TITLE
Cannot manage group level boolean attributes

### ISSUE THREAD

**Issue by varunthakur2480** [jfrog/terraform-provider-artifactory#61]
**Describe the bug**
As of now the only attribute that is supported at group resources is **admin_privileges**, in last some releases Jfrog has added a number of other attributes to the group , this includes 
Manage resources
Manage policies
Manage watches 
and Manage Reports 
With these options not available it is very difficult the mange groups (some settings being manual) 
**Requirements for and issue**

- [7.15.3 ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ .12] Your version of terraform

**Expected behavior**
Provider should give options to set other boolean properties for groups and ditto for users
**Additional context**

**Comment by chb0github** [comment]
Ackowledged. I can't promise when we can get to this. Hopefully others can upvote this

**Comment by chb0github** [comment]
So, can you supply me some free form HCL you think would work? This question is very open-ended. The more specific, the more likely to be implemented.

**Comment by chb0github** [comment]
No response in 10 days. Closing
