### ISSUE TITLE
jfrog/artifactory does not support resource type "artifactory_local_generic_repository

### ISSUE THREAD

**Issue by reddychenna** [jfrog/terraform-provider-artifactory#615]
**Describe the bug**
I am getting this error when I try to create and apply simple TF script to create generic repo "The provider jfrog/artifactory does not support resource type "artifactory_local_generic_repository" "

Terraform version and provider version : 

-     Terraform v1.3.6    on windows_386
-     + provider registry.terraform.io/jfrog/artifactory v2.6.17
-     Artifactory version 7.47.12 ( SaaS version with E+ license) 

Additional Context : 
 I get same error for almost all repo types , fortunately artifactory_user is the only resource working for me.

Sample Terraform script 
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "2.6.17"
    }
  }
}
# Configure the Artifactory provider
provider "artifactory" {
  url           = "https://xyz.jfrog.io/artifactory"
   access_token = "*********"
}

resource "artifactory_local_generic_repository" "terraform-local-test-generic-repo" {
  key = "terraform-local-test-generic-repo"
}

**Comment by alexhung** [comment]
@reddychenna I notice you are using version 2.6.17 of the provider. Is there particular reason for this? 

`artifactory_local_generic_repository` was added in 2.6.19.

**Comment by reddychenna** [comment]
@alexhung thanks , that works with 2.6.19 .  No specific need for 2.6.17 , just picked an example from documentation which has provider version 2.6.17

**Comment by alexhung** [comment]
@reddychenna Good to know. If you are starting fresh using Terraform with Artifactory, please use the latest version which is v6.22.2

**Comment by reddychenna** [comment]
Sure, thanks.
