### ISSUE TITLE
Missing detailed description of managed vs unmanaged vs user resource

### ISSUE THREAD

**Issue by mruepp** [jfrog/terraform-provider-artifactory#619]
**Is your feature request related to a problem? Please describe.**
In the provider documentation, the three resources:
[artifactory_user](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/user)
[artifactory_unmanaged_user](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/unmanaged_user)
[artifactory_managed_user](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/managed_user)

are nearly identical. Is there any detailed description of what is the difference of these three resources?

**Describe the solution you'd like**
Detailed documentation of the three resources including their counterpart on the jfrog platform side.
AFAIK on jfrog, only the "user" resource is existing and the password never returns:
https://www.jfrog.com/confluence/display/JFROG/JFrog+Platform+REST+API#JFrogPlatformRESTAPI-Users

**Comment by slzmruepp** [comment]
Could someone quickly enlighten me? I have to proceed and dont know which one I should pick. Thank you!

**Comment by alexhung** [comment]
@slzmruepp FYI, there was a long discussion last year when the original `artifactory_user` resource was split up: https://github.com/jfrog/terraform-provider-artifactory/discussions/333#discussioncomment-2473565

**Comment by danielmkn** [comment]
@mruepp, released in v6.24.3
