### ISSUE TITLE
Support for priority resolution in local and remote repositories

### ISSUE THREAD

**Issue by thor** [jfrog/terraform-provider-artifactory#62]
Per https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON and the updated REST API following from Artifactory 7.16, I'd like to request (and possibly implement) [support for priority resolution for local and remote repositories](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-AvoidingSecurityRisksbyFlaggingSafeRepositories).

Are there any particular considerations to keep in mind if I want to implement this? Would a pull request for such a change be desired? I'd love to help if possible.

**Comment by chb0github** [comment]
Which particular repo type did you want to use this with? It's not supported by all repo types.

**Comment by thor** [comment]
>
> Which particular repo type did you want to use this with? It's not
> supported by all repo types.
>

I want to use it with our local Docker, pip and npm repositories. I don't
currently imagine the support for adding remote repositories will be
important for us, so if it would be better to limit it to the local
repository resource first then that sounds good to me. What do you think?

**Comment by chb0github** [comment]
I am happy to discuss the contours of the changes. We have a gitter channel or we can discuss here

**Comment by zymzxq** [comment]
> Which particular repo type did you want to use this with? It's not supported by all repo types.

Ideally the provider should be consistent with what Artifactory supports

**Comment by chb0github** [comment]
@zymzxq  ideally. But, for a lot of reasons, it isn't/can't be.

**Comment by chb0github** [comment]
You can submit a pr @thor
