### ISSUE TITLE
Add User/Groups/Roles to Projects

### ISSUE THREAD

**Issue by slzmruepp** [jfrog/terraform-provider-artifactory#625]
**Is your feature request related to a problem? Please describe.**
Since recently, artifactory sports the concept of "Projects". How can I manage projects and project resources with terraform?
We use an artifactory project for each software project internally to segregate blast radius and keep things in order.
Also access to the projects is on a need to know basis and the technical users we use in the certain k8s namespaces for example are scoped to certain projects.

We wanna manage this through terraform. Is this currently possible? Are there workarounds existing if this is not supported now? Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexhung** [comment]
@slzmruepp We have a separate [provider for Project](https://registry.terraform.io/providers/jfrog/project/latest). If you have any question or feature request, you can post to the [GitHub project](https://github.com/jfrog/terraform-provider-project).

**Comment by slzmruepp** [comment]
Thanks I realized this later on!
