### ISSUE TITLE
How can I create an encrypted scoped token to use in my docker config?

### ISSUE THREAD

**Issue by slzmruepp** [jfrog/terraform-provider-artifactory#626]
**Is your feature request related to a problem? Please describe.**
In my terraform config I create a user, a permission target and then I create a scoped token for the user.
The permission target allows the user (which is a technical user) to read from a docker registry.

``` 
resource "artifactory_user" "jfrog_user" {
  name              = var.jfrog_user_name
  email             = var.jfrog_user_email
  groups            = var.jfrog_user_group
  disable_ui_access = var.jfrog_user_disable_ui
  profile_updatable = var.jfrog_user_profile_updatable
}

resource "artifactory_scoped_token" "jfrog_user" {
  username          = artifactory_user.jfrog_user.name
  refreshable       = var.jfrog_token_refreshable
  expires_in        = var.jfrog_token_expire //in seconds
}

resource "artifactory_permission_target" "jfrog_user" {
  name = var.jfrog_user_perm_name

  repo {
    includes_pattern = var.jfrog_user_perm_include
    excludes_pattern = var.jfrog_user_perm_exclude
    repositories     = var.jfrog_user_perm_repos

    actions {
      users {
        name        = artifactory_user.jfrog_user.name
        permissions = var.jfrog_user_perm
      }
    }
  }
}
```
Then I create a docker secret with the output in a kubernetes namespace:
```
output "jfrog_access_token" {
  value = artifactory_scoped_token.jfrog_user.access_token
  description = "Specifies the access token of the technical user"
}

output "jfrog_user_name" {
  value = artifactory_user.jfrog_user.name
  description = "Specifies the name of the technical user"
}

output "jfrog_user_id" {
  value = artifactory_user.jfrog_user.id
  description = "Specifies the id of the technical user"
}

output "jfrog_user_email" {
  value = artifactory_user.jfrog_user.email
  description = "Specifies the email of the technical user"
}
```
However, when I download the secret from the namespace, and decode it base64, I get the following error when I try a docker login:
```
docker login <myserver.jfrog.io>
Username: oc-user-int
Password: <base64 decoded access token>
Get "https://<myserver.jfrog.io>/v2/": unknown: Artifactory configured to accept only encrypted passwords but received a clear text password, getting the encrypted password can be done via the WebUI.
```

**Describe the solution you'd like**
I want to have the possibility to have an encrypted token return from the terraform provider to use in my config files.

**Describe alternatives you've considered**

**Additional context**

**Comment by mruepp** [comment]
Maybe I am just wrong in my approach: We currently use technical users to pull/push from our CI Pipelines. We disable local passwords and create identity tokens which works as passwords. This combination we use for our docker config.
So do I even have to create a scoped access token for this technical user? Is this even the identity token? And do I have to change the encrypted password policy in jfrog.io from "required" to "supported" to use these tokens/passwords unencrypted without the need to download them from the webui? Help appreciated, thanks!
