### ISSUE TITLE
Imported remote repositories don't maintain state for `remote_repo_layout_ref`

### ISSUE THREAD

**Issue by danielmkn** [jfrog/terraform-provider-artifactory#633]
See the [comment](https://github.com/jfrog/terraform-provider-artifactory/issues/605#issuecomment-1400806783) for #605.
We need to reproduce the issue first.

**Comment by danielmkn** [comment]
Fixed in 6.23.0

**Comment by nrowealign** [comment]
I'm using 6.24.2 and seeing items to be changed in `terraform plan` that reflect the current value for remote_repo_layout_ref.

# artifactory_remote_generic_repository.generic-proxy-microsoft-aws will be updated in-place
  ~ resource "artifactory_remote_generic_repository" "generic-proxy-microsoft-aws" {
        id                                    = "generic-proxy-microsoft-aws"
      + remote_repo_layout_ref                = "simple-default"
        # (29 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

this repo is already simple-default and the config also sets it to this value.

**Comment by danielmkn** [comment]
@nrowealign this is happening because the properties of the attribute were changed. Looks like there is no other way to make it work right, and there is no actual change made to the repository.
