### ISSUE TITLE
Project Key

### ISSUE THREAD

**Issue by mcaulifn** [jfrog/terraform-provider-artifactory#657]
**Describe the bug**
Artifactory 7.49.0 is supposed to support project keys up to 20.

```
Error: invalid value for key (project_key must be 2 - 10 lowercase alphanumeric and hyphen characters)
```

**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**
Allow project keys up to 20 for 7.49+

**Comment by alexhung** [comment]
@mcaulifn Thanks for the head up. We'll update the validation to match.
