### ISSUE TITLE
Remove ARTIFACTORY_API_KEY environment variable

### ISSUE THREAD

**Issue by jesseneal** [jfrog/terraform-provider-artifactory#663]
**Is your feature request related to a problem? Please describe.**
remove env ARTIFACTORY_API_KEY if we are supposed to use token now

**Describe the solution you'd like**
No more errors of "api_key": conflicts with access_token

**Describe alternatives you've considered**
I've tried unset env var of ARTIFACTORY_API_KEY but would feels unnecessary since this should be deprecated?

**Additional context**
none

**Comment by alexhung** [comment]
@jesseneal While the API key is deprecated, it has not been removed from Artifactory yet. So we will wait until it is removed from Artifactory before removing it from the provider.

**Comment by jesseneal** [comment]
Can some logic be wrapped around that if token is set then env isn't created? I don't have a way to unset that env var with how I'm really on some code I have to run but don't have access to in my CI.

**Comment by chb0github** [comment]
you'll also have those people who stay on some ancient version of Artifactory for years. You'd also need a deprecation plan in the provider. Or, you could just implement a tool @alexhung to migrate all their code 18 months later 🤣
