### ISSUE TITLE
Deleting `artifactory_proxy` or `artifactory_ldap_setting` resource outside of Terraform causes subsequent `terraform plan` to fail

### ISSUE THREAD

**Issue by 9numbernine9** [jfrog/terraform-provider-artifactory#665]
**Describe the bug**
If an `artifactory_proxy` or `artifactory_ldap_setting` resource is created via Terraform using the provider, then deleted manually through the Artifactory UI, subsequent attempts to `terraform plan` will complain that those resources no longer exist.

**Sample**

- Create the following resource;

```terraform
resource "artifactory_proxy" "proxy" {
  key = "myproxy"
  host = "myproxy.mydomain.com"
  port = "3128"
  platform_default = false
}
```

- Through the Artifactory UI, delete the `proxy` that was created.
- Now run `terraform plan` and observe the error.

**Artifactory Version**
`7.49.8`

**Terraform Version**
`1.3.9`

**Provider Version**
`6.29.1`

**Expected behavior**
Removing the resource outside of Terraform shouldn't cause a subsequent `terraform plan` to fail, and instead the Terraform state should be updated to reflect the removal of this resource.

**Additional context**
Example above is for `artifactory_proxy` but this same behaviour has been observed with `artifactory_ldap_setting` and `artifactory_ldap_group_setting` as well.

**Comment by alexhung** [comment]
@9numbernine9 If you manually remove *any* resources that are managed by Terraform, you should call `terraform refresh` to refresh Terraform's state with your latest infrastruture configuration. This will avoid state drift the next time you run `terraform plan` or `terraform apply`

See https://developer.hashicorp.com/terraform/tutorials/state/state-cli#refresh-modified-infrastructure

**Comment by 9numbernine9** [comment]
@alexhung It fails with `terraform refresh` and `terraform apply` as well. Additionally, the default behaviour of `terraform plan` is to refresh first before generating the plan. 

https://developer.hashicorp.com/terraform/cli/commands/plan#refresh-false

`apply` generates a plan, which ostensibly also does a `refresh` first too.

> If you are using Terraform directly in an interactive terminal and you expect to apply the changes Terraform proposes, you can alternatively run [terraform apply](https://developer.hashicorp.com/terraform/cli/commands/apply) directly. By default, the "apply" command automatically generates a new plan and prompts for you to approve it.

**Comment by alexhung** [comment]
@9numbernine9 

`terraform plan` or `terraform apply` will 'refresh' the state by reading from Artifactory what state of that resource. It uses the new state to determine what it should do to sync up with the infrastructure.

Therefore, after you manually deleted the proxy in Artifactory UI, Terraform will notice it is now gone and prompt you to create it the next time you run `terraform plan`. This is by design.

Also see: https://stackoverflow.com/questions/42628660/what-does-terraform-refresh-really-do

If you want to 'fix' this problem, you will need to manually remove that resource from Terraform state using `terraform state rm` command. Then once it is removed, you then remove the resource from your configuration file as well.

**Comment by alexhung** [comment]
You can also use `terraform apply -refresh-only` to sync up the state.

Regardless on how you remediate this state drift, it is not the responsibility of the provider to automatically do this for you.

**Comment by 9numbernine9** [comment]
@alexhung I think what's happening is that currently the `terraform plan` or `terraform apply` _can't_ get the state of the resource from Artifactory, which is what causes things to go awry. The resource has gone "missing" from the provider's perspective and I don't think it handles this case correctly, as least as far as the few resources that I mentioned so far are concerned.

If an explicit `terraform refresh` *is* required, then I think this would be a very different experience compared to any other Terraform provider that I've seen so far. If I contrast this with with something like `terraform-provider-aws` and follow the same pattern:

- Create a resource via Terraform, e.g. the following:
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.56.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  access_key = "access-key-goes-here"
  secret_key = "secret-key-goes-here"
}

resource "aws_s3_bucket" "bucket" {
  bucket = "mycoolbucket12345"
}
```
- Delete the bucket I just created via the AWS Console, i.e. outside of Terraform's knowledge
- Run another `terraform plan`

Then the behaviour is more along what I would expect: the `terraform plan` shows that it needs to create the bucket and no explicit `terraform refresh` is required - `terraform plan` takes care of any refresh necessary, which is what I would also expect in this provider with respect to `artifactory_proxy` and `artifactory_ldap_setting`.

**Comment by alexhung** [comment]
@9numbernine9 Yes I agree the provider should behave the same as the AWS provider as you described. Is it now happening? You did not provide any error message, if any. You specifically said:

> subsequent attempts to terraform plan will complain that those resources no longer exist.

Which is the same as what you mentioned above.

Please share the output from this provider so we are clear what we are dealing with.

**Comment by 9numbernine9** [comment]
@alexhung Will do! I'm away from my desk but will get back to you first thing Monday morning.

**Comment by alexhung** [comment]
@9numbernine9 I got a break in my work schedule just now and abled to reproduce the issue. Will add this to our sprint planning.

**Comment by 9numbernine9** [comment]
The fixed version works perfectly - thank you @alexhung !
