### ISSUE TITLE
Fetching artifacts fails

### ISSUE THREAD

**Issue by jesseneal** [jfrog/terraform-provider-artifactory#666]
**Describe the bug**
Fetching artifacts fails to url encode properly from ```/``` to ```%2f```

**Requirements for and issue**
```
Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: 
│ 400 GET https://artifactory/artifactory/api/storage/local/repo-file%2Fstuff.zip
```

```
data "artifactory_file" "lambda_stuff" {
  repository  = "repo-name"
  path        = "repo-file/stuff.zip"
  output_path = "${path.module}/tmp/file.zip"
}
```

**Expected behavior**
Artifact should be fetched

url encoding doesn't seem to be working properly for ```/``` and is returning %2f

provider version:  6.30.1
terraform version: 1.3.9

**Comment by alexhung** [comment]
@jesseneal Thanks for the report. Looks like we need to bypass the encoding of path characters.
