### ISSUE TITLE
Creating artifactory_scoped_token with any expires_in value < 10800 causes an error

### ISSUE THREAD

**Issue by watsonjm** [jfrog/terraform-provider-artifactory#684]
**Describe the bug**
Creating artifactory_scoped_token with any expires_in value greater than 0 and less than 10800 causes an error. Using 0 does work, but I don't want an access token forever.

**Requirements for and issue**
- [ ] A description of the bug
Attempting to create the artifactory_scoped_token.scoped_token always gives me the following error, except when `expires_in = 0`
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to artifactory_scoped_token.scoped_token, provider "provider[\"registry.terraform.io/jfrog/artifactory\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). 
```
resource "artifactory_user" "temp_user" {
  name              = "temp-user"
  email             = "temp-user@domain.com"
  profile_updatable = false
}

resource "artifactory_scoped_token" "scoped_token" {
  username    = artifactory_user.temp_user.name
  expires_in  = 3600
  scopes      = ["applied-permissions/user"]
}
```
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
"version" : "7.55.2",
- [ ] Your version of terraform
Terraform v1.3.9
on darwin_arm64
- [ ] Your version of terraform provider
provider registry.terraform.io/jfrog/artifactory v7.1.1

**Expected behavior**
I expect Terraform to be able to create artifactory_scoped_token that expires in 3600 seconds instead of erroring out.

**Additional context**
The access token used in my provider is an admin token with access limited to artifactory

**Comment by alexhung** [comment]
@watsonjm So this is caused by Artifactory's [Persistency Threshold](https://www.jfrog.com/confluence/display/JFROG/Access+Tokens#AccessTokens-PersistencyThreshold) which defaults to 10800 seconds.

I'm updating the provider to display warnings when it runs into token that hits this condition.
