### ISSUE TITLE
v2.2.8 prevents use of conda repositories

### ISSUE THREAD

**Issue by nickwilliams-codynamic** [jfrog/terraform-provider-artifactory#69]
https://github.com/jfrog/terraform-provider-artifactory/blob/2517982102382992a90514bc5317da39ac62224e/pkg/artifactory/resource_artifactory_remote_repository.go#L37

After upgrading to v2.2.8 my terraform plans now fail as I have a conda remote. Seemingly because this is missing from the new validate method.
https://www.jfrog.com/confluence/display/JFROG/Conda+Repositories

My terraform configuration looks like this:
```
resource "artifactory_remote_repository" "conda_remote" {
  ...
  type    = "conda"
  url       = "https://repo.anaconda.com/pkgs/main/"
  layout = "simple-default"
  ...
}
```

**Comment by chb0github** [comment]
looks like you found a gap in our documentation, which bled into the code - I'll have a new version out today

**Comment by nickwilliams-codynamic** [comment]
Awesome, thanks. Let me know if you need me to raise a PR myself. I just wasn't sure where to get a definitive list of repo types to check against.

**Comment by chb0github** [comment]
I was unable to test yesterday - will try again today
