### ISSUE TITLE
Support data sources for federated repositories

### ISSUE THREAD

**Issue by manojwajekar** [jfrog/terraform-provider-artifactory#692]
**Is your feature request related to a problem? Please describe.**
Currently, data sources from federated repositories are not available, making it difficult to manage federated repositories deployed in multiple artifactories. Since the Federated repository creates repository member artifactory automatically.

Code for creating federated repo:

```
resource "artifactory_federated_docker_repository" "docker_test" {
  key                    = "docker_test"
  description        = "This repository is for docker images."
  repo_layout_ref = "simple-default"
  xray_index         = true
  tag_retention     = 1

  dynamic "member" {
    for_each = var.federated_urls
    content {
      url     = join("/", [member.value, "artifactory", "docker_test"])
      enabled = true
    }
  }
}
```

On member artifactory, I got the following error since the federated repository was already created on member artifactory along with primary artifactory by terraform apply on the primary artifactory workspace.
`{ "errors" : [ { "status": 400, "message": "error when validating repository name: Case insensitive repository key already exists" } ] }`

**Describe the solution you'd like**
Data sources for federated repositories are introduced in future releases.

**Describe alternatives you've considered**
I tried importing resources manually in the member artifactory's workspaces, but it's a manual process.
I can create standalone repositories first and then introduce federation, but this required multiple coordinated terraform applies.  

**Additional context**

**Comment by Turhsus** [comment]
Hello! Thanks for posting an issue. 
I am currently working on data sources for federated repositories.

Once it releases, we will update this issue so that you know.

**Comment by alexhung** [comment]
Related to #548

**Comment by Turhsus** [comment]
Data sources for federated repositories have been added in versions v6.34.0 and v7.4.0

Please see the CHANGELOG.md for more details.

Hope this helps!
