### ISSUE TITLE
artifactory provider url needs to be artifactory.site.io/artifactory in the documentation

### ISSUE THREAD

**Issue by ma-sdnshakya** [jfrog/terraform-provider-artifactory#7]
provider "artifactory" {
  url = "artifactory.site.com/artifactory"
  username = "myusername"
  password = "mypassword"
}

**Comment by swails** [comment]
THANK YOU!

I could not for the life of me figure out why I kept getting 404.

**Comment by peters95** [comment]
PR has been merged with this change.
