### ISSUE TITLE
New `artifactory_federated_terraformbackend_repository` resource

### ISSUE THREAD

**Issue by d-m** [jfrog/terraform-provider-artifactory#710]
**Is your feature request related to a problem? Please describe.**

We would like for our application teams to store their Terraform state in a terraform backend repository in Artifactory instead of Terraform Enterprise because Artifactory is more cost effective.

All of our Artifactory repositories are provisioned via Terraform with state stored in Terraform Enterprise and access to the Artifactory UI is limited in our organization.

We currently can't provision terraform backend repositories for teams in Artifactory because we use federated repositories and no federated terraform backend repository resource exists.

**Describe the solution you'd like**
I would like an `artifactory_federated_terraformbackend_repository` to be added to this provider, similar to the existing `artifactory_local_terraformbackend_repository` resource.

**Describe alternatives you've considered**
 We were told that a workaround would be provision local terraform backend repositories in Artifactory and then use the UI to convert them to federated.

This doesn't work for us for a few reasons:

* we have too many teams (several hundred) to do this repeatably via a manual process
* access to the UI is limited so we can't easily convert the local terraform backend repository to a federated repository
* converting a local terraform backend repository provisioned via Terraform into a federated repository via the UI breaks the Terraform state

**Comment by danielmkn** [comment]
Hi @d-m! 
Since Artifactory doesn't have a Federated Terraform Backend repository as a type, you can use [this API](https://jfrog.com/help/r/jfrog-rest-apis/convert-local-repository-to-a-federated-repository) to convert it using a script, for example.
Another approach could be a bit hackish - to add a resource, that creates local repo, then converts it to federated. I'll need a PM input on this and will update here a bit later.
Please, let me know if API will work for you.

**Comment by d-m** [comment]
All of our Artifactory configuration needs to be defined as Terraform so I'm not sure we would be able to use the API unless we created a local repo first and put the API calls in a `local-exec` block. Even then, I think Terraform will look for the local repo, see that it's missing, and try to create it again after migration.

How do you mean there isn't a federated terraform backend type? Other federated repos can be provisioned directly via Terraform. Or is this due to how the terraform backend is implemented in Artifactory specifically?

**Comment by danielmkn** [comment]
Yeah, if you clock on create Federated repository button, you don't see the Terraform Backend icon there. But it exist in the local repo create dialog. 
See screenshots below.
Local has two types of Terraform repos:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/55418063/229939860-093a772c-366e-46d0-84a4-f9f00640a5e1.png">

Federated has only one, for modules: 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/55418063/229939911-7dd8269d-8bba-496d-9e0e-4af8ea3bc9f6.png">
