### ISSUE TITLE
ldap_setting_key is undocumented

### ISSUE THREAD

**Issue by autmwatl** [jfrog/terraform-provider-artifactory#711]
**Describe the bug**
Using the documented args, the following is returned during plan.

```
Error: Missing required argument

  on artifactory.tf line x, in resource "artifactory_ldap_group_setting" "ldap_group_name":
  x: resource "artifactory_ldap_group_setting" "ldap_group_name" {

The argument "ldap_setting_key" is required, but no definition was found.
```

`ldap_setting_key` is not listed anywhere in https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/ldap_group_setting

- artifactory version: 7.41.12
- terraform version: 0.14
- terraform provider version: 7.4.3.

**Expected behavior**
Please provide documentation for `ldap_setting_key`

**Comment by danielmkn** [comment]
@autmwatl thanks for the ticket! I'll add the missing argument description in the next version.
