### ISSUE TITLE
enabled_ldap is "required" and "not expected"

### ISSUE THREAD

**Issue by autmwatl** [jfrog/terraform-provider-artifactory#712]
**Describe the bug**
In the docs for [artifactory_ldap_group_setting](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/ldap_group_setting) it states that,

> [enabled_ldap](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/ldap_group_setting#enabled_ldap) - (Required) The LDAP setting you want to use for group retrieval.

Using the example provided, the `terraform plan` returns,

```
Error: Unsupported argument

  on artifactory.tf line x, in resource "artifactory_ldap_group_setting" "ldap_group_name":
  x:   enabled_ldap           = local.ldapGroupSettings_enabledLdap

An argument named "enabled_ldap" is not expected here.
```

- artifactory version: 7.41.12
- terraform version: 0.14
- terraform provider version: 7.4.3.

**Expected behavior**
Please update so that behaviour and documentation match.

Thanks!

**Comment by danielmkn** [comment]
@autmwatl thanks for the ticket! I'll fix the documentation in the next version.
