### ISSUE TITLE
Add a datasource which will list all Artifactory repositories of one kind (local, remote)

### ISSUE THREAD

**Issue by mkrejza83** [jfrog/terraform-provider-artifactory#716]
**Is your feature request related to a problem? Please describe.**
We are managing several virtual repositories which includes many local a remote repositories. Artifactory users are creating new repos from time to time and we need to keep our virtual repositories up to date including those newly created local/remote repos. We need to get a list of all repos of one kind to include them regularly to our virtual repos. At this time we have to call Artifactory API to get this list.

**Describe the solution you'd like**
Add a terraform datasource, maybe one for local a one for remote repositories, which will list all repos of given type.

**Describe alternatives you've considered**
We have to use Artifactory API to get this list at this time.

**Additional context**

**Comment by Jan-Pleva** [comment]
Is there any improvement?

**Comment by chb0github** [comment]
Do you have some sample syntax?

**Comment by Jan-Pleva** [comment]
`#Maven

data "http" "maven_locals" {

  url = "${var.artifactory_url}artifactory/api/repositories?type=local&packageType=maven"

  request_headers = {

    Accept        = "application/json"

    Content-Type  = "application/json;charset=UTF-8"

    Authorization = "Bearer ${var.token}"

  }

}`

**Comment by alexhung** [comment]
@Jan-Pleva FYI I'm working on add this datasource(s) now.

**Comment by alexhung** [comment]
@Jan-Pleva Do you have a preference for either a single data source (e.g. `artifactory_respositories` that let you specify `package_type` and `repository_type` or four more fine grained data sources, one for each repository type (e.g. `artifactory_local_repositories`, `artifactory_remote_repositories`, etc.)?

And are you looking for particular attribute(s) or wish to have all of them?

**Comment by Jan-Pleva** [comment]
Both are needed, but the package typ can be taken from virtual type, it has to be same type.
