### ISSUE TITLE
Support for webhooks

### ISSUE THREAD

**Issue by cob16** [jfrog/terraform-provider-artifactory#73]
It looks like there is[ REST support for webhooks ](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-WEBHOOKS).

- Would it be a good enhancement to add support for managing webhooks to this provider?
- Would a pull request for this be welcome?

**Comment by chb0github** [comment]
We would welcome a PR

**Comment by chb0github** [comment]
@markgalpin - another feature request

**Comment by chb0github** [comment]
what about xray webhooks?
