### ISSUE TITLE
license_check = false does not work in provider 7.10.0

### ISSUE THREAD

**Issue by kamilsimek-ecb** [jfrog/terraform-provider-artifactory#732]
**Describe the bug**
When using the provider from version 7.8.0 - there are issues acknowledged [here](https://github.com/jfrog/terraform-provider-artifactory/issues/728) and [here](https://github.com/jfrog/terraform-provider-artifactory/issues/729).
The version 7.10.0 fixes the error with `Invalid Provider Server Combination`, however a regression seems exist where the license_check = false doesn't work as expected. Same configuration works without problems on version 7.7.0

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    artifactory = {
      source = "jfrog/artifactory"
      version = "= 7.10.0"
    }
  }
}

provider "artifactory" {
  url           = "https://${YOUR_ARTIFACTORY_INSTANCE}/artifactory"
  access_token  = "*"
  check_license = false
}
```

Error:
```
│ 
│ Error: Failed to check for license. If your usage doesn't require admin permission, you can set `check_license` attribute to `false` to skip this check. 
│ 401 GET https://[REDACTED]/artifactory/api/system/license
│ {
│   "errors" : [ {
│     "status" : 401,
│     "message" : "Unauthorized"
│   } ]
│ }
│ 
│   with provider["registry.terraform.io/jfrog/artifactory"],
│   on main.tf line 19, in provider "artifactory":
│   19: provider "artifactory" {
│ 
│ 
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
The terraform init and terraform plan is executed successfully 

**Additional context**

- artifactory version: 7.55.9
- terraform version: 1.4.6
- terraform provider version: 7.10.0

**Comment by danielmkn** [comment]
The fix is released in v7.10.1
