### ISSUE TITLE
Custom Webhooks Support

### ISSUE THREAD

**Issue by martinm82** [jfrog/terraform-provider-artifactory#738]
**Is your feature request related to a problem? Please describe.**
Since version 7.50.3, Artifactory supports now custom webhooks, useful to trigger GitHub Workflows. This was not possible with the regular webhook type since the payload on Artifactory side was not accepted by GitHub. Now with custom webhooks, the payload can be adjusted accordingly.

See https://jfrog.com/help/r/jfrog-platform-administration-documentation/trigger-a-github-action-using-custom-webhook

**Describe the solution you'd like**
Extend the existing webhook resources with a new handler type attribute that will accept all supported types provided by the REST API (e.g., `webhook`, `custom-webhook`) and additional fields for the `payload` and `http_headers`.

**Describe alternatives you've considered**
-

**Additional context**
https://jfrog.com/help/r/jfrog-rest-apis/webhooks?tocId=f8JC_d63stwnApjNLLunsA

**Comment by alexhung** [comment]
@martinm82 Most likely we'll add another resource (`artifactory_custom_webhook`?) to handle custom webhook, separate from existing one.

**Comment by danielmkn** [comment]
Hi, @martinm82! Just a head up, I'm working on this ticket. It should be done soon. I'll ping you.

**Comment by danielmkn** [comment]
@martinm82, it's released in v8.3.0

**Comment by martinmigasiewicz-tomtom** [comment]
Thanks a lot @danielmkn. I will share the great news to our team to test think feature.
