### ISSUE TITLE
Proxy config for Python Remote Repositories not been correctly applied

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/terraform-provider-artifactory#739]
**Describe the bug**

I as a User would like to remove all proxies config from my available remote repositories. Every time I run terraform it says:

plan:
![image](https://github.com/jfrog/terraform-provider-artifactory/assets/30481051/2c6b2113-38a6-4ce0-b994-8d0165c72f6b)

apply:
![image](https://github.com/jfrog/terraform-provider-artifactory/assets/30481051/1b72535a-8edf-426f-98e6-a1a4d0b9132a)

but every time it gets there again. I'm unsure if it's Artifactory bug or this provider bug. I think it's this provider because it worked in the past.  

snippet:

```terraform
resource "artifactory_remote_pypi_repository" "pypi_org" {
  key                                   = "pypi.org"
  url                                   = "https://files.pythonhosted.org"
  list_remote_folder_items              = false
  xray_index                            = true
  retrieval_cache_period_seconds        = 600
  unused_artifacts_cleanup_period_hours = 96
  property_sets = [
    "artifactory",
  ]
  lifecycle {
    ignore_changes = [
      project_key
    ]
  }
}
```

run apply, then run plan again and proxy config will trigger the following:

![image](https://github.com/jfrog/terraform-provider-artifactory/assets/30481051/2c6b2113-38a6-4ce0-b994-8d0165c72f6b)

version of artifactory:
Enterprise Plus 7.55.9 rev 75509900

version of terraform:
1.1.9

version of provider:
6.37.0

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
Remove proxies

**Additional context**

**Comment by danielmkn** [comment]
Hi @EvertonSA! Thanks for the ticket! 
I've tried your snippet on v6.37.0 and a new Artifactory instance and everything was working as expected. 
As far as I understood from the ticket, you had a repository with the `proxy` attribute, and then you needed to remove the proxy configuration by removing the attribute from the HCL configuration. 
My test scenario: 
```
resource "artifactory_remote_pypi_repository" "pypi_org1" {
  key                                   = "pypi.org1"
  url                                   = "https://files.pythonhosted.org"
  list_remote_folder_items              = false
  xray_index                            = true
  retrieval_cache_period_seconds        = 600
  unused_artifacts_cleanup_period_hours = 96
  proxy                                 = "testProxy"
  property_sets = [
    "artifactory",
  ]
  lifecycle {
    ignore_changes = [
      project_key
    ]
  }
}
```
Where `testProxy` is a pre-existing proxy on my Artifactory instance. 
I ran `terraform plan`, and `terraform apply` all good. 
Then I modified the config by removing the `proxy` attribute: 
```
resource "artifactory_remote_pypi_repository" "pypi_org1" {
  key                                   = "pypi.org1"
  url                                   = "https://files.pythonhosted.org"
  list_remote_folder_items              = false
  xray_index                            = true
  retrieval_cache_period_seconds        = 600
  unused_artifacts_cleanup_period_hours = 96
  property_sets = [
    "artifactory",
  ]
  lifecycle {
    ignore_changes = [
      project_key
    ]
  }
}
```
`terraform plan`
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # artifactory_remote_pypi_repository.pypi_org1 will be updated in-place
  ~ resource "artifactory_remote_pypi_repository" "pypi_org1" {
        id                                    = "pypi.org1"
      - proxy                                 = "testProxy" -> null
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

`terraform apply`

```
Terraform will perform the following actions:

  # artifactory_remote_pypi_repository.pypi_org1 will be updated in-place
  ~ resource "artifactory_remote_pypi_repository" "pypi_org1" {
        id                                    = "pypi.org1"
      - proxy                                 = "testProxy" -> null
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

artifactory_remote_pypi_repository.pypi_org1: Modifying... [id=pypi.org1]
artifactory_remote_pypi_repository.pypi_org1: Modifications complete after 0s [id=pypi.org1]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```
`terraform plan`
```
artifactory_remote_pypi_repository.pypi_org1: Refreshing state... [id=pypi.org1]

No changes. Your infrastructure matches the configuration.
```

Also, I can see the API payload with the `proxy` attribute empty, which means it will be removed from the repo: 
<img width="294" alt="image" src="https://github.com/jfrog/terraform-provider-artifactory/assets/55418063/234d834e-a7e4-4405-976e-8a0dc815d84d">

Double-checked in the UI, no proxy. The attribute doesn't have a default value, so I'm not sure how it's becoming a "Proxy" for you. Even if I change the value in the UI, I can successfully remove it by running `terraform apply`. 
Please tell me if I miss something in the configuration.

**Comment by danielmkn** [comment]
You can use the provider version 7x if you have Artifactory 7x and there will be no need to use lifecycle management for the project key.

**Comment by EvertonSA** [comment]
sorry I was in vacation, the same test you have on my artifactory still adds proxy on the second terraform plan.

I assume it's a problem on my artifactory.

**Comment by EvertonSA** [comment]
My understanding is that Jfrog Artifactory is applying proxy because if we dont set proxy (set proxy as null), this provider does not send the disableproxy attributte on the update of the remote repository. See the request body when I click disable proxy on UI:

![image](https://github.com/jfrog/terraform-provider-artifactory/assets/30481051/4be3a98f-a12e-4e7c-9bc1-39edeb665e7d)

**Comment by EvertonSA** [comment]
so this is not a bug, more likely a feature request to add disableProxy on remote repositories, 

can this be done @danielmkn ?

**Comment by danielmkn** [comment]
Yes, @EvertonSA, `disableProxy` attribute is available for remote and federated repositories in the public API. The value is `false` by default. 
In the UI (Artifactory 7.59.9) this change will be reflected like this, if set to `true`: 
![image](https://github.com/jfrog/terraform-provider-artifactory/assets/55418063/d5900323-07e5-4395-9db7-6c9044f0ddb8)
If the boolean set to `true` together with `proxy` attribute, then `proxy` attribute doesn't exist in the GET repository response, which is a state drift. 
Not sure if adding the boolean attribute will add a lot of value here. I'll add the bool attribute and the restriction, so users can't set `proxy` if `disableProxy` is set to `true`. 
Will this work for you?

**Comment by damacus** [comment]
@danielmkn that won't quite work, as we still need some way of setting this flag from Terraform.

**Comment by danielmkn** [comment]
@damacus, the attribute is available in the API body, not in the HCL config. I mean, I can add that attribute to HCL, but not sure if it will add or fix anything. When the checkbox (corresponding with that bool) is checked, all it does is block the proxy dropdown in the UI. 
If the user deletes the `proxy` attribute in the HCL, the proxy configuration is getting removed from the repo anyway, so the boolean will be redundant IMO. 
Adding the boolean will create a situation when it will be set to `true` at the same time as the `proxy` attribute will not be empty. That will lead to state drift because the API response won't have a proxy list anymore.

**Comment by damacus** [comment]
Sadly that's not what happens in the plan. 

We have a default proxy set, then unset it for 4 repos. 

Those 4 repos have a forever diff where terraform is trying to under the proxy. 

I'm not sure what the proper fix here is then if that box only disables UI elements. I've got to say that UX isn't obvious at all.

**Comment by danielmkn** [comment]
@damacus what is the Artifactory version you use?

**Comment by danielmkn** [comment]
I think we might have missed this part: 

> Whether a proxy has been set manually or by setting a Default Proxy as a Platform Default or for Artifactory, you can override this setting by selecting the No Proxy option for any specific repository.

I'm pretty sure that scenario wasn't tested. I'm looking into it.

**Comment by damacus** [comment]
> @damacus what is the Artifactory version you use? 

7.59.9

**Comment by danielmkn** [comment]
I'll work on that next sprint, which starts tomorrow. The `disableProxy` attribute was added in [Artifactory 7.41.7](https://jfrog.com/help/r/jfrog-artifactory-documentation/remote-repositories), so we need to test it thru with older versions and find a good way to avoid state drift when no `proxy` attribute present in the response body.

**Comment by danielmkn** [comment]
@damacus and @EvertonSA heads up, the attribute will be added in v8.2.0

**Comment by danielmkn** [comment]
@EvertonSA if you really need to have it in v6x, please let me know, I can add it next week in v6.38.0

**Comment by EvertonSA** [comment]
@danielmkn thanks, no need on v6x, i'm on my way to v8.2.0
