### ISSUE TITLE
(Python) CDKTF Provider

### ISSUE THREAD

**Issue by nbaju1** [jfrog/terraform-provider-artifactory#748]
Are there any plans to develop a CDK provider package for Python? CDK offers a lot more flexibility, so this is something that would be instantly adopted by our team at least.

**Comment by danielmkn** [comment]
We don't have plans to develop it for now, but we will take a look into how much effort it could be and if there is a user base for that. Thanks!

**Comment by danielmkn** [comment]
@nbaju1, have you tried [this approach](https://developer.hashicorp.com/terraform/cdktf/concepts/providers#generate-classes) of using providers in CDKTF? 
I've never used it myself, it looks a bit too good to be true, TBH.

**Comment by nbaju1** [comment]
> @nbaju1, have you tried [this approach](https://developer.hashicorp.com/terraform/cdktf/concepts/providers#generate-classes) of using providers in CDKTF? I've never used it myself, it looks a bit too good to be true, TBH.

That...worked! Seemingly at least. Will do some more testing, but that approach seems to create files similar to the ones installed with the cdkt provider packages in pypi.org. 

Thanks for the tip!
