### ISSUE TITLE
LDAP Setting not working with Artifactory v7.57 and upper

### ISSUE THREAD

**Issue by jcoste-orange** [jfrog/terraform-provider-artifactory#749]
**Describe the bug**
We were using the provider to configure artifactory_ldap_setting.
We upgrade to v7.59.9 and this is not working anymore.

Seems to be related to https://jfrog.com/help/r/jfrog-release-information/artifactory-7.57.1-cloud.

ldapsettings are not returned by API system/configuration anymore.

Artifactory version : 7.59.9
Terraform version 1.4.6
Provider version 7.11.2 or 8.0.0

**Comment by danielmkn** [comment]
@jcoste-orange, it's related to the change in the Artifactory, we are planning to add a new resource, which will use the new API for LDAP and LDAP group settings. The Artifactory team is also aware of the breaking change.

**Comment by jcoste-orange** [comment]
Ok thanks

**Comment by danielmkn** [comment]
I'm closing this one. The new resource is a planned work.

**Comment by danielmkn** [comment]
Hi @jcoste-orange, new resources were added in v8.4.0.

**Comment by jcoste-orange** [comment]
Thank you very much.
