### ISSUE TITLE
[FEATURE] use lazy connections

### ISSUE THREAD

**Issue by fl-max** [jfrog/terraform-provider-artifactory#75]
The Provider is currently not using lazy connections. This can cause issues when importing and prevents `depends_on` use-cases.

For example, if lazy connections were implemented, I should be able to build:
```hcl
module "artifactory" {
  source = "./modules/artifactory"
  # Config here
}

provider "artifactory" {
  url      = "${module.artifactory.endpoint}/artifactory"
  username = module.artifactory.admin_user
  password = module.artifactory.admin_password
}
```

without receiving this error:
```bash
Error: either [username, password] or [api_key] or [access_token] must be set to use provider

  on main.tf line 6, in provider "artifactory":
 6: provider "artifactory" {
```

An example of this feature can be seen in this [postgresql provider](https://github.com/hashicorp/terraform-provider-postgresql/pull/199) & [mysql provider](https://github.com/hashicorp/terraform-provider-mysql/pull/43).

**Comment by chb0github** [comment]
@markgalpin - Hmmm. I like the idea. For the record: `${module.artifactory.endpoint}/artifactory` the `artifactory` part is no longer needed as the provider works for xray and artifactory

**Comment by markgalpin** [comment]
@chb0github would this be something that's implemented in the provider-proper, or in the client?

**Comment by chb0github** [comment]
Being entirely honest: It's not clear. @fl-max - are you suggesting that terraform resolve resources lazily? Or are you suggesting it make network sockets lazily?

**Comment by fl-max** [comment]
@chb0github I'm not a TF Provider dev by any means but I believe the idea is to not configure and try to connect to the endpoint until a `resource` is called.

If I understand the example PRs I linked correctly, they're moving the Validation/Connection out of the Provider initialization and into the resource phase. That is to say this (example):
```hcl
provider "artifactory" {
  url      = "${module.artifactory.endpoint}/artifactory"
  username = module.artifactory.admin_user
  password = module.artifactory.admin_password
}
```
won't get evaluated until this:
```hcl
resource "artifactory_local_repository" "my-local" {
  key          = "my-local"
  package_type = "npm"
}
```
is evaluated.

**Comment by chb0github** [comment]
Definitely a provider change then

**Comment by chb0github** [comment]
You see, the problem here is that we could no longer use `terraform validate` and it's generally a very good idea to fail fast then delay it.

Have you tried reproducing this issue with the latest release? This provider moved to the newest SDK. It's possible the issue is entirely gone
