### ISSUE TITLE
Error: Provider produced inconsistent result after apply scoped_token

### ISSUE THREAD

**Issue by slzmruepp** [jfrog/terraform-provider-artifactory#761]
**Describe the bug**
We run a jfrog module. Part of the module is the creation and refreshing of a scoped token and to put the token in a k8s docker secret into a namespace.

Now I try to run the terraform script again (after some time) : 
```
provider registry.terraform.io/jfrog/artifactory v8.2.3
+ provider registry.terraform.io/jfrog/project v1.1.16
+ provider registry.terraform.io/jfrog/xray v1.14.0
```

with the following resource (which already exists):

```
resource "artifactory_scoped_token" "jfrog_user" {
  username          = artifactory_user.jfrog_user.name //some artifactory user created by tf
  refreshable       = var.jfrog_token_refreshable //true
  expires_in        = var.jfrog_token_expire //0
}
```

and I get the following Error:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.project.module.jfrog_setup.artifactory_scoped_token.jfrog_user,
│ provider "provider[\"registry.terraform.io/jfrog/artifactory\"]" produced
│ an unexpected new value: .include_reference_token: was cty.False, but now
│ null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

So our pipeline fails and is blocked and we are unable to introduce new changes into our environment currently.

**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**
I want to have the token value either upgraded if expiry is > 0  or unchanged if expiry is 0
I want the scoped token to be refreshable if refreshable = true according to the documentation
I expect the provider to handle newly introduced values without breaking.

**Additional context**

**Comment by danielmkn** [comment]
Fix is released in v8.3.1
