### ISSUE TITLE
404 when refreshing deleted artifactory-user

### ISSUE THREAD

**Issue by Valerianer** [jfrog/terraform-provider-artifactory#775]
**Description**
Like described in #772 at scoped-token, also the handling of normal artifactory-users seems to fail in the same way. 
When a user gets created withe terraform and the user gets deleted in the target system, terraform fails when refreshing the user.

Example-User (main.tf.json):
```
{
    "provider": {
        "artifactory": {
            "access_token": "access_token",
            "url": "url"
        }
    },
    "resource": {
        "artifactory_user": {
            "artifactory-repo-created-with-crossplane": {
                "name": "crossplane-user",
                "disable_ui_access": true,
                "internal_password_disabled": true,
                "profile_updatable": true,
                "email": "crossplane-user@example.web",
                "groups": [],
                "admin": false
            }
        }
    },
    "terraform": {
        "required_providers": {
            "artifactory": {
                "source": "jfrog/artifactory",
                "version": "8.4.0"
            }
        }
    }
}
```

**Reproduce**
* create above mentioned file in a folder
* run `terraform init`
* run `terraform apply`
* delete the user in artifactory
* run `terraform plan` or `terraform apply` and you should get the following error:

```
artifactory_user.crossplane-user: Refreshing state... [id=crossplane-user]
╷
│ Error: Unable to Refresh Resource
│
│   with artifactory_user.crossplane-user,
│   on main.tf.json line 18, in resource.artifactory_user.crossplane-user:
│   18:             }
│
│ An unexpected error occurred while attempting to refresh resource state. Please retry the operation or report this issue to the provider
│ developers.
│
│ HTTP Error:
│ 404 GET https://<host>/artifactory/api/security/users/crossplane-user
│ {
│   "errors" : [ {
│     "status" : 404,
│     "message" : "Not Found"
│   } ]
│ }
```

**Used versions**
terraform version
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/jfrog/artifactory v8.4.0

artifactory-version: 7.59.11

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
deleted/non-existing resource (user) should be (re-)created by terraform, like it already works for repositories.

**Additional context**
---

**Comment by danielmkn** [comment]
Thanks for reporting! Fixed in v8.4.1
