### ISSUE TITLE
System Configuration

### ISSUE THREAD

**Issue by kavehmz** [jfrog/terraform-provider-artifactory#78]
Is there a plan for adding system configurations like `backups` to the terraform module?

I want to be able to setup my fleet of artifactory clusters using terraform.
I was not able to find how can I achieve configs like `backups`.

I know I can do that through PATCH calls as described in [Artifactory YAML Configurations](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration), but using terraform is the standard way in my case.

**Comment by tielou** [comment]
I would very much appreciate that as well.
We solved it for now by the use of the [shell provider by scott winkler](parameterizable) and simple parameterizable shell scripts which patch the config. It's not perfect but everything is in Code so good enough until it's officially supported.

**Comment by chb0github** [comment]
Good idea - I will pass this along
