### ISSUE TITLE
Bug on plan for local repositories

### ISSUE THREAD

**Issue by EvertonSA** [jfrog/terraform-provider-artifactory#786]
**Describe the bug**
I, as a platform engineering, configuring local (virtuals/remotes might have same behavior) repositories using terraform, need to remove an existing description from one managed terraform local repository. But, when run apply to delete the description, it says it gets deleted, but when I run apply again, it says it will be deleted again.

Jfrog Version:
Enterprise Plus 7.63.11 rev 76311900

Terraform version:
Terraform v1.3.7

Version of provider:
```
    artifactory = {
      source = "jfrog/artifactory"
      version = "8.4.2"
    }
```

**Expected behavior**
when running apply and it says that it had been applied, I would expect to be applied. 

**Additional context**
Follow example code:

```
terraform {
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
      version = "8.4.2"
    }
  }
}

provider "artifactory" {
  url          = "INSTANCE_URL"
  access_token = ""
}

resource "artifactory_local_generic_repository" "terraform-local-test-generic-repo" {
  key = "everton-testing-repo"
  description = "this is a nice description"
}

# run apply
# comment description
# run apply
# run plan again
```

**Comment by alexhung** [comment]
@EvertonSA Unfortunately this is caused by the behavior of the Artifactory API. The absent of the field is treated as no-op, so in order to reset/clear out the repo's description, my recommendation is to set the attribute to empty string (`""`).

**Comment by alexhung** [comment]
Related to #752

**Comment by EvertonSA** [comment]
thanks for the explanation!
