### ISSUE TITLE
Missing resource for `artifactory_virtual_cargo_repository`

### ISSUE THREAD

**Issue by aisamji** [jfrog/terraform-provider-artifactory#789]
**Describe the bug**
There is no resource for `artifactory_virtual_cargo_repository`. I am assuming this was just an oversight during development as the equivalent `local`, `federated`, and `remote` resources **do** exist.

**Artifactory Version:** 7.67.3 rev 76703900
**Terraform Version:** 1.5.2
**Provider Version:** 8.5.0

**Expected behavior**
The following should be a valid resource.
```hcl
resource "artifactory_virtual_cargo_repository" "default" {
  key = "my-cargo"

  project_key = "my"
  project_environments = ["DEV"]
  
  default_deployment_repo = "my-cargo-local"
  repositories = [
    "my-cargo-local",
    "my-cargo-remote"
  ]
}
```

Assuming that the project `my` and the repositories `my-cargo-local` and `my-cargo-remote` have been created externally. The repositories should be a local cargo and remote cargo respectively.

**Comment by danielmkn** [comment]
Hi @aisamji! There is no Cargo virtual repo type in the UI, this is why it's not in the provider as well.
