### ISSUE TITLE
A user resource with capitalization in the name will cause issues on later 'terraform apply' commands 

### ISSUE THREAD

**Issue by derekscp** [jfrog/terraform-provider-artifactory#790]
**Describe the bug**
If you have a user resource in terraform with capital letters there is an issue as terraform is those capital letters in the state.

**Requirements for and issue**
- When running terraform apply for a user with capital letters it will result in this error
`│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to artifactory_user.derekp_new_user, provider
│ "provider[\"registry.terraform.io/jfrog/artifactory\"]" produced an
│ unexpected new value: .id: was
│ cty.StringVal("derekp_new_userszw10srvhelios"), but now
│ cty.StringVal("derekp_new_userSzw10SRVHELIOS").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.`
To reproduce you can use the following steps:
1. Have a user resource with capital letters in the name.
2. Run terraform apply. If this is the first time you run it the user will be created.
3. Run terraform apply again. It will detect a mismatch on what it is expecting and what it is receiving (all lowercase vs some capitalization).
- Terraform snippet:
`resource "artifactory_user" "derekp_new_user" {
  name   = "derekp_new_userSzw10SRVHELIOS"
  email  = "new_user@somewhere.com"
  groups = ["readers"]
}`
- Artifactory Version: 7.67.3
- Terraform Version: v1.5.4
- Terraform Artifactory Provider: v8.6.0

**Expected behavior**
The terraform provider should handle this use case where the username has capital letters in the terraform file.

**Comment by alexhung** [comment]
@derekscp JFrog platform only allows lowercase username. We will fix the provider and add validation for this.

**Comment by derekscp** [comment]
@alexhung yep. Thanks!
