### ISSUE TITLE
artifactory_scoped_token attempts to set description - state drift

### ISSUE THREAD

**Issue by slzwgoosen** [jfrog/terraform-provider-artifactory#792]
**Describe the bug**
When updating the provider to version 8.5.0 from 7.11.2, the provider attempts to set description on artifactory_scoped_token resources. 

Terraform apply output:
```sh
artifactory_scoped_token.scoped_token_user,
│ provider "provider[\"registry.terraform.io/jfrog/artifactory\"]" produced
│ an unexpected new value: .description: was cty.StringVal(""), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Example:
```tf
resource "artifactory_scoped_token" "scoped_token_user" {
  username = artifactory_user.new_user.name
  refreshable             = true
  expires_in              = 7200
  include_reference_token = var.token
}
```
**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

Artifactory version: 8.5.0
Terraform version: v1.5.6

**Expected behavior**
When no value for description on artifactory_scoped_token is present the apply should succeed. Updating the provider version should have no effect.

**Additional context**

Provider changes:
https://github.com/jfrog/terraform-provider-artifactory/commit/c9b4d0cc6ccc1471e146a9465c9403089dfeaacc
https://github.com/jfrog/terraform-provider-artifactory/commit/15059a683772a6ecfdb975ed12cae6b4b07c30a9#diff-0b8ad0f032c7339afc91446dab5a0657ef2f85cca0c98ab0f511a50077e52c63

**Comment by alexhung** [comment]
@slzwgoosen Thanks for the report, we will investigate.
