### ISSUE TITLE
Support docker repo setting for blocking manifest v1 publishing

### ISSUE THREAD

**Issue by asvoboda** [jfrog/terraform-provider-artifactory#8]
Per https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON, I think this is just a single boolean in a local repo setting for 
```
blockPushingSchema1 = true | false
```

**Comment by chb0github** [comment]
@asvoboda - I have taken over this repo and I am going to close this ticket in favor of #34 

The current repository resource is basically a generic+ format. What I mean is that, if has the generic repo payload and then, for a couple of other repo types includes some flags it needs, but then those are totally optional as they only apply for those specific repo types and aren't supported by any others. 

What's needed is proper support for docker repos from TF - that's the crux of #34
