### ISSUE TITLE
artifactory_permission_target: not able to declare several users or groups into repo.actions map

### ISSUE THREAD

**Issue by jmvitali** [jfrog/terraform-provider-artifactory#800]
**Describe the bug**
I would like to create a configuration ressource "artifactory_permission_target" to create a permission for a local repository with several users and groups.

Basically define several name/permissions into the following arguments map
```
repo
  actions
    users
    groups
```

By example the following:

```tf
resource "artifactory_permission_target" "jmv3-docker-prod-jmviz-nce" {
  name = "jmv3-docker-prod-jmviz-nce"

  repo {
    includes_pattern = ["**"]
    repositories     = ["jmv3-docker-prod-jmviz-nce"]

    actions {
      users {
        name        = ["anonymous", "swb2-izu-jmviz"]
        permissions = ["read", "write"]
      }

      groups {
        name        = "readers"
        permissions = ["read"]
      }
    }
  }
}
```

I tried several format to declare several users or groups, but i'm not able to format it successfully.
Our artifactory version is 7.38.8
I'm using the terraform v1.5.6
I'm using the latest version of this terraform provider (i.e.: v8.9.1)

Is it a known limitation of the configuration ressource? To me the attributes "users" and "groups" should accept multiple values ;)

Hope the configuration format i'm using is not the right one. :)

Thanks in advance for you help.
Kind Regards,
JM

**Comment by alexhung** [comment]
@jmvitali I think the confusion arises from the attributes `users` and `groups` being plural back when the resource was created. They should have been singular per Terraform convention. To set the config for multiple users and groups, you need to specific each individually:

```tf
resource "artifactory_permission_target" "jmv3-docker-prod-jmviz-nce" {
  name = "jmv3-docker-prod-jmviz-nce"

  repo {
    includes_pattern = ["**"]
    repositories     = ["jmv3-docker-prod-jmviz-nce"]

    actions {
      users {
        name        = ["anonymous"]
        permissions = ["read", "write"]
      }

      users {
        name        = ["swb2-izu-jmviz"]
        permissions = ["read", "write"]
      }

      groups {
        name        = "readers"
        permissions = ["read"]
      }

      groups {
        name        = "dev"
        permissions = ["read", "write"]
      }
    }
  }
}
```

**Comment by jmvitali** [comment]
Hello @alexhung ,
Thanks a lot for the quick answer and help.
Best Regards,
JM
