### ISSUE TITLE
Bug: Docker repository with configured inputs similar to its current state is throwing an error 400

### ISSUE THREAD

**Issue by neatcoder** [jfrog/terraform-provider-artifactory#801]
**Describe the bug**
Applying a plan that includes creating a new permission along with an imported (unchanged) docker repository with all configured inputs similar to its current state, is throwing an error 400

Artifactory version: `7.69.4`
Terraform version: `v1.5.5`
Provider version: `7.11.2`

I moved to using 7.X version because of #782 and 8.X seemed to be unstable. Idk if that issue is really resolved.

**Snippet**
```hcl
resource "artifactory_local_docker_v2_repository" "repositories" {
  key             = var.repository_name
  repo_layout_ref = var.repo_layout_ref
  description     = var.desc_repo
}

resource "artifactory_permission_target" "permissions" {
  for_each = var.permission_targets

  name = each.key
  repo {
    actions {
      dynamic "groups" {
        for_each = each.value.groups

        content {
          name        = groups.value.name
          permissions = groups.value.permissions
        }
      }
    }
    repositories     = var.repository_name
    includes_pattern = ["**"]
  }
  depends_on = [
    artifactory_local_docker_v2_repository.repositories
  ]
}
```

**Imported config in terraform**
```json
"instances": [
        {
          "schema_version": 0,
          "attributes": {
            "api_version": "V2",
            "archive_browsing_enabled": false,
            "blacked_out": false,
            "block_pushing_schema1": true,
            "cdn_redirect": false,
            "description": "test repo",
            "download_direct": false,
            "excludes_pattern": "",
            "id": "scratch",
            "includes_pattern": "**/*",
            "key": "scratch",
            "max_unique_tags": 0,
            "notes": "test repo",
            "package_type": "generic",
            "priority_resolution": false,
            "project_environments": [],
            "project_key": "",
            "property_sets": [
              "artifactory"
            ],
            "repo_layout_ref": "simple-default",
            "tag_retention": 1,
            "xray_index": false
          },
          "sensitive_attributes": [],
          "private": "XXXXXXXXXXX"
        }
      ]
```
While applying the plan, `project_key` was also reportedly throwing an error that it is less than 2 Alphanumeric character. To resolve it we left it null as there seems to be a default value for it. We then ran into the below error.

**Error**
```log
 Error:
 400 POST <URL OF ARTIFACTORY>
 {
   "errors" : [ {
     "status" : 400,
     "message" : "Changing a repository's type once it's set is not supported"
   } ]
 }

   with artifactory_local_docker_v2_repository.repositories,
   on main.tf line 15, in resource "artifactory_local_docker_v2_repository" "repositories":
   15: resource "artifactory_local_docker_v2_repository" "repositories" {
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
Should work without trying to change the resource

**Comment by alexhung** [comment]
@neatcoder The state shows that the imported repository is of 'generic' package type:

```tf
"package_type": "generic"
```

It is possible there's a bug in the import code (though I think that's unlikely). Can you verify that the import cli command matches your HCL?

**Comment by neatcoder** [comment]
You're right. Facing the error while trying to import a generic repo with a docker module.
Worked when i fixed the imported repo.
Closing the issue as it is working as expected.
