### ISSUE TITLE
A resource to create local, remote and virtual repositories for any PackageType (ex: docker)

### ISSUE THREAD

**Issue by jmvitali** [jfrog/terraform-provider-artifactory#803]
Hello Guys,
I would like to create a module to manage the creation of a local, a remote and a virtual repositories for a specific Package type as an input variable.
I'm young on terraform knowledge :) and my assumption was to create a module variable and to pass it into the ressource type like the following configurations example:
```
output "resource_type_create_local_repo" {
    value = var.repo_techno == "docker" ? "artifactory_local_${var.repo_techno}_v2_repository" : "artifactory_local_${var.repo_techno}_repository"
}

# Create a new local repository
resource "${var.resource_type_create_local_repo}" "create_local_repository" {
   key                      = "${var.repo_prj}-${var.repo_techno}-${var.repo_maturity}-${var.repo_iz_name}-${var.artifactory_instance_site}"
   notes                    = "ticket=${var.repo_jira_ref}"
   description              = "description"
   excludes_pattern         = ""
   includes_pattern         = "**/*"
} 
```

But it seems this one can not be done on terraform :(

The solution I would like could be having a resource like by example artifactory_local_repository and to have a package_type as an argument to pass. 

Thanks a lot in advance.
Kind Regards.
JM

**Comment by chb0github** [comment]
This actually used to be the case long ago in version 3.x. We intentionally migrated away from that because, which many package types are effectively generic, plenty aren't. And non generic types have different rules/schemas that go with them. By having specific resource types for every package type we are able to apply stringent schema validation.

What you want to do is inherently unsafe; hence why it's no longer supported (good riddance!)

**Comment by jmvitali** [comment]
Thanks for your answer @chb0github.
I understand your point, but you could propose safely a resource with basic commons attributes (key, notes, description, etc) like we could implement by using the artifactory REST API.

As the resource type can not be set with a variable, do you have a tips/recommandation to avoid creating a resource configuration for each repository type?

Thanks in advance.
JM

**Comment by chb0github** [comment]
So, you can look at the artifactory APIs to put together rest payloads and use something like a combination of `jq` and `curl`.  [Here](https://github.com/jfrog/terraform-provider-artifactory/blob/a342a30d90773e8b759ab0b9ed8327403e9a1c8d/pkg/artifactory/resource/repository/local/local.go#L13-L34) is a list of all the generic package types

```go
var PackageTypesLikeGeneric = []string{
        "bower",
        "chef",
        "cocoapods",
        "composer",
        "conan",
        "conda",
        "cran",
        "gems",
        "generic",
        "gitlfs",
        "go",
        "helm",
        "npm",
        "opkg",
        "pub",
        "puppet",
        "pypi",
        "swift",
        "terraformbackend",
        "vagrant",
}
```

**Comment by jmvitali** [comment]
Hello,
Ok thanks. Let's consider this request as cancelled then :)

**Comment by jmvitali** [comment]
Thanks
