### ISSUE TITLE
Documentation example how to upload a license file

### ISSUE THREAD

**Issue by odbaeu** [jfrog/terraform-provider-artifactory#81]
Maybe you could add an example to the documentation (https://registry.terraform.io/providers/jfrog/artifactory/latest/docs) how to upload a license file:

With base64 encoded password:
```
curl --location --request POST 'http://localhost:8082/artifactory/api/system/licenses' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YDSAfhdsafdnosavcmQ=' \
--data-raw '{
    "licenseKey": "licese with \n separated lines"
}'
```

With plain text password:
```
curl --user admin:pawwsord --location --request POST 'http://localhost:8082/artifactory/api/system/licenses' \
--header 'Content-Type: application/json' \
--data-raw '{
    "licenseKey": "licese with \n separated lines"
}'
```

**Comment by chb0github** [comment]
This GH repo is for terraform related issues and requests - This is a curl example. If you'd like to submit a request for TF support for licenses, then feel free to do so
