### ISSUE TITLE
Go module path for v9 is still /v8, breaking `go get`

### ISSUE THREAD

**Issue by thomas11** [jfrog/terraform-provider-artifactory#813]
**Describe the bug**
Hi! The recent v9.0 release didn't increase the version number in the Go paths from `github.com/jfrog/terraform-provider-artifactory/v8` to `github.com/jfrog/terraform-provider-artifactory/v9`. This is required by the [Go module spec](https://go.dev/ref/mod#module-path):
> If the module is released at major version 2 or higher, the module path must end with a [major version suffix](https://go.dev/ref/mod#major-version-suffixes) like /v2. This may or may not be part of the subdirectory name. For example, the module with path golang.org/x/repo/sub/v2 could be in the /sub or /sub/v2 subdirectory of the repository golang.org/x/repo.

As a consequence, it's not possible to use v9 in a Go program, at least with standard tooling, since `go get` fails with
> go: github.com/jfrog/terraform-provider-artifactory/v9@cbc1113ccf8288dc531189fcc1bf5c68edae5f74: github.com/jfrog/terraform-provider-artifactory/v9@v9.0.0: invalid version: go.mod has non-.../v9 module path "github.com/jfrog/terraform-provider-artifactory/v8" (and .../v9/go.mod does not exist) at revision v9.0.0

**Expected behavior**
It's possible to add the provider as a module in the standard way: `go get github.com/jfrog/terraform-provider-artifactory/v9`

**Additional context**
The required change should be a straight forward replace in go.mod and all *.go files.

**Comment by alexhung** [comment]
@thomas11 Thanks for the report. I always forget to update the import path 🤦🏼 after bumping major version.
