### ISSUE TITLE
Provider Bug

### ISSUE THREAD

**Issue by MA140589** [jfrog/terraform-provider-artifactory#818]
**Describe the bug**
We are using terraform-provider-artifcatory and recently when we triggered our terraform apply and want to renew token used to login to artifactory, we faced below error. 

We are using artifactory version : 7.56.5

We are using Terraform version : 1.3.6

We are using Terraform provider version : 8.2.3

```
Error: Provider produced inconsistent result after apply

Warning: No password supplied


When applying changes to artifactory_scoped_token.sync, provider
"provider[\"registry.terraform.io/jfrog/artifactory\"]" produced an
unexpected new value: .expires_in: was cty.NumberIntVal(0), but now
cty.NumberIntVal(3.1536e+07).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent result after apply

When applying changes to artifactory_scoped_token.sync, provider
"provider[\"registry.terraform.io/jfrog/artifactory\"]" produced an
unexpected new value: .include_reference_token: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
  with artifactory_user.remote_sync,
  on user.tf line 10, in resource "artifactory_user" "remote_sync":
  10: resource "artifactory_user" "remote_sync" {

One will be generated (12 characters with 1 digit, 1 symbol, with upper and
lower case letters) and this may fail as your Artifactory password policy
can't be determined by the provider.
time=2023-09-27T03:32:28Z level=error msg=Module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/platform-cluster has finished with an error: 1 error occurred:
	* exit status 1

 prefix=[/home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/platform-cluster] 
time=2023-09-27T03:32:28Z level=error msg=Dependency /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/platform-cluster of module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/edge just finished with an error. Module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/edge will have to return an error too. prefix=[/home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/edge] 
time=2023-09-27T03:32:28Z level=error msg=Dependency /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/platform-cluster of module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/eu-west-1/edge just finished with an error. Module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/eu-west-1/edge will have to return an error too. prefix=[/home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/eu-west-1/edge] 
time=2023-09-27T03:32:28Z level=error msg=Module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/edge has finished with an error: Cannot process module Module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/edge (excluded: false, assume applied: false, dependencies: [/home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/platform-cluster, /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/platform]) because one of its dependencies, Module /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/platform-cluster (excluded: false, assume applied: false, dependencies: [/home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-west-2/platform, /home/runners/actions-runner/_work/segment-infrastructure/segment-infrastructure/jfrog/prod/us-east-1/platform]), finished with an error: 1 error occurred:
	* exit status 1
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
It should run successfully and created new token for our internal user.

**Additional context**

**Comment by alexhung** [comment]
@MA140589 Are you applying configuration for existing resources? Or trying to create new ones? The log suggests that you are executing `terraform apply` to an existing set of configuration and get these error? Are you upgrading the provider/terraform/artifactory at the same time? i.e. anything changes to the underlying infrastructures.

Would be very helpful if you can provide a sample of your HCL as well.

**Comment by MA140589** [comment]
> @MA140589 Are you applying configuration for existing resources? Or trying to create new ones? The log suggests that you are executing `terraform apply` to an existing set of configuration and get these error? Are you upgrading the provider/terraform/artifactory at the same time? i.e. anything changes to the underlying infrastructures.
> 
> Would be very helpful if you can provide a sample of your HCL as well.

@alexhung  we were creating new user resource "new-smart-remote-user" on existing configurations.  We have not changed any underlying infrastructures. We have automation in place on bumping "provider/terraform/artifactory"  version and this bumped version is used this time. So yes, we are upgrading provider at the same time. 

Below is the sample code we added recently : 

`resource "artifactory_user" "remote_sync" {
  name  = "new-smart-remote-user"
  email = "noreply@expedia.biz"

  groups = [
    "readers",
  ]
}
`

`resource "artifactory_scoped_token" "remote_sync" {
  scopes   = ["applied-permissions/user"]
  username = artifactory_user.remote_sync.name
}`

`resource "artifactory_permission_target" "remote_deploy" {
  name = "deploy"

  repo {
    repositories = ["ANY REMOTE"]

    actions {
      users {
        name        = artifactory_user.remote_sync.name
        permissions = ["read", "write", "annotate"]
      }
    }
  }
}`

**Comment by MA140589** [comment]
[Do you have record on the previous version of the provider you upgraded from? ](https://github.com/jfrog/terraform-provider-artifactory/issues/818#issuecomment-1747390734) 

@alexhung  Previous version was v7.2.0

**Comment by alexhung** [comment]
@MA140589 Thanks for the info. Armed with that previous version I was able to identify the cause.

Just curious, is there a reason why you are only upgrading to 8.2.3 and not the latest 9.3.0?

This [PR](https://github.com/jfrog/terraform-provider-artifactory/pull/750/files) fixed the inconsistency issue with `include_reference_token` but unfortunately not for `expires_in`. I will apply a patch for that in the next release.

**Comment by MA140589** [comment]
I am not sure if there is no specific reason why we are not using, our bot updated it's version to 8.2.3 as of now. So that's the only reason. I can see that you raised one PR i.e https://github.com/jfrog/terraform-provider-artifactory/pull/820  but also did some commits here  https://github.com/jfrog/terraform-provider-artifactory/commit/2d79553aac1edc22b361347a84852b3a7ba032ed. So please suggest which version now we have to use to fix this issue ?

**Comment by alexhung** [comment]
@MA140589 The general advice/recommendation is to upgrade to the latest version, as we apply fixes to the latest version. Only in exceptional cases where we will retrofit fixes to previous versions.

We understand that is sometimes not practical, especially if the current version is a bit behind. In those instances, it makes sense to upgrade incrementally.

So in your case, you should try to upgrade to the version that includes #820.
