### ISSUE TITLE
Synchronize federated member configuration when a federated resource is changed

### ISSUE THREAD

**Issue by Keyms** [jfrog/terraform-provider-artifactory#825]
**Is your feature request related to a problem? Please describe.**
When we update a federated repository, the others members are detected in '**inconsitent state**' and we must run a call to this endpoint [api/federation/configSync/<repositoryKey>](https://jfrog.com/help/r/jfrog-rest-apis/synchronize-federated-member-configuration) to synchronize the configuration to all other members.

A warning message is viewable in the UI of Artifactory : 

![image](https://github.com/jfrog/terraform-provider-artifactory/assets/35993752/52fdf18f-e86d-42a2-ae22-5a8fa9ed964e)
Warn error in logs :

![image](https://github.com/jfrog/terraform-provider-artifactory/assets/35993752/411f047a-0681-421e-8e36-86bcd631ada6)
![image](https://github.com/jfrog/terraform-provider-artifactory/assets/35993752/51593501-d372-443b-9840-daeea6e53dc1)

**Describe the solution you'd like**
If a federated resource is changed, the provider could run a post request to this endpoint to avoid these warnings.

**Comment by alexhung** [comment]
@Keyms Good idea! We'll add this to our plan.

**Comment by Keyms** [comment]
Thank you @alexhung !
