### ISSUE TITLE
artifactory_mail_server produces an inconsistent result after apply

### ISSUE THREAD

**Issue by testworksau** [jfrog/terraform-provider-artifactory#828]
**Describe the bug**
When configuring the `artifactory_mail_server` without setting a `subject_prefix`, or when setting `subject_prefix` to `null`, the second time the plan is applied we receive the following error.

```
Error: Provider produced inconsistent result after apply

When applying changes to artifactory_mail_server.mail_server_settings, provider "provider[\"registry.terraform.io/jfrog/artifactory\"].au" produced an unexpected new value: .subject_prefix: was null, but now cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Example TF:
```
resource "artifactory_mail_server" "mail_server_settings" {
    enabled         = true
    artifactory_url = "https://ourserver.com"
    from            = "artifactory@ouraddress.com"
    host            = "host.mailserver.com"
    port            = 587
    use_ssl         = false
    use_tls         = true
    subject_prefix  = null
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory `7.55.10`
- [x] Your version of terraform `1.4.5`
- [x] Your version of terraform provider `9.5.1`

**Expected behavior**
Settings are applied correctly

**Comment by alexhung** [comment]
@testworksau Due to how Artifactory REST API behaviors, `null` is not a good value to use to 'reset' the attribute value. Try empty `""` instead.

**Comment by testworksau** [comment]
Hi @alexhung - thanks for the speedy reply!

I had originally omitted the `subject_prefix` attribute altogether, and then tried `null` "just in case" 😄 

I also tried setting to an empty string, but received this error:

```
Error: Invalid Attribute Value Length

   with artifactory_mail_server.mail_server_settings_uk,
   on mail-server-settings.tf line 38, in resource "artifactory_mail_server" "mail_server_settings_uk":
   38:     subject_prefix  = ""

  Attribute subject_prefix string length must be at least 1, got: 0
```

For now, I've populated with a valid string but would prefer to remove it.

**Comment by alexhung** [comment]
@testworksau You're right. That attribute shouldn't have a length validation.
