### ISSUE TITLE
Expose curated property for remotes repositories

### ISSUE THREAD

**Issue by Keyms** [jfrog/terraform-provider-artifactory#831]
**Is your feature request related to a problem? Please describe.**
We are currently testing Jfrog Avanced Security and Curation. 

After activating these two functionalities in our qualification environment, the Artifactory API through the Terraform provider returns an error 400 with the following message `Remote curation settings are invalid`

**Our environment :**
Artifactory v7.63.14
Xray v3.82.11

**Describe the solution you'd like**
Could you expose the new type bool property `curated` for remotes (Type: Docker, Maven, npm, Pypi)

**Comment by alexhung** [comment]
@Keyms Thanks for the report! I'll add this to our plan.

**Comment by alexhung** [comment]
@Keyms I have been unable to reproduce that error message. Can you provide more details on the steps and an example of your HCL?

I'm still going to add `curated` attribute to support toggling of Curation support for these package types (`docker`, `maven`, `npm`, `pypi`).
