### ISSUE TITLE
Xray index option for federated repositories does not sync

### ISSUE THREAD

**Issue by gmartinezmelo** [jfrog/terraform-provider-artifactory#835]
**Describe the bug**
We recently realized that the xrayIndex (boolean) property does not properly sync between federated repositories, which is apparent when applying our Terraform code, since we create these repositories on only one cluster and expect their settings to be synchronized to others.

In Europe, Watches creations generate errors, because the target federated repositories are not indexed, when they should be by replication of the US configurations.

**Requirements for and issue**
- [x] A description of the bug

- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
```
resource "artifactory_federated_docker_v2_repository" "terraform-federated-test-docker-repo" {
  key       = "terraform-federated-test-docker-repo"

  xray_index = true

  member {
    url     = "http://tempurl.org/artifactory/terraform-federated-test-docker-repo"
    enabled = true
  }

  member {
    url     = "http://tempurl2.org/artifactory/terraform-federated-test-docker-repo-2"
    enabled = true
  }
}
```

- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
7.59.9

- [x] Your version of terraform
1.5.4

- [x] Your version of terraform provider
9.0.0

**Expected behavior**
We expect the xrayIndex (boolean) property to sync between federated repositories.

**Comment by alexhung** [comment]
May be related to #825

**Comment by gmartinezmelo** [comment]
In this case, even in the creation of the repo the xray index option is not syncing. The [#845](https://github.com/jfrog/terraform-provider-artifactory/issues/825) is referring to the update. Definitively either way we need the provider to be able to sync the federated repo options.

**Comment by alexhung** [comment]
@gmartinezmelo The synchronization of the repository settings are not done by the Terraform provider. This is performed by Artifactory.

The provider can potentially trigger a synchronization as suggested in #825, but fundamentally this isn't not the core responsibility of the provider.

**Comment by gmartinezmelo** [comment]
Thank you very much @alexhung, for clarifying this. As this not an issue with the provider but and Artifactory sync issue, I will close this issue.
