### ISSUE TITLE
Terraform Backend repository fails with "error writing state file: error uploading state: 400" with Terraform v1.6.3

### ISSUE THREAD

**Issue by mark-strasser-nnl** [jfrog/terraform-provider-artifactory#845]
**Describe the bug**
`terraform apply` fails with error "Error writing state file: error uploading state: 400" when using the Artifactory Terraform backend with Terraform v1.6.3.

**Requirements for an issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

### Terraform Snippet

```terraform
variable "artifactory_url" {
  default = "https://artifactory.mycompany.com/"
}

variable "artifactory_access_token" {
  sensitive = true
}

terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = ">= 8.2.2, <9.0.0" # v9 requires Artifactory (self-hosted) v7.68.7 or later
    }
  }
  backend "remote" {
    hostname     = "artifactory.mycompany.com"
    organization = "terraform-backend-local"
    workspaces {
      name = "artifactory-config"
    }
  }
}

provider "artifactory" {
  url          = "${var.artifactory_url}/artifactory"
  access_token = var.artifactory_access_token
}

resource "artifactory_local_cran_repository" "cran-local" {
  key = "cran-local"
}
```

### Version of Artifactory
7.59.11

### Version of Terraform
1.6.3 (windows_amd64, linux_amd64)

### Terraform Providers
Tried both v8.9.1 and v9.8.0 with the same error.

**Expected behavior**
Expected `terraform apply` to complete with no errors and write state to the remote backend repository in Artifactory.

**Additional context**
 1. Error does *not* occur with Terraform v1.5.4.
 2. `terraform import` with existing resource returns a similar error
 3. If it is more appropriate, I can create a support ticket with JFrog.

**Comment by alexhung** [comment]
@mark-strasser-nnl Are you using Artifactory as your remote backend? If so this may be the answer? https://jfrog.com/help/r/artifactory-how-to-deal-with-terraform-client-returning-error-saving-state-error-uploading-state-400-bad-request-while-terraform-apply-using-backend-repository-in-jfrog-artifactory/terraform-client-output

**Comment by mark-strasser-nnl** [comment]
@alexhung That issue is similar, but applies to an older version of Artifactory v7.55 / v7.56 and Terraform v1.3.8.  I'll file a JFrog Support Ticket, thanks.

**Comment by kallaichan** [comment]
@mark-strasser-nnl the Jira issue was closed at the same day without any indication of the exact solutions (e.g. upgrade to newer Artifactory...?). May I know if JFrog Support have given you any further updates on it? Many thanks!

**Comment by mark-strasser-nnl** [comment]
Per JFrog Support:
 1. The Jira ticket is "in place" and "is currently under internal review"
 2. We can "vote and watch the JIRA you can get an email triggered if any updates are made" and "check the [Artifactory] release notes".

My understanding based on the above:
 * The latest version of Artifactory was affected
 * The fix will require a new Artifactory release, which occur about every 2 weeks.  So you will need to upgrade.
 * No estimate on timeline.  If the resolution/status updates can be trusted, it should be fairly soon.

The bugs fixed in each release are listed in [the JFrog Artifactory release notes](https://jfrog.com/help/r/jfrog-release-information/artifactory-release-note).
