### ISSUE TITLE
State-Drift when AccessToken exists in TerraformState but not in Artifactory

### ISSUE THREAD

**Issue by leokra** [jfrog/terraform-provider-artifactory#86]
**Describe the bug**
When an Access-Token exists in Terraform-State, but is deleted in Artifactory (e.g. by using the UI), the provider is not able to detect the drift. 

I understand from https://github.com/jfrog/terraform-provider-artifactory/blob/c15a858816149c2494ebb8421e1b46eb7479de09/pkg/artifactory/resource_artifactory_access_token.go#L191 that this is intended,  but the provider can at least check if an Access-Token with the same name exists. Otherweise a warning or something comparable would be nice.

**Requirements for and issue**
...

**Expected behavior**
The Access-Token should be created if not existing in artifactory or a warning should be shown.

**Additional context**
...

**Comment by chb0github** [comment]
including @markgalpin for visibility - I can add it to the list of things we are considering. Development on the provider should start back up in June and at that point we will consider what to tackle. As always, PRs are welcome

**Comment by chb0github** [comment]
This actually can't be implemented. The body payload has no id in it and is generated server side. So, in addition to having no knowledge of the state of the token (and no way to get it), knowing that the token "doesn't exist" and can recreate it is a broken understanding of how this API works. The IDs will never be the same, and I can't tell RT to make the the same.

If it's been deleted manually, then the resource is destroyed and can never be created again
