### ISSUE TITLE
Add a way to manipulate project environments

### ISSUE THREAD

**Issue by VincentLim** [jfrog/terraform-provider-artifactory#874]
**Is your feature request related to a problem? Please describe.**

When creating repositories, I want them to be related to a project environment. As far as I know, project environment should have been created before running the script, and need to be referenced by their name

**Describe the solution you'd like**
A simple solution would be a terraform resource like the "artifactory_global_environment" one for project scoped environment, and the associated datasource.

**Comment by alexhung** [comment]
@VincentLim Have you tried creating a project environment using the "Project" provider? It has the [`project_environment` resource](https://registry.terraform.io/providers/jfrog/project/latest/docs/resources/environment) for this purpose.

**Comment by VincentLim** [comment]
No, I wasn't aware of that provider. 
I'll try it, thanks for the quick reply.

**Comment by VincentLim** [comment]
Working, thanks a lot
