### ISSUE TITLE
Provider "artifactory" not available for installation with TF v0.12.20

### ISSUE THREAD

**Issue by mytuanZ** [jfrog/terraform-provider-artifactory#88]
I try to use `provider "artifactory" {}` and I get error message `Provider "artifactory" not available for installation.` Can we use it in TF v0.12.x?
The Readme mentions requirements:

    Terraform 0.11
    Go 1.11+ (to build the provider plugin)

**Comment by chb0github** [comment]
That's a first. Thank you for bringing it to our attention. I'll be honest, It will be some time before we can address this

**Comment by mengesb** [comment]
There's also - terraform 0.13, 0.14, and now 0.15 ... i suspect the provider sdk is WAY out of date!!!

**Comment by mytuanZ** [comment]
Please have an update on this.

**Comment by chb0github** [comment]
Your best bet for traction on this is to raise a support ticket through the official channels. I am sorry I can't do more.

**Comment by chb0github** [comment]
Do you have a sample tcl script I can use to test? If so, I can have a look at this

**Comment by mytuanZ** [comment]
Thanks, you just need to add `provider "artifactory" {}` in the main.tf file and run `terraform init`

> $ cat main.tf
> 
> provider "artifactory" {}

**Comment by chb0github** [comment]
We currently only support terraform v0.13+ - have you tried using TF .13?

**Comment by mytuanZ** [comment]
Yes, I tried on TF 0.13, I thought It can run in on Tf 0.12

**Comment by chb0github** [comment]
@mytuanZ - any reason you closed this issue?

**Comment by mytuanZ** [comment]
@chb0github  I thought It can run with TF v0.12. If it only supports TF v0.13 ++, I should close this issue.
