### ISSUE TITLE
Support type: 'OCI' for resource: 'artifactory_virtual_helm_repository'

### ISSUE THREAD

**Issue by s3-m-bocian** [jfrog/terraform-provider-artifactory#880]
I'd like to request title type for the resource `artifactory_virtual_helm_repository`.

Currently, value for the `package_type` seem to be [hardcoded in the `src`](https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_helm_repository.go#L10).

Rationale: 

i. Since `helm v3.8.0` (rel. date: 2021-12-16) OCI is the default, go-to registry scheme;
ii. In some cases it is impossible to rely on the legacy HTTP scheme.

Ad ii. - Example:
Mirroring AWS Public CR helm registry.

Proposed DoD:

> New `package_type` attr [str] for `artifactory_virtual_helm_repository` .

**Comment by alexhung** [comment]
@s3-m-bocian Thanks for the request. I'll add this to our plan.
