### ISSUE TITLE
Groups with longer than 64 character names lead to 500

### ISSUE THREAD

**Issue by markszabo** [jfrog/terraform-provider-artifactory#883]
**Describe the bug**

If one tries to create an Artifactory group with a name longer than 64 character it fails with a 500 error:

```tf
resource "artifactory_group" "test" {
  name        = format("%070s", "A") # name with 70 'A' characters
  description = "'Test group
}
```

Plan is green, but apply fails:

```
│ Error: Unable to Create Resource
│ 
│   with artifactory_group.test,
│   on main.tf line 1, in resource "artifactory_group" "test":
│   34: resource "artifactory_group" "test" {
│ 
│ An unexpected error occurred while creating the resource update request.
│ Please report this issue to the provider developers.
│ 
│ Error: 
│ 500 PUT
│ https://<redacted>/artifactory/api/security/groups/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
│ {
│   "errors" : [ {
│     "status" : 500,
│     "message" : "Failed to process request for group AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA. Something went wrong"
│   } ]
│ }
╵
```

When creating a group on the web UI, there is a limit of 64 characters, so it is likely that the same limit is being hit here:

![image](https://github.com/jfrog/terraform-provider-artifactory/assets/12611720/3cba4073-4e5b-4baa-9cb1-5e4764d0f6e3)

**Expected behavior**

Plan should fail with a meaningful error message saying that the group name is too long.

**Comment by alexhung** [comment]
@markszabo Thanks for the report! The length limit is most likely the cause of the API error. I'll add the limit validation to the provider.

**Comment by markszabo** [comment]
Thank you very much for the super prompt solution.
