### ISSUE TITLE
Support for repository type 'OCI'

### ISSUE THREAD

**Issue by undefinedhuman** [jfrog/terraform-provider-artifactory#885]
**Is your feature request related to a problem? Please describe.**
Hi there, in the Artifactory UI, I can already create Repositories of type `OCI` but in the provider I can't find a resource to create such a repository.

**Describe the solution you'd like**
I would like to have a resource named: `artifactory_local_oci_repository` and the corresponding data source. 

**Additional context**
If you need any more information, please let me know. Thank you very much!

**Comment by alexhung** [comment]
Related to #880

**Comment by TJM** [comment]
Do we need another issue for `artifactory_remote_oci_repository` (or _registry)? or is "support OCI" close enough?

**Comment by undefinedhuman** [comment]
The #880 issue is related to making the OCI type available to the helm chart repository - where as this issue should keep track of the implementation of the actual OCI repository implementation - my feeling is those should be two seperate things

**Comment by undefinedhuman** [comment]
#880 is more a bug/improvement where as this one is a feature request
