### ISSUE TITLE
Artifactory Scoped Token Resource does not support applied-permissions/groups

### ISSUE THREAD

**Issue by johannges** [jfrog/terraform-provider-artifactory#889]
**Artifactory Scoped Token Resource does not support applied-permissions/groups**
If you try to create a group scoped_token, it will throw an error, that it is not supported:

```
resource "artifactory_scoped_token" "group" {
  username = "group_name"
  scopes   = ["applied-permissions/groups"]
}
```

Returns:

```
│ Error: Invalid Attribute Value Match
│ 
│   with artifactory_scoped_token.group,
│   on tf__artifactory_groups.tf line 24, in resource "artifactory_scoped_token" "group":
│   24:   scopes   = ["applied-permissions/groups"]
│ 
│ Attribute scopes[Value("applied-permissions/groups")] must be '<resource-type>:<target>[/<sub-resource>]:<actions>', got: applied-permissions/groups
```

This is also the case for applied-permissions/group

Terraform Module version: 10.1.3

Terraform Version: 1.5.7

Artifactory Version: 7.71.10

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
It should create a Scoped Token with the permission of the group

**Additional context**

**Comment by alexhung** [comment]
@johannges Your scope is missing a group name. The regex for validating the `scopes` attribute is `^applied-permissions/groups:.+$`. I'm not sure why the error message isn't the correct text. I'll look into that.
