### ISSUE TITLE
Block V2 Schema 1 Support for docker local/remote

### ISSUE THREAD

**Issue by TejjeT** [jfrog/terraform-provider-artifactory#89]
**Describe the bug**
The TF does not allow to configure block pushing/pulling Schema V2 version 1 of docker images. While our images are using latest schema , checking this box has downstream impacts on not being able to pull / push docker images

**Requirements for and issue**

- [x] 
```terraform
resource "artifactory_remote_repository" "dockerhub-docker-remote" {
  count        = var.create_remote && contains(var.repo_types, "docker") ? 1 : 0
  key          = "${var.team}dockerhub-docker-${var.env}-remote"
  package_type = "docker"
  url          = "https://registry-1.docker.io/"
  content_synchronisation {
    enabled = false
  }
  repo_layout_ref = "simple-default"
  property_sets = [ "iac-tf" ]
}
```
- [ ] 7.12.3
- [ ] 0.14

**Expected behavior**
```terraform
 resource "artifactory_remote_repository" "dockerhub-docker-remote" {
  count        = var.create_remote && contains(var.repo_types, "docker") ? 1 : 0
  key          = "${var.team}dockerhub-docker-${var.env}-remote"
  package_type = "docker"
  url          = "https://registry-1.docker.io/"
  content_synchronisation {
    enabled = false
  }
  repo_layout_ref = "simple-default"
  property_sets = [ "iac-tf" ]
 Block_pushing_image_manifest_v2 = true/false
}
```
**Additional context**

The current Cli also seems to have issue with the remote repos where the variable is called block pushing and we do not have an attribute that says block_pullin. Perhaps make it more generic if the api calls are working fine.

**Comment by chb0github** [comment]
Your snippet can't be run independently. You have to give me something I can C&P and verify

**Comment by TejjeT** [comment]
Actual Snippet:

```
resource "artifactory_remote_repository" "dockerhub-docker-remote" {
  key          = "dockerhub-docker-prod-remote"
  package_type = "docker"
  url          = "https://registry-1.docker.io/"
  content_synchronisation {
    enabled = false
  }
  repo_layout_ref = "simple-default"
  property_sets = [ "iac-tf" ]
}
```

But the target snipper  we would want is 

``` 
resource "artifactory_remote_repository" "dockerhub-docker-remote" {
  key          = "dockerhub-docker-prod-remote"
  package_type = "docker"
  url          = "https://registry-1.docker.io/"
  content_synchronisation {
    enabled = false
  }
  repo_layout_ref = "simple-default"
  property_sets = [ "iac-tf" ]
  block_pushing_image_manifest_v2 = true/false
}
``` 

This seems to be a bug in artifactory SAAS  where consumers  or not able to download the artifacts if block_pushing_image_manifest_v2 is true and support team mentioned that this is fixed in latest version. I did not get a chance to test this. Either way the above snippet makes sense to have like for like between Ui and Code

**Comment by asvoboda** [comment]
Back in #9, I opened a PR to accomplish this. I think the repo definitions need to be updated to use the new jfrog go sdk, since this option appears to be supported https://github.com/jfrog/jfrog-client-go/blob/master/artifactory/services/localrepository.go#L177
