### ISSUE TITLE
Support anonymous; make default

### ISSUE THREAD

**Issue by mengesb** [jfrog/terraform-provider-artifactory#90]
**Describe the bug**
There are some API methods that do not require authentication. Thus, if the user doesn't provide authentication to the provider, it should allow the anonymous capable resources/sources to function.

```hcl
data "artifactory_file" "my-file" {
   repository = "repo-key"
   path = "/path/to/the/artifact.zip"
   output_path = "tmp/artifact.zip"
}

resource "aws_lambda_function" "lambda" {
  function_name    = var.function_name
  role             = aws_iam_role.role.arn
  filename         = data.artifactory_file.my-file.output_path
  handler          = var.handler
  source_code_hash = data.artifactory_file.my-file.sha256
  runtime          = var.runtime
  memory_size = 128
  timeout     = 10
  vpc_config {
    subnet_ids         = data.aws_subnet_ids.private.ids
    security_group_ids = [aws_security_group.lambda_security_group.id]
  }
  lifecycle {
    create_before_destroy = true
  }
  tags = {
    Name = var.function_name
  }
  depends_on = [
    aws_cloudwatch_log_group.cloudwatch_log_group
  ]
}
```

This should work in anything Terraform 0.12 to current. This example was using 0.13.7. This is dependent on the provider being compatible with terraform versions.

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform

**Expected behavior**
Terraform should download the file, and allow the AWS resource to upload (publish) it, providing the correct sha256 hash

**Additional context**
Provider currently requires authentication ... since we allow non-authenticated downloads at some repository paths, this should be an anonymous call and the provider should allow it.

**Comment by chb0github** [comment]
1. I don't see how this snippet of code uses this TF provider
2. I don't see your artifactory version
3. I don't see your terraform version

Are you trying to provide an artifact from RT to AWS as your lambda?

**Comment by uday1bhanu** [comment]
`filename         = data.artifactory_file.my-file.output_path` and `source_code_hash = data.artifactory_file.my-file.sha256`
this is where the artifactory data source is being referenced in lambda resource.

Below is the providers.tf snippet for which this is reproducible.
```
terraform {
  required_version = "~> 0.14.10"
  required_providers {
    archive = "~> 2.1"
    aws     = "~> 3.33"
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "2.2.7"
    }
  }

  backend "remote" {}
}

provider "aws" {
  region     = var.region
}

provider "artifactory" {
  url     = var.artifactory_url
  api_key = var.artifactory_token
}

```

Yes, the artifact is stored in artifactory and needs to be set as input to AWS lambda.

**Comment by mengesb** [comment]
> 1. I don't see how this snippet of code uses this TF provider
> 2. I don't see your artifactory version
> 3. I don't see your terraform version
> 
> Are you trying to provide an artifact from RT to AWS as your lambda?

As @uday1bhanu mentioned, the resource that uses the provider is `data.artifactory_file.my-file.*`. In order to use that resource, we have to be authenticated per the restrictions with the provider you've coded, whereas the API _can_, and in our case **does** allow anonymous pulls of artifacts - thus we don't need to be authenticated. I simply didn't show the `provider "artifactory"` configuration, because technically only the `url` is needed, the `api_key` _shouldn't_ be needed.

Our work-around is to have users generate an API token and use that... but this allows for credentials creep, and brings in the issue of securing the credentials. Given the call **can and should** be made anonymously, I wanted to suggest development to the provider supporting that which the API allows.

Our artifactory version: `Artifactory Enterprise 6.23.3 rev 62303900`

Terraform version will be current, so at this stage we'll be using `1.0.0`

**Comment by chb0github** [comment]
To make this work I would have to remove authentication verification entirely, and not just for file access. Because, even if your situation allows for anonymous read, that's not a general case. I mean, I would simply be punting to RT to do that job. Fail-fast is the motto to follow. 

There is simply no way for me to introspect what you're trying to accomplish in TF and grant an "exception" - the TF APIs are designed well enough to give precisely zero context to the operation at hand. 

Sorry, But I think I would need a ground swell of votes for me to remove auth validation
