### ISSUE TITLE
OIDC support

### ISSUE THREAD

**Issue by oxdef** [jfrog/terraform-provider-artifactory#904]
Jfrog [announced OIDC support for Artifactory](https://jfrog.com/blog/secure-access-development-jfrog-github-oidc/) this year and there is [API for it](https://jfrog.com/help/r/jfrog-rest-apis/oidc-integration-api). And that's a really good news! OIDC looks really promising thing in case of secure authentication in Artifactory for GitHub Actions.

**Describe the solution you'd like**
It will be great if there is support for OIDC in Terraform provider for Artifactory as well. It should be helpful especially for companies with many projects. As a reference we can look on [same feature in the Vault Terraform provider](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/jwt_auth_backend_role).

**Comment by alexhung** [comment]
@oxdef Thanks for the suggestion. This has been suggested by others before but I moved them to the [JFrog Platform provider repo](https://github.com/jfrog/terraform-provider-platform/issues). I'll leave this here so others will see where the resource will be implemented.

**Comment by alexhung** [comment]
Dup of https://github.com/jfrog/terraform-provider-platform/issues/26

**Comment by alexhung** [comment]
See https://github.com/jfrog/terraform-provider-platform/pull/47
