### ISSUE TITLE
Support any_federated option in webhook resources

### ISSUE THREAD

**Issue by manojwajekar** [jfrog/terraform-provider-artifactory#906]
**Is your feature request related to a problem? Please describe.**
Currently in webhook resources there are options to set any_local (select all local repos) and any_remote (select all remote repos), but not an option to select all federated repos.

There is option to set any federated repo in artifactory UI.
![image](https://github.com/jfrog/terraform-provider-artifactory/assets/24420986/3cb258c1-b57a-4b45-976f-a92580d4eeac)

**Describe the solution you'd like**
Introduce new attribute any_remote in all webhook resources

**Describe alternatives you've considered**
I can read all federated repos using artifactory_repositories data resources and pass as list in repo_key attribute in webhook resources, but it's not as clean approach, as I will have to run terraform again after new federated repo creation, to make sure that new federated repo is added in repo_key.

**Comment by alexhung** [comment]
@manojwajekar Thanks for the report. I've added this to our plan.
