### ISSUE TITLE
Unable to install provider in OpenTofu 

### ISSUE THREAD

**Issue by fabiankle** [jfrog/terraform-provider-artifactory#913]
(This is the analogue to https://github.com/jfrog/terraform-provider-project/issues/108)

Describe the bug
When trying to install the jfrog/artifactory provider we get the error

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing jfrog/artifactory v10.3.0: authentication signature
│ from unknown issuer
╵
```

Expected behavior
Being able to install the provider.

We guess this is the same issue as with jfrog/project (it is just blocking our pipeline, thus the tickt)

Thank you!

**Comment by alexhung** [comment]
@fabiankle Please switch to 10.3.3 which is signed using the same key as the other provider.
