### ISSUE TITLE
Migration guide for `artifactory_permission_target` → `platform_permission`

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#924]
### Is your feature request related to a problem? Please describe.

Upgraded Terraform Provider for Artifactory to v10.4.3. Was notified that:

> This resource has been deprecated in favor of "platform_permission"
> (https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission)
> resource.
>
> (and 403 more similar warnings elsewhere)

I do not see any reference to this deprecation in the CHANGELOG. Neither do I see a migration guide that will help me perform this migration.

Reviewing the documentation, it says:

> This resource is applicable for the next-generation permissions model and fully backwards compatible with the legacy `artifactory_permission_target` resource in Artifactory provider.

However, it does not appear that these resources are 1:1 compatible. More work is required than what is presently documented.

### Describe the solution you'd like

A clear and detailed migration guide for porting my 400+ `artifactory_permission_target` resources over to the new `platform_permission` resource in the `jfrog/platform` provider without breaking anything.

### Describe alternatives you've considered

Experimenting with porting a single instance of `artifactory_permission_target` until I get it figured out, then using find/replace regular expressions in my IDE to port the remaining resources.

### Additional context

I don't have a lot of time to spend on this at the moment. The more information we have to streamline this process, the better.

**Comment by alexhung** [comment]
> I do not see any reference to this deprecation in the CHANGELOG.

@skyzyx Good point. I forgot to add it to CHANGELOG. I'll update it retroactively.

As for the migration guide, I'll add that to our plan.

**Comment by alexhung** [comment]
@skyzyx Updated the changelog for v10.3.1: https://github.com/jfrog/terraform-provider-artifactory/blob/master/CHANGELOG.md#1031-mar-14-2024
