### ISSUE TITLE
artifactory_virtual_helmoci_repository creating docker virtual repo instead of helmoci

### ISSUE THREAD

**Issue by ram-devsecops** [jfrog/terraform-provider-artifactory#925]
**Describe the bug**
When attempting to create a virtual Helm OCI repository using the artifactory_virtual_helmoci_repository resource, the applied configuration unexpectedly creates a virtual repository of Docker type instead of Helm OCI.

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
    terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "10.4.2"
    }
  }
}
```
resource "artifactory_virtual_helmoci_repository" "helmoci_virtual" {
  key = "helmoci"
  repositories = [
    "helmoci-ghcr-remote",
    "helmoci-aws-remote",
  ]
  description = "Helm Oci Repository"
  includes_pattern = "**/*"
  repo_layout_ref = "simple-default"
  resolve_oci_tags_by_timestamp = false
}
```
# Terraform Plan
``` 
  + resource "artifactory_virtual_helmoci_repository" "helmoci_virtual" {
      + artifactory_requests_can_retrieve_remote_artifacts = false
      + description                                        = "Helm Oci Repository"
      + id                                                 = (known after apply)
      + includes_pattern                                   = "**/*"
      + key                                                = "helmoci"
      + package_type                                       = (known after apply)
      + project_environments                               = (known after apply)
      + repo_layout_ref                                    = "simple-default"
      + repositories                                       = [
          + "helmoci-ghcr-remote",
          + "helmoci-aws-remote",
        ]
      + resolve_oci_tags_by_timestamp                      = false
    }
```

Result:
<img width="1394" alt="image" src="https://github.com/jfrog/terraform-provider-artifactory/assets/8261270/7fd04445-467f-49a6-9317-0ad0c308eb69">

- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
        SAAS latest version
- [ ] Your version of terraform
- [x] Your version of terraform provider
       Provider "registry.terraform.io/jfrog/artifactory" v10.4.2

**Expected behavior**
The expected behavior is for the artifactory_virtual_helmoci_repository resource to create a virtual repository of type Helm OCI, not Docker.

**Additional context**

**Comment by alexhung** [comment]
@ram-devsecops Thanks for the report. I'll add this to our sprint plan.
