### ISSUE TITLE
This provider have to use terraform-provider-sdk v2

### ISSUE THREAD

**Issue by cappyzawa** [jfrog/terraform-provider-artifactory#94]
[Announcing HashiCorp Terraform 1\.0 General Availability](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability)

> The Terraform Plugin SDK is a framework that lets developers create and maintain Terraform providers. HashiCorp will be ending support for the version 1 release of the Plugin SDK on July 31, 2021. Users of the Terraform CLI and Terraform Cloud are not affected by this and do not need to take any action. Maintainers of Terraform providers who are impacted are encouraged to use our upgrade guide to move to version 2 of the Terraform Plugin SDK. Follow our tutorials to develop your first provider. Additional information can be found in the Terraform Provider Developer Community Discuss forum: End of Life Timeline for v1 of the Terraform Plugin SDK.

This provider doesn't use SDK v2. (https://github.com/jfrog/terraform-provider-artifactory/blob/master/go.mod#L6)

**Comment by cappyzawa** [comment]
It has been labeled as a bug, but it is not a bug 🙇

**Comment by cappyzawa** [comment]
OK.
I'll submit a PR.

**Comment by drcrees** [comment]
@cappyzawa I'm fairly confident we were successful in upgrading to `v2 (v2.7.0)` of `terraform-provider-sdk` in #95 

Currently awaiting review 👍
