### ISSUE TITLE
`artifactory_managed_user` should replace on username change

### ISSUE THREAD

**Issue by NiklasRosenstein** [jfrog/terraform-provider-artifactory#944]
**Describe the bug**

When the `username` of a `artifactory_managed_user` changes, the plan indicates that it would update the resource, rather than replacing it. The apply fails with "Error: - Not Found". The resource should

**Requirements for and issue**

Try to rename a user with Terraform.

```hcl
resource "artifactory_managed_user" "myuser" {
  name              = "myuser"
  email             = "myuser@example.com"
  disable_ui_access = true
  admin             = false
  profile_updatable = false
  password          = "foobar32!!"
}
```

**Expected behavior**

Artifactory doesn't support renaming users, so I would expect the resource to be recreated.

**Actual behaviour**

Example:

<img width="1084" alt="image" src="https://github.com/jfrog/terraform-provider-artifactory/assets/1318438/046c01f7-fd9e-4f76-897c-9157fa2dd748">

<img width="1085" alt="image" src="https://github.com/jfrog/terraform-provider-artifactory/assets/1318438/41110638-ca40-4215-9f50-6cb9e5beaa3f">

The `publish-hdf-2081-playground` user continutes to exist after the Terraform apply failed. Deleting the user and running the apply again fixes it.

**Comment by alexhung** [comment]
@NiklasRosenstein Thanks for the report! I've added this to our plan to fix.
