### ISSUE TITLE
`artifactory_managed_user` Error: parse `{...}access/api/v2/users/...` first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by NiklasRosenstein** [jfrog/terraform-provider-artifactory#945]
**Describe the bug**

```
╷
│ Error: Unable to Create Resource
│ 
│   with module.config.module.project["hdf/hdf-ingest"].module.service_accounts["snapshot"].artifactory_managed_user.main,
│   on .terraform/modules/config/modules/artifactory-sa/main.tf line 19, in resource "artifactory_managed_user" "main":
│   19: resource "artifactory_managed_user" "main" {
│ 
│ An unexpected error occurred while creating the resource update request.
│ Please report this issue to the provider developers.
│ 
│ Error: parse
│ "{\"add\":[],\"remove\":[\"readers\"]}access/api/v2/users/publish-hdf-2713-snapshot/groups":
│ first path segment in URL cannot contain colon
╵
```

Unfortunately cannot currently offer a way to replicate this issue. Subsequent to encountering it, I removed the `readers` group from Artifactory. I think it is some default group that grants read permissions to all repositories and by default all new users get added to it, but we don't want that.

I'm still waiting for the next run to finish (or error) to see if the error no longer occurs.

Provider version 10.7.2

**Comment by alexhung** [comment]
@NiklasRosenstein Thanks for the report. I'll investigate this issue. This hasn't shown up in our acceptance test suite so any help in reproducing this will be appreciated.
