### ISSUE TITLE
`api_key` cannot be defined without `access_token`

### ISSUE THREAD

**Issue by kelvin-glass-db** [jfrog/terraform-provider-artifactory#966]
**Describe the bug**
I cannot specify `api_key` since it fails and requests to specify `access_token` (which then takes precedence)
(I am aware that the key is deprecated and I want to move to the token asap 😃 )

I reduced my problem to the following dummy code
```hcl
terraform {
  required_version = ">= 1"
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "10.7.6"
    }
  }
}

provider "artifactory" {
  url           = "https://jfrog.com"
  check_license = false
  api_key       = "not-a-real-key"
}


data "artifactory_file" "code" {
  repository  = "no-real-repo"
  path        = "no-real-path"
  output_path = "${path.module}/code.zip"
}
```

failing with
```
│ Error: Missing JFrog Access Token
│
│   with provider["registry.terraform.io/jfrog/artifactory"],
│   on test.tf line 11, in provider "artifactory":
│   11: provider "artifactory" {
│
│ While configuring the provider, the Access Token was not found in the JFROG_ACCESS_TOKEN/ARTIFACTORY_ACCESS_TOKEN environment variable or provider
│ configuration block access_token attribute.
╵
```

I assume the problem is that only the token is validated without checking if the key was specified: https://github.com/jfrog/terraform-provider-artifactory/blob/1942a28912362a431a0cdb0e93f3a859089e7de4/pkg/artifactory/provider/framework.go#L142-L150

With:
- Terraform `v1.7.5` on `darwin_arm64`
- provider `registry.terraform.io/jfrog/artifactory` `v10.7.6`
- Artifactory `7.41.12`

**Expected behavior**
The Terraform run is successfully authenticating using the `api_key` and does not ask for the `access_token`.

**Additional context**

**Comment by alexhung** [comment]
@kelvin-glass-db Thanks for the report! I've added this issue to our plan.
