### ISSUE TITLE
Assign users to group within artifactory_group resource

### ISSUE THREAD

**Issue by cramaker** [jfrog/terraform-provider-artifactory#97]
This is a resurrection of the issue originally listed under the Atlassian organization: https://github.com/atlassian/terraform-provider-artifactory/issues/40 

### Description

When defining a group, it'd be super helpful to identify users belonging to said group.

Current use case: my users come in via SAML, and are granted permissions according to team membership.

This feature request was originally declined due to the fact that the Jfrog API didn't allow the group resource to take members. I believe that has been overcome according to the documentation here: https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON under `application/vnd.org.jfrog.artifactory.security.Group+json`
### New or Affected Resource(s)

artifactory_group
### Potential Terraform Configuration

```
# Example block, won't actually work.

resource "artifactory_group" "test-group" {
  name             = "terraform"
  description      = "test group"
  admin_privileges = false

  users = ["user1", "user2"]
}
```

**Comment by ax-taustgen** [comment]
+1 on that usecase,

I've got users created via saml with read only by default and a per namespace repository that I would like to be able to assign those users to the correct rw group

**Comment by cramaker** [comment]
I took a look at the `go-artifactory` client library (https://github.com/atlassian/go-artifactory) which facilitates this provider's requests. This library only has the most rudimentary support for V2 and doesn't include the user/groups options we're looking for. Further, it appears to be abandoned: it hasn't had a commit in 2 years and there's a backlog of pull requests that maintainers haven't been reviewed:

https://github.com/atlassian/go-artifactory/pulls

I'm pessimistic about the changes of this getting resolved in a timely fashion since it appears that we'd be hampered by this upstream dependency.

**Comment by ax-taustgen** [comment]
Conveniently they are also already using the newer https://github.com/jfrog/jfrog-client-go elsewhere in the package. I've got a PR #99 up that swaps groups to use the newer client add would allow us to add users. Unfortunately some recent commits directly to master have broken the testing setup so i can't even run tests.

**Comment by chb0github** [comment]
@ax-taustgen - I heard from your wife today about this PR/issue.  In the future, though, the process is to start here. You can tag me too. When I am unable to get people's needs addressed I will direct them to create a support ticket - which usually gets things moving. I try to be quite responsive on here and gitter, so please try those avenues first

You are right about the old atlassian client. It's currently on my agenda, and under development, to entirely rip out the atlassian client and use the JFrog client (though, that too has some limitations). 

As for the issue at hand: I directly pushed to master (by accident); but, that was obvious. There was an outstanding PR that was reviewed. 

Which tests are you referring to that are broken? We can address them. The recent changes to master were to address the lack of error checking, as well as subsequent lack of check for `nil` in response objects from the old atlassian client. This lack of checking was cause the provider itself to crash with nil pointers. Those had to be addressed, but if there are issues, please bring them to my attention. 

JFrog and myself are always happy to help the community get involved. Show we what's broken and let's get it fixed.

**Comment by ax-taustgen** [comment]
Hey @chb0github I was trying to run the tests according to https://github.com/jfrog/terraform-provider-artifactory#testing
but the docker-compose command failed as the docker-compose.yaml was removed https://github.com/jfrog/terraform-provider-artifactory/commit/be8f7157040ca8a74f0524376a531dda20ac9cb7.


As for specific request, I would like to be able to update a group with a list of users and have the group be updated to match.  I've taken a stab at it myself with #99 but I could use help with getting the local artifactory container set-up for testing without the docker compose

**Comment by chb0github** [comment]
@ax-taustgen Did you actually get the docker-compose ever working? I had a lot of issues getting it to consistently start so I removed it. I mean, technically, you can always resurrect it. 

If you need an instance to test against, I can actually spin you up one no problem, just let me know. And, find me on gitter

**Comment by ax-taustgen** [comment]
👍 If you could spin that instance up for me I'd appreciate it. I thought I could get the docker compose working but I'm getting 403'd when trying to pull down `jfrog/artifactory-pro:latest ` which is sort of the end of the road for that path.

I'll reach out via gitter, but if you could spin me up an instance and let me know the commands you usually use to run the test i'd appreciate it!

**Comment by chb0github** [comment]
I emailed you with your details - let me know if you have questions

**Comment by chb0github** [comment]
How's it coming? I'd like to get this folded in

**Comment by cramaker** [comment]
Likewise, interested to see if there's any updates here

**Comment by chb0github** [comment]
@ax-taustgen -

**Comment by chb0github** [comment]
I have folded your changes into the 2.3.x branch which I really hope to release this week. I had wanted to do it by yesterday but I am unable to get unrelated tests passing. I really don't want to release 2.3.1 until all the major changes are complete and I can move 2.3.x into a moer stable, maintainable branch

**Comment by chb0github** [comment]
These changes have been folded in. Current release is 2.3.5

**Comment by cramaker** [comment]
@chb0github Thanks for this! Trying to use 2.3.5 as a provider and I'm getting the following error:
`jfrog/artifactory: no available releases match the given constraints 2.3.5`
I see that you've tagged it as a release, but is there a missing Github action that needs to take place? 
Thanks again!

**Comment by chb0github** [comment]
Sometimes the TF release action fails. But right now, I am not even seeing where it even happened. I have another change pending to be pushed. Should be out tomorrow with luck. It will include these changes too.

**Comment by chb0github** [comment]
[2.3.6 is released](https://registry.terraform.io/providers/jfrog/artifactory/latest)
