### ISSUE TITLE
Support detecting wrong resource configuration in stage "terraform plan"

### ISSUE THREAD

**Issue by gyzong1** [jfrog/terraform-provider-artifactory#972]
**Is your feature request related to a problem? Please describe.**

When the resource configuration is wrong, the command "terraform plan" should report error message.

1. Such as when we want to create two duplicate users in Artifactory, and the wrong **main.tf** is:

```terraform
terraform {
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
      version = "10.7.4"
    }
  }
}

provider "artifactory" {
  url          = "http://localhost:8082/artifactory"
  access_token = "xxxxx"
  
}

resource "artifactory_user" "**example_user2**" {
  name     = "**user2**"
  email    = "user2@example.com"
  admin    = false
  groups   = [
    "readers"
  ]
}

resource "artifactory_user" "**example_user3**" {
  name     = "**user2**"
  email    = "user2@example.com"
  admin    = false
  groups   = [
    "readers"
  ]
}
```

2. Then, we execute the command:

```shell
terraform plan
```

3. The response is normal (It should be wrong due to the username is duplicate):

![terraform_plan](https://github.com/jfrog/terraform-provider-artifactory/assets/40457486/5f72d80c-1d8b-4d64-8354-b8690561099c)

**Describe the solution you'd like**
The response should report an error such as "Error: Unable to Create Resource due to the user is duplicate"

```shell
$ terraform -v
Terraform v1.8.3
on darwin_amd64
provider registry.terraform.io/jfrog/artifactory v10.7.4
```

**Comment by alexhung** [comment]
@gyzong1 Thanks for the report. I've added this to our plan.

**Comment by alexhung** [comment]
@gyzong1 The reason the provider can't return an error during the planning phase is that Terraform treats each resource independently. i.e. `artifactory_user.example_user2` has no relationship with `artifactory_user.example_user3` when Terraform checks with Artifactory if `user2@example.com` exists or not.

When you apply the configuration, then you will get the error:
```shell
│ Error: Unable to Create Resource
│
│   with artifactory_user.new_user,
│   on sample.tf line 10, in resource "artifactory_user" "new_user":
│   10: resource "artifactory_user" "new_user" {
│
│ An unexpected error occurred while creating the resource update request. Please report this issue to the provider developers.
│
│ Error: CONFLICT - User already exists
```

So this is not a bug.
