### ISSUE TITLE
metadata_retrieval_timeout_secs docs need updating

### ISSUE THREAD

**Issue by davidcorrigan714** [jfrog/terraform-provider-artifactory#983]
**Describe the bug**
The docs for the `metadata_retrieval_timeout_secs` attribute on remote repos need fixing. Looks like it used to just be for maven remote repos but works for all remote repos now.

**Requirements for and issue**
- [x] A description of the bug

**Expected behavior**
The `artifactory_remote` doc page should have details about the `metadata_retrieval_timeout_secs` attribute.

**Comment by alexhung** [comment]
@davidcorrigan714 Thank you for the report. Indeed it does look like that field is now available for all package types. This will involve more than just documentation changes. The code requires updating too.

**Comment by davidcorrigan714** [comment]
@alexhung Thought it being [here ](https://github.com/jfrog/terraform-provider-artifactory/blob/bc6386039bf9cb0595aae1e36da80bc67afcb2d6/pkg/artifactory/resource/repository/remote/remote.go#L198) would mean the code is good to go, my terraform plan operation also hasn't failed yet but it's not done yet and doesn't quite touch all repo types. It's also referenced in release notes [here ](https://github.com/jfrog/terraform-provider-artifactory/blob/bc6386039bf9cb0595aae1e36da80bc67afcb2d6/CHANGELOG.md?plain=1#L801) though I didn't go track down the commits to see what actually changed.

**Comment by alexhung** [comment]
@davidcorrigan714 Ah you're right. I haven't worked on that part of the code for a while and I didn't check first. So this may be smaller change than I envision.
