### ISSUE TITLE
`platform_permission` resource is not useable

### ISSUE THREAD

**Issue by ArieLevs** [jfrog/terraform-provider-artifactory#994]
**Describe the bug**
the `platform_permission` is missing from terraform provider, cannot locate the resource here https://registry.terraform.io/providers/jfrog/artifactory/latest/docs

when adding the resource an error returend from terraform
```
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/platform: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/platform
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see
│ which modules are currently depending on hashicorp/platform, run the following command:
│     terraform providers
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
Add a simple `platform_permission` resource and try to terraform init / plan
```hcl
resource "platform_permission" "example" {
  name = "example"

  artifact = {
    targets = [
      {
        name = "example"
        include_patterns = ["**"]
        exclude_patterns = []
      }
    ]

    actions = {
      groups = [
        {
          name = "example"
          permissions = ["READ"]
        }
      ]
    }
  }
}
```

- [x] Your version of artifactory 7.77.7
- [x] Your version of terraform 1.7.5
- [x] Your version of terraform provider 1.8.3

**Expected behavior**
terraform apply should work as usual when using the `platform_permission` resource

**Comment by alexhung** [comment]
@ArieLevs The `platform_permission` resource is part of the `jfrog/platform` provider. The documentation is at: https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission

You'll need to ensure your TF configuration has the `jfrog/platform` provider defined:

```terraform
terraform {
  required_providers {
    platform = {
      source  = "jfrog/platform"
      version = "1.7.4"
    }
  }
}
```

**Comment by ArieLevs** [comment]
:grimacing:
missed that its from a total different provider as mentioned here https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/guides/permission_targets_migration "... added to the Platform Terraform **provider** ..."

thanks, and sorry :sweat:
