### ISSUE TITLE
Unable to manage "Allow Content Browsing" option for remote docker repositories

### ISSUE THREAD

**Issue by cfergs** [jfrog/terraform-provider-artifactory#999]
Is it possible to manage the setting "Allow Content Browsing" via terraform for remote docker repositories?
This option provides the functionality: _"When set, you may view content such as HTML or Javadoc files directly from Artifactory.
 This may not be safe and therefore requires strict content moderation to prevent malicious users from uploading content that may compromise security (e.g., cross-site scripting attacks)."_

I can't seem to find the option for this in the existing TF or API (https://jfrog.com/help/r/jfrog-rest-apis/repository-configuration-json).

Am i imagining this or just reading the doco incorrectly?

**Comment by alexhung** [comment]
@cfergs The field you are looking for is `archiveBrowsingEnabled` and currently it is only supported in the local repository resources. I will add that to the remote resources.
